### ISSUE TITLE
Reduce cost of performing S3 ListBucket requests

### ISSUE THREAD

**Issue by prutz1311** [hashgraph/hedera-mirror-node#1026]
We are building a Hedera explorer and using the mirror node to download data. We found out that the mirror node sends a lot of requests to S3 and the majority of those requests are `ListBucket` requests. This incurred AWS costs of more than $500 for the last month. Are there ways we can reduce the number of these requests?

Probably related to #357 and #557

**Comment by steven-sheehy** [comment]
We have issue #371 that tracks inefficient listing of S3. We currently optimize for latency over cost. Until we find time to improve our algorithm to be smarter, you can adjust some settings that optimize for cost at the possible expense of latency.

Firstly, there are three S3 streams: account balances, events and records. If you don't care about data from a certain stream you can disable its downloads using the `hedera.mirror.importer.downloader.(balance|event|record).enabled` property.

Second, you can increase how often it polls S3 for data by adjusting the `hedera.mirror.importer.downloader.(balance|event|record).frequency` property. For example, the record file is written every 2s but we poll every 500ms to ensure we get it as soon as it's available. You can change it to every 5s and it will download all data missing in the last 5s instead.

**Comment by steven-sheehy** [comment]
Has this sufficiently answered your questions? Can we close this and track the optimizations via #371?
