### ISSUE TITLE
Kubernetes: Performance testing

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-mirror-node#1107]
**Problem**
We would like to migrate to Kubernetes based deployment, but need to gain confidence in the performance of this approach.

**Solution**
Stress test the various parts of the system (REST API, gRPC API, importer)

**Alternatives**

**Additional Context**

**Comment by xin-hedera** [comment]
## Benchmark Configuration

1. GKE cluster
    - version: v1.17.12-gke.500
    - region: us-central1, 3 zones
    - node-pool: 1 node per zone, machine type: n1-standard-4, vCPUs - 4, memory - 15GB
2. PostgreSQL
   - version: CloudSQL 9.6
   - vCPUs - 10, memory - 37.5GB, storage - 300GB SSD
3. Load Balancer:
   - Traefik: 9.5.1
   - HAProxy: 2.1.8 
5. Deployment
    - helm
	    - charts version: 0.8.0-rc1
        - hedera-mirror-node version: v0.21.0-rc1
    - max rest pods = 10

## REST Service Performance

Bechmark command:

```bash
$ hey -n 100000 -c concurrency -m GET http://LOAD_BALANCER_IP/api/v1/transactions?limit=1
```
The command sends 100,000 HTTP GET requests which query the latest transaction with the specified concurrency (number of workers).

concurrency 50:
| Load Balancer | RPS  | Min Latency | Max Latency | Average Latency |
|---------------|------|-------------|-------------|-----------------|
| Traefik       | 2023 |  0.0040s    | 0.3786s     |   0.0243s       |
| HAProxy       | 2324 |  0.0035s    | 0.6216s     |   0.0417s       |


concurrency 100:
| Load Balancer | RPS  | Min Latency | Max Latency | Average Latency |
|---------------|------|-------------|-------------|-----------------|
| Traefik       | 2135 |  0.0037s    | 0.5958s     |   0.0456s       |
| HAProxy       | 2365 |  0.0035s    | 0.4258s     |   0.0207s       |

## Importer Performance

With importer configured to pull historical high TPS record stream files from perfnet bucket, the average ingestion rate is around 15k/s.
 
## GRPC Service Performance

Importer is configured to pull historical high TPS record stream files from perfnet bucket, two scenarios are tested.

- Single HCS topic subscriber, the peak TPS is ~20k/s and the 30-min average TPS is ~15k/s.
- 10 concurrent HCS topic subscribers on the same HCS topic, with importer's CPU resource limit lowered to cap the importer ingestion rate. All 10 subscribers can sustain the 30-min test with ~3.5k/s TPS.

**Comment by steven-sheehy** [comment]
Results look good for the most part. Do you have comparative numbers for the REST API on our VM deployment?

~3.5k/s TPS for 10 subscribers is low. We can support at least 10K in VM. Can we retest at a higher rate?

**Comment by xin-hedera** [comment]
I'll add the REST API perf numbers on our VM deployment. I'll also rerun the 10 concurrent subscriber scenario at ~10k tps.

**Comment by steven-sheehy** [comment]
This looks really good. It looks like our Kubernetes deployment is comparable to our VM deployment. We'll need to do additional testing as we roll it out further with real traffic, but this gives us confidence with our Kubernetes deployment. I think we can close this.
