### ISSUE TITLE
Allow monitor checks to be disabled

### ISSUE THREAD

**Issue by beeradb** [hashgraph/hedera-mirror-node#1153]
**Problem**
The work done in https://github.com/hashgraph/hedera-mirror-node/issues/1033 was very useful in that it allows thresholds to be set on individual checks. However, it introduced another problem which makes automation difficult - it relies on the monitor to know details of network state to pass checks. Specifically, you now need to know a valid topic ID: https://github.com/hashgraph/hedera-mirror-node/blob/master/hedera-mirror-rest/monitoring/monitor_apis/config/sample.serverlist.json#L32

This is a challenge when using the monitor to automate networks that have regular state resets.

**Solution**
Either remove the reliance on specific topic IDs, or allow the check to be disabled.

**Comment by steven-sheehy** [comment]
It is already optional. You can omit the topic id and all topic messages will be skipped. We should consider populating it for testnet and mainnet though.

**Comment by beeradb** [comment]
👍 thanks. My apologies! I think this can be closed.
