### ISSUE TITLE
RecordStreams - cater for genesis event

### ISSUE THREAD

**Issue by gregscullard** [hashgraph/hedera-mirror-node#119]
When the networks are upgraded a record file will contain a `previousHash` which will be 0 (or a string of 0s), this needs to be accommodated for as the genesis event.

-Add a parameter (to the database ?) indicating this is anticipated (AwaitRecordGenesis=true)
-While parsing record files, if `AwaitRecordGenesis ==true` and `previousHash==000..000` continue processing as per normal, record `000.....0000` hash as the previous hash.
-When this occurs, set `AwaitRecordGenesis ` to false and store so that future such hashes result in an error.

**Comment by steven-sheehy** [comment]
Stale
