### ISSUE TITLE
EventStreams - cater for genesis event

### ISSUE THREAD

**Issue by gregscullard** [hashgraph/hedera-mirror-node#120]
When the networks are upgraded an event file will contain a `previousHash` which will be 0 (or a string of 0s), this needs to be accommodated for as the genesis event.

-Add a parameter (to the database ?) indicating this is anticipated (AwaitEventGenesis=true)
-While parsing record files, if `AwaitEventGenesis ==true` and `previousHash==000..000` continue processing as per normal, record `000.....0000` hash as the previous hash.
-When this occurs, set `AwaitEventGenesis ` to false and store so that future such hashes result in an error.

**Comment by steven-sheehy** [comment]
We don't support events currently
