### ISSUE TITLE
Optimise sorting in records/balance/events downloader

### ISSUE THREAD

**Issue by gregscullard** [hashgraph/hedera-mirror-node#121]
A fix to sort the `sigFiles` array was implemented in PRs #111 and #116, but could be done better as follows

Update `Downloader.downloadSigFiles()` by using TreeSet instead of List for `sigFiles`. Even better would be to use Guava's Multimap to let it manage the internal data structure:

```
Multimap<String, File> sigs = TreeMultimap.create();
sigs.put("foo.rcd_sig", new File("bar"));
sigs.put("foo.rcd_sig", new File("baz"));
Collection<File> files = sigs.get("foo.rcd_sig");
```

**Comment by apeksharma** [comment]
Sorting efficiently would be important if the number of items being sorted. We only ever sort ~100 items. Optimizing sorting of sigFiles in downloader will probably save few ms and won't be worth our time.
Let's close this one.
