### ISSUE TITLE
TimescaleDB: Update docs with support information

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-mirror-node#1310]
**Problem**
Timscaledb usage and access especially in Kubernetes cluster may differ from base Postgres configs.
Docs need to be updated where they differ

**Solution**
- Updated install doc
- Update configuration doc
- Update operation doc
- Update main readme doc

**Alternatives**

**Additional Context**
Kubernetes and psql commands that aid in operation checks may be useful to add

**Comment by steven-sheehy** [comment]
Closing. We will update docs once we choose a distributed database
