### ISSUE TITLE
TimescaleDB: Update DB User Permissions

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-mirror-node#1387]
**Problem**
Currently the main user on the db servers as the owner and therefore has extra permissions not needed.
We want to lock this down further and ensure permissions are intentionally set only as needed.

**Solution**
- Create a new schema on init
- Create importer users as a reader/writer not owner
- Grant explicit permissions for select and connect to users and roles in new schema
- Update init job in helm chart to apply above

**Alternatives**

**Additional Context**
See PR #1359 for comments

**Comment by steven-sheehy** [comment]
Fixed by #1364
