### ISSUE TITLE
Tweak database initialization process for security and ease of use

### ISSUE THREAD

**Issue by mike-burrage-hedera** [hashgraph/hedera-mirror-node#140]
The database user for the mirror node shouldn't require CREATEROLE permission in the postgresql database, and shouldn't create the API user.

We shouldn't be modifying the `postgres` database at all.

This eliminates the DB/user-creation steps from the code and leaves that to admin/ops.

It makes it trivial to fully create a brand new DB and just attach existing users to it without having to get hacky (if we have a restart for example).

The flow should be:

1. documented postgresql calls to create the database and users and enough grants to have flyway do the migration, but no other permissions on the accounts (no superuser or createrole)
2. when the app runs, flyway creates the schema within the database - but no users are created here

Tasks:

- The README should document the postgresql steps to be run as an admin user on the database host (create db, create users if not exists, grant all on db to the flyway/writer user)
- Update config.json.sample to not have dbUser as postgres and not have postgres in the db url. something like hedera_mirror_node or hederamirror or something as the default. User should be similar (hedera_mirror_node, hedera_mirror_node_api) with same username/password or with "pass" appended.
- Eliminate all references to that dbuser and `postgres` (database name) in the code.
- Remove V1.0 db script since it has the user create in it.
- Create a replacement V1.0.0.1 db script that does the exact same thing as V1.0 except that it doesn't have the create user and skip the entirety of the script if any of the known/common tables exists.

**Comment by steven-sheehy** [comment]
This ship has sailed long ago. We'll correct the user creation in the V2 schema during the migration to TimescaleDB.
