### ISSUE TITLE
Monitor delay and repeat

### ISSUE THREAD

**Issue by tomzhenghedera** [hashgraph/hedera-mirror-node#1405]
In addition of running load test on a profile with a single TPS level, two more profiles would be added:

* sine wave profile (can be constructed with ramp-up, steady for a short period, ramp-down, cooling down period(very low TPS), and then ramp up, minimally 2 round trips, more depends on requested test duration)
* phased profile(for example, load, spike/stress, cool down/idle, load(may be different from first load phase but less than stress), load phases needs to be long duration)

currently these load profiles could be implemented by combining separate monitor test configs and pods used as 
load generators but somewhat difficult to control and to manage.

**Comment by steven-sheehy** [comment]
I think this can be accomplished with a number of related but separate features:

- Ramp up period #1396 
- Cool down period
- Start delay
- Repeat interval
