### ISSUE TITLE
TimescaleDB: Explore Hosting Options

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-mirror-node#1422]
**Problem**
TimescaleDB offers multiple support options in terms of host location of the db.
We could have it in the k8s cluster, or utilize Timescale Cloud or even a vm host

**Solution**
Explore the options and make a recommendation on which based on our current deployment architecture and needs

**Alternatives**

**Additional Context**
Option should be cloud provider agnostic to support various customer scenario support.
Additionally, it should support our distributed scaling and load balancing scaling

Take into account
- Pricing costs
- Overhead of DB Management service

**Comment by steven-sheehy** [comment]
After contrasting the different options and presenting them to operations, we've decided on going forward with Timescale Cloud for production environments and the performance environment while the TimescaleDB single Helm chart will be used for non-prod.
