### ISSUE TITLE
timescaledb-multinode attach data node job may fail

### ISSUE THREAD

**Issue by xin-hedera** [hashgraph/hedera-mirror-node#1441]
**Detailed Description**
The attach data node job in timescaledb-multinode chart may fail during deployment.

**Actual Behavior**
1. run helm install with timescale enabled
2. check the status of the attach data node jobs, sometimes they fail

**Expected Behavior**
The attach data node job should succeed.

**Environment:**
- timescaledb-multinode version: 0.7.0

**Additional Context**

**Comment by steven-sheehy** [comment]
Switching to single node chart in #1439 so this will no longer be applicable
