### ISSUE TITLE
Accessing Transactions for Smart Contracts by contract ID returns empty response on Testnet mirror node.

### ISSUE THREAD

**Issue by digantgarude** [hashgraph/hedera-mirror-node#1541]
**Detailed Description**
**Related to :**  Smart contract transaction response on Hedera mirror node. 

**Actual Behavior**
I received an empty response for transaction info of Smart contracts on Hedera Testnet Mirror Node.

The smart contract transactions are however visible on Dragonglass and Kabuto.

**Steps to reproduce the behavior:**

Following is the test smart contract ID that I have:

Hitting this endpoint : Returns an empty response.

https://testnet.mirrornode.hedera.com/api/v1/transactions?account.id=0.0.257846

But Dragonglass page shows info for smart contract transactions.
https://testnet.dragonglass.me/hedera/contracts/0.0.257846

**Expected Behavior**
Transactions for smart contracts using their contract Id show be returned.

**Comment by steven-sheehy** [comment]
Hi @digantgarude. It might not be quite clear from the name, but the `account.id` parameter specifies the payer account ID who paid for the smart contract execution. We don't currently have a standalone `contracts` REST API like DragonGlass that you could use to search for the smart contract ID itself. You can find your transactions if you plug in the payer ID:

https://testnet.mirrornode.hedera.com/api/v1/transactions?account.id=0.0.198260

**Comment by steven-sheehy** [comment]
Going to close this, but feel free to reopen if you feel there is still an issue that needs to be addressed.
