### ISSUE TITLE
Transactions REST API account filter does not include sender and receiver token transfers

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-mirror-node#1587]
**Detailed Description**
Transactions REST API with an `account.id` parameter (`api/v1/transactions?account.id=0.0.x`) currently returns HBAR crypto transfer transactions where the account shows up as a payer, sender, or receiver. However, if those crypto transfers only include token transfers then it only returns accounts that match the payer account.

**Actual Behavior**
1. With payer `0.0.11093`, submit hbar + token transfers (could also just do hbar only) sending and receiving to `0.0.365339`:
https://testnet.mirrornode.hedera.com/api/v1/transactions?account.id=0.0.365339
2. Since `0.0.365339` shows up in every hbar transfer every transaction shows up.
3. With payer `0.0.11093`, submit token only transfers sending and receiving to `0.0.365346`:
https://testnet.mirrornode.hedera.com/api/v1/transactions?account.id=0.0.365346
4. Only the create account shows up

**Expected Behavior**
Account filter should include token transfers for sender and receiver.

**Environment:**
- Version: 0.27.0

**Additional Context**

**Comment by timmolter** [comment]
Just to clarify with some examples:
```
/api/v1/transactions?account.id=0.0.116946

{"consensus_timestamp":"1613855139.028011000","transaction_hash":"wb7VAxCZQUcLg9qmSVR+t4x1+5ilXya/am4S6RVUYM0UBDJDkjITSMaiLY2RG+4O","valid_start_timestamp":"1613855127.453656373","charged_tx_fee":646493,"memo_base64":"bWFtYQ==","result":"SUCCESS","name":"CRYPTOTRANSFER","max_fee":"100000000","valid_duration_seconds":"120","node":"0.0.9","transaction_id":"0.0.116946-1613855127-453656373","transfers":[{"account":"0.0.9","amount":45462},{"account":"0.0.98","amount":601031},{"account":"0.0.116946","amount":-646493}],

"token_transfers":
[{"token_id":"0.0.107762","account":"0.0.117030","amount":1}
,{"token_id":"0.0.107762","account":"0.0.116946","amount":-1}
]},

/api/v1/transactions?account.id=0.0.117030

???
```
For the account `0.0.116946` we can see that it transferred 1 token to account `0.0.117030`.

```
{"token_id":"0.0.107762","account":"0.0.117030","amount":1}
```
However, using `/api/v1/transactions?account.id=0.0.117030` doesn't show the incoming token transaction.

As a side note, this REST endpoint does show incoming and outgoing transactions for normal HBAR transactions. The bug is that incoming token transactions are missing.

**Comment by timmolter** [comment]
Any ETA on this fix?

**Comment by ijungmann** [comment]
> Any ETA on this fix?

Code to fix this has been merged.
