### ISSUE TITLE
TOKENASSOCIATE transaction in REST api doesn't include the associated Token Id/account relationship

### ISSUE THREAD

**Issue by gregscullard** [hashgraph/hedera-mirror-node#1590]
**Detailed Description**

The REST response for a TOKENASSOCIATE transaction doesn't include the token Id and Account that were involved in the transaction (note: the payer could be different to the account being associated).

**Actual Behavior**

Query: https://testnet.mirrornode.hedera.com/api/v1/transactions?timestamp=1613665608.839086000
notice the TOKENASSOCIATE transaction doesn't include the token or account being associated.

**Expected Behavior**

The account and token pair being associated is included in the response.
The query should return the pair whether the payer and associated accounts are the same or not.
The query should return the pair if the `account.id` is being associated.

**Environment:**

N/A

**Additional Context**

N/A

**Comment by steven-sheehy** [comment]
You can query for what tokens are associated with an account already using /api/v1/tokens?account.id=. I don't think we need to modify the generic transaction API to add token account specific fields to it that don't apply to most transaction types. https://mainnet.mirrornode.hedera.com/api/v1/tokens?account.id=116946

**Comment by steven-sheehy** [comment]
#1594 and #1586 have been addressed. We also have #1639 to expose the entity ID. Closing this.
