### ISSUE TITLE
Handle unrecognized transaction types and result ids

### ISSUE THREAD

**Issue by mike-burrage-hedera** [hashgraph/hedera-mirror-node#168]
**Detailed Description**

In the t_transactions table, the fk_trans_type_id and fk_result_id should be the raw values from the transaction/transactionrecord.

If they are the raw value the system won't halt when encountering a new result_id or transaction_type_id in the data stream and won't insert "unknown" and lose the information (the unrecognized transaction_type or result). It'll get inserted fine. The only issue would be in translating that to human readable text on the query side (REST API).

- replace these fields with transaction_type_id and result_id. The raw values of the appropriate sizes (smallint?)
- upgrade the data (set the raw value on the existing data based on the data in the t_transaction_types/result_types tables)
- replace the reference data tables with simple tables that map the raw id to text; no sequences
- modify the inserts on the java side, including elimination of the caching of that id-to-text mapping for both results and transaction types.
- modify the queries on the REST API side (to also handle the case where the mapping of raw ID to text is missing)
- schedule the elimination of the (now-deprecated) columns for a subsequent release, but eliminate the foreign key constraint and indexes now. keeping these columns around, nullable, for 1 more release makes the upgrade process safer (we won't lose data during it)

**Actual Behavior**

**Expected Behavior**

**Environment:**

**Additional Context**

**Comment by apeksharma** [comment]
How often does platform (or services?) add new txn types or result ids?

**Comment by apeksharma** [comment]
Very good detailed description!

Two minor questions.
>replace the reference data tables with simple tables that map the raw id to text; no sequences 

you mean keep proto_id and name and remove id column, right?
```
id   proto_id   name
1	-1	UNKNOWN
18	23	FREEZE
2	14	CRYPTOTRANSFER
```

> upgrade the data (set the raw value on the existing data based on the data in the t_transaction_types/result_types tables)

This will be flywheel migration, right?

**Comment by mike-burrage-hedera** [comment]
Yes, don't use postgresql sequences for identifiers, use the protobuf value for ID.

Also - It may not be trivial to have the java code handle unrecognized transaction types, but:
  - the database can use just the protobuf ID and not the DB-generated ID
  - this isn't a problem for result code enum

We will still have a problem if new transaction types are added (on the mirror-node's java-side), but not result code (and a DB change won't be required if we can eventually work around the issue for transaction type, with a hack). The value for transaction type ID isn't directly exposed by the protobuf library.
