### ISSUE TITLE
Querying Credit Type Transfers for a recipient account does not retrieve token transfers

### ISSUE THREAD

**Issue by georgiyazovaliiski** [hashgraph/hedera-mirror-node#1686]
**Detailed Description**
Querying Credit Type Transfers for a recipient account does not retrieve token transfers. On the other hand, querying Debit Type Transfers for the sender works OK.

**Actual Behavior**
1. Create a token
2. Associate an account to the token
3. Transfer some token units to the account
4. Query this:
http://testnet.mirrornode.hedera.com/api/v1/transactions?account.id=0.0.xxxxxx&result=success&order=desc, where xxxxxx is the account number

**Expected Behavior**
I expected to get not only the crypto transfer list from the query, but the token_transfers object, whenever a token transfer has occurred.

**Comment by ijungmann** [comment]
Reopening this ticket, the issue exists in the `type` query parameter (credit or debit), using that parameter causes a separate query to build that does not have the logic added in #1587, though the fix needed for this will likely look very similar.
