### ISSUE TITLE
Transaction type testing

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-mirror-node#169]
**Problem**
We should ensure we're testing all types of HAPI transaction types. Currently we just run it in a real environment so we have no guarantee about correctness of handling the various types.

**Solution**
Create detailed, automated JUnit tests to check entities of all types are created/updated/marked for deletion, that file data is created, updated, marked for deletion, same for smart contracts.

**Alternatives**
Manual testing by sending real transactions to testnet.

**Additional Context**
N/a

**Comment by gregscullard** [comment]
I have created a utility which uses the SDK to generate a number of sample transactions, output below. From this I have four record files which we can use to test parsing.

[GeneratedTxOutput.txt](https://github.com/hashgraph/hedera-mirror-node/files/3579542/GeneratedTxOutput.txt)
