### ISSUE TITLE
Change cucumber reporting plugin

### ISSUE THREAD

**Issue by ijungmann** [hashgraph/hedera-mirror-node#1796]
**Problem**
We currently have a [dependency that is being archived 5/1/2021.](https://gitlab.com/monochromata-de/cucumber-reporting-plugin/-/tree/master).

**Solution**
Swap the plugin out for an alternative, or remove altogether if the plugin is no longer needed.

**Additional context**
Identified in [this bump](https://github.com/hashgraph/hedera-mirror-node/pull/1782)

**Comment by steven-sheehy** [comment]
This was completed in https://github.com/hashgraph/hedera-mirror-node/pull/2292
