### ISSUE TITLE
Downloaders: Inconclusive error logging

### ISSUE THREAD

**Issue by gregscullard** [hashgraph/hedera-mirror-node#180]
**Detailed Description**
Errors such as
`./mirrorNode.log-2019-09-02-1.log:468784:2019-09-02 04:32:36,578 ERROR [main ] c.h.d.RecordFileDownloader Failed downloading recordstreams/record0.0.10/2019-09-02T04_32_25.122613Z.rcd_sig after 35.86 ms` and `
./mirrorNode.log-2019-09-01-1.log:29:2019-08-31 10:58:05,333 ERROR [main ] c.h.d.AccountBalancesDownloader Error downloading balance files` appear in the logs, they are not conclusive as to the reason for the error.

**Expected Behavior**
Errors should include additional information to aid fault finding.

**Comment by steven-sheehy** [comment]
No longer relevant
