### ISSUE TITLE
Optimize Timescaledb migration script

### ISSUE THREAD

**Issue by ijungmann** [hashgraph/hedera-mirror-node#1820]
**Problem**
[This PR](https://github.com/hashgraph/hedera-mirror-node/pull/1798) added some fixes to the timescaledb migration script, however some optimization could still be done.

**Solution**

- Find a way to handle the column order mismatch that does not require an explicit column list in the restore script (this becomes a maintenance burden as time goes on).  Some suggestions include using pg_dump instead of COPY commands, as it provides a way to pull the column headers with the data, as well as using `header true` for the copy commands.
- It may also be worthwhile to investigate using the Flyway CLI for parts of the migration, instead of just referencing the Flyway migration in part of the script, as this causes the Flyway migration to be run twice (the migrations are written in a way that this does not impact anything, so this is not as critical).

**Comment by steven-sheehy** [comment]
Closing as not needed since column names won't change once we have a permanent environments.
