### ISSUE TITLE
/transactions API is slow

### ISSUE THREAD

**Issue by atul-hedera** [hashgraph/hedera-mirror-node#183]
**Detailed Description**
The /transactions API uses an inner query to filter the transactions based on the user parameters and then uses an outer query to get the details of those selected transactions. This query does not perform very well - and takes long (in seconds) depending on whether the requested account id exists or not. 

This query needs to be optimized.

**Actual Behavior**
1. Query /transactions based on various account ids - existent and non-existent and ranges

**Expected Behavior**
The query should return in ~ 1 second

**Environment:**
- Version: [e.g. 0.1.0]

**Additional Context**
 Seeking a help of PostgreSQL expert for this.

**Comment by mike-burrage-hedera** [comment]
@atul-hedera Please add the exact types of queries that are causing the performance problems and we need to see if end-users are actually hitting those cases.

**Comment by mike-burrage-hedera** [comment]
Closing the investigation - #220 should be the fix. Please reopen this if @gregscullard or @atul-hedera are still working on investigating further
