### ISSUE TITLE
Records and events versioning handling

### ISSUE THREAD

**Issue by gregscullard** [hashgraph/hedera-mirror-node#184]
Hi, we have been reviewing code around processing event and record files and are somewhat confused over the different version numbers and how they are handled in the code.

There seem to be similar constant declarations for version numbers (legacy, current, etc...) and in processing the file the check is performed on version >= current.

Can you explain the different version constants ? (They are now in a separate class called FileDelimiters.java to ensure they are only declared in one place)
What happens when CURRENT is no longer current ?
Should we fail processing if the version doesn't match a known version, replacing >= with == and raising an error/failing if the version is unknown.
Many thanks

**Comment by gregscullard** [comment]
Hi, we have been reviewing code around processing event and record files and are somewhat confused over the different version numbers and how they are handled in the code.

There seem to be similar constant declarations for version numbers (legacy, current, etc...) and in processing the file the check is performed on version >= current.

1. Can you explain the different version constants ? (They are now in a separate class called `FileDelimiters.java` to ensure they are only declared in one place)
2. What happens when CURRENT is no longer current ?
3. Should we fail processing if the version doesn't match a known version, replacing >= with == and raising an error/failing if the version is unknown.

Many thanks

**Comment by QianSwirlds** [comment]
Hi @gregscullard 

`EVENT_STREAM_VERSION ` is the version of the format we serialize each event;
`EVENT_STREAM_START_NO_TRANS_WITH_VERSION `, `EVENT_STREAM_START_WITH_VERSION`, and `EVENT_COMM_EVENT_LAST ` are delimiters in `EVENT_STREAM_VERSION `(2)

`EVENT_STREAM_FILE_VERSION` is the version of the format we generate each eventStream file. there is a `EVENT_STREAM_FILE_VERSION_LEGACY`  (2), and a `EVENT_STREAM_FILE_VERSION_LEGACY` (3). These two file version use the same `EVENT_STREAM_VERSION`(2) , the only difference is the way we calculating eventStream file Hash.

If current version is no longer current, we can reformat it to be `..._LEGACY_3`;

sure, please raise an error/failing if the version is unknown.

Please let me know if you have any questions, thanks.
