### ISSUE TITLE
Use multi-arch builds for Docker to support Apple M1

### ISSUE THREAD

**Issue by rbair23** [hashgraph/hedera-mirror-node#1842]
**Problem**
I am unable to run the mirror node software on my Apple MacBook Pro M1. It crashes in the OpenJDK JVM.

**Solution**
The underlying issue is that the M1 is an ARM-based system, whereas the images we're generating and the JDK we're using are AMD64-based containers. The [documentation from Docker](https://docs.docker.com/docker-for-mac/apple-m1/) suggests that the solution is in building multi-arch images using the tool "buildx". Docker has [GitHub actions](https://docs.docker.com/ci-cd/github-actions/) to handle this.

Perhaps the solution to supporting M1 (and any other ARM architecture such as the Raspberry PI) would be to use these Docker github actions to build multi-arch images.

**Alternatives**
We could use buildx manually and not use the github action. We could also not support ARM, and have people use a VM (perhaps on the local machine, perhaps on a cloud provider) to run the mirror nodes. This seems less desirable as it raises the level of difficulty to use our software or contribute to it.

**Comment by steven-sheehy** [comment]
Jib has [support](https://github.com/GoogleContainerTools/jib/blob/master/docs/faq.md#how-do-i-specify-a-platform-in-the-manifest-list-or-oci-index-of-a-base-image) for multi-arch images. It has some limitations like building to a local Docker so we wouldn't be able to enable it by default, but we can try enabling for push to registry.

I'm not sure about docker-maven-plugin. We can probably do it there with matrix github actions and specifying different base images for each.
