### ISSUE TITLE
Acceptance tests should use validated network nodes

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-mirror-node#1852]
**Problem**
Occasionally a node IP may change or go down. 
In test environment this can be cumbersome with the current limitation of only 1 node in the acceptance test.

**Solution**
At start up, the tests should use the available config as a bootstrap and validate each node for availability.
For prod environments the tests should pull the latest file `0.0.102` details and validate that list.
Validated nodes should be used to create the final SDK client for use by all tests.

As part of this the config logic should be updated to take a list of nodes (similar to the monitor module) instead of only 1

**Alternatives**
Update module to take list of nodes but don't pull new address book 

**Additional Context**

**Comment by steven-sheehy** [comment]
- Use SDK hardcoded IPs for public env to bootstrap
- For non-public env use a list of IPs. Can just populate a single ip:port
- On start, always download 0.0.102 using bootstrap IPs
- Loop over each node in address book and verify it's reachable, removing unreachable
- Use reachable IPs from address book for tests
