### ISSUE TITLE
/accounts API call returns a consensus timestamp that doesn't apply to all returned fields

### ISSUE THREAD

**Issue by mike-burrage-hedera** [hashgraph/hedera-mirror-node#186]
**Detailed Description**

The /accounts REST API request returns account attributes such as:

- public key
- balance
- expiry
- autorenew time

As well as a consensus timestamp (consensus_ns), making it appear that the consensus timestamp is for all of the fields, when in fact it only applies to the balance.

**Actual Behavior**

**Expected Behavior**

Some distinction in the API response (structure of the response) to indicate that the account_balances is tied to the consensus_ns but nothing else is.

**Environment:**

**Additional Context**

**Comment by atul-hedera** [comment]
The connseus_timestamp is already attached to the balance sub-object in the JSON response. Here's an example response: 
{
   "accounts": [
       {
           "balance": {
               "timestamp": "1567381500.036376000",
               "balance": 78325556
           },
           "account": "0.0.37031",
           "expiry_timestamp": null,
           "auto_renew_period": 2592000,
           "admin_key": {
               "_type": "ProtobufEncoded",
               "key": ""
           },
           "key": {
               "_type": "ED25519",
               "key": "5dc0eb34028a1a98260478044b9e5191b1bf77cd67cb7d9d08bd29a19bd6b358"
           },
           "deleted": false,
           "entity_type": "account"
       }
   ],
   "links": {
       "next": null
   }
}
