### ISSUE TITLE
Entities: Missing database fields

### ISSUE THREAD

**Issue by gregscullard** [hashgraph/hedera-mirror-node#189]
**Detailed Description**
Some data is missing from entities in the database.

We have:
- ID (all entities)
- deleted (all entities)
- proxyAccountID (all entities)
- key (account, file)
- admin_key (contract)
- expirationTime (all entities)
- autoRenewPeriod (account, contract)
- memo (all entities)

We are missing
- ~proxyReceived~ (account) No such data in transactions or records. Only in state and queries
- ~generateSendRecordThreshold~ (account)
- ~generateReceiveRecordThreshold~ (account)
- ~receiverSigRequired~ (account)
- ~size~ (file) No such field
- ~storage~ (contract) Covered by #1237
- ~contractAccountId~ (contract) - solidity format. Not in transaction or record. Can be generated locally from contractID
- ~AccountID~ (contract) Contracts also have an associated account id, that probably needs to be reflected through a self-reference

**Actual Behavior**
Mirror node doesn't reflect the complete set of properties of an entity

**Expected Behavior**
Mirror node reflects the complete set of properties of an entity

**Environment:**

**Additional Context**
This information will not have been populated for entities loaded prior to this issue being addressed. A one-off data pull operation (using getInfo HAPI on entities below a given number may be required to bring this information into the database).

**Comment by mike-burrage-hedera** [comment]
How much of this data is absolutely required for OA?

**Comment by gregscullard** [comment]
Unsure whether this is strictly require by OA, however the longer we wait, the more data there will be to backfill.

**Comment by Nana-EC** [comment]
Updated.

Moved memo to what we have.
Highlighted deprecated fields.

Also some of these items might be better situated under a new/exiting entity type table - similar to `token`, `file_data`.
Most of this predated the `topic`, `token` and `schedule` entities.

**Comment by steven-sheehy** [comment]
Closing as we now have all relevant field mentioned in description.
