### ISSUE TITLE
Database connection: Flyway failure results in repeated connection pool failures.

### ISSUE THREAD

**Issue by gregscullard** [hashgraph/hedera-mirror-node#190]
**Detailed Description**
In the event that flyway fails to migrate the database to a new version, an error message indicating a connection cannot be established repeats over and over again.

**Actual Behavior**
Introduce a failure in the database migration process, launch a process that requires a database connection, logs are rapidly filling up with unable to connect messages.

**Expected Behavior**
Upon failure to migrate, an error should indicate this is the case and the launched process should stop. Otherwise, it requires scrolling up through the log files to figure out that the database connection is in fact ok (the process could connect), but the flyway migration failed.

**Environment:**

**Additional Context**

**Comment by mike-burrage-hedera** [comment]
Did the flyway error happen on 0.1.0 upgrade?
What was the database failure that caused the migration issue?

**Comment by apeksharma** [comment]
Decreasing priority to P3 since hasn't happen in months.
On connection failure, flyway retires every 1 second which seems appropriate periodicity.
As for count of retries, we can change from default (infinite) to to say 60 (try a minute).

**Comment by steven-sheehy** [comment]
If flyway migration fails, we want it to retry indefinitely. The application should never just stop.
