### ISSUE TITLE
Rosetta scheduled transaction support

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-mirror-node#1919]
**Problem**
The Rosetta module may not contain support for scheduled transaction.

**Solution**
- Ensure Rosetta module can return scheduled transactions via its API.
- Add tests that verify support
- If applicable, enhance Rosetta so that any future transaction type is automatically supported assuming no custom API changes are necessary

**Alternatives**

**Additional Context**

**Comment by xin-hedera** [comment]
close as there's no use case
