### ISSUE TITLE
List Blocks REST API

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-mirror-node#1933]
**Problem**
HIP-415 is codifying the concept of blocks in relation to the Hedera network. The mirror node should expose block information via its REST API for use by bridges and other clients.

**Solution**
A new list block REST API will be added to support the ability to search for block information. Note it only contains aggregate information about the blocks. It’s expected that users use the returned information like timestamps to query the transaction or contract results REST APIs for details about the transactions within the block.

Add a `/api/v1/blocks` API:

```json
{
  "blocks": [{
    "count": 4,
    "gas_used": 50000000,
    "hapi_version": "0.24.0",
    "hash": "0xa4ef824cd63a325586bfe1a66396424cd33499f895db2ce2292996e2fc5667a69d83a48f3883f2acab0edfb6bfeb23c4",
    "logs_bloom": "0x549358c4c2e573e02410ef7b5a5ffa5f36dd7398",
    "name": "2022-04-07T16_59_23.159846673Z.rcd",
    "number": 19533336,
    "previous_hash": "0x4fbcefec4d07c60364ac42286d5dd989bc09c57acc7370b46fa8860de4b8721e63a5ed46addf1564e4f8cd7b956a5afa",
    "size": 8489,
    "timestamp": {
      "from": "1649350763.159846673"
      "to": "1649350763.382130000"
    }
  }],
  "links": {
    "next": null
  }
}
```

Note: `logs_bloom` and `gas_used` depend upon https://github.com/hashgraph/hedera-mirror-node/issues/3584 being implemented first.

Query parameters:

- `block.number` - The block number. Used as the primary key in pagination. Maps to `record_file.index`. Supports `eq`, `gt`, `gte`, `lt`, `lte` operators.
- `limit` - The maximum number of results to return. Defaults to 25 and max 100 allowed.
- `order` - Sort by the block number. Value of `asc` or `desc`  with a default of `desc`.
- `timestamp` - The consensus timestamp of the last transaction in the block. Supports `eq`, `gt`, `gte`, `lt`, `lte` operators. Maps to `record_file.consensus_end`.

**Alternatives**
A `/api/v1/records`

**Additional Context**

**Comment by steven-sheehy** [comment]
I don't think `/api/v1/records/info` is needed. To get the latest you can use the previous `/api/vi/records?limit=1&order=desc`.

**Comment by Kalina-Todorova** [comment]
Assigned to @natanasow
