### ISSUE TITLE
Expand non_fee_transfer table support for failed transactions 

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-mirror-node#1936]
**Problem**
In #1620 users highlighted `non_fee_transfers` table was missing intent for transactions that failed

**Solution**
Expand support by
- Add a `success` (true|false) column to table to allow for distinguishing of transfers
- Insert into `non_fee_transfers` table on failed transactions
- ~[Stretch]Insert to `non_fee_transfer` by default~

**Alternatives**

**Additional Context**
In #1620 users "It seems that if a transaction fails there are no records stored on the non_fee_transfer table - so the original intent of the transfer is lost." and "Always store original transfer info to the non_fee_transfer table."

**Comment by steven-sheehy** [comment]
> Add a success (true|false) column to table to allow for distinguishing of transfers

This isn't necessary since we already store if a transaction is successful in the transaction table. We shouldn't repeat ourselves.

**Comment by steven-sheehy** [comment]
Closing since customer no longer exists and we don't expose non_fee_transfer on any API
