### ISSUE TITLE
Integration tests for the REST API

### ISSUE THREAD

**Issue by mike-burrage-hedera** [hashgraph/hedera-mirror-node#202]
Create integration tests for the REST API and integrate them with CI. REST API to postgres integration.

Currently if you clone the repo, cd rest-api, npm test - all 4 tests fail.

We need a way for local development and for CI integration to:
- stand up a postgresql instance
- upgrade it to the latest schema
- seed any data needed for testing
- run integration/function tests against the REST API against the database

If the existing (failing) tests can use a mocked out database and become unit tests instead - that's also a good step (#201 requires unit testing of the REST API)

**Comment by calvinchengx** [comment]
This is related to #72
