### ISSUE TITLE
docker-compose.yml components

### ISSUE THREAD

**Issue by bert2002** [hashgraph/hedera-mirror-node#2024]
Hi,
are all components that are configured in the `docker-compose.yml` needed to run a Hedera Mirror node or just some services?

Thanks,
bert

**Comment by steven-sheehy** [comment]
Depends upon your use case. The only truly required components are a database (postgres or timescale) and the importer. Redis is required with the default config but you can disable its use on the importer and grpc. gRPC, REST and Rosetta are various APIs you can optionally run depending upon your use case. The monitor is just for monitoring and can be omitted.

**Comment by bert2002** [comment]
Thanks @steven-sheehy , the thing is `monitor` is complaining not to find nodes and wondering if it was really needed.
