### ISSUE TITLE
Monitoring infrastructure for mirror nodes

### ISSUE THREAD

**Issue by atul-hedera** [hashgraph/hedera-mirror-node#204]
**Problem**
We need a monitoring infrastructure for the mirror nodes.
**Solution**
It should detect when anything fails in the pipeline from the files in S3 collector to the parser to DB to the REST APIs.

**Alternatives**
Manual monitoring

**Comment by steven-sheehy** [comment]
There's some overlap with #81 in that if we get metrics for downloading and parsing and push to elasticsearch, ops team can then alert off those metrics.
