### ISSUE TITLE
Investigate the possible failure in  transaction monitoring test on testnet

### ISSUE THREAD

**Issue by atul-hedera** [hashgraph/hedera-mirror-node#205]
**Detailed Description**
Reported by Lionel: The transaction monitoring tool had detected a failure in the test that went away by itself. Need to investigate if this is a real issue with the rest apis or with the DB, or an issue with the test.

**Actual Behavior**
Unknown - it was seen once

**Expected Behavior**
The tests should not fail

**Environment:**
- Version: 0.1.1

**Additional Context**
<img width="1434" alt="Screen Shot 2019-09-04 at 6 59 17 PM" src="https://user-images.githubusercontent.com/53272623/64351786-c8680f00-cfaf-11e9-8206-293ee1cf425f.png">

**Comment by atul-hedera** [comment]
There are duplicate transactions in the record stream. These need to be handled. Otherwise, several things will break: the response from the rest apis, pagination logic that counts number of returned transactions, query of a single transaction using /transactions/:id, etc. Here's the db query:

postgres=>  select t.fk_payer_acc_id, t.valid_start_ns, t.consensus_ns, tr.result from t_transactions t
postgres->     join t_transaction_results tr on t.fk_result_id = tr.id
postgres->  where consensus_ns<=1567648650140377010 and consensus_ns>=1567648650140376999;
 fk_payer_acc_id |   valid_start_ns    |    consensus_ns     |        result         
-----------------+---------------------+---------------------+-----------------------
            6772 | 1567648640025000000 | 1567648650140377002 | DUPLICATE_TRANSACTION
            6772 | 1567648640025000000 | 1567648650140377001 | SUCCESS
(2 rows)

**Comment by mike-burrage-hedera** [comment]
I see that there are duplicates and that's a bug.
How does the alert on the monitor of "Transaction Ids don't match" lead to this being the problem?

**Comment by atul-hedera** [comment]
Hi Mike,

Sorry, I should have explained it:

The test that I had was as follows: I first do a /transactions request (see the first function below getTransactionosNoParams). I store the timestamp in the first returned transaction (the most recent transaction). To be exact, I store the entire result of the first query in ‘testTransactions’ variable.

Then, in the second function (checkTransactionsWithTimestamp), I do a query for transactions where timestamp < testTransactions[0].consensus_timestamp;
And if the system worked correctly, the returned list should be exactly same as the first list offset by 1. So I check for the transaction-id of 2nd entry in the original (no-timestamp) request and compare against the transaction-id of the 1st entry in the ‘timestamp < testTransactions[0].consensus_timestamp’ query.

When this query happens to be executed when there are duplicates, the second result also has the same transaction id (not offset by 1).

You can see that these 2 queries return exactly the same transaction-id for the 1st entry:
http://35.243.216.157:5551/api/v1/transactions?timestamp=lt:1567648650.140377002<https://nam03.safelinks.protection.outlook.com/?url=http%3A%2F%2F35.243.216.157%3A5551%2Fapi%2Fv1%2Ftransactions%3Ftimestamp%3Dlt%3A1567648650.140377002&data=02%7C01%7Catulmahamuni%40hedera.com%7Cb6ee14d53ef24417b78708d731a7ffee%7Cfc4ba5c9edb540698216b30b59828750%7C1%7C0%7C637032469953019236&sdata=0H93LVcCn3SH%2F9HDIy7lJGlndkN4HrCPAJ8QeRL%2FmzA%3D&reserved=0>

http://35.243.216.157:5551/api/v1/transactions?timestamp=lte:1567648650.140377002<https://nam03.safelinks.protection.outlook.com/?url=http%3A%2F%2F35.243.216.157%3A5551%2Fapi%2Fv1%2Ftransactions%3Ftimestamp%3Dlte%3A1567648650.140377002&data=02%7C01%7Catulmahamuni%40hedera.com%7Cb6ee14d53ef24417b78708d731a7ffee%7Cfc4ba5c9edb540698216b30b59828750%7C1%7C0%7C637032469953019236&sdata=ZC3sXtZykqOpcKurIuTB1ys78HSihaNqPPHutvivpz8%3D&reserved=0>

Here’s my test code snippet:


/**

 * Executes the /transactions API with no parameters

 * @param {Object} server The server to run the test against

 * @return {} None. updates testTransactions variable

 */

const getTransactionsNoParams = async (server) => {

        const url = getBaseUrl(server);

    const response = await fetch(url);

        const data = await response.json();



        common.logResult (server, url, 'getTransactionsNoParams',

                (data.transactions.length === 1000) ?

                {result: true, msg: "Received 1000 entries"} :

                {result: false, msg: "Received less than 1000 entries"});



        const txSec = data.transactions[0].consensus_timestamp.split('.')[0];

        const currSec = Math.floor(new Date().getTime() / 1000);

        const delta = currSec - txSec;



        common.logResult (server, url, 'getTransactionsNoParams',

                (delta < (60 * 20)) ?

                {result: true, msg: "Freshness: Received data from " + delta + " seconds ago"} :

                {result: false, msg: "Freshness: Got stale data from " + delta + " seconds ago"});



        testTransactions = data.transactions;

}



/**

 * Executes the /transactions API with timestamp filter

 * @param {Object} server The server to run the test against

 * @return {} None.

 */

const checkTransactionsWithTimestamp = async (server) => {

        const url = getBaseUrl(server) + '?timestamp=lt:' + testTransactions[0].consensus_timestamp;

    const response = await fetch(url);

    const data = await response.json();



        common.logResult (server, url, 'checkTransactionsWithTimestamp',

                (data.transactions.length === 1000) ?

                {result: true, msg: "Received 1000 entries"} :

                {result: false, msg: "Received less than 1000 entries"});





    common.logResult (server, url, 'checkTransactionsWithTimestamp',

                (data.transactions[0].transaction_id ===

                testTransactions[1].transaction_id) ?

                {result: true, msg: "Transaction Ids matched"} :

                {result: false, msg: "Transaction Ids don't match"});

}

**Comment by atul-hedera** [comment]
Hi Mike,

There is one more failure: the API is returning less than 1000 transactions. And that is also because I query for 1000 distinct timestamps (consensus_ns), but because the successful and the duplicate transactions get merged into a single list, the API is returning less than 1000 transactions.  That’s the “Received less than 1000 entries” error message in the  first test  (getTransactionsNoParams)  below.

Thanks,
-- atul

From: Atul Mahamuni <atulmahamuni@hedera.com>
Date: Thursday, September 5, 2019 at 9:33 PM
To: hashgraph/hedera-mirror-node <reply@reply.github.com>, hashgraph/hedera-mirror-node <hedera-mirror-node@noreply.github.com>
Cc: Assign <assign@noreply.github.com>
Subject: Re: [hashgraph/hedera-mirror-node] Investigate the possible failure in transaction monitoring test on testnet (#205)

Hi Mike,

Sorry, I should have explained it:

The test that I had was as follows: I first do a /transactions request (see the first function below getTransactionosNoParams). I store the timestamp in the first returned transaction (the most recent transaction). To be exact, I store the entire result of the first query in ‘testTransactions’ variable.

Then, in the second function (checkTransactionsWithTimestamp), I do a query for transactions where timestamp < testTransactions[0].consensus_timestamp;
And if the system worked correctly, the returned list should be exactly same as the first list offset by 1. So I check for the transaction-id of 2nd entry in the original (no-timestamp) request and compare against the transaction-id of the 1st entry in the ‘timestamp < testTransactions[0].consensus_timestamp’ query.

When this query happens to be executed when there are duplicates, the second result also has the same transaction id (not offset by 1).

You can see that these 2 queries return exactly the same transaction-id for the 1st entry:
http://35.243.216.157:5551/api/v1/transactions?timestamp=lt:1567648650.140377002<https://nam03.safelinks.protection.outlook.com/?url=http%3A%2F%2F35.243.216.157%3A5551%2Fapi%2Fv1%2Ftransactions%3Ftimestamp%3Dlt%3A1567648650.140377002&data=02%7C01%7Catulmahamuni%40hedera.com%7Cb6ee14d53ef24417b78708d731a7ffee%7Cfc4ba5c9edb540698216b30b59828750%7C1%7C0%7C637032469953019236&sdata=0H93LVcCn3SH%2F9HDIy7lJGlndkN4HrCPAJ8QeRL%2FmzA%3D&reserved=0>

http://35.243.216.157:5551/api/v1/transactions?timestamp=lte:1567648650.140377002<https://nam03.safelinks.protection.outlook.com/?url=http%3A%2F%2F35.243.216.157%3A5551%2Fapi%2Fv1%2Ftransactions%3Ftimestamp%3Dlte%3A1567648650.140377002&data=02%7C01%7Catulmahamuni%40hedera.com%7Cb6ee14d53ef24417b78708d731a7ffee%7Cfc4ba5c9edb540698216b30b59828750%7C1%7C0%7C637032469953019236&sdata=ZC3sXtZykqOpcKurIuTB1ys78HSihaNqPPHutvivpz8%3D&reserved=0>

Here’s my test code snippet:


/**

 * Executes the /transactions API with no parameters

 * @param {Object} server The server to run the test against

 * @return {} None. updates testTransactions variable

 */

const getTransactionsNoParams = async (server) => {

        const url = getBaseUrl(server);

    const response = await fetch(url);

        const data = await response.json();



        common.logResult (server, url, 'getTransactionsNoParams',

                (data.transactions.length === 1000) ?

                {result: true, msg: "Received 1000 entries"} :

                {result: false, msg: "Received less than 1000 entries"});



        const txSec = data.transactions[0].consensus_timestamp.split('.')[0];

        const currSec = Math.floor(new Date().getTime() / 1000);

        const delta = currSec - txSec;



        common.logResult (server, url, 'getTransactionsNoParams',

                (delta < (60 * 20)) ?

                {result: true, msg: "Freshness: Received data from " + delta + " seconds ago"} :

                {result: false, msg: "Freshness: Got stale data from " + delta + " seconds ago"});



        testTransactions = data.transactions;

}



/**

 * Executes the /transactions API with timestamp filter

 * @param {Object} server The server to run the test against

 * @return {} None.

 */

const checkTransactionsWithTimestamp = async (server) => {

        const url = getBaseUrl(server) + '?timestamp=lt:' + testTransactions[0].consensus_timestamp;

    const response = await fetch(url);

    const data = await response.json();



        common.logResult (server, url, 'checkTransactionsWithTimestamp',

                (data.transactions.length === 1000) ?

                {result: true, msg: "Received 1000 entries"} :

                {result: false, msg: "Received less than 1000 entries"});





    common.logResult (server, url, 'checkTransactionsWithTimestamp',

                (data.transactions[0].transaction_id ===

                testTransactions[1].transaction_id) ?

                {result: true, msg: "Transaction Ids matched"} :

                {result: false, msg: "Transaction Ids don't match"});

}

**Comment by atul-hedera** [comment]
This bug caused two failures in the tests that monitor the REST APIs:

1. Because of the (incorrect) aggregation based on the of the duplicate transaction-IDs,  the resultant response of the /transactions API has less than 1000 entries. 
This caused the test that checks for 1000 entry response to fail.

2. There is a test that makes 2 queries - one without any timestamp constraint and the second with a timestamp < {timestamp of first entry returned by the first query}.  And it expects that the responses for these two API calls are offset by 1 transaction. 

If the test is run between the successful and duplicate transactions, this test will 
fail as well.

The screenshot attached showed that the transaction-id didn't match (Problem#2 above). 
Subsequent testing observed that the check for 1000 entries fails as well.
