### ISSUE TITLE
Relocate domain cache and update logic for cleaner insert and update processing

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-mirror-node#2098]
**Problem**
Currently the domain update logic as well as cache management is spread amongst multiple classes.
This results in `SqlEntityListener` having to be concerned with cache management and as a result updates to items in cache.
~Additionally some updates are done in transaction handlers and others in the EntityListener implementations .~

**Solution**
- Consolidate cache management into `EntityRecordItemListener` since this has access to transactionahndler logic
- Update EntityListener interface to allow `OnX` methods to take a list instead of single items. In this way cache can be built up and full list of domain objects passed to `SqlEntityListener` and other implementations for persistence only
- ~Update `EntityRecordItemListener` to contain all logic to create and update domain objects.~

**Alternatives**
- Don't update EntityListener interface to allow `OnX`
- Other approaches welcome e.g. #2123

**Additional Context**
This shouldn't result in any performance changes but should improve code cleanliness and readability

**Comment by steven-sheehy** [comment]
I don't think the approach in this ticket is ideal. Instead, we should convert all parsing classes to be stateless. A context object should be created (or perhaps use the `RecordItem`) and passed through the layers. It should contain the collections of objects to be batched inserted and any caches uses for the lifecycle of processing the record file. That way the classes stay stateless and the state gets thrown away for the next file.

**Comment by steven-sheehy** [comment]
Closing for the reasons noted above.
