### ISSUE TITLE
I get failed While setting up mirror node from GCP market place. 

### ISSUE THREAD

**Issue by designOm** [hashgraph/hedera-mirror-node#2106]
<div id="content"><div class="tabs "><nav class="tabs-navigation"><ul class="tabs-menu" role="tablist"><li class="tabs-menu-item json is-active" role="presentation"><span class="devtools-tab-line"></span></li></ul></nav></div></div><span class="devtools-tab-line"></span><span class="devtools-tab-line"></span><div id="json-panel" style="visibility: visible; height: 100%;" class="tab-panel-box" role="tabpanel" aria-labelledby="json-tab"><div class="tab-panel json"><div class="jsonPanelBox tab-panel-inner"><div class="toolbar"></div></div></div></div><div id="json-panel" style="visibility: visible; height: 100%;" class="tab-panel-box" role="tabpanel" aria-labelledby="json-tab"><div class="tab-panel json"><div class="jsonPanelBox tab-panel-inner"><div class="toolbar"><div class="devtools-separator"></div><input class="searchBox devtools-filterinput" placeholder="Filter JSON"></div><div class="panelContent">
&nbsp; | &nbsp;
-- | --
kind | "Status"
apiVersion | "v1"
metadata | {}
status | "Failure"
message | "forbidden: User \"system:anonymous\" cannot get path \"/\": No policy matched."
reason | "Forbidden"
details | {}
code | 403

</div></div></div></div>

**Comment by steven-sheehy** [comment]
Thanks for your report. We need some more information to investigate. What version is your kubernetes cluster and what configuration options did you choose when setting it up? Where do you see this error? Can you provide the yaml output of the Kubernetes LoadBalancer services (`kubectl get service -A -o yaml`)?

**Comment by steven-sheehy** [comment]
Closing due to lack of response. Note we do have a new marketplace version 0.37.1 out you can try.
