### ISSUE TITLE
Importer UpsertGenerator Improvements

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-mirror-node#2122]
**Problem**
There's some valuable imrpovements that can be added to the UpsertGenerator classes.
To reduce code churn in a recent [PR 2006](https://github.com/hashgraph/hedera-mirror-node/pull/2006) these were left out

**Solution**
- Dynamically lookup `TABLE ` and `TEMP_TABLE ` via `EntityType.getName()`
- Dynamically determine `nullableColumns` by looking at `SingularAttribute.isOptional()`
- Dynamically determine `conflictTargetColumns ` by looking at `SingularAttribute.isId`
- Determine `updatableColumns` determine this dynamically from attributes on SingularAttribute and potentially adding custom annotations to the domain fields. Let's consider for a follow up.
- Automate conflictTargetColumns for v2 schema by adding `created_timestamp` to all domain objects that have it. Also add `Auditable` interface similar to spring that may be applied to updatable domains. This may result in dropping those tables as hyper tables

Additionally minor items to other classes
- Consider `metric.record(() -> someAction(foo))` to avoid  2 methods per action

**Alternatives**

**Additional Context**

**Comment by steven-sheehy** [comment]
This was completed as part of #2840
