### ISSUE TITLE
Remove Duplicate Cache & Merge Logic for updatable domains

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-mirror-node#2123]
**Problem**
Currently `SQLEntityListener` manages a cache for updatable domains and merges new additions to ensure a single item Ito the temp table during PgCopy.
This ensures efficiencies on insert but results in some duplication fo effort as `insert ... on conflict (do nothing)` also removed some duplicates

**Solution**
- Remove cache and merge logic and leave it to DB to filter out duplications
- Update UpsertGenerators to ensure sql where clauses pick up the right rows per operation
- Update RecordEntityItemListener to prevent unnecessary OnEntity() calls for the entity being created

**Alternatives**

**Additional Context**

**Comment by steven-sheehy** [comment]
This was mostly completed by #2840 and the `GenericUpsertQueryGenerator`. We could still optimize `SqlEntityListener` to automate the merge functions but probably more effort than it's worth right now.
