### ISSUE TITLE
Run DB migrations from deliverable without starting the mirror-node

### ISSUE THREAD

**Issue by mike-burrage-hedera** [hashgraph/hedera-mirror-node#214]
**Problem**

We should be able to run a migrations-only process during upgrades, potentially while the previous version of the mirror-node is running.

To minimize the amount of time nodes are down during deployment.

We should be aiming for 0 downtime deployments.

**Solution**

Script to run mirror-node migration without actually starting to process files/downloads.

**Alternatives**

Install flyway command line on all the deployed environments and work with it that way

**Additional Context**

**Comment by steven-sheehy** [comment]
I don't think this is necessary and adds unnecessary complexity when we have zero downtime (with time delay) already with our failover environment. If the db upgrade takes awhile that's fine as it's occuring in the unused environment.
