### ISSUE TITLE
Upsert pgcopy flow attempt to create already present temp table

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-mirror-node#2154]
**Detailed Description**
When a file with a transaction count greater than the batch count is processed the upsert pgcopy flow will attempt to create the temp table when it already exists, causing an Exception to be thrown e.g.
```com.hedera.mirror.importer.exception.ParserException: Error copying 4 items to table entity_temp```

**Actual Behavior**
1. Submit a transaction record with more transactions than the batch size
2. Run parser
3. ParserException thrown

**Expected Behavior**
No issues

**Environment:**
- Java: [e.g. OpenJDK 11.0.4]
- Node: [e.g. v12.9.1-x86]
- OS: [e.g. Ubuntu 18.04]
- Version: 0.36.0-rc1

**Additional Context**
Add any other context about the problem here. Attach any logs here, if applicable.

**Comment by steven-sheehy** [comment]
This is completed.
