### ISSUE TITLE
Unit tests for monitoring

### ISSUE THREAD

**Issue by mike-burrage-hedera** [hashgraph/hedera-mirror-node#227]
The /rest-api/monitoring needs unit tests to make sure it is properly identifying successful vs unsuccessful conditions (results of polling the API).

Also - add it to CI.

**Comment by Nana-EC** [comment]
This preceded and was mostly addressed by the monitoring rewrite of #332 

The only non addressed item is putting monitoring tests into CI. This may not be necessary with integration tests coverage

**Comment by steven-sheehy** [comment]
Added CI part to #424
