### ISSUE TITLE
REST API: /transactions/ID doesn't return the expected transaction

### ISSUE THREAD

**Issue by gregscullard** [hashgraph/hedera-mirror-node#230]
**Detailed Description**
Querying for a transaction ID via the REST api doesn't return the expected result.

**Actual Behavior**
The following transaction ID exists in the database:

```
   id    | fk_node_acc_id | memo | fk_trans_type_id | fk_result_id | consensus_seconds | consensus_nanos | fk_payer_acc_id | charged_tx_fee | initial_balance | fk_cud_entity_id | fk_rec_file_id |   valid_start_ns    |    consensus_ns
---------+----------------+------+------------------+--------------+-------------------+-----------------+-----------------+----------------+-----------------+------------------+----------------+---------------------+---------------------
 9119529 |              1 | \x   |               14 |           24 |        1568118285 |       222910000 |               2 |        8404260 |         1000000 |           957406 |        1347767 | 1568118274068528000 | 1568118285222910000
```

query `http://35.222.234.122:5005/api/v1/transactions/0.0.2-1568118274.68528000`
or
query `http://35.222.234.122:5005/api/v1/transactions/0.0.2-1568118274.068528000`

returns `Not found`

**Expected Behavior**
The API request should return the transaction for this transaction Id.

**Environment:**

**Additional Context**

**Comment by mike-burrage-hedera** [comment]
@gregscullard is fk_payer_account_id 2 the account "0.0.2"? That's an autogenerated ID column, not necessarily the account ID.

**Comment by gregscullard** [comment]
Closing, due to user issue.
