### ISSUE TITLE
Remove maxDownloadItems

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-mirror-node#231]
**Problem**
`maxDownloadItems` option was added to chunk the downloads into batches so that the parser could run after downloader and add that batch to the database. With the removal of combined downloader/parser mode, this option is no longer relevant.

In fact, setting a low `maxDownloadItems` reduces the efficiency of downloader by having to listObjects more often instead of a single listObjects with paging.

**Solution**
Remove the config option and anywhere that uses it.

**Alternatives**
Keep it but set it to `Integer.MAX_VALUE` by default.

**Additional Context**
It was used as a workaround for a race condition #195 but ended up slowing down processing so much that records could never catch up.

**Comment by steven-sheehy** [comment]
Actually, this option is still relevant as it will download all of a single node first before moving to the next node without this option. Thus this is dependent on parallel S3 downloading (#74) being implemented first.

**Comment by gregscullard** [comment]
Agreed
