### ISSUE TITLE
REST API. /transactions/{} api requires that nanoseconds are zero padded

### ISSUE THREAD

**Issue by gregscullard** [hashgraph/hedera-mirror-node#233]
**Problem**
the transactions api accepts an account number, seconds and nanoseconds (which make up a transaction ID). The nanoseconds has to be left padded to 9 digits. e.g.

works: `/api/v1/transactions/0.0.2-1568118274-068528000`
doesn't work: `/api/v1/transactions/0.0.2-1568118274-68528000`

note the missing `0` leading the nano seconds.

**Solution**
the REST API formats the provided nano seconds as required for query purposes, this burden shouldn't be on the user of the api.

**Alternatives**

**Additional Context**

**Comment by mike-burrage-hedera** [comment]
If this is a unique ID for the transaction represented as a string - in the format we've decided, there should be a single format - with the 9 digit nanoseconds.

From a REST/caching perspective there should be a single unique identifier for the object.
Same thing for accounts. We don't need to support "00.00.02" for account IDs.

**Comment by gregscullard** [comment]
IMO the 0 padding imposes a burden on clients that is unnecessary and could lead to queries not returning data when they should. The generated transaction ID in the SDK returns a numerical value for nanos that could be 1234. If we have decided to internally store 1234 as 000001234, that's our choice. Being the transaction ID supplied to the rest api is separated by dashes we can easily pad the nanos to 9 digits and make this entirely transparent to the client.

**Comment by mike-burrage-hedera** [comment]
The string is a format we define. Keep it in a single canonical form and it is the one and only unique identifier (in the rest-api) for that transaction.

**Comment by steven-sheehy** [comment]
This is now fixed in master.
