### ISSUE TITLE
BalanceFileLogger logs misleading

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-mirror-node#235]
**Detailed Description**
The BalanceFileLogger (and related classes) show it processed 0 balance files after it finishes processing a balance file. This is because it processes the latest balance file first, then processes the rest in ascending order in a different method. It should just sort the balance files in descending order and process them in one method to simplify things and show the correct count.

**Actual Behavior**
One file put in valid balance folder. The logs show 0 balance files completed

**Expected Behavior**
The logs show 1 balance file completed

**Environment:**
- Version: v0.1.1

**Additional Context**
```
Sep 10 21:45:07 mirrornode-mainnet-2 java[3330]: 2019-09-10 21:45:07,494 INFO  [main ] c.h.m.d.AccountBalancesFileLoader Starting processing account balances file /var/lib/mirror-node/accountBalances/valid/2019-09-10T21_45_00.181240Z_Balances.csv
Sep 10 21:45:08 mirrornode-mainnet-2 java[3330]: 2019-09-10 21:45:08,936 INFO  [main ] c.h.m.d.AccountBalancesFileLoader Successfully processed account balances file /var/lib/mirror-node/accountBalances/valid/2019-09-10T21_45_00.181240Z_Balances.csv with 14829 records in 1.442 s
Sep 10 21:45:08 mirrornode-mainnet-2 java[3330]: 2019-09-10 21:45:08,939 INFO  [main ] c.h.b.BalanceFileLogger Completed processing 0 balance files in 103.5 μs
```

**Comment by gregscullard** [comment]
That behaviour was because we were originally logging the latest balances in one table, and the rest in a history table.
If we're not doing that anymore, we can process them in alphabetical order.
