### ISSUE TITLE
Importer uses incorrect startDate in no stream file case with startDate set

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-mirror-node#2355]
### Description

`MirrorDateRangePropertiesProcessor.newDateRangeFilter()` seems to have a regression and returns `Instant.EPOCH` when startDate is set and no stream file is present.

Expected: Importer to start at `hedera.mirror.importer.startDate`
Actual: Importer starts at `Instant.EPOCH` 

### Steps to reproduce

1. Set `hedera.mirror.importer.startDate` to greater than `Instant.EPOCH` 
2. Start new importer on empty database

### Hedera network

testnet

### Version

v0.38.0-rc1

### Operating system

macOS

**Comment by steven-sheehy** [comment]
I can't reproduce this. Can you provide your application.yml and logs? Most likely the start date is not getting set properly.
