### ISSUE TITLE
LiveHashes - missing deleted flag

### ISSUE THREAD

**Issue by gregscullard** [hashgraph/hedera-mirror-node#243]
**Problem**
Livehashes do not have a deleted indicator in the database, it is therefore not possible to indicate that a previously stored live hash is now deleted.

There is no java code to delete a live hash

**Solution**
Either:
-Add a deleted boolean to the database and add the java code to manage
or
-Add java code to simply delete the hash rather than mark it as deleted.

**Alternatives**

**Additional Context**
Not urgent, live hashes aren't supported at OA.

**Comment by mike-burrage-hedera** [comment]
Closing in favor of #303 (includes requirement for duration field).
