### ISSUE TITLE
Split and denormalize entity table into sub entity tables

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-mirror-node#2646]
### Problem

Currently the db schema for entities is a mix and match.
The entity table needs to be consulted often for complete specific entity info.
Additionally the importer also performs many inserts of partial entity info. These duplicate insert attempts consume resources and grow as the entity table grows in size.

The REST API is plagued by many joins with large tables than need entity info.
These adversely affect both write (importer) and read (APIs) performance. 

### Solution

Distribute current entity table columns to their more appropriate entity type tables.
This reduces the number of columns in the `entity` table making joins lighter and in some cases should reduce need to add a join. This will allow for cleaner distribution of data in the multi node scenarios that will come with db v2 schema.

* #2784
* #2785
* #2786
* #2787
* #2788

### Alternatives

Use an inheritance model in which common columns remain in `entity` table and select statements pull from both specific and general entity table

**Comment by steven-sheehy** [comment]
After splitting contract out we later realized it was better to remain in entity and merged them again in #4150. Splitting causes too much duplication and decreases performance when needing to search across multiple types. Better to keep as separate until an inheritance model can be utilized.
