### ISSUE TITLE
Citus: Update docker-compose flow 

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-mirror-node#2684]
### Problem

The `docker-compose.yml` can be used to spin up the mirror node modules as services. 
Currently it utilizes only the postgres image for the db service

### Solution

Add support for citus 

- Add a `citus_single` service for single node mode
- Add a `citus_multi` service for multi node mode
- Add an additional init script to
  - add user roles across coordinator and worker nodes in multimode scenario
  - connect worker nodes to coordinator (if not successfully connected on startup)

**Comment by steven-sheehy** [comment]
Closing since compose supports citus now.
