### ISSUE TITLE
Citus: Explore multi-cloud deployment solution

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-mirror-node#2688]
### Problem

In an effort to increase decentralization, security and compatibility, deployments must support multi cloud options. As of now Citus PasS is only supported on Azure. Azure Arc can be used to deploy multi-cloud but it incurs a per-CPU cost on top of the cloud resource costs.

### Solution

* Investigate and document pricing of Azure Arc with one or more of the configurations mentioned in #2685
* Install Azure Arc in GCP
* Install a `Azure Cosmos DB for PostgreSQL` instance

### Alternatives

Explore manual configuration on a Kubernetes resource to support citus.
Note challenges of coordination around HA and replication details

**Comment by edwin-greene** [comment]
Link to an Azure Arc demo:

https://drive.google.com/drive/u/0/folders/1dJI3cQ2jwDZDQYLgoJs6unDu1TN9SxzP

**Comment by edwin-greene** [comment]
Pricing:

A price calculator can be found here: 
https://azure.microsoft.com/en-us/pricing/calculator/?service=cosmos-db

Estimate for [Coordinator - 8 vCores / 32 GiB RAM, 0.5 TiB storage, Workers: 4 vCores / 32 GiB RAM, 1 TiB storage]: 

- Single region (US East)
- About 40% savings by signing a year long agreement
- High Availability

$3,155.65/month


Each region has slightly different pricing, for example US West is priced at $3,882.55 for the same configuration.

**Comment by edwin-greene** [comment]
Current limitations of Azure Arc and PostgreSQL: 

https://learn.microsoft.com/en-us/azure/azure-arc/data/limitations-postgresql

-No Restore after a Backup.
-No High Availability.

**Comment by steven-sheehy** [comment]
We will go with a Kubernetes native based approach due to the above.
