### ISSUE TITLE
Paths in mirror node are not windows compliant

### ISSUE THREAD

**Issue by gregscullard** [hashgraph/hedera-mirror-node#281]
**Detailed Description**
Mirror node won't run on windows due to paths generally assuming a unix format with forward slashes.

**Actual Behavior**
Run mirror node on windows and errors occur due to invalid path names.

**Expected Behavior**
Mirror node should run on any operating system that supports Java.

**Environment:**
- OS: Windows
- Version: 0.2.0 rc4

**Additional Context**

**Comment by steven-sheehy** [comment]
Yep, always use `Path` and `Paths.get("foo", "bar")`

**Comment by steven-sheehy** [comment]
Support for Windows was added in v0.36.0 with a CI check added for verification.
