### ISSUE TITLE
Scale testing from DB-to-front-end

### ISSUE THREAD

**Issue by atul-hedera** [hashgraph/hedera-mirror-node#282]
**Problem**
Test the performance, at scale, of the Database and front-end transactions (query performance).

We need to test the mirror node for 1 year of anticipated data (in the database). At 4 TPS (mainnet throughput), we will have ~ 125M transactions, and ~ 625M cryptotransferlist entries. We should create tests that validate the infrastructure including DB and queries to ensure we can handle this volume and the rest-api queries still perform well against the DB with that much data in it.

**Comment by mike-burrage-hedera** [comment]
- create the test data to simulate the year's worth of data
- run end-to-end tests to quantify the system's performance against that data
