### ISSUE TITLE
Some rest APIs may show incorrect balance / transfer amount

### ISSUE THREAD

**Issue by xin-hedera** [hashgraph/hedera-mirror-node#2830]
### Description

Account balance (both hbar and tokens) and crypto / token transfer amount may be incorrect in rest API response.

The rest APIs format most balance and transfer amount as a number and in the js code, the value is converted to a js `Number` before JSON stringified by `express`.

Unfortunately, due to js number precision limit, any integer larger than js `Number.MAX_SAFE_INTEGER` may show up incorrectly.

The affected APIs include `/accounts`, `/balances`, `/tokens`, and `/transactions`.

### Steps to reproduce

Query the rest APIs for

1. accounts with balance (hbar or tokens)
2. transactions with transfer amount
3. tokens with certain account holding balance

greater than js `Number.MAX_SAFE_INTEGER`

### Hedera network

testnet

### Version

v0.43.0

**Comment by steven-sheehy** [comment]
Fixed by https://github.com/hashgraph/hedera-mirror-node/pull/3719
