### ISSUE TITLE
Revisit contract metadata table Citus distribution column

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-mirror-node#2867]
### Problem

There is some debate on the contract metadata tables `contract_result`, `contract_log` etc and which column is should be distributed on for optimal write and read.

Currently most contract executions have been performed by ACCOUNT entity types and not CONTRACTs.
This has led for the choice of `payer_account_id` as the distribution of choice with colocation with `entity`.
This would provide node clustering on contract execution information by the payer living alongside its entity row.

However, this may result in cross node queries for many of the `api/v1/contract/{id}/...` endpoints since they will be joining to pull `transaction`, `record` and sometimes `contract` information.

### Solution

Revisit the column choice

Consider the questions
- How does the choice of `payer_account_id` as the distribution column and colocation with `entity` spread data out? 
- Will this encourage or discourage clustering of related information (transaction, contract, file, record)?
- Will this result in cross node querying for `api/v1/contract/{id}/...` endpoints?
- How does this compare to the alternatives?

The goal should be to chose a distribution column that
- splits the data somewhat evenly across nodes - historic and future data should be collectively considered
- positions shards close to related information to avoid cross node queries
- supports joins with related tables

### Alternatives

Distribution options include.

1. distribute on `payer_account_id`, colocate with `transaction` since `contract_result` and company are more related to transactions/transfers than the entity `CONTRACT`. Db nodes will now have contract executions and the transaction rows on the same nodes. On joins do where `transaction.entity_id = contract_result.conract_id`.
2. distribute on `contract_id` and colocate with `contract`. Db nodes will now have contract executions and the contract row on the same nodes. On joins do where `transaction.entity_id = contract_result.conract_id`. This is useful when pulling entity info for a transfer which we won't do much under the contract metadata APIs.
3. distribute on `payer_account_id` and colocate with `entity`. Db nodes will now have contract executions funded by a payer on the same nodes as the payers entity row. 
4. ...

**Comment by steven-sheehy** [comment]
Will close and do performance testing to verify which distribution approach is more appropriate.
