### ISSUE TITLE
/transactions query is slow on mainnet with account.id range 

### ISSUE THREAD

**Issue by atul-hedera** [hashgraph/hedera-mirror-node#288]
This query takes over 5 seconds on mainnet: /transactions?account.id=gt:18000&account.id=lt:19900

**Detailed Description**
transactions query with account id range takes long.

**Actual Behavior**
1. Query "/transactions?account.id=gt:18000&account.id=lt:19900" on mainnet

**Expected Behavior**
It should return in under 1 second

**Environment:**
- Version: [e.g. 0.2.0]

**Comment by mike-burrage-hedera** [comment]
Ask Mike about the DB Schema design doc.

**Comment by Nana-EC** [comment]
Reviewed Mike doc on DB schema long term goal.
Per my understanding to deal with this issue we'd "Replace t_cryptotransferlists.account_id (referencing t_entities) with account_realm_num, and account_num"

The reason being it'd shorten he number of table joins needed to get the account num and real num that are part of the account.id that is specified in the query.

This would require a replace of the column for all current entries in the DB.
Also an update of the internal rest-api logic in transactions.js which creates the sql query
@mike-burrage-hedera let me know if that's what you were going for.
