### ISSUE TITLE
Convert top level REST module files into Route, Controller and Service files

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-mirror-node#2913]
### Problem

Currently the top level files in the `Hedera-mirror-rest` module contain  logic that handles REST API logic form the http call all the way to the db call.
This includes http -> query param extraction, business logic and then db query logic.

The lack of separation makes the files bloated and difficult to manage and test.

### Solution

The top level files in the `Hedera-mirror-rest` module should be split up into
- Routes
- Controllers
- Services

These files currently include
- [ ] `accounts.js`
- [ ] `balances.js`
- [ ] `schedules.js`
- [ ] `stateproof.js`
- [ ] `tokens.js`
- [ ] `topicmessage.js`

### Alternatives

Split this into separate tickets for each file

**Comment by steven-sheehy** [comment]
Closing in favor of https://github.com/hashgraph/hedera-mirror-node/issues/1699
