### ISSUE TITLE
Support ECDSA signing via Rosetta API

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-mirror-node#2928]
### Problem

We currently only ED25519 signing via the Rosetta API. We should add support for the new ECDSA signing algorithm.

### Solution

Add support for ECDSA signing to construction API. May require Go SDK support first.

**Comment by xin-hedera** [comment]
close since ED25519 signing is sufficient for the current use cases, will reopen if ever needed by users
