### ISSUE TITLE
FileUpdate with no contents specified inserts null fileContents row

### ISSUE THREAD

**Issue by gregscullard** [hashgraph/hedera-mirror-node#294]
**Detailed Description**
When a file update transaction occurs and this transaction doesn't specify contents, a row containing no data is added to the fileData table.

Will discuss with engineering.

**Actual Behavior**
Run a fileUpdate transaction with no `fileContents` set, check the `t_file_data` table for this transaction, a row containing empty data has been created.

**Expected Behavior**
In the event a file update transaction contains no data, no row should be created.

**Environment:**
version 0.2.0-rc4

**Additional Context**
Add any other context about the problem here. Attach any logs here, if applicable.

**Comment by gregscullard** [comment]
We should also remove any rows from `t_file_data` where the `fileData` column is null as part of this bug fix.

**Comment by steven-sheehy** [comment]
We discussed as a team. We feel regardless if it's empty we should store the change in the file entity to show a history of changes over time.
