### ISSUE TITLE
Consistently high cloudsql replication lag

### ISSUE THREAD

**Issue by xin-hedera** [hashgraph/hedera-mirror-node#3022]
### Description

Cloudsql replication lag for testnet cloudsql instances has been on the increasing trend recently. It correlates with the increasing size of account balance files in testnet.

 PR #3000 tried to improve it by fixing the account balance file ingestion performance issue. However, counterintuitively, while the account balance file ingestion performance is improved by at least 4x, the cloudsql replication lag goes even higher. 

### Steps to reproduce

Compare the testnet cloudsql replication lag before and after 0.46.x deployment.

### Hedera network

testnet

### Version

v0.46.0

**Comment by xin-hedera** [comment]
Tested with a pg13 primary-replica cluster, data is restored from a full testnet pg9.6 dump. No more large replication lag when processing account balance files.

Note that pg13 does show more frequent small replication lags (up to 3 secs, most are 1-2 secs), however, the actual tx consensus timestamp to mirror node rest api lag is on the save level v.s. pg9.6 (excluding when processing account balance file). So it's possible in pg13 the replication lag stats reported by the db are more fine-grained.

**Comment by steven-sheehy** [comment]
Closing this out as ops is rolling out PostgreSQL 14 to testnet next week.
