### ISSUE TITLE
LiveHashes don't have duration and deleted columns

### ISSUE THREAD

**Issue by gregscullard** [hashgraph/hedera-mirror-node#303]
**Detailed Description**
The `t_livehashes` table doesn't include a duration or deleted column.

**Actual Behavior**
Inspect the `t_livehashes` table, witness the missing columns.

**Expected Behavior**
The `t_livehashes` table should include duration (long) and deleted (boolean) columns

**Environment:**
- Version: 0.2.0.rc4

**Additional Context**
Add any other context about the problem here. Attach any logs here, if applicable.

**Comment by steven-sheehy** [comment]
Looks to be a duplicate of #243 ?

**Comment by steven-sheehy** [comment]
Will revisit if livehashes ever gets implemented on the main nodes
