### ISSUE TITLE
Submit transaction timeout in Rosetta API

### ISSUE THREAD

**Issue by Ljzn** [hashgraph/hedera-mirror-node#3177]
### Description

![origin_img_v2_a77b83ce-c60f-4731-9cb7-88d3e6927f0h](https://user-images.githubusercontent.com/19494388/150309981-0b3412b7-3e28-4d98-8883-3c41f4b40ac2.png)

### Steps to reproduce

```
curl -v -H "Content-Type: application/json" -d '{"network_identifier":{"blockchain":"Hedera","network":"mainnet","sub_network_identifier":{"network":"shard 0 realm 0"}},"signed_transaction":"0x0ac4012ac1010a570a140a0c08a7e9a08f0610f7ecc6c101120418b3e125120218101880c2d72f220208783208393331333739363872280a0012240a041885e707120d0a0418b3e12510efb4d4ba8f0f120d0a041888b71110f0b4d4ba8f0f12660a640a207c59a27e57165ed204b699f9e0bedf83a17c205e33ba223fc6cd25cf094d84b71a40125cb3920ca7aae5fe8ebc67cf540e2eda085da09c5823eb609e6c3bac22d85f132fdc092ad0d1f33e1ee1fbf0c31092fef33e40715876c8b8825e07c83c8209","id":"1","jsonrpc":"2.0"}' .../construction/submit -X post
```

got 400 Bad Request

### Hedera network

mainnet

### Version

v0.45.0

**Comment by xin-hedera** [comment]
@Ljzn can you upgrade to the latest release v0.48.0? There are two issue behind it as of v0.45.0:

- the go sdk auto retry when submitting a transaction to the network by default is enabled, so in case the network node the transaction intended for is unhealthy, SDK will auto retry the transaction a predefined number of attempts
- newer release has SDK auto retry disabled. when hitting an unhealthy node, you need to reconstruct the transaction with the same operations, and usually the new transaction will set to use a different node

**Comment by steven-sheehy** [comment]
Closing due to staleness. Please let us know if you still encounter this issue.
