### ISSUE TITLE
/api/v1/transactions?account.id={accountId} is slow

### ISSUE THREAD

**Issue by xin-hedera** [hashgraph/hedera-mirror-node#3208]
### Problem

Load testing shows the rest endpoint `/api/v1/transactions?account.id={accountId}` is slow.

We should look into potential optimizations. In addition to the transactions query by just account id, we should also analyze and optimize `/api/v1/transactions?account.id={accountId}&timestamp={timestamp}`

### Solution

Profile the query and analyze the underlying SQL query.

**Comment by matheus-dallrosa** [comment]
The query being used by this mentioned route is using the appropriate indexes, and in the last 3 months there was no slow request on the `/api/v1/transactions` route. See https://mirrornode.grafana.net/goto/PnxB24Lnz?orgId=1 and select the `/api/v1/transactions` route.
