### ISSUE TITLE
HIP-336 NFT allowance REST API

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-mirror-node#3245]
### Problem

[HIP-336](https://hips.hedera.com/hip/hip-336) describes new APIs to approve and exercise allowances to a delegate account. An allowance grants a spender the right to transfer a predetermined amount of the payer's hbars or tokens to another account of the spender's choice. The mirror node should expose this data via its REST API.

### Solution

Add a `/api/v1/accounts/{idOrAliasOrEvmAddress}/allowances/nfts` as per the design doc.

**Comment by Ashe-Oro** [comment]
i think we need to either include both `approve` and `approveForAll` on the token or move both to the account. But consistency seems like the right play here.

**Comment by justynspooner** [comment]
This is still an issue as of 0.73.0.

We would like a simple way to list NFT allowances for an account that has used the `approveTokenNftAllowance` or `approveTokenNftAllowanceAllSerials` [allowance transactions](https://docs.hedera.com/hedera/sdks-and-apis/sdks/cryptocurrency/approve-an-allowance).

Currently, the only way to get this information is via the `spender` field on an nft and paginate through every NFT with a query such as:

https://testnet.mirrornode.hedera.com/api/v1/accounts/0.0.1792/nfts

This is still not 100% complete as the `spender` field doesn't get set when using `approveTokenNftAllowanceAllSerials`. So currently there is no way to check which NFTs have been affected by the "All Serial allowances" transaction. There is another issue open for that specific bug [here](https://github.com/hashgraph/hedera-mirror-node/issues/4346).

**Comment by AdriMsM91** [comment]
Good morning,

Yes, exactly. We need this, right now it's a bit frustrating and also If you use `approveTokenNftAllowanceAllSerials` you can't see anything... :(

**Comment by AdrianKBL** [comment]
Hello, any updates? @SimiHunjan we keep having issues with this and we can't check the Allowance...

**Comment by SimiHunjan** [comment]
hey @AdrianKBL ! Checked with the team and the current target is end of Q3/ early Q4.

**Comment by AdrianKBL** [comment]
Okey thanks for the response.

**Comment by vinaysingh8866** [comment]
Hey Guys, 
Any updates on this, our UX needs this functionality on karateka.io.

**Comment by steven-sheehy** [comment]
Thanks for your feedback. We will be working on the design for this API and a few other allowance related APIs this sprint as part of https://github.com/hashgraph/hedera-mirror-node/issues/7143. We'll be creating a HIP soon and will appreciate your feedback on it once it's available. 🙏🏻

**Comment by mgoelswirlds** [comment]
[Here](https://github.com/hashgraph/hedera-improvement-proposal/pull/857) is the HIP for the NFT allowance API. I would greatly appreciate any feedback.

**Comment by vinaysingh8866** [comment]
Thanks guys was waiting for this for long time, will add it next month and let you know if there's any feedback.

**Comment by steven-sheehy** [comment]
> Is this API still not released ?

Not yet. We're taking this opportunity to tackle some technical debt and this will be our first REST API written in Java instead of JavaScript. So this effort is taking a bit longer than usual. That said, a beta version of this API will be available in 0.104 for you to try and provide any feedback.
