### ISSUE TITLE
Add history table for token_account

### ISSUE THREAD

**Issue by xin-hedera** [hashgraph/hedera-mirror-node#3251]
### Problem

The current token account association and changes in the past are all saved in table `token_account` unlike the main table and history table for entities.

While this preserves all info, the query to get the token account snapshot at a specific time as well as the latest will become slower when the table grows bigger.

### Solution

Adopt the entity table and corresponding history table paradigm, update rest api query and rosetta query accordingly.

Per discussions with Xin and Steven:
`token_account` will drop `modifiedTimestamp`, have a new column `timestamp_range` and new primary key of `(token_id, account_id)`. `token_account_history` will have a primary key of `(token_id, account_id, timestamp_range)`

**Comment by edwin-greene** [comment]
Per discussions with Xin and Steven: 
`token_account` will drop `modifiedTimestamp`, have a new column `timestamp_range` and new primary key of `(token_id, account_id)`. `token_account_history` will have a primary key of `(token_id, account_id, timestamp_range)`
