### ISSUE TITLE
Upgrade to Spring Boot 2.2

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-mirror-node#329]
**Problem**
Spring Boot 2.2 was just [released](https://spring.io/blog/2019/10/16/spring-boot-2-2-0) and we should consider upgrading to it. 2.2 has reduced startup time and reduced memory usage. In addition, Spring Boot manages the versions of most of our 3rd party libraries so updating it will also bring in bug fixes and security improvements for everything else too.

**Solution**
- Update parent pom version to `2.2.0.RELEASE`
- Rework the junit dependencies as 2.2 comes with junit 5 by default
- Remove `@Named` from `@ConfigurationProperties` and add `@ConfigurationPropertiesScan`
- Set `spring.main.lazy-initialization=true` to improve startup performance
- Remove `MirrorNodeConfiguration.flywayCustomizer()`

**Alternatives**
Don't upgrade

**Additional Context**

**Comment by Nana-EC** [comment]
Are there any known risks and do you think it'd be a large PR or multiple PR's to make the change?
Those would help decide when to do it as your benefits seem good and suggest we should do it.

**Comment by steven-sheehy** [comment]
It will be a small PR and since it's a minor upgrade there shouldn't be any breaking changes. You could also argue it's a risk to not keep dependencies up to date.
