### ISSUE TITLE
Reformat Code

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-mirror-node#338]
**Problem**
The code contains a lot of inconsistencies with tabs being used in places and spaces in others, various line endings, indentations and other style formats. We should standardize this so we're all on the same format and not causing unnecessary churn on the code due to whitespace changes.

**Solution**
We now have [EditorConfig](https://editorconfig.org) support checked in and enforces some basic formats for all IDEs and some specific formats for just Intellij. We should use Intellij's ability to reformat all code at once and create a PR that contains only format changes. It won't fix everything and it won't enforce all standards across all IDEs, but it's a start.

**Alternatives**
- Leave as is
- Fix as we go

**Additional Context**

**Comment by mike-burrage-hedera** [comment]
Also - move recordFileLogger into `mirror` package during code reformat.

**Comment by steven-sheehy** [comment]
No, do not do move recordFileLogger as part of this PR. That is already covered in #339
