### ISSUE TITLE
Event stream v3 support

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-mirror-node#340]
**Problem**
There will be a v3 event stream file format that we need to eventually support.

**Solution**
Support all 3 event stream file formats.

**Alternatives**

**Additional Context**
See https://github.com/swirlds/platform-swirlds/issues/1519

**Comment by JeffreyDallas** [comment]
Event stream data format documentation link:

https://hederatest.sharepoint.com/:w:/s/Engineering/ES3CqUYSXR1Bjb5Zj-1hUI4Bd3s7il4IyyPOcp6DrAXnBw?e=CN6hzS

**Comment by steven-sheehy** [comment]
We don't support events currently
