### ISSUE TITLE
Support repeated topics for contract logs API

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-mirror-node#3505]
### Problem

The contract logs REST API supports `topic0`, `topic1`, `topic2`, `topic3` query parameters. If you supply multiple different topic parameters (e.g. `topic0` and `topic1`) it is considered an `AND` operation. `eth_getLogs` JSON-RPC also supports an OR operation like `[[A, B], [A, B]]` where it means (A OR B) in first position AND (A OR B) in second position.

### Solution

* Allow repeated topic query parameters e.g. `topic0=0x1234&topic0=0x5678`
* Treat repeated topics as OR filters

**Comment by Kalina-Todorova** [comment]
Assigned to @arrusev
