### ISSUE TITLE
Add from/to block parameters to contract log REST API

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-mirror-node#3506]
### Problem

`eth_getLogs` supports optional `fromBlock` and `toBlock` parameters to narrow down which blocks it should return results within.

### Solution

* Add a `block.from` query parameter to `/api/v1/contracts/{id}/results/logs`
* Add a `block.to` query parameter to `/api/v1/contracts/{id}/results/logs`
* Validate that both are non-negative integers
* Validate that `block.to` is greater than or equal to `block.from`
* Validate that the provided block range is within a period of at most `maxTimestampRange`
* If block range is provided, timestamp is not required since they both reduce time range
* If `block.from` is provided but not `block.to`, default `block.to` to now for validation purposes
* If `block.to` is provided but not `block.from`, throw an error
* If `block.from`, `block.to` and `timestamp` are all provided, reduce to minimum bounds and ensure it's within `maxTimestampRange`
* Filter log results using the mapped timestamps `[block.from.consensusStart, block.to.consensusEnd]`

**Comment by Kalina-Todorova** [comment]
Assigned to @arrusev

**Comment by Daniel-K-Ivanov** [comment]
We will need to add the same `from/to` parameters to the `/api/v1/contracts/results` endpoint as-well.

**Comment by steven-sheehy** [comment]
Closing this in favor of an extra call to `/api/v1/blocks?block.number=1&block.number=100`. Then the block timestamps can be passed to `/api/v1/contracts/{id}/results/logs?timestamp=gte:{block1.timestamp.from}&timestamp=lte:{block100.timestamp.to}`.
