### ISSUE TITLE
Add pagination to contract logs REST API

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-mirror-node#3581]
### Problem

The `/api/v1/contracts/{address}/results/logs` currently does not support pagination since it would've required a multi-column key.

### Solution

`/api/v1/contracts/{address}/results/logs` and `/api/v1/contracts/results/logs` API will be enhanced to support pagination. The existing `index` and `transaction` parameters will be used as the multi-column key and be set for subsequent requests in the `next` link. The `index` parameter cannot be present without the `timestamp` parameter. The index only applies within a given timestamp, not across timestamps.

**Comment by Kalina-Todorova** [comment]
@ar-conmit will pick this up next

**Comment by ar-conmit** [comment]
I have made a bit of research about this issue and it seems such functionality already exists.

We can use query parameter ```index``` in combination with ```timestamp``` to filter out contract logs

Example:
https://testnet.mirrornode.hedera.com/api/v1/contracts/0.0.34396093/results/logs?timestamp=gt:1651664958&timestamp=lt:1651664999&index=0

it works even with greater than or equal operation
https://testnet.mirrornode.hedera.com/api/v1/contracts/0.0.34396093/results/logs?timestamp=gt:1651664958&timestamp=lt:1651664999&index=gte:0

Two things are missing in the current implementation:
* if ```index``` is not provided as a query parameter then it is not used. There is no default value
* API swagger does not support things like ```gt, gte, lt, etc.```. It supports an integer only

**Comment by steven-sheehy** [comment]
> If the index parameter is NOT presented in the query, then:

To be clear, `index` is not required to be supplied by the user. But if there are more results to be paged then the next link we generate will always have both a `timestamp` and `index`.

> the next link should be null?  

The `next` link would not be null if there are more results.

> the endpoint behaviour should stay as it is right now(eg. 7days timestamp range is required if topics are presented in the query and etc..)?

We still need to implicitly add the 7 day timestamp range. We can consider increasing the range if you think it's necessary for the relay. But due to performance, we can't support querying for topics without first narrowing down the set of rows to a timestamp range.

So when generating the next link we probably have to provide both a lower and upper bound for the timestamp range so that it doesn't exceed 7 days. If the user already supplied both bounds we should not change them.

> Should both query parameters index and timestamp support gt(e), lt(e), eq ?

Yes, they would need those operators to be able to page properly.
