### ISSUE TITLE
Contract Logs REST API

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-mirror-node#3582]
### Problem

`eth_getLogs` allows searching across contracts but our API requires a contract.

### Solution

A new `/api/v1/contracts/results/logs` API will be added with the same query parameters and response as `/api/v1/contracts/{address}/results/logs` (including any unimplemented tickets) but with the ability to search across contracts. It will not support address as it’s expected users use the existing API if they need logs for a specific address. The same rules around not exceeding `maxTimestampRange` will still apply and allow it to stay performant. Pagination will be possible using a combination of the timestamp and index query parameters.

**Comment by Kalina-Todorova** [comment]
Assigned to @Ivo-Yankov
