### ISSUE TITLE
High stream file processing latency in perfnet with s3

### ISSUE THREAD

**Issue by xin-hedera** [hashgraph/hedera-mirror-node#3664]
### Description

High stream file processing latency is observed in perfnet a couple of times recently. The time from download begins to download a record file to the RecordFileReader finishes reading can reach up to 80 secs. Most likely it's caused by transient s3 high latency but it's also possible that RecordFileReader is slow.

If it's s3 latency, we can improve it by setting a configurable timeout when downloading files from s3 and retrying with either the same node or the next available node.

![mirror_parser_c2mp](https://user-images.githubusercontent.com/59580070/165562536-b265b559-eae0-47c3-8841-fa90f4aa7ada.PNG)
 

### Steps to reproduce

refer to the description

### Hedera network

other

### Version

v0.55.0

**Comment by steven-sheehy** [comment]
Haven't seen for awhile.
