### ISSUE TITLE
Unit test transactions.js

### ISSUE THREAD

**Issue by mike-burrage-hedera** [hashgraph/hedera-mirror-node#368]
**Problem**
There are no unit tests, only full end-to-end integration tests for /api/v1/transactions (transactions.js).

**Solution**
- add method _processDbQueryResponse_ translating SQL results to REST API results
- add unit tests (testing **ONLY** the method in question, not the entire system) for:
  - reqToSql
  - processDbQueryResponse
  - getTransactions
  - getOneTransaction
  - createTransferLists
  - getTransactionsInnerQuery
  - getTransactionsOuterQuery

**Alternatives**

**Additional Context**
See parts of branch rest-api-cleanup, associated with https://github.com/hashgraph/hedera-mirror-node/pull/31

**Comment by steven-sheehy** [comment]
No longer applies
