### ISSUE TITLE
Unit test accounts.js

### ISSUE THREAD

**Issue by mike-burrage-hedera** [hashgraph/hedera-mirror-node#369]
**Problem**
There are no unit tests, only full end-to-end integration tests for /api/v1/accounts (accounts.js).

**Solution**
- refactor to add methods _processDbQueryResponse_ (translating SQL results to REST API results) and _reqToSql_ (translating incoming REST query to SQL statement)
- add unit tests (testing **ONLY** the method in question, not the entire system) for:
  - reqToSql
  - processDbQueryResponse
  - getAccounts
  - getOneAccount

**Alternatives**

**Additional Context**
See parts of branch rest-api-cleanup, associated with https://github.com/hashgraph/hedera-mirror-node/pull/31

**Comment by steven-sheehy** [comment]
No longer applies
