### ISSUE TITLE
Document record (and other) streams' specifications

### ISSUE THREAD

**Issue by mike-burrage-hedera** [hashgraph/hedera-mirror-node#372]
Document/publish the record stream format (and balances and event streams) and include information about:
- the relation of the timestamp in the file name to the data in the file
- what the range of consensus timestamps in the stream files are relative to that file name timestamp
- what triggers the generation (and upload) of the record stream files (for what set of data)
- the expected latency in uploading the streams once they're generated and when they're generated relative to what data is in them
- notes about the consensus timestamp of transactions in the stream relative to the time transactions are received by the Hashgraph network (ie - the _consensus timestamp_ is a timestamp applied _after_ consensus is achieved, which means the _consensus timestamp_ leads consensus by some time, and gets written and uploaded some time after that)

**Comment by steven-sheehy** [comment]
This is not the responsibility of the mirror node. Services will soon add stream format documentation to their repo.
