### ISSUE TITLE
nft_transfers missing when querying transaction history by account id

### ISSUE THREAD

**Issue by teacoat** [hashgraph/hedera-mirror-node#3722]
### Description

When I hit https://testnet.mirrornode.hedera.com/api/v1/transactions/0.0.2077256-1651714357-892057509 it shows nft_transfers:
![image](https://user-images.githubusercontent.com/3913019/166852614-a4a406a3-3901-427a-92f1-a7e9b303be2d.png)

but when I do https://testnet.mirrornode.hedera.com/api/v1/transactions?limit=100&account.id=0.0.2077256 it does not include nft_transfers.
![image](https://user-images.githubusercontent.com/3913019/166852570-fdee7325-0e95-4f2b-8b4e-f5507e599a95.png)

### Steps to reproduce

Visit the two links above

### Hedera network

testnet

### Version

latest

**Comment by steven-sheehy** [comment]
This is by design. The transaction API is our most heavily used API and we can't support too many joins or the larger response size that it would bring. The crypto transfers are only there for legacy reasons otherwise they wouldn't be there if designed today.

**Comment by teacoat** [comment]
@steven-sheehy can you tell me how I am meant to see a full picture of an accounts history then? Do I get the transaction list and then individually query every single transaction to get the full list including nft transfers involved in a transaction?
