### ISSUE TITLE
Impact on mirror node if the frequency of files in increased

### ISSUE THREAD

**Issue by atul-hedera** [hashgraph/hedera-mirror-node#373]
To get reconnect to work well, we may need to modify the record and event streaming so that it creates a new file once per round. That might mean a new file once per second. Maybe slightly longer when we get a lot more traffic. I think we’re currently doing it once every 5 seconds. So this will actually improve latency, but mean there are more files to deal with.

What is the impact of this change on the mirror node - from functionality, performance, and cost perspective? And the impact, if any on HCS as well as any existing integrations (e.g. exchanges)

**Comment by apeksharma** [comment]
For now, the approach for reconnect logic has changed and will not increase frequency of files.
Closing this. We can reopen this back if needed in future.
