### ISSUE TITLE
Account With Empty Info

### ISSUE THREAD

**Issue by EliAzev** [hashgraph/hedera-mirror-node#3735]
### Description

Accounts ID from 101 to 799 are shown with empty public key and auto renew period. 

### Steps to reproduce

1. Search for the referred account ID in any Hedera explorer.

### Hedera network

mainnet

### Version

v0.25.x

**Comment by steven-sheehy** [comment]
Have you tried querying HAPI for those details? Below 1000 are reserved IDs and don't necessarily exist on the network. 101, 102, 111, 112 do exist and have public keys. A few others in between exist but don't have keys. Most of the others I believe simply haven't been created yet and are for future use.

**Comment by steven-sheehy** [comment]
And I should clarify that a lot of the ones that do exist like 101/102/111/112/121/122 are all files, not accounts. So wouldn't show up in an accounts REST API.

**Comment by EliAzev** [comment]
Yes, I was getting info through https://mainnet-public.mirrornode.hedera.com/api/v1/accounts?account.id=0.0.101 for example. Your information clarified a lot.

**Comment by steven-sheehy** [comment]
Cool, going to close this then if my response clarifies things.

**Comment by EliAzev** [comment]
Thank you so much
