### ISSUE TITLE
Mirror Node and HCS MVP Functional Requirements

### ISSUE THREAD

**Issue by donaldthibeau** [hashgraph/hedera-mirror-node#374]
- Sub 20 second Latency
- 1000 tps peak throughput
    - Reason: Fabric has 3-4k tps
    - 200 tps average
- 1000 Topics
- ~1000 Messages per topic~ (this isn't really a metric we need; active connections and tps)
- One year Mirror node retention
    - ~Can’t come close to holding for a year, at best a couple of weeks~
    - Alternative would be to archive in a bunch of files in S3 - AWS glacial 
    - First phase will build one year retention @200tps. Increase it to 1k tps as market demand comes.
    - All the data does not need to be accessible from the same mirror node instance, it just needs to be accessible
- 150 simultaneous connections by 1y after HCS release
  - IBM's initial use case is for 7 orgs of 2 peers; they have ~100 users, we'll target 10% first year.
- SDK Support
    - Create a topic
    - Submit a transaction
    - Monitor a topic
    - Java support
        - State proofs will only be in Java
    - fragmentation and re assembly

**Comment by mike-burrage-hedera** [comment]
Think I figured that 1kTPS (200 TPS sustained) w/ 2k messages for 1 year + overhead = ~15TB. So, possible from a data storage perspective. not cheap, and getting within an order of magnitude of pg's table size limit.
