### ISSUE TITLE
Searching by evm address at contracts endpoint not always working 

### ISSUE THREAD

**Issue by Kalina-Todorova** [hashgraph/hedera-mirror-node#3813]
### Description

We are trying to search by `evm address` at the `contracts` endpoint. Use these two examples, given that both contracts exist:
- https://testnet.mirrornode.hedera.com/api/v1/contracts/104ceaC64AB4193d840989375B7dD75F3ce228BF `contract id` = 0.0.34843246
- https://testnet.mirrornode.hedera.com/api/v1/contracts/B8e87C06dc5C0A299C52a6B31a57C8Fb1D61143a `contract id` = 0.0.34843038

### Steps to reproduce

1. Create a pair and add liquidity to it in the same transaction
2. Check that the pair contract is then not found by the mirror node

If we do the above in two separate transactions - everything works fine

### Hedera network

testnet

### Version

v0.56

**Comment by natanasow** [comment]
Spent a lot of time trying to reproduce it both on local node and testnet, but without success.

**Comment by Kalina-Todorova** [comment]
Closing this as not reproducible, if it happens again please feel free to reopen.
