### ISSUE TITLE
Expose the ethereum transaction hash in api/v1/contracts/results endpoints

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-mirror-node#3820]
### Problem

Currently a result entity in the [api/v1/contracts/results](https://previewnet.mirrornode.hedera.com/api/v1/docs/#/contracts/listAllContractsResults) endpoint does not contain a unique identifier that point to the transaction in the EVM context i.e. hash
In the case of `eth_getBlockX` this makes it challenging to request further information from the MirrorNode on the result since neither transactionId nor hash is present.

### Solution

Given the ethereum hash is sometimes sufficient in `eth_getBlockX` calls it would be good to initially start off by exposing this.
If subsequent calls to the mirror node are needed this same hash can be used to call [api/v1/contracts/results/{ethereumHash}](https://previewnet.mirrornode.hedera.com/api/v1/docs/#/contracts/getContractResultByTransactionIdOrHash) to get further details

- Add `hash` to the `api/v1/contracts/results` responses.

**Comment by Nana-EC** [comment]
Moving out of sprint `v0.58.0` goals.
Priority remains but given sprint load and resources it can be pushed to `v0.59.0`

**Comment by Daniel-K-Ivanov** [comment]
Picking this up, since we have the bandwidth
