### ISSUE TITLE
Importer sets ethereumnonce to 0 for non-account entities

### ISSUE THREAD

**Issue by xin-hedera** [hashgraph/hedera-mirror-node#3843]
### Description

Importer sets ethereum nonce to the default value 0 for all non-account entities. The problem is the db column `ethereum_nonce` has a default of 0, the upsert sql will then always set it to 0 since for non-account entities the value is `null` in the domain object.  

### Steps to reproduce

1. downgrade maven surefire plugin to 3.0.0-M5
2. run `./mvnw test -pl hedera-mirror-importer` some tests will fail due to expect `ethererum_nonce = null` instead of `ethereum_nonce = 0`

### Hedera network

other

### Version

v0.57.0

**Comment by steven-sheehy** [comment]
We can close and fix if we ever have non-account entities with nonce
