### ISSUE TITLE
rest-api metrics

### ISSUE THREAD

**Issue by mike-burrage-hedera** [hashgraph/hedera-mirror-node#391]
**Problem**
The rest-api needs to export metrics at least equivalent to apache access logs.

Obviously more detail is needed here, but we need to be logging/reporting some useful info.

**Solution**

**Alternatives**

**Additional Context**
This data then needs to be ingested by ops, monitored, and exposed such that performance reports can be generated.

**Comment by apeksharma** [comment]
Duplicates #661
