### ISSUE TITLE
rest-api log maintenance

### ISSUE THREAD

**Issue by mike-burrage-hedera** [hashgraph/hedera-mirror-node#392]
**Problem**
There's currently no log maintenance on the rest-api production (mainnet/testnet) or staging/dev logs, and they're rather large in production (~15GB total on mainnet as of today).

**Solution**

- the default log level for production should be warning (it's currently debug)
- logs should be rotated daily, by default, with 2 weeks worth of logs stored (see https://github.com/log4js-node/streamroller for possible implementation).

**Alternatives**

- use logrotate

**Additional Context**

**Comment by steven-sheehy** [comment]
We now log to stdout. Debug level is fine after I moved query logging to trace. It's ops responsibility to configure pm2 to rotate logs now.
