### ISSUE TITLE
HCS GRPC API stub

### ISSUE THREAD

**Issue by mike-burrage-hedera** [hashgraph/hedera-mirror-node#394]
**Problem**
The SDK and possibly CLI will need early access to test against the GRPC interface that will be exposed by the mirror node.

**Solution**
- Implement a stub GRPC API so that other projects can begin integrating against it early in the sprint.
See `Protobuf` and `Consensus Service` sections in design document (PR #327)
- Dummy responses and simple dummy data publishing are fine.

**Alternatives**
- Make the other projects wait until the end of the sprint or build and run their own mirror node locally.

**Additional Context**

**Comment by steven-sheehy** [comment]
Merged to hcs branch
