### ISSUE TITLE
Internal error when retrieving contract result by ethereum transaction hash

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-mirror-node#3952]
### Description

When querying `/api/v1/contracts/results/{ethereum-tx-hash}` with an ethereum transaction that has been submitted multiple times to the network (e.g. it failed and the user wanted to retry), the REST API returns `Internal error` instead of a successful response. This occurs because of an internal check for multiple results for what is supposed to be a unique key (see logs below).

### Steps to reproduce

Invoke contract results by ethereum hash with an ethereum transaction that you've submitted multiple times to the network.

https://previewnet.mirrornode.hedera.com/api/v1/contracts/results/0xb8e8b5f4a0e5821fd12fe7b0dbc14036ead8bfe30a04ef34274e6affa9ed4a69

### Additional context

```bash
9|6559  | 2022-06-15T14:45:42.218Z ERROR 694775b4 75.12.148.71 GET /api/v1/contracts/results/0xb8e8b5f4a0e5821fd12fe7b0dbc14036ead8bfe30a04ef34274e6affa9ed4a69 in 4 ms: 500 Internal error Error: Transaction invariance breached
9|6559  |     at getContractResultsByTransactionIdOrHash (/opt/restapi/controllers/contractController.js:1025:13)
9|6559  |     at runMicrotasks (<anonymous>)
9|6559  |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
9|6559  |     at async wrappedMiddleware (/opt/restapi/node_modules/@awaitjs/express/index.js:64:9)
```

### Hedera network

previewnet

### Version

v0.58.0

**Comment by steven-sheehy** [comment]
Discussions are underway to:

1) Skip duplicate ethereum transactions calls on the relay within the 3 minute window
2) Skip duplicate ethereum transactions call on services within the 3 minute window

Regardless of the above outcome, the mirror node should adjust the query that queries for `ethereum_transaction.hash` to return the latest by consensus timestamp instead of throwing an error.

**Comment by shemnon** [comment]
Per my recommendations in #3953, skip duplicates with WRONG_NONCE, and return the _oldest_ transaction that does not have WRONG_NONCE as the status.  Typically this will always be the oldest but if metamask is really confused about the transaction count it may send a too-large nonce.
