### ISSUE TITLE
System requirement and recommendation

### ISSUE THREAD

**Issue by pathornteng** [hashgraph/hedera-mirror-node#4045]
### Problem

Mirror node is quite a resource-intensive application. Currently, there is no information about the size of db, the CPU, and RAM the system is required to run the mirror node. 

### Solution

Add minimum/recommendation system specification to readme/doc

**Comment by steven-sheehy** [comment]
This info is documented on our docs site: https://docs.hedera.com/hedera/core-concepts/mirror-nodes/run-your-own-beta-mirror-node
