### ISSUE TITLE
Incorrect offset in next link for blocks endpoint

### ISSUE THREAD

**Issue by tgpa** [hashgraph/hedera-mirror-node#4069]
### Description

Querying the blocks endpoint (in ascending order) returns 25 results: block 0 to block 24, as expected. However, the links.next value is incorrect: it returns a link with `block.number=gt:0`, which returns block 1 to block 25. The subsequent links.next returns a link with `block.number=gt:1`, which returns block 2 to block 26 and so on and so forth.

The block.number offset in links.next should be the number of last block in the results to return results after that block. Instead, it is taking the block number for the first result in the array.

https://testnet.mirrornode.hedera.com/api/v1/blocks?order=asc

Returns 25 results: block 0 to block 24. 

The next link is `/api/v1/blocks?order=asc&block.number=gt:0` but it should be `/api/v1/blocks?order=asc&block.number=gt:24`

This is also an issue in descending order.

Actual
1. https://testnet.mirrornode.hedera.com/api/v1/blocks?order=asc (0 - 24)
2. https://testnet.mirrornode.hedera.com/api/v1/blocks?order=asc&block.number=gt:0 (1 - 25)
3. https://testnet.mirrornode.hedera.com/api/v1/blocks?order=asc&block.number=gt:1 (2 - 26)
4. https://testnet.mirrornode.hedera.com/api/v1/blocks?order=asc&block.number=gt:2 (3 - 27)
5. https://testnet.mirrornode.hedera.com/api/v1/blocks?order=asc&block.number=gt:3 (4 - 28)

Expected
1. https://testnet.mirrornode.hedera.com/api/v1/blocks?order=asc (0 - 24)
2. https://testnet.mirrornode.hedera.com/api/v1/blocks?order=asc&block.number=gt:24 (25 - 49)
3. https://testnet.mirrornode.hedera.com/api/v1/blocks?order=asc&block.number=gt:49 (50 - 74)
4. https://testnet.mirrornode.hedera.com/api/v1/blocks?order=asc&block.number=gt:74 (75 - 99)
5. https://testnet.mirrornode.hedera.com/api/v1/blocks?order=asc&block.number=gt:99 (100 - 124)

### Steps to reproduce

1. Go to https://testnet.mirrornode.hedera.com/api/v1/blocks?order=asc
2. Follow links.next

### Hedera network

mainnet, testnet

### Version

0.59.1

**Comment by steven-sheehy** [comment]
Thanks for the report. We'll get that fixed soon.
