### ISSUE TITLE
Provide a way to compound or unify multiple mirror node queries

### ISSUE THREAD

**Issue by ed-marquez** [hashgraph/hedera-mirror-node#4071]
### Problem

Multiple Discord users have expressed a sub-optimal experience when it comes to querying mirror nodes to obtain NFT and other entity information. Some things that should take 1 query can often take 3 or more separate queries. 

### Solution

- Is it possible to evaluate providing a way (programmatic and UI) for users to compound multiple mirror queries into a single action/command? Otherwise, we will need to continue addressing feedback from users suggesting new mirror API calls to get detailed information about entities like NFTs.
- FYI @mohsin-hedera

**Comment by steven-sheehy** [comment]
This is a general problem with REST APIs and not something specific to mirror nodes. This is one of the main reasons why GraphQL was introduced by Facebook and has become increasingly popular. It doesn't make sense to invest in ways to make our REST API more like GraphQL, so we are exploring a GraphQL HIP via https://github.com/hashgraph/hedera-mirror-node/issues/4795 so closing this in favor of that.
