### ISSUE TITLE
Single process mode

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-mirror-node#41]
Currently the architecture is complex with 5 java processes starting up each with only a single thread. We should also support starting up in a single process with each of the standalone processes now running in a separate thread. Wouldn't take much work, just need to consolidate to a single main() and have each of the previous mains implement a common interface. A flag would allow you to pick and choose which module you wanted to run on startup.

**Comment by mike-burrage-hedera** [comment]
When the systemd scripts get updated, can we call this one hedera-mirror-node.service. I'll use that in the documentation for #165 as well.

**Comment by mike-burrage-hedera** [comment]
If this change adds the ability to run the single executable with the option "--db-upgrade" (or similar) and _just_ runs the migration and exits - that would be incredibly useful.

**Comment by steven-sheehy** [comment]
No, but can do that just by bring it up, wait for flyway logs then stopping it.
