### ISSUE TITLE
REST API integration tests for all parameters

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-mirror-node#412]
**Problem**
We keep having regressions in the REST API because we don't have good test coverage. We have an integration test framework but it is not filled out with specs for all URLs and combinations of parameters.

In addition - the way we setup integration test data, execute integration tests, and compare results, is not intuitive/clear.

**Solution**
- Refactor the integration_test.js such that each test:
  - ~clears out the database of data before each test (see cleanup.sql), using jest's `beforeEach`~
  - ~specifies a test data file to use to setup database data at the beginning of the test (see integration_test_data.json and related logic in integration.test.js). The data setup files can be moved into a new `data` folder.~
  - ~`specs` can specify which data file they will use in the spec's json (`data_setup_file`: _path_)~
  - ~run the test against the target code (reqToSql or calling the REST API)~
  - ~compare the results to a result file and output/assert differences~
- Add spec files to `hedera-mirror-rest/__tests__/specs` for every URL and parameters we support. Also add negative test cases.

**Alternatives**

**Additional Context**
integration.test.js contains tests for both the end-to-end REST API-through-DB and reqToSql-through-DB. Don't split the file up into multiple files without ensuring that the tests do not run in parallel, as there is only 1 integration test DB.

**Comment by Nana-EC** [comment]
Check on Atul's previous PR that made code suggestions on this. Might prove useful

**Comment by Nana-EC** [comment]
Closing, as addressed by https://app.zenhub.com/workspace/o/hashgraph/hedera-mirror-node/issues/603

**Comment by steven-sheehy** [comment]
We just have the framework, but we don't have the coverage. The ticket is about both as the title indicates.
