### ISSUE TITLE
Add raw transaction bytes to t_transactions table (optionally)

### ISSUE THREAD

**Issue by carlcherry** [hashgraph/hedera-mirror-node#414]
**Problem**
For 3rd party integrations there are times when the raw bytes are required for validation, audit, etc. This feature allows integrators to get at any other fields not parsed by the mirror node without any further modifications to the mirror node.

**Solution**
- Add a new field to the t_transactions table named transaction_bytes.
- Add a property to the RecordParserProperties to disable this behavior by default.

**Alternatives**
None that I can see besides parsing the files again when the raw bytes are needed.

**Additional Context**
I have already done a test run of these changes in my own fork - I am available to do the work.

**Comment by mike-burrage-hedera** [comment]
Sounds good.

I think we'll want it configurable, as you said, with a property (such as `hedera.mirror.parser.record.persistTransactionBytes`) with a default of false.

This is something we can merge as soon as you're all set with the PR.

**Comment by carlcherry** [comment]
Mike - just curious about one thing.  I will have to change 81 unit tests, plus add a couple.  Did you prefer that I create 2 storeRecord methods: i.e.
storeRecord(Transaction tx, TransactionRecord txRecord);
storeRecord((Transaction tx, TransactionRecord txRecord, byte[] rawBytes);

Then have the first call the second with a "null"

**Comment by mike-burrage-hedera** [comment]
Adding that overload is fine. The few new unit tests should cover the code that stores the rawBytes.
