### ISSUE TITLE
The max_automatic_token_associations field is not populated in mirror node database

### ISSUE THREAD

**Issue by natanasow** [hashgraph/hedera-mirror-node#4192]
### Description

I created a contract via [ContractCreateTransaction](https://docs.hedera.com/guides/docs/sdks/smart-contracts/create-a-smart-contract#contractcreatetransaction) in the JS SDK, set a `setMaxAutomaticTokenAssociations` field and I expect the result to be populated in the mirror node database, but its value is always 0, no matter what we pass as a parameter. Debugged it in the services and it seems to work. The problem is in the importer, [here](https://github.com/hashgraph/hedera-mirror-node/blob/main/hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java#L261) I think.

### Steps to reproduce

1. Run hedera-local
2. Create a sample npm project using hedera SDK
3. Deploy a contract and use the `setMaxAutomaticTokenAssociations` method
4. Explore the contract in the mirror node (/contracts route)

### Hedera network

other

### Version

v0.61.0

### Operating system

Linux

**Comment by steven-sheehy** [comment]
I'm unable to reproduce. I created a contract with `max_automatic_token_associations` set to one and see it in the REST API. Can see my contract on testnet: http://testnet.mirrornode.hedera.com/api/v1/contracts/0.0.47777064

**Comment by steven-sheehy** [comment]
BTW, the linked code you [mention](https://github.com/hashgraph/hedera-mirror-node/blob/main/hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java#L261) is for child contract creates before we had synthetic children transactions and is not applicable to the above.
