### ISSUE TITLE
Validate that `eth_call` works for pure solidity functions

### ISSUE THREAD

**Issue by IvanKavaldzhiev** [hashgraph/hedera-mirror-node#4224]
### Problem

We need to validate that `eth_call` can successfully perform calls to `pure` solidity functions.

### Solution

Create a test with `eth_call` invoking a `pure` solidity function from a test smart contract. Validate that the expected return result is correct.

**Comment by ivanparnarev** [comment]
Created new branch only with the changes regarding the new test.
