### ISSUE TITLE
Convert monitoring tool to a maven module

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-mirror-node#424]
**Problem**
The monitoring tool is located at `hedera-mirror-rest/monitoring` even though it is a separate deployable. Additionally, it is split into `monitoring_apis` and `monitoring_dashboard` with only the former having a proper `package.json`.

**Solution**
- Move monitoring to be a separate maven module `hedera-mirror-monitor`
- Run monitoring unit tests in CI
- Consider merging APIs and dashboard into a single deployable unit as they are always ran together anyways (they can still be separate processes/ports)

**Alternatives**
- Separate modules for both monitor APIs and monitor dashboard

**Additional Context**

**Comment by Nana-EC** [comment]
This has been satisfied with the addition of java based monitor.
Now runs in Github Actions CI, with tests and API and dashboard were merged
