### ISSUE TITLE
Enable pg_stat_statements in Postgres

### ISSUE THREAD

**Issue by apeksharma** [hashgraph/hedera-mirror-node#427]
The plugin will give us wealth of information about our queries patterns, which in turn will help us optimize the db. Kinds of information it can provide:
- queries distribution
- query time: find slow queries -> optimize indexes
- io performance of queries

**Comment by mike-burrage-hedera** [comment]
Note that this will require a database restart (devops).

**Comment by steven-sheehy** [comment]
Not needed for now since we're using https://cloud.google.com/sql/docs/postgres/using-query-insights
