### ISSUE TITLE
Swagger Issue

### ISSUE THREAD

**Issue by Reccetech** [hashgraph/hedera-mirror-node#4351]
### Description

For this API: https://testnet.mirrornode.hedera.com/api/v1/docs/#/topics/getTopicMessagesByConsensusTimestamp
I'll plug in a valid consensus timestamp but just get this error:
"message": "Invalid parameter: consensus_timestamp"

Maybe a bad swagger config?

### Steps to reproduce

Go to swagger
enter any valid c timestamp
always get invalid parameter error

### Hedera network

testnet

### Version

v0.62.1

**Comment by xin-hedera** [comment]
What's the format of timestamp used in the query? The timestamp is required to be `secs.nanos`. The following query works:

https://testnet.mirrornode.hedera.com/api/v1/topics/messages/1661456262.348865003

**Comment by steven-sheehy** [comment]
There's a bug in the `openapi.yml`. It's a mismatch between expected path param name and actual one in the schema. We'll address. Invoking via swagger produces:

```
GET /api/v1/topics/messages/%7BconsensusTimestamp%7D in 6 ms: 400 Bad request InvalidArgumentError Invalid parameter: consensus_timestamp
```
