### ISSUE TITLE
Search transaction by hash

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-mirror-node#4364]
### Problem

As a user, given a transaction hash, I want to search the transaction by its hash using mirrornode REST API.

### Solution

- [x] #4362
- [x] #4363
- [x] #4361
- [x] #4423

**Comment by mgarbs** [comment]
I can query mainnet mirror with a transaction hash, but cannot do the same for testnet. Did we remove this?

An example transaction is here:
https://hashscan.io/testnet/transaction/1675718206.003138003?tid=0.0.255940-1675718195-071835593
We can see it obviously if we look it up by transactionId, but we can't see it if we look it up by hash:  [https://hashscan.io/testnet/search-result/d573d039acfebb180cc24d3a4faf697acec369fe[…]ae4b8e9b84878be8a78712c49a481b49e0c29b6cddb8b1b3a8?errorCount=0](https://hashscan.io/testnet/search-result/d573d039acfebb180cc24d3a4faf697acec369fe[%E2%80%A6]ae4b8e9b84878be8a78712c49a481b49e0c29b6cddb8b1b3a8?errorCount=0)

```bash
> curl https://testnet.mirrornode.hedera.com/api/v1/transactions/d573d039acfebb180cc24d3a4faf697acec369fefbc139ae4b8e9b84878be8a78712c49a481b49e0c29b6cddb8b1b3a8
{"_status":{"messages":[{"message":"Not found"}]}}% 
```   
Lookups by hash seem to work on mainnet, but not on testnet:
```bash
> curl https://mainnet-public.mirrornode.hedera.com/api/v1/transactions/ded0be600f4608b7b64943a98f04008e7096ece8f36689a8805dea6066c1e577ca6e2b0842fddf016ca1cc5f7e807fb5
{"transactions":[{"bytes":null,"charged_tx_fee":137395,"consensus_timestamp":"1674261292.691051950","entity_id":"0.0.45242","max_fee":"200000000","memo_base64":"ZTk1MWFlYWMwYWVmZjJhNTRhYjY5YTIwY2I3NTZhMGQ2OWRkZjExMjhhOWRmN2VhOTMxZjkyY2IwNWJlOTcwZg==","name":"CONSENSUSSUBMITMESSAGE","node":"0.0.7","nonce":0,"parent_consensus_timestamp":null,"result":"SUCCESS","scheduled":false,"staking_reward_transfers":[],"transaction_hash":"3tC+YA9GCLe2SUOpjwQAjnCW7OjzZomogF3qYGbB5XfKbisIQv3fAWyhzF9+gH+1","transaction_id":"0.0.44034-1674261281-480306324","transfers":[{"account":"0.0.7","amount":6900,"is_approval":false},{"account":"0.0.98","amount":130495,"is_approval":false},{"account":"0.0.44034","amount":-137395,"is_approval":false}],"valid_duration_seconds":"120","valid_start_timestamp":"1674261281.480306324"}]}%
```

**Comment by steven-sheehy** [comment]
It's never been enabled on testnet. On mainnet it only supports a subset of data. It's a performance concern with the current short-term solution.

**Comment by gharriso** [comment]
I think the functionality enabled on the mainnet should be reflected in testnet, otherwise, we need to test new functionality in production.  Also, allow our ProvenDB users to issue testnet transactions, so testnet functionality is "production" for us. 

Is there any chance that this will be enabled in testnet?  What is the "subset of data" supported?  Thanks!

**Comment by steven-sheehy** [comment]
Testnet now has transaction hash lookups enabled. Closing

https://testnet.mirrornode.hedera.com/api/v1/transactions/78e3390cc733f7b6a2989f637e6871abd83a2a4b465f0dcc9a8372fdbbfb643816d937eea5693cc3b6cf882a1bfeed1e
