### ISSUE TITLE
Contract state REST API

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-mirror-node#4484]
### Problem

As a smart contract developer, I'd like to be able to view my current contract state via an API.

### Solution

Add an `/api/v1/contracts/{idOrAddress}/state` REST API where `id` is either the `shard.realm.num`, `realm.num`, `num`, or hex encoded EVM address of the contract, similar to other APIs.
```json
{
  "state": [{
    "address": "0x0000000000000000000000000000000000001f41",
    "contract_id": "0.0.100",
    "slot": "0x",
    "timestamp": "10000000.000000001",
    "value": "0x"
  }],
  "links": {
    "next": null
  }
}
```
* Supported query parameters:
  * `limit` - The maximum number of results to return. Defaults to 25 and max 100 allowed.
  * `order` - Sort by the slot. Value of `asc` or `desc` with a default of `asc`.
  * `slot` - The slot value of the contract storage. Used as the primary key in pagination. Supports `eq`, `gt`, `gte`, `lt`, `lte` operators.

**Comment by steven-sheehy** [comment]
Depends on https://github.com/hashgraph/hedera-mirror-node/issues/4476

**Comment by stoqnkpL** [comment]
@steven-sheehy should the `index`, `limit`, and `order` be based on the `slot` field?

**Comment by steven-sheehy** [comment]
I updated it to remove `index` and just use `slot` directly. We'll take care of zero-padding slots on write so they sort properly.
