### ISSUE TITLE
nonce is `null` for non-eth transactions fetched from the `contract_result` table

### ISSUE THREAD

**Issue by dimitrovmaksim** [hashgraph/hedera-mirror-node#4501]
Now that https://github.com/hashgraph/hedera-mirror-node/pull/4381 is merged and non-eth transactions are fetched from the `contract_result` table, the nonce for non-eth transactions is always `null` (as mentioned here https://github.com/hashgraph/hedera-mirror-node/pull/4381#issuecomment-1233061413), which will break the integrations with some tools, for example TheGraph, but it is not obvious how to resolve it.

**Comment by steven-sheehy** [comment]
@dimitrovmaksim Is this still a concern or did you guys handle this on the [relay](https://github.com/hashgraph/hedera-json-rpc-relay/issues/566)? If not a problem, please close.

**Comment by dimitrovmaksim** [comment]
Handled in the relay
