### ISSUE TITLE
Testing on Win10

### ISSUE THREAD

**Issue by Jomond** [hashgraph/hedera-mirror-node#453]
Hi, We tried to set up on a Mirror Node Win10 - where we have done all our dev work so far (our Power Transition, Energy Microgrid Platform).  Obviously we ran into trouble straight away and realized that we need to set up on OSX/Linux.  Will there be a port onto Win10 in the near future? We'd like to keep things operating on the same OS.

**Comment by steven-sheehy** [comment]
There's no plans currently, but in theory it should work once this [issue](https://github.com/hashgraph/hedera-mirror-node/issues/281) is addressed. It should be a pretty easy to fix up and I can provide some guidance if that's something you're interest in taking on.

Alternatively, you can look into running the mirror node in a [Docker container](https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/linux-containers) on Windows.

**Comment by Jomond** [comment]
Yes, I saw the Docker container option. Do you know if anyone has been successful in this approach? Cheers, Jiro

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by steven-sheehy** [comment]
Sorry, don't know if anyone's been successful.

**Comment by Jomond** [comment]
Okay thanks, I’ll ask Greg Scullard who posted it on Discord :-J

**Comment by steven-sheehy** [comment]
I'm going to close this since it was mainly a question that's hopefully been answered. We'll track the Windows support in #281.

**Comment by Jomond** [comment]
Yes, this can be closed, but please track the Win10 port.  I think this is important for Hedera Hashgraph moving forward into mainstream use.  Jiro
