### ISSUE TITLE
api/v1/accounts/0.0.xxx?token.id=0.0.yyyy doesn't filter by tokenId

### ISSUE THREAD

**Issue by gregscullard** [hashgraph/hedera-mirror-node#4607]
### Description

Querying this endpoint https://testnet.mirrornode.hedera.com/api/v1/accounts/0.0.1156?token.id=0.0.48252238 doesn't filter the result by tokenId, all tokens are returned.

### Steps to reproduce

Query https://testnet.mirrornode.hedera.com/api/v1/accounts/0.0.1156?token.id=0.0.48252238, witness list of tokens is not limited to 0.0.48252238.

### Hedera network

testnet

### Version

v0.64.4

**Comment by steven-sheehy** [comment]
This is the same underlying problem as https://github.com/hashgraph/hedera-mirror-node/issues/4575. We validate query params via a common method shared by all endpoints. So if a query param works for any endpoint it won't throw an error for ones it should not. 

Only query params noted in the OpenAPI docs are actually supported. We will fix it to throw an error for unsupported params, but probably don't need a ticket for every combination of endpoints and params that have the problem.
