### ISSUE TITLE
RecordFileParserIntegrationTest fails

### ISSUE THREAD

**Issue by xin-hedera** [hashgraph/hedera-mirror-node#4613]
### Description

`RecordFileParserIntegrationTest` fails on verifying the number of crypto transfers saved to db.

The problem is the record file used in the test class has several successful `CryptoCreate` transactions with non-zero `initialBalance` but the initial balance transfer to the new account is missing from the corresponding transaction record transfer list. Mirrornode used to add such missing crypto transfers and save them to db, however, later version has removed the logic, thus we will see a mismatch of the number of crypto transfers.

### Steps to reproduce

Run the test class `RecordFileParserIntegrationTest`

### Hedera network

other

### Version

v0.67.0-SNAPSHOT

**Comment by steven-sheehy** [comment]
Closing since this test now is re-enabled and passing.
