### ISSUE TITLE
Update the HIP-573 documentation

### ISSUE THREAD

**Issue by mgoelswirlds** [hashgraph/hedera-mirror-node#4648]
### Problem

As part of HIP-573 Blanket exemptions for custom fee collectors a new fields `bool all_collectors_are_exempt ` was added to CustomFee in mirror node.
The HIP documentation for this needs to be updated.

### Solution

- Add mirror node section to HIP/hip-573.md

**Comment by steven-sheehy** [comment]
This was completed
