### ISSUE TITLE
Citus: Performance test REST API

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-mirror-node#4655]
### Problem

We need to test the performance of CitusDB with 100B transactions when using the REST API

### Solution

* Depends on #5750
* Run the k6 performance test
* Compare with Cloud SQL mainnet staging against same version and similar timeframe
* Load transactions into CitusDB maxing out TPS using `RecordFileParserPerformanceTest`
* Verify gRPC API at 10K TPS
* Repeat at 25B, 50B, 75B, and 100B

**Comment by mgoelswirlds** [comment]
I think we should list out other tasks that need to be done as part of this ticket and create separate tasks to be able to divide the work properly.

**Comment by steven-sheehy** [comment]
This has been completed and done in an ongoing basis
