### ISSUE TITLE
Monitor not updated for current account balance

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-mirror-node#4674]
### Description

The monitor shows an error of `balances.length of 0 was expected to be 1` when pointing to a REST API v0.66.1. This occurs because we switch the balances API to use the live account balance and this check is confirming an exact timestamp from the balances list will show up with timestamp parameters.

### Steps to reproduce

https://{hostname}/api/v1/balances?timestamp=gt:1666034723.874913934&timestamp=lt:1666034725.874913934&limit=1

Replace hostname with an env that is using v0.66.1 and replace timestamp with the latest balance timestamp +/- one second.

### Hedera network

testnet

### Version

v0.66.1

**Comment by steven-sheehy** [comment]
## Solution

* Change `checkBalanceFreshness` to pass `?timestamp=${now}` where `now = new Date().getTime() / 1000;`
* Remove `getBalancesWithTimeAndLimitParams` check since it no longer makes sense with live balance

**Comment by MarcKriguerAtHedera** [comment]
I couldn't get the revised query (using the current time as the timestamp) to work, but removing `getBalancesWithTimeAndLimitParams` makes all the tests green again.
