### ISSUE TITLE
HIP-406 Show staking reward transfers in transactions API

### ISSUE THREAD

**Issue by xin-hedera** [hashgraph/hedera-mirror-node#4703]
### Problem

As a user who stakes to a node and opts in reward, I'd like to see my staking reward transfers in related transactions response.

### Solution

Add `staking_reward_transfers` to transactions list and by ID responses
```json
{
  "transactions": [
    {
      "transaction_id": "0.0.112233-1666555555-560065123",
       "staking_reward_transfers": [
         {
           "account": "0.0.112233",
           "amount": 5000000
         }
       ]
    },
    ...
  ],
  ...
}
```

* Because staking reward transfers are rare in relation to regular transfers, we should keep the existing transactions query the same, collect the timestamps that had any transfers from 0.0.800, then perform a separate query for those `staking_reward_transfers` and merge into existing response.

**Comment by teacoat** [comment]
It would be great if there were a way to get a users historical staking rewards without being required to query and parse their entire transaction history, as this is an expensive operation

**Comment by steven-sheehy** [comment]
> It would be great if there were a way to get a users historical staking rewards without being required to query and parse their entire transaction history, as this is an expensive operation

Opened https://github.com/hashgraph/hedera-mirror-node/issues/4744 to capture that request

**Comment by svienot** [comment]
Would it be possible to retrieve the hbar (to $) exchange rate at the time of the reward in addition to its amount ?
Hashscan will need ([#287](https://github.com/hashgraph/hedera-mirror-node-explorer/issues/287)) to provide amount and corresponding rate to the user retrieving historical reward data for keeping/reporting purposes. 
Getting the rate alongside the amount would avoid the cost of an additional API call to /api/v1/network/exchangerate?timestamp=:rewardTimestamp for each reward transaction.

**Comment by edwin-greene** [comment]
For reference, getting the exchange rate has been opened as an issue here: https://github.com/hashgraph/hedera-mirror-node/issues/4927
