### ISSUE TITLE
Create synth events for HAPI transactions

### ISSUE THREAD

**Issue by stoqnkpL** [hashgraph/hedera-mirror-node#4738]
**Problem** 

Users writing dApps want to monitor for token approval and transfer events.

HAPI transactions like `CryptoTransfer`, `CryptoApproveAllowance`, `CryptoDeleteAllowance`, `TokenMint`, `TokenWipe`, and `TokenBurn` do not emit events that could be captured by monitoring tools since they’re executed outside the EVM.

We should also calculate the index of each log in the block.

**Proposed Solution**

Explore possible ways to create synthetic events for HAPI transfers/approvals and what impact these changes would have on mirror node performance.

**Comment by Kalina-Todorova** [comment]
Related to: https://github.com/hashgraph/hedera-mirror-node/issues/4337
