### ISSUE TITLE
HIP-406 Account staking rewards API

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-mirror-node#4744]
### Problem

As an Hedera account holder, I'd like to find out my past staking reward payouts for tax purposes.

### Solution

* Add a new `/api/v1/accounts/{id}/rewards` REST API

```json
{
  "rewards": [{
    "account_id": "0.0.1000",
    "amount": 10,
    "timestamp": "123456789.000000001"
  }],
  "links": {
    "next": null
  }
}
```

* Supported query parameters:
  * `limit` -  The maximum number of results to return. Defaults to 25 and max 100 allowed.
  * `order` - Sort by timestamp. Value of `asc` or `desc` with a default of `desc`.
  * `timestamp` - The timestamp range to filter by. Supports `eq`, `gt`, `gte`, `lt`, `lte` 

### Alternatives

`/api/v1/accounts/{id}/stake`

**Comment by ericleponner** [comment]
One question : in `/api/v1/accounts/{id}/rewards` response, what does `account_id` represent ?
- Is it `0.0.800` ? 
- or the `id` in `/api/v1/accounts/{id}/rewards` ?


One request : in explorer [#287](https://github.com/hashgraph/hedera-mirror-node-explorer/issues/287), requested infos are:
1) Transaction Time (_stamp_)
2) Transaction ID
3) Transaction Type
4) Reward Amount

Items 1) and 4) can be found in `/api/v1/accounts/{id}/rewards` response.
Items 2) and 3) are missing : could we add them ? or should we skip them and update the requirement ?

**Comment by steven-sheehy** [comment]
@ericleponner Mohsin confirmed we can omit transaction type and ID.

**Comment by ericleponner** [comment]
Ok. I updated [#287.](https://github.com/hashgraph/hedera-mirror-node-explorer/issues/287)

**Comment by MarcKriguerAtHedera** [comment]
On Thu, Nov 10, 2022 at 8:05 AM Eric Le Ponner ***@***.***>
wrote:

> One question : in /api/v1/accounts/{id}/rewards response, what does
> account_id represent ?
>
>    - Is it 0.0.800 ?
>    - or the id in /api/v1/accounts/{id}/rewards ?
>
> The latter - it's the id of the account that *received* the staking
> reward.
>
       -- Marc

**Comment by ericleponner** [comment]
> The latter - it's the id of the account that *received* the staking

So it's the value of `{id}` in `/api/v1/accounts/{id}/rewards`, right ?

**Comment by steven-sheehy** [comment]
Correct

**Comment by ericleponner** [comment]
Thanks for clarifying, folks.
I'm a bit surprise because `account_id` will have the same value for all the items in the response.
But may be there are some future usages planned for it.

**Comment by steven-sheehy** [comment]
Technically the `id` in the URL can be a hedera ID, evm address or an alias.

**Comment by ericleponner** [comment]
Ok, I got it. Thanks Steve.
