### ISSUE TITLE
Add a timestamp parameter to account REST API

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-mirror-node#4762]
### Problem

Currently it's not possible to get an accurate value of an accounts balance at a given timestamp. `/api/v1/accounts{id}` returns the latest balance and `/api/v1/balances` returns the balance reported by the balance stream files every 15 mins. However, the balance at a given time especially within the last 15 mins is not exposed but needed.

### Solution

Enhance `/api/v1/accounts/{id}` REST API to:
* Add a `timestamp` filter that supports `lt`, `lte`, `eq`, and `gt`, `gte` operators
* Retrieve `account_balance` closest to time and sum transfers to show historical balance
* Return entity info from either `entity` or `entity_history` to provide the state of the account at that latest time within the given range
* Filter transactions list using that timestamp range

**Comment by steven-sheehy** [comment]
Duplicates https://github.com/hashgraph/hedera-mirror-node/issues/5862 which was fixed by https://github.com/hashgraph/hedera-mirror-node/pull/6034
