### ISSUE TITLE
Empty and null uint256 values show up as 0x

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-mirror-node#4769]
### Description

Contract state changes and contract state REST APIs show uint256 values as `0x` when the data is  `null` or an empty byte array. Instead, an empty byte array represents zero (since consensus nodes remove leading zeros to save on bytes) so should be shown as `0x0000000000000000000000000000000000000000000000000000000000000000`. For `null` db values we should show `null` in the REST API. This applies to `slot`, `value_read`, `value_written`, and `value` fields in those APIs.

### Steps to reproduce

https://testnet.mirrornode.hedera.com/api/v1/contracts/0.0.48679581/results/1666888106.746168003

### Hedera network

previewnet

### Version

v0.67.1

**Comment by steven-sheehy** [comment]
To fix, create a new utility method `toUint256()` that pads all non-null arrays to 64 characters and null values to null. Then use that util method everywhere for contract slot and values

**Comment by shemnon** [comment]
Canonically all storage is some 32 byte value, with special handling for the all-zero value.  This is consistent with the ethereum spec.

**Comment by shemnon** [comment]
The JSON-RPC specs are a bit vauge on the "correctness" of this.  The execution spec type for the [storage value](https://github.com/ethereum/execution-apis/blob/main/src/eth/state.yaml#L31-L34) is `bytes`, which is distinct from `bytes32` which must be zero padded.  The prose (non-normative) doc declares the type as `DATA`, which makes the length relevant, however it does not specify the length.

So the only incorrect value is `null`, a fully trimmed zero would fit the spec. However all examples in [the prose doc](https://ethereum.org/en/developers/docs/apis/json-rpc/#eth_getstorageat) use a 32 byte padded value, so fully padding appears to be a good choice.

**Comment by steven-sheehy** [comment]
True, we can add a note to the OpenAPI spec to that effect. Perhaps Hashscan can explicitly put a `No write occurred` for null `value_written` when displaying it.

**Comment by dimitrovmaksim** [comment]
I think the the storage slot should not be long-zero e.g. 0 should be 0x0, 1 should be 0x1 and so on

**Comment by dimitrovmaksim** [comment]
Should the slot be long-zero padded? I can't get a definite answer to that
