### ISSUE TITLE
mirror-node: validate system against services/R4 once it reaches staging

### ISSUE THREAD

**Issue by donaldthibeau** [hashgraph/hedera-mirror-node#478]
@mike-burrage-hedera commented on [Thu Nov 14 2019](https://github.com/hashgraph/internal/issues/39)

**Timeline for this is not known - depends on services R4 release to staging.**

Once the services R4 release hits staging, which has the ability to publish streams to buckets:

- deploy production mirror-node code to mirror-node-dev
- run acceptance tests against the mirror-node to validate that the integration between services and mirror-node still works

_Note: mirror-node may have to generate traffic through services in order to validate this integration. This may get to use code written for the scale testing https://github.com/hashgraph/hedera-mirror-node/issues/282 ticket_

---

@donaldthibeau commented on [Fri Jan 03 2020](https://github.com/hashgraph/internal/issues/39#issuecomment-570597868)

@mike-burrage-hedera moving this to the mirror node repo.

**Comment by steven-sheehy** [comment]
We've validated mirror node against staging and testnet.
