### ISSUE TITLE
mirror-node: Setup proper staging environment pointing at mainnet bucket

### ISSUE THREAD

**Issue by donaldthibeau** [hashgraph/hedera-mirror-node#480]
@mike-burrage-hedera commented on [Tue Dec 10 2019](https://github.com/hashgraph/internal/issues/45)

- Work with ops to create a new staging importer box, api box, and cloudsql DB.
- Install the importer and rest-api on these boxes. Importer should point at mainnet bucket.
- Delete the existing staging boxes.

We should decide if we either want these boxes to be the current production hardware spec, or more like the current dev hardware spec with a larger DB - this is a cheaper spec that we plan on migrating production to.

The reasoning behind this is to ensure that we test upgrades against mainnet data before getting to testnet.

**Comment by steven-sheehy** [comment]
We have this now
