### ISSUE TITLE
Update GCP Marketplace

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-mirror-node#4801]
### Problem

The version of mirror node in GCP Marketplace is out of date and may contain security vulnerabilities

### Solution

Update GCP Marketplace as per [checklist](https://github.com/hashgraph/hedera-mirror-node/blob/main/docs/checklist/marketplace.md)

**Comment by steven-sheehy** [comment]
We should tackle #4806 before working on this

**Comment by mgoelswirlds** [comment]
This has been published https://console.cloud.google.com/marketplace/product/mirror-node-public/hedera-mirror-node?project=mirror-node-public
