### ISSUE TITLE
mirror-node: integration environment cleanup

### ISSUE THREAD

**Issue by donaldthibeau** [hashgraph/hedera-mirror-node#481]
@mike-burrage-hedera commented on [Tue Sep 17 2019](https://github.com/hashgraph/internal/issues/2)

- *Decide what additional non-production environments need to be setup for the mirror-node*
  - Just a staging environment that's very close to production (in terms of the codebase installed) and only differs from production briefly during upgrades?
  - A "stable/preview/canary" additional environment that holds to-be-released code (new features) for a while before being released to production?

- Rebuild the staging environment with the same spec (hardware and software) as "dev" - see infrastructure ticket infrastructure [#125](https://github.com/swirlds/infrastructure/issues/125).
  - Use the same database host as dev (rather than creating another instance) - with a different database name.
- Setup the stable/preview/canary environment in the same manner as staging/dev (using the same DB host - not an additional host)

**Comment by steven-sheehy** [comment]
Mirror node now has a staging environment with a similar setup as testnet and mainnet (but without the failovers). It also has integration, performance, dev, testnet and mainnet environments. I think this is good for now and we can close.
