### ISSUE TITLE
Investigate and add autovacuum settings back for v2 partitioning

### ISSUE THREAD

**Issue by mgoelswirlds** [hashgraph/hedera-mirror-node#4814]
### Description

Currently if we add the autovacuum settings for v2 partitioning , the importer throws an error.  As in the image.
<img width="1468" alt="Screen Shot 2022-11-01 at 10 11 28 PM" src="https://user-images.githubusercontent.com/106084778/199774769-57dc7fd6-3881-4656-aec9-e2717b558778.png">

We need to investigate what is going on and add autovacuum settings back.

### Steps to reproduce

When you run `SPRING_PROFILES_ACTIVE=v2 ./mvnw spring-boot:run -pl hedera-mirror-importer` it throws the above error.

### Hedera network

other

### Version

latest main

**Comment by jnels124** [comment]
confirmed that you are not able to configure any vacuum settings for individual tables. Created a [ticket](https://github.com/citusdata/citus/issues/7129) upstream. Still investigating the issue and trying to determine if there is still a need for these settings given [each shard is vacuumed with its own process](https://docs.citusdata.com/en/v12.0/admin_guide/table_management.html#vacuuming-distributed-tables).
