### ISSUE TITLE
Mirrorrnode shows incorrect staking state

### ISSUE THREAD

**Issue by xin-hedera** [hashgraph/hedera-mirror-node#4815]
### Description

There are some issues in staking related info shown by mirrornode:

1. Some accounts have more pending reward shown by the REST API than it should
2. An account's pending reward stays 0 one full staking period after a staking reward payout is triggered
3. Some accounts started to stake to a node before staking feature went alive in mainnet. services OKed such transactions and ignored the staking info while mirrornode processed the staking info as if the accounts had staked to a node.

### Steps to reproduce

Query the affected account's pending reward and staking state through REST API

### Hedera network

mainnet

### Version

v0.67.0

**Comment by robkainz** [comment]
@xin-hedera Hi Xin, please also be aware that according to Michael Tinker the stake period start date was showing incorrectly also on the mirror node in the issue he cited in which I saw the date 10/31 on Hashscan whereas the paid query showed 10/30: https://github.com/hashgraph/hedera-services/issues/4166

**Comment by xin-hedera** [comment]
Thanks @robkainz, will look into that as well

**Comment by robkainz** [comment]
> Thanks @robkainz, will look into that as well

Actually, I don't think this is a problem. I believe the mirror is reporting October 31 because it's showing the time as UTC midnight, whereas the paid query is returning October 30 8 PM EDT (4 hours before.) They are the same, just a formatting issue.

**Comment by robkainz** [comment]
Hi @xin-hedera 

FYI (in case you are not already aware): I am still seeing in mainnet an issue with the start stake time, they can be a day off.

mirror node reports: 1668038400.000000000 => (Thursday, November 10, 2022 12:00:00 AM GMT), Wednesday, November 9, 2022 7:00:00 PM GMT-05:00

hedera services reports:: 1667952000 => (Wednesday, November 9, 2022 12:00:00 AM GMT), Tuesday, November 8, 2022 7:00:00 PM GMT-05:00

**Comment by xin-hedera** [comment]
@robkainz it will be addressed by the PR which should go into 0.68.x soon.
