### ISSUE TITLE
mirror-node: move "pinger" to monitor server

### ISSUE THREAD

**Issue by donaldthibeau** [hashgraph/hedera-mirror-node#485]
@mike-burrage-hedera commented on [Tue Oct 15 2019](https://github.com/hashgraph/internal/issues/10)

The "pinger" app that generates transactions frequently in testnet to ensure that records files get written - should move off publictestnet-1 host and onto the host monitoring testnet.

- It should be in source control somewhere
- It should be moved off the production publictestnet host and onto the monitoring host.
- It should be documented (internal on sharepoint) as to how the mirror-node team and ops can identify that production issues are related to it (it stopped) and then how to restart it.

**Comment by steven-sheehy** [comment]
Ops has completed this task and is now part of ansible
