### ISSUE TITLE
Create a bucket restructuring HIP

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-mirror-node#4875]
### Problem

The current stream file structure in cloud storage is based around node account IDs. Hedera wants nodes to be able to change their node account IDs.

### Solution

Create a HIP detailing the desired node ID based bucket structure.

**Comment by mgoelswirlds** [comment]
[This](https://github.com/hashgraph/hedera-improvement-proposal/pull/679) is the link to the HIP PR.
