### ISSUE TITLE
gRPC Consensus Service Repository Query Stuck in Idle State

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-mirror-node#491]
**Detailed Description**
When a client calls the subscribeTopic() endpoint the first action performed is a repository.findByFilter() call that uses the databaseClient to obtain historic messages for a given topic. Following this if the POLL mode is set we will query the db for messages that came in after the initial query, this is to obtain incoming messages.

During load testing it was observed that on some client subscriptions the select query operation to obtain messages is not performed. Other connection pool operations for the load tester are successful run but the connection by the gRPC endpoint seems to not make it through. The result is that no items are passed along the flux to the client and no topic messages are returned (history and incoming). Incoming messages can be blocked due to this flow because of the Flux logic used - we obtain historic messages first before attempting to get incoming.
Additionally if the historic query is run the incoming messages query can hit this same issue.

Watching the db queries, it was confirmed that the query was not even being run on the db.
Querying the pg_stat_activity table for idle transactions confirmed the expected query was submitted and received but not being run.

` usename  | application_name | backend_start     | xact_start |     query_start     |     state_change     | wait_event_type | wait_event | state | backend_xid | backend_xmin |                                                                                              query
`
`mirror_grpc | r2dbc-postgresql | 2020-01-08 22:01:34.507146+00 |      | 2020-01-08 22:03:25.08462+00 | 2020-01-08 22:03:25.085652+00 |         |      | idle |       |       | SELECT topic_message.consensus_timestamp, topic_message.message, topic_message.realm_num, topic_message.running_hash, topic_message.sequence_number, topic_message.topic_num FROM topic_message WHERE topic_message.realm_num = $1 AND topic_message.topic_num = $2 AND topic_message.consensus_timestamp >= $3 AND topic_message.consensus_timestamp < $4 ORDER BY consensus_timestamp ASC`

This issue seems to be intermittent and future subscriptions do not always encounter this.
Also not all gRPC channel subscriptions experience the issue

**Actual Behavior**
1. Subscribe to a topic with historic messages present
2. gRPC server returns 0 messages with no errors relating to connection pool issues

**Expected Behavior**
gRPC server returns n number of historic messages

**User/gRPC Client Impact**
1. No messages are returned
2. All historical messages are returned but no incoming messages (if issue is hit on first poll)
3. All historical messages are returned but not all incoming messages (if issue is hit on future polls)

**Environment:**
- Java: OpenJDK 11
- Node: n/a
- OS: Mac OSX 10.14.6 & Ubuntu 16.04
- Version: 0.5.0

**Additional Context**
This issue is not a result of extensive load testing as originally expected. Idle transactions can be viewed in db after single subscription and a newly started Postgres instance

**Comment by steven-sheehy** [comment]
This was due to bad data in dev with sequence numbers and consensus timestamps that were duplicate or invalid. We also fixed a race condition in #505 that may help. Closing
