### ISSUE TITLE
Add missing rest api performance tests to k6 test suite

### ISSUE THREAD

**Issue by xin-hedera** [hashgraph/hedera-mirror-node#4961]
### Problem

The k6 rest api test suite has not been updated properly whenever we add new endpoints

### Solution

- Add new performance test for every endpoint that is missing

**Comment by mgoelswirlds** [comment]
Missing endpoints so far:

```
/accounts/{id}/allowances/tokens
/accounts/{id}/nfts
/accounts/{id}/tokens
/blocks
/blocks/{id}
/contracts/{id}/state
/contracts/result
/contracts/result/{transactionId}
/contracts/result/{transactionId}/actions
/contracts/result/logs
/network/exchangerate
/network/fees
/network/nodes
/transactions/{id}/stateproof
```

**Comment by mgoelswirlds** [comment]
A part of the above mentioned rest endpoints are handles as part of this story.
Others would be done as part of https://github.com/hashgraph/hedera-mirror-node/issues/5104
