### ISSUE TITLE
Slow monitor check 'transactions and performed account'

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-mirror-node#500]
**Detailed Description**
Brad noticed the last check on the monitor `Successfully called transactions and performed account check` can sometimes fail. It looks like it times out since it exceeds the 5s timeout of the proxy. If you invoke the underlying REST API call it references `http://ip:port/api/v1/transactions?account.id=98&type=credit&limit=1` it can exceed 10s.

**Actual Behavior**
1. Visit monitor
2. Click particular server
3. View last test sometimes fail

**Expected Behavior**
No timeouts and the monitor to stay green

**Environment:**
- Node: v12
- OS: Ubuntu 18.04
- Version: v0.5.1

**Additional Context**
Add any other context about the problem here. Attach any logs here, if applicable.

**Comment by apeksharma** [comment]
I see no "Successfully called transactions and performed account check" test on the monitor, maybe it's disabled to avoid escalations.
Ran the query locally, i don't see it taking >1.3sec in 369 runs. Maybe some db schema change in last 3 months fixed it already (although i can't find a good candidate in migration files). 

```
$ while [ 1 == 1 ]; do time curl  -s 'https://testnet.mirrornode.hedera.com/api/v1/transactions?account.id=98&type=credit&limit=1'; sleep 1;  done > curl_log.txt 2>&1
```
[curl_log.txt](https://app.zenhub.com/files/197364349/6ce51388-80f0-44e4-9255-381499b822e9/download)

Anyways, let's reenable it. Closing this ticket.
