### ISSUE TITLE
HIP-584: Security & Cache enhancements for `eth_call` JSON RPC calls

### ISSUE THREAD

**Issue by IvanKavaldzhiev** [hashgraph/hedera-mirror-node#5048]
### Problem

We need to provide the following enhancements for `eth_call` requests:

1. Enhance security mechanisms for `eth_call` requests, so that the system is not overloaded
2. Provide cache mechanism wherever possible to optimize performance for multiple requests

The following tasks have been defined:

- [x] #5049 
- [x] #5050 
- [x] #5051 
- [x] #5320 
- [x] #5052 
- [x] #5321 
- [x] #5397 
- [x] #5399 

### Solution

1. Provide rate limit for HTTP requests and gas limit for a single execution
2. Investigate where and how cache could be added and define proper parameters

**Comment by steven-sheehy** [comment]
All tasks completed
