### ISSUE TITLE
Add remaining missing rest api performance tests to k6 test suite

### ISSUE THREAD

**Issue by mgoelswirlds** [hashgraph/hedera-mirror-node#5104]
### Problem

The following rest endpoints are missing from the k6 spec tests.

```
/contracts/{id}/state
/contracts/result/{transactionId}
/contracts/result/{transactionId}/actions
/contracts/result/logs
/network/exchangerate
/network/fees
/network/nodes
/transactions/{id}/stateproof
```

### Solution

Add tests for the above mentioned rest endpoints to the k6 spec.

A part of this was done as part of https://github.com/hashgraph/hedera-mirror-node/issues/4961 for reference

**Comment by MarcKriguerAtHedera** [comment]
8 new tests added.  6 of them green checks, 1 gives a red check that it worked 93% of the time, and the last one consistently gets back an empty array from the API call.  I don't see an alternative API call to make to get back a transaction hash that's more likely to have a non-empty "actions" array.

Stats from the run:
     ✓ Contracts id state OK
     ✓ Contracts Results id OK
     ✗ Contracts Results id Actions OK
      ↳  0% — ✓ 0 / ✗ 7423
     ✓ Contracts Results Logs OK
     ✓ Network exchangerate OK
     ✓ Network Fees OK
     ✓ Network Nodes OK
     ✗ Transactions id Stateproof OK
      ↳  93% — ✓ 3519 / ✗ 264

     █ setup

     checks........................................................................: 97.70%  ✓ 326809     ✗ 7687
     ✓ { scenario:contractsIdState }...............................................: 100.00% ✓ 7396       ✗ 0
     ✓ { scenario:contractsResultsId }.............................................: 100.00% ✓ 7799       ✗ 0
     ✗ { scenario:contractsResultsIdActions }......................................: 0.00%   ✓ 0          ✗ 7423
     ✓ { scenario:contractsResultsLogs }...........................................: 100.00% ✓ 7106       ✗ 0
     ✓ { scenario:networkExchangerate }............................................: 100.00% ✓ 7453       ✗ 0
     ✓ { scenario:networkFees }....................................................: 100.00% ✓ 7778       ✗ 0
     ✓ { scenario:networkNodes }...................................................: 100.00% ✓ 7582       ✗ 0
     ✗ { scenario:transactionsIdStateproof }.......................................: 93.02%  ✓ 3519       ✗ 264

     ✓ { scenario:contractsIdState,expected_response:true }........................: avg=66.85ms  min=49.62ms  med=57.87ms  max=799.12ms p(90)=72.67ms  p(95)=81ms
     ✓ { scenario:contractsResultsId,expected_response:true }......................: avg=64.86ms  min=49.6ms   med=57.42ms  max=631.98ms p(90)=73.01ms  p(95)=82.78ms
     ✓ { scenario:contractsResultsIdActions,expected_response:true }...............: avg=60.22ms  min=48.43ms  med=55.94ms  max=557.61ms p(90)=69.72ms  p(95)=76.55ms
     ✓ { scenario:contractsResultsLogs,expected_response:true }....................: avg=164.39ms min=140.52ms med=159.86ms max=719.32ms p(90)=185.41ms p(95)=194.85ms
     ✓ { scenario:networkExchangerate,expected_response:true }.....................: avg=90.96ms  min=59.58ms  med=72.51ms  max=1.1s     p(90)=98.4ms   p(95)=166.47ms
     ✓ { scenario:networkFees,expected_response:true }.............................: avg=91.25ms  min=60.25ms  med=73.81ms  max=961.22ms p(90)=102.53ms p(95)=168.56ms
     ✓ { scenario:networkNodes,expected_response:true }............................: avg=63.21ms  min=48.61ms  med=57.06ms  max=731.87ms p(90)=72.47ms  p(95)=81.43ms
     ✗ { scenario:transactionsIdStateproof,expected_response:true }................: avg=451.83ms min=176.89ms med=377.43ms max=10.46s   p(90)=718.53ms p(95)=900.16ms

     ✓ { scenario:contractsIdState }...............................................: 7396    2.803092/s
     ✓ { scenario:contractsResultsId }.............................................: 7799    2.955829/s
     ✓ { scenario:contractsResultsIdActions }......................................: 7423    2.813325/s
     ✓ { scenario:contractsResultsLogs }...........................................: 7106    2.693181/s
     ✓ { scenario:networkExchangerate }............................................: 7453    2.824695/s
     ✓ { scenario:networkFees }....................................................: 7778    2.94787/s
     ✓ { scenario:networkNodes }...................................................: 7582    2.873586/s
     ✓ { scenario:transactionsIdStateproof }.......................................: 3783    1.433761/s

     scenario_duration.............................................................: 50363   min=144      max=52299
     ✓ { scenario:contractsIdState }...............................................: 50204   min=170      max=50204
     ✓ { scenario:contractsResultsId }.............................................: 50333   min=157      max=50333
     ✓ { scenario:contractsResultsIdActions }......................................: 51514   min=157      max=51514
     ✓ { scenario:contractsResultsLogs }...........................................: 50374   min=258      max=50374
     ✓ { scenario:networkExchangerate }............................................: 50305   min=172      max=50305
     ✓ { scenario:networkFees }....................................................: 50309   min=178      max=50309
     ✓ { scenario:networkNodes }...................................................: 50390   min=157      max=50390
     ✓ { scenario:transactionsIdStateproof }.......................................: 52299   min=442      max=52299
