### ISSUE TITLE
Gradle release task always set image tag to the version property

### ISSUE THREAD

**Issue by xin-hedera** [hashgraph/hedera-mirror-node#5113]
### Description

The maven version replacer allows setting module version and docker tag version separately. The docker tag version is used to replace the hedera-mirror-* docker image version in `docker-compose.yml` and the Chart.appVersion in our charts. This provides the flexibility for our release automation to:

- Set the version in `docker-compose.yaml` and Chart.appVersion to the same non-snapshot versions
- Set the version in `docker-compose.yaml` and Chart.appVersion to `main` for snapshot versions 

The Gradle task will set everything to the `version` property.

### Steps to reproduce

Run `./gradlew release -Pversion=$VERSION`

### Hedera network

other

### Version

0.72.0-SNAPSHOT

### Operating system

None

**Comment by steven-sheehy** [comment]
This was intentional to simplify the logic and only maintain a version property. We only use the release task in CI and the current behavior is sufficient for its needs. Why does it need to change?

**Comment by steven-sheehy** [comment]
Also should clarify that we now maintain a `x.y.z-SNAPSHOT` tag that always points to the latest `main` for that milestone. We should use that snapshot tag in the charts and compose files, not the old `main`. Thus we wouldn't need a separate docker tag property like we had in main and can set everything to snapshot using `version` property.

**Comment by xin-hedera** [comment]
due to how we replace the version in docker-compose.yaml

```
replaceVersion("docker-compose.yml", "(?<=:)main")
``

and how the release automation creates the snapshot version bump PR

suppose we tag a 0.72.0-rc1 from main using the automation release, the following will happen

- creates `release/0.72` branch
- tags 0.72.0-rc1, the gradle release step will replace version with `0.72.0-rc1` everywhere
- in the `Create PR` job, `Gradle Release for Next Minor Snapshot` tries to replace version with `0.73.0-SNAPSHOT`, however the version in docker-compose will remain at `0.72.0-rc1`

**Comment by xin-hedera** [comment]
sounds like I need to close this ticket and create another one for the issue that the regex for docker-compose.yaml version rerplacer is hardcoded with main.

**Comment by xin-hedera** [comment]
found another issue caused by changing `Chart.appVersion` from `"main"` to snapshot version in main branch, the chart install job will fail since for rosetta chart test, it'll try to run the postman from branch/tag v0.72.0-SNAPSHOT which obviously doesn't exist

**Comment by xin-hedera** [comment]
I can create another ticket "Gradle release task break contract with some github workflows"

To fix it, we need

- Change the release task's docker-compose regex to `"(?<=gcr.io/mirrornode/hedera-mirror-.*:).+"`
- Change the chart install job to use the head commit SHA for push event to get the correct postman.json file
- Fix any other place depending on `Chart.appVersion = main`

We will then have

- consistent version across board
- working github workflows

**Comment by steven-sheehy** [comment]
That sounds like a reasonable approach. We can just use this ticket to fix anything needed.

Also, the regex hack in the chart test to add v prefix also seems hacky. Wondering if we should move that to chart workflow so we don't have to repeat it for each chart like web3.
