### ISSUE TITLE
Record Parser unable to keep up

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-mirror-node#512]
**Detailed Description**
In the performance test environment, 1.5K TPS was ran at 11 CST then pushed to 5K TPS at 3 CST. During this time the mirror node became increasingly unable to keep up, eventually becoming 7hrs behind in 23hr test.

**Actual Behavior**
Generate a load on mainnet and watch parser not keep up

**Expected Behavior**
Record parser can keep up with increased transactions per second that mainnet can handle.

**Environment:**
- Java: OpenJDK 11.0.2
- OS: Ubuntu 18.04
- Version: v0.5.2

**Additional Context**
PostgreSQL statistics show the inserts to `t_cryptotransferlists` and `t_transactions` are the heaviest used part of the system at the time.

```
mirror_node=> SELECT substring(query, 1, 50) AS short_query,
mirror_node->               round(total_time::numeric, 2) AS total_time,
mirror_node->               calls,
mirror_node->               round(mean_time::numeric, 2) AS mean,
mirror_node->               round((100 * total_time /
mirror_node(>               sum(total_time::numeric) OVER ())::numeric, 2) AS percentage_cpu
mirror_node-> FROM    pg_stat_statements
mirror_node-> ORDER BY total_time DESC
mirror_node-> LIMIT 20;
                    short_query                     | total_time  |   calls    | mean  | percentage_cpu
----------------------------------------------------+-------------+------------+-------+----------------
 INSERT INTO t_cryptotransferlists (consensus_times | 25789531.56 | 1161347973 |  0.02 |          68.57
 INSERT INTO t_transactions (fk_node_acc_id, memo,  | 10149207.22 |  232698039 |  0.04 |          26.99
 <insufficient privilege>                           |   599819.72 |      57614 | 10.41 |           1.59
 <insufficient privilege>                           |   577730.14 |      54292 | 10.64 |           1.54
 <insufficient privilege>                           |   262085.52 |      57614 |  4.55 |           0.70
 <insufficient privilege>                           |    39465.54 |    1139951 |  0.03 |           0.10
 <insufficient privilege>                           |    30767.96 |    1727118 |  0.02 |           0.08
 INSERT INTO t_contract_result (consensus_timestamp |    30511.47 |    1462108 |  0.02 |           0.08
 <insufficient privilege>                           |    25529.41 |      57614 |  0.44 |           0.07
 select entities0_.id as id1_3_0_, entities0_.auto_ |    22934.61 |    1461926 |  0.02 |           0.06
 select * from f_file_create($1, $2 )  as result    |    13087.12 |      53856 |  0.24 |           0.03
 <insufficient privilege>                           |    10791.66 |     938608 |  0.01 |           0.03
 <insufficient privilege>                           |    10605.67 |      57614 |  0.18 |           0.03
 select * from f_file_complete( $1, $2, $3 )  as re |     9218.32 |      27629 |  0.33 |           0.02
 <insufficient privilege>                           |     8764.41 |      57614 |  0.15 |           0.02
 <insufficient privilege>                           |     6438.64 |      57614 |  0.11 |           0.02
 update t_application_status set status_value=$1 wh |     4240.41 |      93368 |  0.05 |           0.01
 select applicatio0_.status_code as status_c1_0_0_, |     3256.72 |      86764 |  0.04 |           0.01
 insert into account_balances (consensus_timestamp, |     2593.74 |     114249 |  0.02 |           0.01
 <insufficient privilege>                           |     2375.97 |     115227 |  0.02 |           0.01
```

**Comment by gregscullard** [comment]
Which node code base was this ? The latest (per testnet) has less data in records (fewer transfer list since fee payments are aggregated)  

Would this alleviate the load somewhat ?

Envoyé depuis mon iPhone/Sent from my iPhone

**Comment by steven-sheehy** [comment]
This was in perf test environment which I believe has latest R4 release candidate. There might be a few less entries per cryptotransfer but I don't think that's enough to make an impact.

**Comment by gregscullard** [comment]
Could be a 50 to 75% reduction in the number of table rows inserted. 

Envoyé depuis mon iPhone/Sent from my iPhone

**Comment by mike-burrage-hedera** [comment]
Quick Suggestions:
- Removing foreign keys and trigger in production
- Remove index on "amount" for t_cryptotransferlists
- Remove unneeded indexes on t_transactions that aren't part of rest-api queries (indexes on fk_rec_file_id and idx_t_transactions_node_account). Possibly index on fk_payer_acc_id - need to check rest-api queries
- See what the effect of batchSize is and if increasing/decreasing it speeds things up.

More involved suggestions:
- Don't use an overall db transaction for record streams (requires additional logic to handle failures)
- Move topic_message data to a separate database
- Load record streams concurrently

**Comment by steven-sheehy** [comment]
Another suggestion:
- Remove `t_record_files` and corresponding foreign key/index. It's not read by anybody and would be useless later if we changed aggregated older record files to speed catch up.
