### ISSUE TITLE
Optionally break out fees explicitly in the rest-api results.

### ISSUE THREAD

**Issue by mike-burrage-hedera** [hashgraph/hedera-mirror-node#516]
**Problem**
In the upcoming Hedera network upgrade (version R4), which is currently in testnet, the TransferList in the TransactionRecord contains _only_ 1 Transfer per account.

It is an aggregated amount that aggregates any of the following into a single row/transfer per account:
- explicit transfers to/from the account from a CryptoTransfer or CryptoCreateAccount (initial_balance)
- any node, network, service or threshold record fees paid or received (including the node account and treasury accounts)

Provide the ability for the rest-api to return _either_ these aggregated transferlists (raw data from the TransactionRecord itself) or to return a TransferList that has explicit transfers and threshold record fees broken out. Each explicit CryptoTransfer transfer, CryptoCreateAccount amount, node fee, or threshold record fee applied to/from each account to appear as a separate transfer item, and the network+service fees (both paid to the treasury) will be combined in a single item.

**Solution**
In the prior version of the Hedera network (R3, currently in mainnet), the rest-api response for a CryptoTransfer from account 0.0.98765 to 0.0.56789 for 10000 tinybar, generating a receiver threshold record (which costs the reciever 100 tinybars), may look like this (reflecting the actual underlying TransactionRecord's transferlist):

**R3 (current mainnet) transfers look like:**
```
"charged_tx_fee":1000,  /* node + network + service fee paid by transaction payer, not including any threshold record fees */
"transfers":[
    {"account":"0.0.5", "amount":400}, /* node fee paid to node */

    {"account":"0.0.98", "amount":100}, /* threshold record fee paid to treasury */
    {"account":"0.0.98", "amount":250}, /* network fee paid to treasury */
    {"account":"0.0.98", "amount":350}, /* service fee paid to treasury */

    {"account":"0.0.56789", "amount":-100}, /* threshold record fee paid by receiver */
    {"account":"0.0.56789", "amount":10000}, /* transfer to receiver */

    {"account":"0.0.98765", "amount":-10000}, /* transfer from sender */
    {"account":"0.0.98765", "amount":-750}, /* node fee + service fee paid by sender */
    {"account":"0.0.98765", "amount":-250} /* network fee paid by sender */
]
```

As of R4, only the _aggregate_ amount each account changed is provided in the TransactionRecord's transferlist:

**R4 (current testnet) transfers look like:**

```
"charged_tx_fee":1000,  /* node + network + service fee paid by transaction payer, not including any threshold record fees */
"transfers":[
    {"account":"0.0.5", "amount":400}, /* node fee paid to node */

    {"account":"0.0.98", "amount":700}, /* threshold record + network + service fees paid to treasury */

    {"account":"0.0.56789", "amount":9900}, /* transfer to receiver minus threshold record fee */

    {"account":"0.0.98765", "amount":-11000} /* transfer from sender minus node + network + service fee */
]
```

Provide an option for the mirror-node's rest-api to continue returning a (similar to R3) itemized list of transfers, such that the returned "transfers" would look like this:

**Proposed option:**
```
"charged_tx_fee":1000, /* node + network fee paid by transaction payer, not including any threshold record fees */
"transfers":[
    {"account":"0.0.5", "amount":400}, /* node fee paid to node */

    {"account":"0.0.98", "amount":100}, /* threshold record fee paid to treasury */
    {"account":"0.0.98", "amount":600}, /* network + service fees paid to treasury */

    {"account":"0.0.56789", "amount":-100}, /* threshold record fee paid by receiver */
    {"account":"0.0.56789", "amount":10000}, /* transfer to receiver */

    {"account":"0.0.98765", "amount":-10000}, /* transfer from sender */
    {"account":"0.0.98765", "amount":-600}, /* network + service fees paid by sender */
    {"account":"0.0.98765", "amount":-400} /* node fee paid by sender */
]
```

**Additional Context**
The proposal is for:
- the rest-api to return the "Proposed Option" above as the default for `/api/v1/transactions`.
- `/api/v1/transactions` to accept a query string parameter "transfers=raw" to return the "R4" data above, the exact transfers from the underlying TransactionRecord

Logic for deriving the "Proposed Option" from the raw "R4" data:

1. Take the aggregate transfers from the TransactionRecord and store in a map (1 entry per account):
```
unallocatedTransferAmounts:
  98765: -11000
  56789: 9900
  98: 700
  5: 400
```
2. Add the CryptoTransfer transaction transfers and CryptoCreateAccount initial balance transfers explicitly to the output transfer list and update the map, leaving fees only in the map:
```
transfers: [98765: -10000, 56789: +10000]
unallocatedTransferAmounts:
  98765: -1000 /* -11000 + 10000 (xfer sent) = -1000 (node + network + service fees) */
  56789: -100 /* 9900 - 10000 (xfer received) = -100 (threshold fee) */
  98: 700 /* (network + service + threshold fees) */
  5: 400 /* (node fee) */
```
3. Extract the threshold records from the map into the transfers list:
```
transfers: [98765: -10000, 56789: +10000] + [56789: -100, 98: +100]
unallocatedTransferAmounts:
  98765: -1000 /* unchanged, 1000 is the charged_tx_fee, no threshold fee here */
  56789: 0 /* deducted the remainder as threshold fee -100 (because this was neither payer, node, or treasury */
  98: 600 /* deducted threshold fee paid by 56789, remainder is network+service fee */
  5: 400
```
4. Extract the node and network+service fees explicitly (paid for by payer account and adding up to charged_tx_fee):
```
transfers: [98765: -10000, 56789: +10000, 56789: -100, 98: +100] + [98765: -600, 98: +600, 98765: -400, 5: +400]
unallocatedTransferAmounts:
  98765: 0 /* 1000 - 1000 (charged_tx_fee) */
  56789: 0
  98: 0 /* -600 network+service fee */
  5: 0 /* -400 node fee */
```

Implementation suggestion:
- new table `non_fee_transfers` identical in structure to t_cryptotransferlists to store the requested transfers from the CryptoTransferTransactionBody's transferlist or CryptoCreateAccount's initial balance.
- `importer` to store data in `non_fee_transfers`, on successful CryptoTransfer/CryptoCreateAccount/ContractCreate processing, if the TransactionRecord is not itemized (ie R4 or later)
- `rest-api` (in /api/v1/transactions if no "transfers=raw" is specified) to:
  - query t_cryptotransferlists in addition to non_fee_transfers
  - run the algorithm above to generate an itemized/broken-out transfer list response

**Comment by carlcherry** [comment]
A couple of questions about the algorithm:
1. Once you get aggregated number how do you determine which account paid the record fees. If I have this: A: -1000, B: +990, could it not be that A sent 990 and paid a 100 fee OR that A sent 1000 and B paid the 100 fee.  Ken had mentioned that either the sender or receiver could be paying the record fee but maybe that is not correct.
2. Is it possible to have multiple senders and receivers?  The use case above is for the simple case of a single sender/receiver so I am curious how it will work with a more complicated case.
3. I assume that the record fees are "not" some hard-coded amount.

**Comment by carlcherry** [comment]
I also found this case in the postgres database - looks like account 15396 send 200000 tinybars to the node 0.0.3. It has a type of CryptoTransfer. Once aggregated it seems to me that it would difficult to differentiate fees from a transfer - unless this is just some transfer early after release that is not really valid.

https://explorer.kabuto.sh/mainnet/transaction/5c6be8cfdca5644613daaa3ba7223d9ede153d10ad0a06b3a65f3f060878ede022bc6f661f8e214fc92fcb8863f7fc9d

 consensus_timestamp | realm_num | entity_num | amount
---------------------+-----------+------------+---------
 1568429317684754000 |         0 |                     3 |    1810
 1568429317684754000 |         0 |                     3 |  200000
 1568429317684754000 |         0 |                   98 |  134932
 1568429317684754000 |         0 |                   98 |     880
 1568429317684754000 |         0 |             15396 | -136742
 1568429317684754000 |         0 |             15396 |    -880
 1568429317684754000 |         0 |             15396 | -200000

**Comment by mike-burrage-hedera** [comment]
In order to take an aggregated transfer list (1 entry per account) and generate an itemized list that splits out explicitly requested transfers, threshold record fee payments, node fee payment, and network-service fee payments to the treasury account (aka transaction fees in some places), the transaction's requested transfers (explicitly requested transfers) are required.

Those transfers (A transfers 1000 to B and 2000 to C, or A creates B with 1000 initial balance) need to go into the new `non_fee_transfers` table in the mirror-node importer.

In the case in the comment above, if the transfer was from 15396 to 3 for 200k, there would be 2 rows in `non_fee_transfers` of (15396, -200k) and (3, +200k).

Step 1: aggregated list of amounts per account
```
charged_tx_fee: 137622
aggregated amounts:
3: 201810
98: 135812
15396: -337622
non_fee_tranfers:
3: 200000
15396: -200000
```

Step2: extract explicit transfers (non-fees) using non_fee_transfers table
```
itemized list (being built):
3: 200000
15396: -200000
charged_tx_fee: 137622
unallocated aggregated amounts (now only fee-related):
3: 1810
98: 135812
15396: -137622
```

Step3: extract threshold records
```
itemized list (being built):
3: 200000
15396: -200000
charged_tx_fee: 137622
unallocated aggregated amounts -now only representing node fee and network-service/transaction fees:
3: 1810
98: 135812
15396: -137622
```

Here there are none.
charged_tx_fee does not include threshold record fees and exactly matches the payer's unallocated amount.
If 15396 generated a threshold record, 15396's amount + charged_tx_fee would still be negative (by exactly the threshold record fee).
If the transfer included some other accounts that generated threshold records, then there would be non-node, non-treasury accounts with negative unallocated amounts (equal to the threshold record fee that those recipient accounts paid).

Step4: extract network-service/transaction and node fees
```
itemized list (being built):
3: 200000
15396: -200000
3: 1810 /* node fee */
15396: -1810 /* node fee */
98: 135812 /* network-service/transaction fee */
15396: -135812 /* network-service/transaction fee */
charged_tx_fee: 137622
unallocated aggregated amounts:
3: 0
98: 0
15396: 0
```

**Comment by mike-burrage-hedera** [comment]
importer portion of code change was done in #534 
rest-api is changes is not required, but committed to https://github.com/hashgraph/hedera-mirror-node/tree/feature/fee-breakout-rest-api in case
