### ISSUE TITLE
mirror node returns incorrect gas used value

### ISSUE THREAD

**Issue by mshakeg** [hashgraph/hedera-mirror-node#5195]
### Description

I've noticed that for some transactions the mirror node returns incorrect `gas_used` values. Take for example the following tx:
https://hashscan.io/testnet/transaction/1673360342.289826004?tid=0.0.29667223-1673360328-223842716

The mirror node returns a `gas_used` value of `13_146`, which is completely nonsensical as the base gas cost is >20_000 in addition to the fact that the tx involves an HTS transfer which would use at least another 20k gas, and including other gas used the actual gas cost would be somewhere around 150_000.

### Steps to reproduce

I think the above example tx is sufficient evidence of the issue.

### Hedera network

testnet

### Version

mirror-node@0.71.0

### Operating system

None

**Comment by tinker-michaelj** [comment]
Hey @mshakeg, the record you linked is a "child" of a [parent `ContractCall` transaction](https://hashscan.io/testnet/transaction/1673360342.289826003?tid=0.0.29667223-1673360328-223842716).

The parent had `gasLimit=500_000` and a `gasUsed=411_120`.

But this child `CryptoTransfer` operation only required `13_146`.

**Comment by mshakeg** [comment]
@tinker-michaelj I see, in which case it isn't related to the other issue, didn't know Hedera gave granular gas details on each child tx.
