### ISSUE TITLE
Citus optimize list account balances query

### ISSUE THREAD

**Issue by xin-hedera** [hashgraph/hedera-mirror-node#5229]
### Problem

REST API performance test with citus db shows list account balances (with no additional query params) REST API performs poorly.

### Solution

- Run explain analyze to understand the bottleneck of the SQL query
- Optimize the query based on the analysis, split the query into multiple parts if necessasry
- Run performance test to verify

**Comment by steven-sheehy** [comment]
We've [optimized](https://github.com/hashgraph/hedera-mirror-node/pull/9195) some of the balance API combinations and the current results look sufficient.
