### ISSUE TITLE
Add primary keys to large tables for better postgres logical replication performance

### ISSUE THREAD

**Issue by mike-burrage-hedera** [hashgraph/hedera-mirror-node#525]
**Problem**
The `t_cryptotransferlists` and `non_fee_transfers` tables do not have a primary key, which means that during logical replication, a full table scan may be required, and these tables gets rather large (so the scan will be long).

**Solution**
As there are no natural primary keys for these tables:
- Add an `id` primary key column that is a sequence
- Update all existing records to set a value for this `id` (preferably in order by consensus_timestamp)
- Ensure the `id` column is defaulted to the sequence on insert
- Set the `id` field as the primary key, with corresponding btree index
- Update Java repositories to utilize the new PK for these tables

**Alternatives**

**Additional Context**
Additionally, while working on this table it may make sense to remove the index that is only on the `amount` field (verifying no impact to restapi queries), as this is just an insert performance and storage penalty. Unused indexes on t_cryptotransferlists may be removed as part of #512

**Comment by mike-burrage-hedera** [comment]
This needs some performance testing to see the impact.
Adding ID/PK will slow down inserts and use more space but there may be a logical replication problem if there is no ID.
That's the tradeoff that needs to be considered/measured.

**Comment by steven-sheehy** [comment]
We're moving towards TimescaleDB which prefers time based primary keys. Closing this.
