### ISSUE TITLE
Missing token information via /api/v1/balances endpoint

### ISSUE THREAD

**Issue by rhysied** [hashgraph/hedera-mirror-node#5331]
### Description

To qualify for additional rewards in our app we require users to associate the Yamgo token (ID: 0.0.1391075). Recently one of our users approached us to say that after associating the token we still weren't picking up the association, as we were checking the results of the following request: [/api/v1/balances?account.id={accountID}](https://mainnet-public.mirrornode.hedera.com/api/v1/balances?account.id=0.0.316647)

The Yamgo token ID is not found however (also note that it is missing when viewing the account on [hashscan.io](https://hashscan.io/mainnet/accountbalances/0.0.316647))

### Expected behaviour

The expected behaviour is that the above response should include the Yamgo token ID (0.0.1391075) or it should return a non-null value for links.next to allow us to paginate through the data until the token ID is found.

### Additional Info

It does not appear to be a a case of missing data in the Mirror Node as the token association can be observed in the mirror node however when instead searching the following route and specifying the account ID [/api/v1/tokens/0.0.1391075/balances](https://mainnet-public.mirrornode.hedera.com/api/v1/tokens/0.0.1391075/balances?account.id=0.0.316647)

The user in question has a large amount of both NFTs and Fungible tokens, so this may form part of the issue. It is unknown how many other accounts and/or tokens this affects.

The result is also the same comparing the public Mainnet Mirror Node to our private API and Mirror setup running v0.68.1

### Steps to reproduce

1. Click [here](https://mainnet-public.mirrornode.hedera.com/api/v1/tokens/0.0.1391075/balances?account.id=0.0.316647) to verify that the Yamgo Token is associated to the account as shown by /api/v1/tokens
2. Then view the data shown by [/api/v1/balances](https://mainnet-public.mirrornode.hedera.com/api/v1/balances?account.id=0.0.316647)
- EXPECTATION: The Yamgo token association should either be returned in the first request or subsequent requests where pagination is required
- ACTUAL RESULT: The Yamgo token association is not visible and there is no extra data to fetch (pagination not required)

### Hedera network

mainnet

### Version

v0.72.0

### Operating system

macOS

**Comment by steven-sheehy** [comment]
Hi Rhys, as noted in [HIP-367](https://hips.hedera.com/hip/hip-367#mirror-node) the balances endpoint is limited to `at most 50 token balances per account`. This is because we can't return an unbounded amount of information in a nested list in REST. So we created the `/api/v1/accounts/{id}/tokens` to view token relationships and allow the data to be paged.

**Comment by rhysied** [comment]
Hi Steven,

sorry about that, I wasn't aware of that change so feel free to close this issue.

One thing I would mention though is that neither the old docs site (on the new version the API section is broken which I'll mention in Discord now) nor the Swagger docs mention this limitation. Is it worth updating them (or deprecating the route even?)

Thanks for your help.

**Comment by steven-sheehy** [comment]
That's good feedback. We'll use this ticket to update the OpenAPI spec to note this limitation on both accounts and balances endpoints.
