### ISSUE TITLE
AWS / GCP file fetch automatic failover

### ISSUE THREAD

**Issue by gregscullard** [hashgraph/hedera-mirror-node#54]
## Problem

Currently, the importer is configured to either download from AWS or GCS. In the event of a connection failure, the mirror node should support failing over to one or more other cloud providers.

## Solution

* Add a `hedera.mirror.importer.downloader.sources` to `CommonDownloaderProperties`:
```java
    private List<StreamSourceProperties> sources = new ArrayList<>();

    public static class StreamSourceProperties {
        private StreamCredentials credentials;
        private String projectId; // maps to gcpProjectId
        private StreamSourceType type; // Renamed from CloudProvider
        private URI uri; // maps to endpointOverride
    }

    public static class StreamCredentials {
        private String accessKey;
        private String secretKey;
    }
```
* Keep existing bucket properties as is. On startup, create a `StreamSourceProperties` from the existing properties and push to the front of the `sources` list.
* Add a class to abstract away the source of stream files
```java
public interface StreamFileProvider {

    Mono<StreamFileData> get(ConsensusNode node, StreamFilename streamFilename);

    Flux<StreamFileData> list(ConsensusNode node, StreamFilename lastFilename);
}
```
* Add a `S3StreamFileProvider` that uses `S3AsyncClient`
  * A `GcsStreamFileProvider` is not necessary since we can reuse `S3StreamFileProvider` for both since they implement the same API.
* Add a `CompositeStreamFileProvider` to handle the failover functionality
  * Iterate over the sources always starting with the first
  * If the selected source throws an exception, and it's not the last functioning source, remove it from the list of valid sources
  * Don't remove if it's a common, transient exception like `NoSuchKeyException`, etc. Check historical logs to verify which ones.
  * Periodically retry bad sources to see if they've become healthy again and re-add to valid sources

**Comment by nickpoorman** [comment]
We should be very careful about doing this. Right now we don't pay for the bandwidth when pulling from a bucket that's in the same cloud. If a mirror node starts pulling from a bucket in a different could it could get expensive rather quickly.

So maybe if the importer is unable to connect for a certain amount of time, it falls over to the other cloud, but it should eventually go back to the matching cloud it's in.

The reality of these outages is if S3/cloud storage is down in a region, there's a good chance that compute services like EC2/GCP experience an outage as well.

**Comment by steven-sheehy** [comment]
That's what it will do if `loadBalance=false`, which will be the default.
