### ISSUE TITLE
Web3 Module to support traceability actions

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-mirror-node#5408]
### Problem

Currently the network exports traceability side cars which contain the contract call flow (Actions).
This requires additional side car files to be processed

### Solution

Explore the possibility of utilizing the web3 module presented in HIP 584 to support contract actions information.

**Comment by steven-sheehy** [comment]
This design task is completed and the implementation can be followed via https://github.com/hashgraph/hedera-mirror-node/issues/6781
