### ISSUE TITLE
api/v1/accounts/0.0.88 returns 503 when limit=1

### ISSUE THREAD

**Issue by ericleponner** [hashgraph/hedera-mirror-node#5416]
### Description

The following call to mirror node:
`https://testnet.mirrornode.hedera.com/api/v1/accounts/0.0.88?limit=1`

return status 503 and the following body:
`{"_status":{"messages":[{"message":"Service unavailable"}]}}`

Without `limit=1`, call returns successfully.

### Steps to reproduce

See Description section

### Hedera network

testnet

### Version

?

### Operating system

macOS

**Comment by steven-sheehy** [comment]
Looks like it's no longer occurring. Can you confirm and close?

**Comment by ericleponner** [comment]
Indeed it's no longer occurring.
