### ISSUE TITLE
Enhance PubSub publishing retry mechanism

### ISSUE THREAD

**Issue by edwin-greene** [hashgraph/hedera-mirror-node#5422]
### Problem

In the event of that the Pubsub Publisher is down or if there is a network problem, the `PubSubRecordItemListener` retries publishing the message a configurable number of times. But if the problem is not fixed in time, then the published message could be lost. 

### Solution

Determine if when publishing messages if there some other mechanism to block or if we should just retry indefinitely to avoid data loss.

**Comment by steven-sheehy** [comment]
pub sub is deprecated
