### ISSUE TITLE
ethereum transaction result returns 0 gas limit

### ISSUE THREAD

**Issue by mshakeg** [hashgraph/hedera-mirror-node#5428]
### Description

The mirror node returns a `gas_limit` value of 0 for Ethereum transactions, take the following as an example:
```shell
curl -X 'GET' \
  'https://testnet.mirrornode.hedera.com/api/v1/contracts/results/0x43456c4cc39c7d8f8005057e062b0537ea515ddc7a3f80f2ef1fffa54b24fa4c' \
  -H 'accept: application/json'
```

The specified gasLimit was 550k gas, however, 0 is returned, the `gas_used` is however correct 440k(i.e. given the gas maximum refund of 20%).

### Steps to reproduce

See above.

### Hedera network

testnet

### Version

V0.74.2

### Operating system

None

**Comment by xin-hedera** [comment]
Issue is [here](https://github.com/hashgraph/hedera-mirror-node/blob/d6202a0e7e342ce75d34f2dc010e78b16cae8a1c/hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/EthereumTransactionHandler.java#L123) in `EthereumTransactionHandler`, the gas limit is converted based on the assumption that it's in weibar, but in fact it's not according to the HIP. The `contract_result.gas_limit` from the transaction record is correct though. It's worth cross checking with the HIP to see if we have the same issue on other gas related fields.

**Comment by mgoelswirlds** [comment]
Looking at the code where you pointed, we are assuming that all the gas related fields are in weibar. According to [HIP-410](https://hips.hedera.com/hip/hip-410#value-of-gas-price-and-value-fields) the ethereum fields would be in Weibar right?
and any fractional parts below a tiny bar are dropped, which is happening here.
