### ISSUE TITLE
Optimize Transaction By Id Query With Native Partitioning

### ISSUE THREAD

**Issue by jnels124** [hashgraph/hedera-mirror-node#5430]
### Problem

When partitioning tables definied in https://github.com/hashgraph/hedera-mirror-node/issues/5208 performance was decreased on the /api/v1/transactions/{id} endpoint.

### Solution

- Query needs to be optimized to limit scanned partitions

**Comment by steven-sheehy** [comment]
Already addressed by https://github.com/hashgraph/hedera-mirror-node/pull/5353
