### ISSUE TITLE
HIP-584: `eth_estimateGas` with precompiles

### ISSUE THREAD

**Issue by Kalina-Todorova** [hashgraph/hedera-mirror-node#5504]
### Problem

We need to enhance `eth_estimateGas` to support precompile calls.

### Solution

The following tasks have been defined:

**Implementation**

- [x] #5597 
- [x] #6581 
- [x] #6582 
- [x] #6583 
- [x] #5598 
- [x] #5599
- [x] #5648 
- [x] #5649 
- [x] #5650 
- [x] #5651
- [x] #5652
- [x] #6460 
- [x] #6461 
- [x] #6462 
- [x] #6463 
- [x] #5653
- [x] #5654
- [x] #5655
- [x] #5656
- [x] #5657
- [x] #5658
- [x] #5659
- [x] #5660
- [x] #5562 
- [x] #5601 
- [x] #5755 
- [x] #5756 
- [x] #5757 
- [x] #5758 
- [x] #5666 
- [x] #5722 
- [x] #5907 
- [x] #5917 
- [x] #5957 
- [x] #6156 
- [x] #6235 
- [x] #6236
- [x] #6237 
- [x] #6238 
- [x] #6324 
- [x] #6325 
- [x] #6326 
- [x] #6327 
- [x] #6299 
- [x] #5868 
- [x] #5976
- [x] #5977
- [x] #6030 
- [x] #6031 
- [x] #6005 
- [x] #6019 
- [x] #5959 
- [x] #6340 
- [x] #6584 

**Tests**

- [x] #5501
- [x] #5502
- [x] #5503
- [x] #5676 
- [x] #5677

**Comment by david-bakin-sl** [comment]
(I added #5562 on the assumption this issue tracked _all_ work for HIP-584 `estimateGas` - if that's wrong and it only tracks acceptance tests please remove it (and update the issue title!).)
