### ISSUE TITLE
HIP-584: Enable `eth_call` to work with non pure/view functions without precompiles

### ISSUE THREAD

**Issue by Kalina-Todorova** [hashgraph/hedera-mirror-node#5505]
### Problem

We need to add support for `eth_call` regarding invoking methods that are not `pure`/`view`. In this way a given transaction simulation would fail but would still return an output with the information read. This task covers calling methods which are not precompiles.

### Solution

Enhance `hedera-evm` to allow this support. This could be done via having a special `SSTORE` op code overload that allows static context to invoke non pure/view functions. We should also validate the REST API behaviour via different unit and acceptance tests.

**Comment by stoqnkpL** [comment]
done with https://github.com/hashgraph/hedera-mirror-node/pull/6240
