### ISSUE TITLE
HIP-584: Enable `eth_call` to work with non pure/view functions with precompiles

### ISSUE THREAD

**Issue by Kalina-Todorova** [hashgraph/hedera-mirror-node#5506]
### Problem

We need to add support for `eth_call` regarding invoking methods that are not pure/view. In this way a given transaction simulation would fail but would still return an output with the information read. This task covers calling all type of methods including precompiles.

### Solution

Enhance `hedera-evm` to allow this support. Most of the work would be covered by https://github.com/hashgraph/hedera-mirror-node/issues/5505. The main efforts here would be to validate that calling `eth_call` with a static frame would successfully execute a precompile call and return a result. We already have this logic in place via executing `ViewExecutor`/`RedirectViewExecutor` logic. We should also validate the REST API behaviour via different unit and acceptance tests.

**Comment by IvanKavaldzhiev** [comment]
Already implemented
