### ISSUE TITLE
503 Service Unavailable (query transactions/balances)

### ISSUE THREAD

**Issue by bert2002** [hashgraph/hedera-mirror-node#5582]
### Description

Hi,
since the network outage from the 9th of May we are seeing reoccurring `503 response` from our mirror node (v0.76.0) for `/transactions` and `/balances` calls. After some time (not sure how many minutes/hours), but the service is responding with proper respond again. I assume something since the network restart with the syncing is either slower or broken (just guessing).

Anyhow we can improve the logging to see why a 503 is thrown? Because in the logs we cant really see it.

Thanks,
bert

### Steps to reproduce

```
curl -v "http://x.x.x.x:5551/api/v1/transactions?account.id=0.0.322335&timestamp=gt:1636445270.744710000&limit=1000"
*   Trying x.x.x.x:5551...
* Connected to x.x.x.x (x.x.x.x) port 5551 (#0)
> GET /api/v1/transactions?account.id=0.0.322335&timestamp=gt:1636445270.744710000&limit=1000 HTTP/1.1
> Host: x.x.x.x:5551
> User-Agent: curl/7.74.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 503 Service Unavailable
< Access-Control-Allow-Origin: *
< Content-Type: application/json; charset=utf-8
< Content-Length: 60
< ETag: W/"3c-LcYCavokCZ+/WzSMVZr2dITVsPw"
< Vary: Accept-Encoding
< Date: Mon, 13 Mar 2023 05:22:08 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
< 
* Connection #0 to host x.x.x.x left intact
```
and after some time its working
```
$ curl "http://x.x.x.x:5551/api/v1/transactions?account.id=0.0.322335&timestamp=gt:1678679219.943483362&limit=1000"
{"transactions":[],"links":{"next":null}}
$ curl "http://x.x.x.x:5551/api/v1/balances?account.id=0.0.322335&timestamp=gte:1678679100.816866000"
{"timestamp":"1678763700.194960000","balances":[{"account":"0.0.322335","balance":773286658,"tokens":[]}],"links":{"next":null}}
```

### Hedera network

mainnet

### Version

v0.76.0

### Operating system

Linux

**Comment by bert2002** [comment]
Actually this started shortly before when we upgraded from `v0.74.2` to `v0.76.0`.

**Comment by steven-sheehy** [comment]
Is this your own instance of the mirror node or mainnet-public.mirrornode.hedera.com? If it's your own, you can see in the REST API logs for that request why it's failing. Most likely the query is timing out. You might try increasing the REST API logs to print the query and running an explain analyze on it. It could be your database is under provisioned or needs a full vacuum.

**Comment by bert2002** [comment]
Hi @steven-sheehy we did some psql improvements and it seems the errors are gone. I will re-open it in case it will happen again.
