### ISSUE TITLE
Parser performance tests

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-mirror-node#559]
**Problem**
We need an automated way to test parser's performance to ensure it reaches our goals and to catch regressions

**Solution**
- Should only test parser to DB flow (no S3 or downloader involved)
- Should run as part of Maven and behind a profile flag: `./mvnw integration-test -P=performance-tests`
- Should use JMH or JUnit
- Should have fixed suite of large input test data
- Should test against a large database (can be a secondary step)
- Should eventually run as part of CI

**Alternatives**
- JMeter
- System tests executed in an environment

**Additional Context**

**Comment by Nana-EC** [comment]
Closing this as I branched the only left task of testing against a large db to #591
