### ISSUE TITLE
Expose entity keys in the t_entities_table

### ISSUE THREAD

**Issue by gregscullard** [hashgraph/hedera-mirror-node#56]
Entity keys (key for accounts and files and admin_key for contracts) are currently stored in protobuf format.

1. Add column to store key in plain text
1.1 Consolidate key and admin_key into a single column
2. Modify java code to extract the ED25519 key from protobuf at the time of parsing and store in that column
3. Ignore keys that contain keylist or threshold keys
4. Optionally implement a migration for the entities that already exist in the database.

**Comment by mike-burrage-hedera** [comment]
@atul-hedera @gregscullard - What do we actually need this for?

If we need this for searching by key then the task should be "enable searching by key" and include both the rest api and database side.

We already have some code in the rest api to filter by key in the existing schema (I believe, correct me if I'm wrong). Is that sufficient for OA?

**Comment by gregscullard** [comment]
It was originally only about storing keys in plain text rather than protobuf. But we now have a requirement to query on key, so changing the issue name and description here makes sense unless we have a separate issue for the REST api side.

**Comment by gregscullard** [comment]
Note: the REST api query could be implemented without any changes to the database.
