### ISSUE TITLE
Upgrade JS AWS SDK to v3

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-mirror-node#5619]
### Problem

The v2 JS AWS SDK will enter maintenance mode in 2023. The test logs show the below error dozens of times:

```
Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(node:28405) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.
```

### Solution

Upgrade the JS AWS SDK to v3

**Comment by MarcKriguerAtHedera** [comment]
I was able to install/run "aws-sdk-js-codemod" and then run `npx aws-sdk-js-codemod -t v2-to-v3 ./hedera-mirror-rest`, which had a few errors:
```
All done.
Results:
0 errors
263 unmodified
0 skipped
20 ok
``` (see attached "hedera-mirror-rest.txt" for full transcript.  However, the resulting changes (only 3 files changed) would not compile, as `s3client.makeUnauthenticatedRequest` is not supported in v3 (and I could not get the listed "workaround" to actually work).

[hedera-mirror-rest.txt](https://github.com/hashgraph/hedera-mirror-node/files/11084140/hedera-mirror-rest.txt)

Note that there was nothing inside the `hedera-mirror-test` directory that needed to be converted to v3.

**Comment by MarcKriguerAtHedera** [comment]
The issue where the code conversion is failing is that we have a lot of calls to
```
    await s3client
      .makeUnauthenticatedRequest('createBucket', {
        Bucket: bucketName,
      });
```
where `s3client` above is defined as new S3(....) (where S3 is imported from `@aws-sdk/client-s3` (and not the single call to `this.s3.makeUnauthenticatedRequest('getObject', params, callback);` which **can** be made to work anonymously using the work-around described at https://github.com/aws/aws-sdk-js-v3/issues/2321 (which is a response to an open bug on the v3 S3 AWS SDK, requesting Anonymous AWS Credentials (for S3).  Other developers have also indicated that the work-around doesn't work for them (on v3).

I used up the allocated amount of time for this ticket, and could make no more progress.

See also https://github.com/aws/aws-sdk-js-v3/issues/3038 .

**Comment by MarcKriguerAtHedera** [comment]
Closing as "Won't fix"

**Comment by xin-hedera** [comment]
code snippet to get object from bucket anonymously

```javascript
const { S3Client, GetObjectCommand } = require('@aws-sdk/client-s3')

const client = new S3Client({
  region: 'us-east-1',
  signer: { sign: async (request) => request }
});

const input = {
  "Bucket": "hedera-demo-streams",
  "Key": "recordstreams/record0.0.3/2019-10-11T16_38_11.244816Z.rcd",
};
const command = new GetObjectCommand(input);

const response = await client.send(command);
```

The key is creating a `S3Client` with `{signer: { sign: async (request) => request }}`

the create bucket call in the integration test can be done in a similar way (to be verified)

we need to also replace the `aws-sdk-mock` package with `aws-sdk-client-mock` for v3 support
