### ISSUE TITLE
HIP-584: Acceptance tests for `eth_estimateGas` with approve methods

### ISSUE THREAD

**Issue by IvanKavaldzhiev** [hashgraph/hedera-mirror-node#5677]
### Problem

We need to provide acceptance tests for eth_estimateGas that invokes precompiles related to approve methods, including ERC related ones.

### Solution

Provide acceptance tests for `ApprovePrecompile`.

**Comment by yiliev0** [comment]
Done in https://github.com/hashgraph/hedera-mirror-node/pull/6241
