### ISSUE TITLE
HIP-584: Acceptance tests for `eth_estimateGas` with redirect methods

### ISSUE THREAD

**Issue by IvanKavaldzhiev** [hashgraph/hedera-mirror-node#5681]
### Problem

We need to provide acceptance tests for eth_estimateGas that use `redirectForToken` functionality.

### Solution

Provide acceptance tests for all scenarios where `redirectForToken` could be used.

**Comment by yiliev0** [comment]
Done in https://github.com/hashgraph/hedera-mirror-node/pull/6241
