### ISSUE TITLE
HIP-584: Acceptance tests for `eth_estimateGas` with mint and burn logic

### ISSUE THREAD

**Issue by IvanKavaldzhiev** [hashgraph/hedera-mirror-node#5682]
### Problem

We need to provide acceptance tests for eth_estimateGas that use mint and burn methods.

### Solution

Provide acceptance tests for `MintPrecompile` and `BurnPrecompile`.

**Comment by yiliev0** [comment]
Done in https://github.com/hashgraph/hedera-mirror-node/pull/6241
