### ISSUE TITLE
HIP-584: Acceptance tests for `eth_estimateGas` with wipe logic

### ISSUE THREAD

**Issue by IvanKavaldzhiev** [hashgraph/hedera-mirror-node#5683]
### Problem

We need to provide acceptance tests for eth_estimateGas that use wipe method.

### Solution

Provide acceptance tests for:

- `WipeFungiblePrecompile`
- `WipeNonFungiblePrecompile`

**Comment by yiliev0** [comment]
Done in https://github.com/hashgraph/hedera-mirror-node/pull/6241
