### ISSUE TITLE
HIP-584: Acceptance tests for `eth_estimateGas` with freeze and unfreeze logic

### ISSUE THREAD

**Issue by IvanKavaldzhiev** [hashgraph/hedera-mirror-node#5684]
### Problem

We need to provide acceptance tests for eth_estimateGas that use freeze and unfreeze methods.

### Solution

Provide acceptance tests for `FreezeTokenPrecompile` and `UnfreezeTokenPrecompile`.

**Comment by yiliev0** [comment]
Done in https://github.com/hashgraph/hedera-mirror-node/pull/6241
