### ISSUE TITLE
HIP-584: Acceptance tests for `eth_estimateGas` with granting and revoking kyc logic

### ISSUE THREAD

**Issue by IvanKavaldzhiev** [hashgraph/hedera-mirror-node#5685]
### Problem

We need to provide acceptance tests for eth_estimateGas that use granting and revoking kyc logic.

### Solution

Provide acceptance tests for:

- RevokeKycPrecompile
- GrantKycPrecompile

**Comment by yiliev0** [comment]
Done in https://github.com/hashgraph/hedera-mirror-node/pull/6241
