### ISSUE TITLE
HIP-584: Acceptance tests for `eth_estimateGas` with token update methods

### ISSUE THREAD

**Issue by IvanKavaldzhiev** [hashgraph/hedera-mirror-node#5687]
### Problem

We need to provide acceptance tests for eth_estimateGas that invokes precompiles related to token update methods.

### Solution

Provide acceptance tests for:

- UpdateTokenExpiryInfoPrecompile
- TokenUpdatePrecompile
- TokenUpdateKeysPrecompile

**Comment by yiliev0** [comment]
Done in https://github.com/hashgraph/hedera-mirror-node/pull/6241
