### ISSUE TITLE
PostgreSQL ingestion perf test

### ISSUE THREAD

**Issue by apeksharma** [hashgraph/hedera-mirror-node#569]
`data-generator` is good at generating lots of data real fast. Can be easily configured to generate custom workloads.
Currently, `data-generator` outputs to `DomainWriter` which is very similar to `EntityListener`
Replace `DomainWriter` with `EntityListener`, so that it's possible to hook up `SqlEntityListener` directly into `data-generator`. That'll make it very easy to test db insert performances for any kind of workload we want.
Also, establish baselines for typical workloads.

**Comment by steven-sheehy** [comment]
Closing as we've removed the data generator in the last release
