### ISSUE TITLE
Refactor RecordItemParser class into reusable helper functions

### ISSUE THREAD

**Issue by apeksharma** [hashgraph/hedera-mirror-node#571]
`RecordItemParser` class has a giant function to parse `Transaction` and `TransactionRecord`.
For basic code sanity, it should be split up into reusable helper functions.
Going step further, it should make it easy for 3rd party mirror nodes to write custom parsers.

**Comment by steven-sheehy** [comment]
I had looked at this some in the past and had come up with an interface like below:
```java
public interface TransactionHandler {
    // Parse the main entity associated with this transaction so we can create/retrieve it if needed ahead of time
    EntityId getId(RecordItem recordItem);

    default EntityId getProxyId(RecordItem recordItem) {
        return null;
    }

   void update(ParsedTransaction parsedTransaction);
}

@Value
class ParsedTransaction {
  private final Entities entity;
  private final Entities proxyEntity;
  private final com.hedera.mirror.importer.domain.Transaction transaction;
  private final RecordItem recordItem;
}
```

Separating entity extraction from updates would allow us to filter transactions before parsing. The update method would allow individual transaction handlers to construct dependent objects and call downstream listeners.

**Comment by apeksharma** [comment]
Items remaining here:
- Unit tests for updateEntity() and updateTransaction() functions
- move RecordItemParser's insert*() functions to TransactionHandler

**Comment by steven-sheehy** [comment]
Move follow up items to https://github.com/hashgraph/hedera-mirror-node/issues/1374
