### ISSUE TITLE
Add support for network prefix for resettable environments

### ISSUE THREAD

**Issue by mgoelswirlds** [hashgraph/hedera-mirror-node#5713]
### Problem

Currently an example of resettable environment is testnet. 
In order to support that with the following new structure in[ HIP-679](https://github.com/mgoelswirlds/hedera-improvement-proposal/blob/main/HIP/hip-679.md#specification) these environments need to be handled differently.

### Solution

- For networks that can be reset the network key in the path will start with the network name prefix followed by a timestamp, as stated in the above testnet example. On a reset, to get the latest network one would need to filter by the network prefix (e.g. `testnet`) then sort the output to get the latest network to read from.

**Comment by steven-sheehy** [comment]
Depends on #4388

**Comment by steven-sheehy** [comment]
Closing since HIP-679 won't be implemented in favor of block nodes.
