### ISSUE TITLE
Ability to get contract logs by topic id via REST API

### ISSUE THREAD

**Issue by iron4548** [hashgraph/hedera-mirror-node#5720]
### Problem

JSON-RPC has the ability to fetch contract logs based on topic id between starting and ending block numbers. This is useful as sometimes there is many instances of the same contract (one for each liquidity pair for example). 

However I'd prefer to use REST API if I can as it allows me to specify unix timestamp range (i.e. from 00:00:00 to 23:59:59 for a given day).

Currently REST API currently doesn't seem to have the ability to fetch logs based on topic id. Every smart contract log starts with a recognizable topic id in the topics array

Currently I have to fetch every logs for all liquidity pairs in order to find the ones I want based on topic ids which is a waste of resources, and I'll have to monitor for new liquidity pairs. All this is solvable if I can fetch logs based on topic id

### Solution

A possible option is to add 'topic' as a filter option. 

```
/api/v1/contracts/{contractIdOrAddress}/results/logs?topic={topic id}
/api/v1/contracts/{contractId}/results/{timestamp}?topic={topic id}
/api/v1/contracts/results/{transactionId}?topic={topic id}
/api/v1/contracts/results/logs?topic={topic id}
```

And allow timestamp ranges, example:

```
/api/v1/contracts/{contractIdOrAddress}/results/logs?topic={topic id}&timestamp=gte:{start}&timestamp=lt:{end}`
/api/v1/contracts/{contractId}/results/{timestamp}?topic={topic id}&timestamp=gte:{start}&timestamp=lt:{end}`
/api/v1/contracts/results/{transactionId}?topic={topic id}&timestamp=gte:{start}&timestamp=lt:{end}`
/api/v1/contracts/results/logs?topic={topic id}&timestamp=gte:{start}&timestamp=lt:{end}`

where start and end is unix timestamps
```

**Comment by steven-sheehy** [comment]
You already can search for contract logs via its topic. Both `/api/v1/contracts/logs` and `/api/v1/contracts/{id}/logs` support a `topic0` through `topic3` query parameters that can be used to filter the logs. These parameters require a timestamp range be provided. Please see our OpenAPI [docs](https://previewnet.mirrornode.hedera.com/api/v1/docs/#/contracts/listContractsLogs). Does that address your concern or am I missing something?

**Comment by iron4548** [comment]
Thanks @steven-sheehy, I didn't know about that docs link. I was going off https://docs.hedera.com/hedera/sdks-and-apis/rest-api and `topic0` through `topic3` wasn't listed there. 

But I see now. Even this OpenAPI [docs](https://mainnet-public.mirrornode.hedera.com/api/v1/docs/#/contracts/listContractsLogs) for mainnet didn't have `topic0`

So `topic0` must be new. I see that it's only available in previewnet. Is that correct?

**Comment by steven-sheehy** [comment]
It's not new and is available on mainnet. I can see it on the mainnet swagger link you provided.

**Comment by iron4548** [comment]
Oh haha, that was embarrassing. Not sure how I missed it in the first place. I was able to get it working in the end. Thank you for your help!
