### ISSUE TITLE
expiry_timestamp value type/encoding inconsistent with other timestamps for tokens response

### ISSUE THREAD

**Issue by robkainz** [hashgraph/hedera-mirror-node#5779]
### Description

The expiry_timestamp does not have a decimal included in it's value as the others do (created_timestamp and modified_timestamp). In fact, the others are also encoded as strings whereas the expiry_timestamp is a number. Is this intentional? Or an oversight and it's too late to change as it's a breaking change? I would have prefered all timestamp types/encodings to be consistent in their responses.

Here are the relevant lines from the response from this query: https://testnet.mirrornode.hedera.com/api/v1/tokens/0.0.3535601 

> {
> ...
>   "created_timestamp": "1676983236.926863003",
> ...
>   "expiry_timestamp": 1684759236926863003,
> ...
>   "modified_timestamp": "1676983236.926863003",
> ...
> }

### Steps to reproduce

1. Query the testnet mirror for a token: https://testnet.mirrornode.hedera.com/api/v1/tokens/0.0.3535601

### Hedera network

testnet

### Version

v0.77.0

### Operating system

macOS

**Comment by steven-sheehy** [comment]
> I would have prefered all timestamp types/encodings to be consistent in their responses.

Me too.

> Or an oversight and it's too late to change as it's a breaking change? 

Unfortunately, it would be a breaking change so we have to leave it as is.
