### ISSUE TITLE
Analyze importer memory usage at 10K HCS

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-mirror-node#5853]
### Description

Performance environment shows increased memory usage when processing 10K HCS TPS

### Steps to reproduce

10K HCS

### Hedera network

other

### Version

0.78.1

### Operating system

None

**Comment by xin-hedera** [comment]
Analysis of the java process CPU usage, memory consumption, cpu usage of the importer pod and the GKE node the pod was running on show that during the 10K HCS traffic

- pod CPU usage max at 120%
- JVM memory usage higher than normal
- many other pods competing CPU on the GKE node and the node's 4 CPU cores was busy all the tim

A normal 10K TPS HCS traffic ingestion at < 1.5s record file parsing duration require around 3 CPU cores.

The conclusion is the importer pod was pegged on CPU, thus it wasn't able to handle 10K TPS HCS ingestion, the high memory usage is just a consequence of not enough CPU to GC the memory
