### ISSUE TITLE
Add support for evmAddress to Balances endpoint

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-mirror-node#5863]
### Problem

Current the balances endpoint `account.id` param only support accounts identifiers of the HederaAccountId.
In some cases calls to Hedera APIs will use the evm address (not a long zero).
In this case developers are foced to first call teh `api/v1/accounts` endpoint to get the AccountID before calling for balances (since the accounts endpoint doesn't support historical timestamps)

### Solution

Update the logic for `account.id` to manage evmAddresses also by utilizing the internal mapping - same logic used on `api/v1/accounts`.
This will the reduce for an extra call in some situations.

**Comment by steven-sheehy** [comment]
`/api/v1/balances?account.id=` supports operators like `ne`, `gt`, etc. and supports multiple account IDs. For `account.id=${evmAddress}`, we will only support exactly one EVM address and only with `eq` operator.
