### ISSUE TITLE
REST API Docs error

### ISSUE THREAD

**Issue by gregscullard** [hashgraph/hedera-mirror-node#5911]
### Description

Looking at https://testnet.mirrornode.hedera.com/api/v1/docs/ and scrolling all the way down to the message descriptions, opening TopicMessageResponse, TopicMessages, TopicMessage, ChunkInfo,TransactionId

The transactionId element includes `transaction_valid_startTimestamp` when it is in fact `transaction_valid_start`, the `Timestamp` is extra and incorrect.

### Steps to reproduce

See description

### Additional context

![image](https://user-images.githubusercontent.com/9549788/234903870-5f15ffa5-a837-44c8-9470-14c2e0246cee.png)

### Hedera network

testnet

### Version

v0.78.1

### Operating system

None

**Comment by xin-hedera** [comment]
looks like it's just a display issue, it's actually `transaction_valid_start Timestamp string` and there's space between `transaction_valid_start` and `Timestamp`, `Timestamp` is the type

**Comment by steven-sheehy** [comment]
This is an issue with the [swagger-ui library](https://github.com/swagger-api/swagger-ui) that is out of our control. Feel free to open a bug upstream, if you like.
