### ISSUE TITLE
Change transaction by ID API to use nested NFT transfers

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-mirror-node#6009]
### Problem

As an API user, I'd like to avoid the N+1 problem and get all my NFT transfers for a list of transactions with a single call.

### Solution

After #6008 is implemented:

* Change `/api/v1/transactions/:id` to use `transaction.nft_transfer`
* Fix the API to always show `nft_transfers` and `token_transfers` even if empty

**Comment by MarcKriguerAtHedera** [comment]
The proper PR for this change is here: https://github.com/hashgraph/hedera-mirror-node/pull/6212
