### ISSUE TITLE
Change NFT history API to use nested NFT transfers

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-mirror-node#6010]
### Problem

As an API user, I'd like to avoid the N+1 problem and get all my NFT transfers for a list of transactions with a single call.

### Solution

After #6008 is implemented, change `/api/v1/tokens/:id/nfts/:serial/transactions` to use `transaction.nft_transfer`

**Comment by xin-hedera** [comment]
need an index on the `nft_transfer` column and `consensus_timestamp` column
