### ISSUE TITLE
HIP-584: Design historical support flows for contracts/call

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-mirror-node#6164]
### Problem

Currently HIP 584 eth_call coverage has been designed and implemented for latest block scenarios.
We should plan support for the final user story in HIP 584 which is historical block support

### Solution

Add a HIP 584 design doc for historical block `contracts/call` support

**Comment by mshakeg** [comment]
Hey @Nana-EC I just wanted to ask if you could share a rough ETA for this feature?

**Comment by Nana-EC** [comment]
Hey @mshakeg 
Unfortunately can't give a rough ETA for this feature.
I can say we're focused on it and it's underway.

Here's some more items to track

- https://github.com/hashgraph/hedera-mirror-node/issues/6697
- https://github.com/hashgraph/hedera-mirror-node/issues/6718
- https://github.com/hashgraph/hedera-mirror-node/issues/6698

**Comment by Nana-EC** [comment]
@mshakeg 
Additionally, could you assist by giving a bit more information on where it's useful to you.
A few questions
- What sort of contract or DApp flow do you have? We'd like to understand the user flow a bit more so any info around your context would be helpful.
- Is there a specific DApp you're intending to use this functionality in to increase our awareness?
- Does your use case relate to HTS or ERC tokens?
- How far back do you expect to call in terms of block or time? e.g. 5 blocks back from current, 1hr back in timestamp etc
- Do you repeatedly make calls for the same info or will your app cache it after first query?

Thanks

**Comment by mshakeg** [comment]
Thanks for the update @Nana-EC 

To answer you questions:

> What sort of contract or DApp flow do you have? We'd like to understand the user flow a bit more so any info around your context would be helpful.

> Is there a specific DApp you're intending to use this functionality in to increase our awareness?

Subgraphs that implement event handlers that query contract state do make eth_call requests at the specific block for the given event that the event handler is processing. Currently, if such a subgraph is deployed to a graph node supporting Hedera it'll halt indefinitely when it attempts to make such an `eth_call`.

---

> Does your use case relate to HTS or ERC tokens?

Not directly, it's currently limited to querying contract state at a specific block as mentioned above. I also don't foresee a subgraph making eth_calls for quering state of an HTS token or ERC token contract, as it could index all the ERC token events to reconstruct this state internally.

---

> How far back do you expect to call in terms of block or time? e.g. 5 blocks back from current, 1hr back in timestamp etc

Ideally, as far back to genesis, Ethereum's full archive nodes store historical states back to genesis, however, a partial archive node storing states from a few months ago and if that's not achievable then a worst case would be a partial archive node from a TBD block(around the time that this feature goes live) onwards.

---

> Do you repeatedly make calls for the same info or will your app cache it after first query?

In my case the subgraph stores the result of the eth_calls

---

btw I had a chance to make a few updates to the HTS system/precompile mocks, might get some time this coming weekend to continue working on it so if you have a moment to spare, I'd appreciate a review before then.

**Comment by steven-sheehy** [comment]
This design task is completed. See the epic for further details of tasks: https://github.com/hashgraph/hedera-mirror-node/issues/6698
