### ISSUE TITLE
Add ability to start a mirror node from a network state snapshot

### ISSUE THREAD

**Issue by pathornteng** [hashgraph/hedera-mirror-node#6186]
### Problem

Currently, to build a complete network state on a mirror node, all transaction history is required. However, syncing the entire transaction history would take months as the current database is almost 20TB, making it very difficult for the community to run and operate their own mirror node from an empty database.

In most cases, users don't actually need the complete transaction history but rather desire a complete network state. This is important because having an incomplete network state is very dangerous and error-prone for the applications. 

Since we already have pruning capability, it would be very beneficial for the mirror node operators if the mirror node could start from a specific state snapshot, allowing anyone to start a mirror node with a complete network state at a specific time from a state snapshot. This way, mirror node operators wouldn't need to sync all the transaction history to obtain the complete network state.

### Solution

This would be possible if we introduce:

1. The ability for the mirror node to start from a specific state snapshot.
2. Regularly provided updated state snapshots for download

**Comment by xin-hedera** [comment]
Agree on the issues of the current approach with the full database backup. However, the proposed approach would take quite some engineering effort.

If we are sure that the custom just needs the latest state without transaction / balance history, instead we can create a runbook to truncate those tables and easily reduce the database dump to tens of or at most hundreds of GBs.

**Comment by pathornteng** [comment]
Thanks @xin-hedera. Yes, it's totally understandable regarding the effort. In the meantime, is it possible to provide truncated db dump regularly? I feel that its kind of similar to state snapshot and would serve the purpose.

**Comment by steven-sheehy** [comment]
Forgot this ticket existed before creating https://github.com/hashgraph/hedera-mirror-node/issues/6912. It's purely for the snapshot side of things though and relates to HIP-794.

**Comment by Satish-Masa** [comment]
Hi.
Are there any developments regarding Snapshot?
Or if there is a way to speed up syncing, please share.
Thanks and regards,
