### ISSUE TITLE
REST API code coverage

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-mirror-node#623]
**Problem**
We currently only provide code coverage for our Java modules. We should enable this for our JavaScript module as well.

**Solution**
Generate code coverage report and upload to codecov.io. Looks like it's as easy as:

1. [Configure](https://github.com/codecov/example-node) jest to enable code coverage in `package.json`:
"jest": {
  "coverageDirectory": "./coverage/",
  "collectCoverage": true
}
2. `npm install codecov --save-dev`
3. Modify CircleCI config to call `./node_modules/.bin/codecov` after js tests

**Comment by Nana-EC** [comment]
Picking up as I'll be doing the REST API addition so this will go hand in hand
