### ISSUE TITLE
Some node's public key in \addressbook\mainnet doesn't match what is listed on the website

### ISSUE THREAD

**Issue by iron4548** [hashgraph/hedera-mirror-node#6286]
### Description

\src\main\resources\addressbook\mainnet contains 12 nodes and their public key. 

https://docs.hedera.com/hedera/networks/mainnet/mainnet-nodes also contains a list of nodes and their public key

However, there are some inconsistencies. They are:

- 0.0.3 (in file) has the public key of 0.0.10 on the website
- 0.0.10 (in file) doesn't match the public key of any node on the web site

Expectation:

They should match

### Steps to reproduce

Review public key for each node and ensure that it matches what is listed in src\main\resources\addressbook\mainnet and https://docs.hedera.com/hedera/networks/mainnet/mainnet-nodes

### Hedera network

mainnet

### Version

v0.84.0-SNAPSHOT

### Operating system

None

**Comment by steven-sheehy** [comment]
The address book in the classpath is the Genesis address book, not the current address book. As such there is zero expectation it matches the latest info in the API or Hedera docs.

**Comment by iron4548** [comment]
> The address book in the classpath is the Genesis address book, not the current address book. As such there is zero expectation it matches the latest info in the API or Hedera docs.

With a fresh mirror_node installation, it appears to import the address book from \src\main\resources\addressbook\mainnet into address_book_entry table. I'm assuming that because the data in the table matches the data in the mainnet file, and the importer downloader is only checking and downloading data from those 12 nodes. Or is my understanding wrong?

**Comment by steven-sheehy** [comment]
That's correct. For partial mirror nodes with startDate set implicitly or explicitly to a date after genesis, it could be inaccurate at the time it starts. But it will resolve itself after the next address book update. There's not a good solution to get the correct address at time X in the past without being able to parse consensus node state files. That ability is being considered but is a large effort.

But it's also true we cannot provide every possible address book for any given timestamp in the classpath. So the genesis address book is the correct one to store.

**Comment by iron4548** [comment]
I see. That make sense. In that case, I think you can go ahead and close this one.
