### ISSUE TITLE
Custom /addressbook/mainnet doesn't load all nodes properly

### ISSUE THREAD

**Issue by iron4548** [hashgraph/hedera-mirror-node#6287]
### Description

I'm wanting to experiment using a custom mainnet nodes for addressbook for importer. There are 11 nodes in the custom list.

Here's the modified file (.txt was added so that I can upload the file here) [mainnet.txt](https://github.com/hashgraph/hedera-mirror-node/files/11888435/mainnet.txt)

I cleaned the database and ran the importer anew and here's the relevant logs for the address book import:

```
Jun 28 00:52:53 harbot-gci java[201748]: 2023-06-27T18:52:53.585-0600 INFO scheduling-5 c.h.m.i.a.AddressBookServiceImpl Searching for address book on file system
Jun 28 00:52:53 harbot-gci java[201748]: 2023-06-27T18:52:53.585-0600 INFO scheduling-5 c.h.m.i.a.AddressBookServiceImpl Loading bootstrap address book from /addressbook/mainnet
Jun 28 00:52:53 harbot-gci java[201748]: 2023-06-27T18:52:53.585-0600 INFO scheduling-5 c.h.m.i.a.AddressBookServiceImpl Loaded bootstrap address book of 9436 B
Jun 28 00:52:53 harbot-gci java[201748]: 2023-06-27T18:52:53.679-0600 INFO scheduling-5 c.h.m.i.a.AddressBookServiceImpl Saved new address book to db: AddressBook(startConsensusTimestamp=1, endConsensusTimestamp=null, entries=[AddressBookEntry(description=, id=AddressBookEntry.Id(consensusTimestamp=1, nodeId=1), memo=0.0.4, nodeAccountId=0.0.4, serviceEndpoints=[], stake=0), AddressBookEntry(description=, id=AddressBookEntry.Id(consensusTimestamp=1, nodeId=2), memo=0.0.5, nodeAccountId=0.0.5, serviceEndpoints=[], stake=0), AddressBookEntry(description=, id=AddressBookEntry.Id(consensusTimestamp=1, nodeId=8), memo=0.0.11, nodeAccountId=0.0.11, serviceEndpoints=[], stake=0), AddressBookEntry(description=, id=AddressBookEntry.Id(consensusTimestamp=1, nodeId=10), memo=0.0.13, nodeAccountId=0.0.13, serviceEndpoints=[], stake=0), AddressBookEntry(description=, id=AddressBookEntry.Id(consensusTimestamp=1, nodeId=11), memo=0.0.14, nodeAccountId=0.0.14, serviceEndpoints=[], stake=0), AddressBookEntry(description=, id=AddressBookEntry.Id(consensusTimestamp=1, nodeId=14), memo=0.0.17, nodeAccountId=0.0.17, serviceEndpoints=[], stake=0), AddressBookEntry(description=, id=AddressBookEntry.Id(consensusTimestamp=1, nodeId=0), memo=0.0.23, nodeAccountId=0.0.23, serviceEndpoints=[], stake=0)], fileId=0.0.102, nodeCount=11)
Jun 28 00:52:53 harbot-gci java[201748]: 2023-06-27T18:52:53.728-0600 INFO scheduling-5 c.h.m.i.a.AddressBookServiceImpl Processed 0 historic address books
Jun 28 00:52:53 harbot-gci java[201748]: 2023-06-27T18:52:53.728-0600 INFO scheduling-5 c.h.m.i.a.AddressBookServiceImpl Migration complete. Current address book to db: AddressBook(startConsensusTimestamp=1, endConsensusTimestamp=null, entries=[AddressBookEntry(description=, id=AddressBookEntry.Id(consensusTimestamp=1, nodeId=1), memo=0.0.4, nodeAccountId=0.0.4, serviceEndpoints=[], stake=0), AddressBookEntry(description=, id=AddressBookEntry.Id(consensusTimestamp=1, nodeId=2), memo=0.0.5, nodeAccountId=0.0.5, serviceEndpoints=[], stake=0), AddressBookEntry(description=, id=AddressBookEntry.Id(consensusTimestamp=1, nodeId=8), memo=0.0.11, nodeAccountId=0.0.11, serviceEndpoints=[], stake=0), AddressBookEntry(description=, id=AddressBookEntry.Id(consensusTimestamp=1, nodeId=10), memo=0.0.13, nodeAccountId=0.0.13, serviceEndpoints=[], stake=0), AddressBookEntry(description=, id=AddressBookEntry.Id(consensusTimestamp=1, nodeId=11), memo=0.0.14, nodeAccountId=0.0.14, serviceEndpoints=[], stake=0), AddressBookEntry(description=, id=AddressBookEntry.Id(consensusTimestamp=1, nodeId=14), memo=0.0.17, nodeAccountId=0.0.17, serviceEndpoints=[], stake=0), AddressBookEntry(description=, id=AddressBookEntry.Id(consensusTimestamp=1, nodeId=0), memo=0.0.23, nodeAccountId=0.0.23, serviceEndpoints=[], stake=0)], fileId=0.0.102, nodeCount=11)
```
It somehow didn't import the last four nodes:
- 0.0.24
- 0.0.25
- 0.0.27
- 0.0.30

I'm unsure why. There are no errors or warnings.

What am I missing?

### Steps to reproduce

1. Clean database
2. Use the attached mainnet file
3. Rebuild jar
4. Run mirror node importer
5. Observe that only 7 out of 11 addresses were added to the database

### Hedera network

mainnet

### Version

v0.84.0-SNAPSHOT

### Operating system

None

**Comment by iron4548** [comment]
Just to clarify: I'm only importing data from today onwards.

**Comment by xin-hedera** [comment]
the uploaded file seems to be corrupted:

```shell
$ protoc --decode_raw < ~/Downloads/mainnet.txt
Failed to parse input.
```

perhaps upload to other places and provide a link so we can better understand the issue

**Comment by iron4548** [comment]
> Also, should use the `hedera.mirror.importer.initialAddressBook` property intended to override the bootstrap address book.

Didn't know about that, so thanks for that tip

> the uploaded file seems to be corrupted:
> 
> ```shell
> $ protoc --decode_raw < ~/Downloads/mainnet.txt
> Failed to parse input.
> ```
> 
> perhaps upload to other places and provide a link so we can better understand the issue

I've just downloaded protoc to my desktop and tried decoding the original files (previewnet, demo, testnet, mainnet) using the method you shown and I'm also getting the same 'Failed to parse input.' error for each file even though they were not touched or modified. Is that the case for you too? Or are you able to successfully decode the original bootstrap files?

**Comment by xin-hedera** [comment]
> > Also, should use the `hedera.mirror.importer.initialAddressBook` property intended to override the bootstrap address book.
> 
> Didn't know about that, so thanks for that tip
> 
> > the uploaded file seems to be corrupted:
> > ```shell
> > $ protoc --decode_raw < ~/Downloads/mainnet.txt
> > Failed to parse input.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > perhaps upload to other places and provide a link so we can better understand the issue
> 
> I've just downloaded protoc to my desktop and tried decoding the original files (previewnet, demo, testnet, mainnet) using the method you shown and I'm also getting the same 'Failed to parse input.' error for each file even though they were not touched or modified. Is that the case for you too? Or are you able to successfully decode the original bootstrap files?

I can decode files in our repo, e.g.

```bash
$ protoc --decode_raw < hedera-mirror-importer/src/main/resources/addressbook/testnet
```

**Comment by iron4548** [comment]
> > > Also, should use the `hedera.mirror.importer.initialAddressBook` property intended to override the bootstrap address book.
> > 
> > 
> > Didn't know about that, so thanks for that tip
> > > the uploaded file seems to be corrupted:
> > > ```shell
> > > $ protoc --decode_raw < ~/Downloads/mainnet.txt
> > > Failed to parse input.
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > perhaps upload to other places and provide a link so we can better understand the issue
> > 
> > 
> > I've just downloaded protoc to my desktop and tried decoding the original files (previewnet, demo, testnet, mainnet) using the method you shown and I'm also getting the same 'Failed to parse input.' error for each file even though they were not touched or modified. Is that the case for you too? Or are you able to successfully decode the original bootstrap files?
> 
> I can decode files in our repo, e.g.
> 
> ```shell
> $ protoc --decode_raw < hedera-mirror-importer/src/main/resources/addressbook/testnet
> ```

Oh that's funny.

I tried mainnet, previewnet and demo and they gave me the 'Failed to parse input' error, but I never tried testnet. After trying with testnet it worked! Have you tried mainnet, previewnet and demo?

**Comment by xin-hedera** [comment]
yes all address book files in the directory

**Comment by iron4548** [comment]
> yes all address book files in the directory

Very strange! I wonder why it's not working for me then. Is it my OS (Windows)?

What version of protoc are you using? I'm using `libprotoc 23.3` which I installed via `choco install protoc`

**Comment by iron4548** [comment]
[addressbook files (original).zip](https://github.com/hashgraph/hedera-mirror-node/files/11899911/addressbook.files.original.zip)

Here's my address book repo (unmodified)

**Comment by xin-hedera** [comment]
the address book file you created is missing node ids for each node. Historically, old address book files had a bug that node id was not set and I believe we fixed the address book file before we had more than 17 nodes.

**Comment by iron4548** [comment]
> the address book file you created is missing node ids for each node. Historically, old address book files had a bug that node id was not set and I believe we fixed the address book file before we had more than 17 nodes.

Okay. Can you send me an sample address book that has node ids in them? So that I can work off that example. The address book I recently created came from main branch's /addressbook/mainnet

Also have you figured out why my protoc isn't be parsing the files (previewnet, demo, mainnet)? Were you able to replicate that on your side?

**Comment by xin-hedera** [comment]
[this](https://file.io/UtXACI8PABGt) is the latest mainnet address book file. The file you provided have the windows 0d 0a carriage return + line feed instead of 0a, perhaps is git or some other tools being smart.

Once you verify, can you close the ticket?

**Comment by iron4548** [comment]
> [this](https://file.io/UtXACI8PABGt) is the latest mainnet address book file. The file you provided have the windows 0d 0a carriage return + line feed instead of 0a, perhaps is git or some other tools being smart.
> 
> Once you verify, can you close the ticket?

Could you reupload the file? It tells me that it's deleted.

**Comment by steven-sheehy** [comment]
You can just use the address books in the SDKs: https://github.com/hashgraph/hedera-sdk-java/tree/develop/sdk/src/main/resources/addressbook

**Comment by iron4548** [comment]
> You can just use the address books in the SDKs: https://github.com/hashgraph/hedera-sdk-java/tree/develop/sdk/src/main/resources/addressbook

Thanks, I confirm I can decode those address books.

Can you advise how to encode the original data into these encoded files (i.e. mainnet or mainnet.pb)? I did some research and online sources tell me that I cannot re-encode back to the same format after decoding it using --decode_raw.  I have protoc (libprotoc 23.3) on my PC. Once I can encode it properly I will retest with my custom address list.

Thanks in advance.

**Comment by steven-sheehy** [comment]
You have to write code to generate an address book and it's not trivial to provide. Going to close this as there doesn't seem to be a mirror node issue.
