### ISSUE TITLE
There is a `token_transfers` field for FT mints. There should be a `nft_transfers` field NFT mints in the `/transactions` response

### ISSUE THREAD

**Issue by ed-marquez** [hashgraph/hedera-mirror-node#6293]
### Problem

I am trying to calculate NFTs minted in the last X number of days using the mirror REST API. 
It is possible, but highly inefficient. 

# Problem
1. Here's the request used to collect all the transaction data:
```
base_url = "https://mainnet-public.mirrornode.hedera.com"
url = f"{base_url}/api/v1/transactions?transactionType=TOKENMINT&limit=100&timestamp=gt:{start_in_seconds}"
```

2. **Problem 1:** The token type is deduced from the transactions in that API response. However, **this should be more intuitive or explicit**. The way to do it from that response is to check for the `token_transfers` field (present only in fungible tokens). So: 
```
if transaction['result'] == 'SUCCESS':
          if 'token_transfers' in transaction:
            # If the transaction has a 'token_transfers' field, it's a fungible token mint
            fungible_token_count += 1
          else:
            nft_count += 1
```
**Just like the is a `token_transfers` for FT mints, there should be a `nft_transfers` field for non-fungible tokens in that response.** 

- `nft_transfers` field is present if you were to look for that transaction by `transaction_id` (e.g. https://mainnet-public.mirrornode.hedera.com/api/v1/transactions/0.0.1384080-1687541806-431159625).

- But it's not present in the `transactions` query (e.g. https://mainnet-public.mirrornode.hedera.com/api/v1/transactions?transactionType=TOKENMINT&limit=100&timestamp=gt:1687541820.097531647&timestamp=lt:1687541823.097531647)

This leads to the following inefficient workaround.

3. The `nft_count` calculated in 2 is incorrect because that is only counting mint operations, not serial numbers minted (single mint operation can mint up to 10 serials). Thus, **it is required to then iterate through all the NFT mint operations and query each one of them to obtain and sum the length of the `nft_transfers` field**. **This wouldn't be required if the `nft_transfers` field was returned in the `/transactions` endpoint suggested in point 2.** 
  ```
          # =================================================================================
            # TO INCLUDE NFT MINTS THAT MINT MULTIPLE SERIALS IN A SINGLE TX
            # =================================================================================
            # If the transaction doesn't have a 'token_transfers' field, it's an NFT mint
              # Fetch the details of the NFT mint transaction
            transaction_id = transaction['transaction_id']
            nonce = transaction['nonce']
            response = requests.get(f"{base_url}/api/v1/transactions/{transaction_id}?nonce={nonce}")
            transaction_details = response.json()
  
            # Add the size of the 'nft_transfers' field to the NFT counter
            nft_count += len(transaction_details['transactions'][0]['nft_transfers'])
```

@steven-sheehy and team - FYI 

### Solution

**Just like there is a `token_transfers` for FT mints, there should be a `nft_transfers` field for non-fungible tokens in that response.** 

`nft_transfers `field is present if you were to look for that transaction by `transaction_id `(e.g. https://mainnet-public.mirrornode.hedera.com/api/v1/transactions/0.0.1384080-1687541806-431159625).

But it's not present in the `/transactions `query (e.g. https://mainnet-public.mirrornode.hedera.com/api/v1/transactions?transactionType=TOKENMINT&limit=100&timestamp=gt:1687541820.097531647&timestamp=lt:1687541823.097531647)

### Alternatives

Mentioned in step 3 of the problem. A graphQL API would be valuable.
I had to switch to hgraph.io

**Comment by steven-sheehy** [comment]
We just worked on the [epic](https://github.com/hashgraph/hedera-mirror-node/issues/4099) with 6 tickets to add `nft_transfers` list to the transactions list API. This is in 0.83 and live on previewnet. Please test it out there and close this if that solves your problem.

**Comment by steven-sheehy** [comment]
If you're attempting query a large amount of REST API calls or even GraphQL API calls to provide aggregate data over the last X time period, you're not using the API for its intended purpose. The mirror node is intended for point searches to look up info associated with a dApp's executed transaction and providing the latest N items for use by explorers. 

Sounds like you're trying to do analytics which would require a specialized columnar database to be efficient. We have a [ticket](https://github.com/hashgraph/hedera-mirror-node/issues/5730) to explore that but the suggestion is to run your own mirror node for that purpose until then.

**Comment by ed-marquez** [comment]
Good to see `nft_transfers` on Previewnet. Thanks for the update on that ticket for the database. 
Closing this issue.
