### ISSUE TITLE
Optimize 10K TPS ingest performance

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-mirror-node#6295]
### Description

Testing in performance environment indicates an increase in CPU and memory is necessary to process a 10K TPS record file without falling behind. We should run the importer locally and analyze its performance and make the necessary optimizations.

### Steps to reproduce

Ingest 10K TPS on Kubernetes with previous resource requirements

### Hedera network

other

### Version

0.83.0

### Operating system

None

**Comment by jnels124** [comment]
Several Issues were identified as part of this investigation. 

- Rolled back concurrent sig downloads via config change #6130 
- Rolled back synthetic contract results via config change #5909
- Disabled topic message lookup via config change
