### ISSUE TITLE
Enforce that the address book is downloaded from the network if not present on first run

### ISSUE THREAD

**Issue by gregscullard** [hashgraph/hedera-mirror-node#63]
When any of the download or mirror processes start, check the address book file is present in ./config.
If not, attempt to download using parameters from config.json or .env (NODE_ID, NODE_ADDRESS, OPERATOR_ID and OPERATOR_KEY).
If the address book fails to download of those parameters are missing, exit with error message.

**Comment by steven-sheehy** [comment]
Closing as we now store the address book in the classpath and use that unless the user overrides it or it already exists.
