### ISSUE TITLE
Contract Call endpoint does not respect block

### ISSUE THREAD

**Issue by pwoosam** [hashgraph/hedera-mirror-node#6307]
### Description

The mirror node's `/contracts/call` endpoint does not respect `block` from the request body.

I called the `/contracts/call` endpoint using an HTS token as the contract id (`to` address), called the `totalSupply()` method, added a hex-formatted block number to the `block` field, and filled in the remaining props for the post body. I got back the current totalSupply for the HTS token instead of the totalSupply at that block.

[Swagger Docs for contractsCall endpoint](https://mainnet-public.mirrornode.hedera.com/api/v1/docs/#/contracts/contractsCall)

The `/contracts/call` endpoint is failing to respect the request body's `block` field.

### Steps to reproduce

1. Make a POST request to `https://mainnet-public.mirrornode.hedera.com/api/v1/contracts/call` using request body:
```json
{
    "block": "0x2e9b7d3",
    "data": "0x18160ddd",
    "estimate": false,
    "gas": 15000000,
    "gasPrice": 100000000,
    "from": "0x0000000000000000000000000000000000000003",
    "to": "0x00000000000000000000000000000000001647e8",
    "value": 0
 }
```

You will get a response containing the HTS token's current total supply, instead of the total supply at block `0x2e9b7d3`

### Additional context

```js
{
  apiRequestBody: {
    block: '0x2fc2cd3',
    data: '0x18160ddd',
    estimate: false,
    gas: 15000000,
    gasPrice: 100000000,
    from: '0x0000000000000000000000000000000000000003',
    to: '0x00000000000000000000000000000000001647e8',
    value: 0
  }
}
{
  contractResult: '0x0000000000000000000000000000000000000000000000000000b0af3521ac9a',
  totalSupply: '194266557164698',
  blockNumber: 50080979,
  blockNumberHex: '0x2fc2cd3'
}
{
  apiRequestBody: {
    block: '0x2f78f93',
    data: '0x18160ddd',
    estimate: false,
    gas: 15000000,
    gasPrice: 100000000,
    from: '0x0000000000000000000000000000000000000003',
    to: '0x00000000000000000000000000000000001647e8',
    value: 0
  }
}
{
  contractResult: '0x0000000000000000000000000000000000000000000000000000b0af3521ac9a',
  totalSupply: '194266557164698',
  blockNumber: 49778579,
  blockNumberHex: '0x2f78f93'
}
{
  apiRequestBody: {
    block: '0x2f2f253',
    data: '0x18160ddd',
    estimate: false,
    gas: 15000000,
    gasPrice: 100000000,
    from: '0x0000000000000000000000000000000000000003',
    to: '0x00000000000000000000000000000000001647e8',
    value: 0
  }
}
{
  contractResult: '0x0000000000000000000000000000000000000000000000000000b0af3521ac9a',
  totalSupply: '194266557164698',
  blockNumber: 49476179,
  blockNumberHex: '0x2f2f253'
}
```

### Hedera network

mainnet

### Version

?

### Operating system

None

**Comment by steven-sheehy** [comment]
You are correct. HIP-584 is still under heavy development and support for historical blocks has not yet been worked on. It's on the roadmap for this year and there's already a ticket to track it. Can we close this in favor of https://github.com/hashgraph/hedera-mirror-node/issues/6164 ?

**Comment by pwoosam** [comment]
Closing as duplicate 😊
