### ISSUE TITLE
Importer performance regression when TopicMessageLookups enabled 

### ISSUE THREAD

**Issue by xin-hedera** [hashgraph/hedera-mirror-node#6422]
### Description

Performance tests result show when topic message lookup is enabled, even though when topic message table is not partitioned thus there's no writes to the `topic_message_lookup` table, there is noticeable increase in parser duration metric. 

### Steps to reproduce

Run performance tests and compare parser duration metric pre and post the topic message lookup feature.

### Hedera network

other

### Version

v0.82.0

### Operating system

None

**Comment by steven-sheehy** [comment]
Closing since it's not needed for v1 schema
