### ISSUE TITLE
HIP-584: Acceptance tests for eth_estimateGas with GetTokenCustomFeesPrecompile, GetTokenKeyPrecompile, GetTokenExpiryInfoPrecompile, IsTokenPrecompile

### ISSUE THREAD

**Issue by IvanKavaldzhiev** [hashgraph/hedera-mirror-node#6464]
### Problem

We need to provide acceptance tests, validating the estimate values returned from using `eth_estimateGas` with the following precompiles:

- GetTokenCustomFeesPrecompile
- GetTokenKeyPrecompile
- GetTokenExpiryInfoPrecompile
- IsTokenPrecompile

### Solution

Provide acceptance tests for eth_estimate gas for:

- GetTokenCustomFeesPrecompile
- GetTokenKeyPrecompile
- GetTokenExpiryInfoPrecompile
- IsTokenPrecompile

**Comment by yiliev0** [comment]
Done in https://github.com/hashgraph/hedera-mirror-node/pull/6241
