### ISSUE TITLE
Crash importing records into non_fee_transfers

### ISSUE THREAD

**Issue by carlcherry** [hashgraph/hedera-mirror-node#647]
**Detailed Description**
There are a few transfers in mainnet where the entity_num > 2147483647.  When the mirror node attempts to put these transfers into the non_fee_transfers table it crashes since the value is outside the range.

**Actual Behavior**
1. Set up a mirror node where it saves non_fee_transfers.
2. Create a transaction and have the receiving account be 0.0. 100000000000 and send.
3. The server will charge you a fee and then return ACCOUNT_ID_DOES_NOT_EXIST
4. When the mirror node attempt to add this transfer to the non_fee_transfers table it will throw and exception and get stuck on that file.

**Expected Behavior**
Not sure exactly - if the mainnet server allows invalid account numbers via the API then I guess the mirror node needs to throw the non_fee_transfer parts away. I guess checks should also be in place for the t_crytotransferlist and t_entities tables.
FYI - the t_entities table has entity_num as a "bigint"

**Environment:**
- 0.5.4 mirror node, saving non_fee_transfers
- mainnet

**Additional Context**

**Comment by apeksharma** [comment]
I guess if a txn is a failed one, we should just store its TxnId, hash, type, and status. It'd be great if we don't have to store "extra info", for example, transfer lists, contract call, etc.
There can be any number of ways in which the failed txn may not conform to the current assumptions of schema. Also, it'll be very difficult to design schemas which will be able to handle myriad ways in which txns can fail.
Currently, we don't store "extra info" for file txns (append, create, update), hcs message, and live hash for a failed txn.
We store "extra info" for crypto transfers, contract call, contract create for failed txns.

**Comment by carlcherry** [comment]
As long as I can determine the amount of HBAR that changed hands in the failed transaction this is fine.  So besides the items you listed above we would also need to have the charged_fee and payer account number.

**Comment by apeksharma** [comment]
I see. So that use case perspective, isn't the current logic wrong too?
It basically does this:
For a transaction with fee transfers (FT) and non-fee transfers (NFT),
For a successful txn, all transfers would have happened and all get stored into db. So this case works correctly.
For a failed txn, FT would still happen (change hands) and NFT would not. So we want to store FT. However, current code is storing NFT. Isn't that wrong?
Just confirming my suspicion.

**Comment by carlcherry** [comment]
What I was saying was this - at a "minimum" for a failed transaction I would want to have enough information to understand why a users balance went down.  So having the charge_fee and payer account plus the type, hash, error would give me enough information to at least validate the balance change.

What I would prefer is having everything - all the transfers and the non-fee transfers. That way for auditing purposes I could see that user A **tried** to send 20 HBAR to user B even though it failed.  Without the non fee transfers all I know is that user A tried something and it failed. So if a user restored an existing Wallet they might see their failed transaction but know know the details.

I am fine with the minimum support - I can work with that too.
