### ISSUE TITLE
Revert bump org.sonarsource.scanner.gradle:sonarqube-gradle-plugin from 4.2.1.3168 to 4.3.0.3225 

### ISSUE THREAD

**Issue by jnels124** [hashgraph/hedera-mirror-node#6485]
### Problem

Dependabot updated the sonarqube plugin version with #6471 . However, this version is incompatible with our current configuration/code and causes the sonar task to fail in CI

### Solution

Investigate change log and breaking changes
Adjust necessary changes to be compatible with latest version

**Comment by xin-hedera** [comment]
This is a downgrade, am I right?
