### ISSUE TITLE
HIP-646/657/765: Update HIPs with Mirror REST API changes

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-mirror-node#6551]
### Problem

The proposed HIPs need to contain the Mirror Node REST API changes to return the new `metadata` and `metadata_key` fields. Given the interconnectedness of the HIPs, the API changes will be the same in each.

### Solution

* Add a base64 encoded `metadata` field to the `/api/v1/tokens` and `/api/v1/tokens/{id}` REST API endpoints
* Add a standard key encoding format `metadata_key` field to the `/api/v1/tokens/{id}` REST API endpoint

**Comment by jascks** [comment]
Opened [PR 877](https://github.com/hashgraph/hedera-improvement-proposal/pull/877) in HIP repo.

**Comment by jascks** [comment]
PR approved and merged into main.
