### ISSUE TITLE
HIP-584: Create integration tests for dynamic `eth_call` with precompiles

### ISSUE THREAD

**Issue by IvanKavaldzhiev** [hashgraph/hedera-mirror-node#6584]
### Problem

We need to create integration tests that validate `eth_call` works correctly in dynamic cases using the precompiles.

### Solution

We need to create more tests cases in `hedera-mirror-web3` by combining different precompile methods and validate a dynamically changed values is read properly after it was changed by a modification precompile.

The following subtasks has been defined:

- [x] #6585
- [x] #6586

**Comment by steven-sheehy** [comment]
All sub tasks complete
