### ISSUE TITLE
HIP-584: Create integration tests for testing dynamic `eth_call` using `create` and `update` token precompiles

### ISSUE THREAD

**Issue by IvanKavaldzhiev** [hashgraph/hedera-mirror-node#6585]
### Problem

We need to create integration tests that validate `eth_call` works correctly in dynamic cases using create and update precompiles to validate that they update the in-memory state properly.

### Solution

We need to create more tests cases in `hedera-mirror-web3` by combining update and create token precompiles and then using token read precompiles. In this way we would test 2 thing simultaneously:

1. Update and create token precompiles update properly the in-memory state
2. All token read related precompiles are reading properly correct values in dynamic cases (using non-static frames)

The following method combinations could be defined in separate smart contract methods:

- Update token key + get token info key
- Update token expiry + get token info expiry
- Update token info that updates symbol + get token info symbol
- Update token info that updates name + get token info name
- Update token info that updates memo + get token info memo
- Update token info that updates decimals + get token info decimals
- Update token info that updates tokenUri + get token info metadata
- Update auto renew period + get token info auto renew period
- Delete fungible/non-fungible token + get token info isDeleted
- CreateToken for fungible token with/without default freeze/kyc status + name + symbol + decimals + getDefaultFreezeStatus + getDefaultKycStatus + isToken
- CreateToken for nft with/without default freeze/kyc status + name + symbol + tokenUri + ownerOf + getDefaultFreezeStatus + getDefaultKycStatus + isToken

**Comment by bilyana-gospodinova** [comment]
There is no way to update the token decimals so this test will be skipped: "Update token info that updates decimals + get token info decimals".
