### ISSUE TITLE
REST API Metrics

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-mirror-node#661]
**Problem**
We should collect metrics for REST API calls and make them available via a metrics aggregator

**Solution**
We currently support both Kibana/Elasticsearch and Grafana/Prometheus for the GRPC and importer. We can do this because we use Micrometer as an abstraction layer. For REST, since there doesn't seem to be a Micrometer-equivalent library in Javascript we need to ensure any solution we implement can be configurable to be on or off depending upon which metric API we are targeting. I say we focus our efforts on Prometheus metrics with a config option to turn it off when running outside Kubernetes

- Use an Express middleware like [express-prom-bundle](https://github.com/jochen-schweizer/express-prom-bundle) or [promster](https://github.com/tdeekens/promster) or something else to automatically hook into routes and expose metrics
- Add an option `hedera.mirror.api.prometheus.enabled=false` around prom middleware

**Alternatives**

**Additional Context**

**Comment by Nana-EC** [comment]
Exploring https://swaggerstats.io/guide/intro.html
Supports express middleware and provides:
Metrics in Prometheus format, so you may use Prometheus and Grafana to setup API monitoring and alerting
Storing details about each API Request/Response in Elasticsearch, so you may use Kibana to perform analysis of API usage over
