### ISSUE TITLE
`/api/v1/contracts/call` failing when using Swagger UI

### ISSUE THREAD

**Issue by Neurone** [hashgraph/hedera-mirror-node#6629]
### Description

**Problem**
Sending a valid payload to the `/api/v1/contracts/call` endpoint using the [Swagger UI ](https://testnet.mirrornode.hedera.com/api/v1/docs/) fails with the following error:  **Error: response status is 431** (or _HTTP 431 Request Header Fields Too Large_.)

**Analysis**
The API works as expected if you send the same payload via `curl`.
The problem seems related to the presence of a cookie (`cf_clearance=XXXXXX`) in the request of the Swagger UI.
The `/api/v1/contracts/call` is served by the web3 service, not the REST API one.
The web3 service sets a limit of `1024` bytes for the request headers, and the presence of the cookie exceeds that limit, raising the 431 error.
The Swagger UI does not create the cookie, but other Hedera websites do (i.e., hedera.com) when protected by  [Cloudflare](https://developers.cloudflare.com/fundamentals/get-started/reference/cloudflare-cookies/).

**Workaround**
The cookie is set and sent back by the browser automatically, so there's no easy way to remove that once set.
A potential solution is to let [Traefik removes cookies for this specific route](https://doc.traefik.io/traefik/middlewares/http/headers/#adding-and-removing-headers), so that no cookie ever reaches the web3 service.

### Steps to reproduce

1. Open an incognito window
2. Navigate to https://testnet.mirrornode.hedera.com/api/v1/docs/#/contracts/contractsCall
3. Test the `/api/v1/contracts/call` endpoint with a valid payload. Please note the default example sets too much gas, so you receive a "400 ... gas field must be less than or equal to 15000000" message, we will fix that later.
4. Navigate to https://hedera.com
5. Go back to https://testnet.mirrornode.hedera.com/api/v1/docs/#/contracts/contractsCall
6. Test the `/api/v1/contracts/call` endpoint with the same payload
7. You receive the message **Error: response status is 431**

### Hedera network

other

### Version

v0.85.1

### Operating system

None

**Comment by steven-sheehy** [comment]
I am unable to reproduce. Perhaps hedera.com no longer places a large `cf_clearance` cookie. Regardless, I don't think this is an impactful issue to concern ourselves with as it's a rare scenario for a doc site.

**Comment by Neurone** [comment]
Yep, I tested this again and now it seems to work fine. The `cf_clearance` is still there though, but now it's significantly shorter, so the request headers don't hit the 1Kb limit. I still suggest to strip away cookies and unknown headers from the request at the reverse proxy level, so users will not need to deal with these edge cases.
