### ISSUE TITLE
Performance test sustained high TPS on Cloud SQL

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-mirror-node#6671]
### Problem

To prepare for a future with higher levels of TPS, we need to do sustained performance tests on our current architecture.

### Solution

* Clone mainnet staging
* Create a separate GKE cluster in same network
* Run k6 tests against it to gather a baseline
* Generate record files to simulate a load
* Monitor database and app
* Stop load after a set amount of time or transactions
* Re-run k6 tests
* Repeat until it breaks something

**Comment by edwin-greene** [comment]
Performance test results captured here:
https://www.notion.so/swirldslabs/8K-TPS-Cloud-Sql-K6-Performance-f4e878cd99964b768767abc453086f22

**Comment by edwin-greene** [comment]
Performance test results captured here:
https://www.notion.so/swirldslabs/Performance-Cloud-Sql-K6-Performance-f4e878cd99964b768767abc453086f22
