### ISSUE TITLE
Review REST API caching approach

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-mirror-node#668]
**Problem**
Current REST API had logic for using node-cache that was not completed in implementation and was not in use. As such the Cacher.js file has been idle.

Explore the caching state and decide on a way forward

**Solution**
Remove the Cacher.js file if significant implementation work is needed.

**Alternatives**
- Complete implementation using node-cache 
- Research and utilize a different caching framework that plugs into express easily

**Additional Context**
Right now there's not a huge concern around caching, however might be good to have a basic solution in place. Especially for the collection returning endpoints e.g. /transactions /topics

**Comment by steven-sheehy** [comment]
Cacher.js has been removed. CDN provides the bulk of necessary caching and we can add caching at the application layer as the need arises.
