### ISSUE TITLE
Public testnet record file signature verification fails

### ISSUE THREAD

**Issue by gregscullard** [hashgraph/hedera-mirror-node#67]

**Comment by mike-burrage-hedera** [comment]
Investigate @gregscullard

**Comment by apeksharma** [comment]
@gregscullard @mike-burrage-hedera More info to repro easily will help the person picking it up. Would appreciate any relevant information added to the description. Thanks.

**Comment by mike-burrage-hedera** [comment]
No information here. Re-open with information to repro or specifics on the problem if you need to.
