### ISSUE TITLE
HIP-584 Historical: Create a yaml configuration for evm versions and supported precompiles based on block number and a mechanism to read from the configuration

### ISSUE THREAD

**Issue by stoqnkpL** [hashgraph/hedera-mirror-node#6718]
### Definition

We need to add support of historical blocks related to the work defined in HIP-584, so that we enrich user experience. Additionally we would want to support historical state in the context of system precompiles.

### **Abstract**

This work package would enhance the user experience by extending `eth_call` to work with different block values in the context of system precompiles.

### **Motivation**

Ongoing support of `eth_call` executions require full support of all possible block values for all type of read calls, including system precompiles.

### **Rationale**

As defined in HIP-415, in Hedera the block number is the consecutive number of a record file that was streamed from the consensus nodes. 

The JSON-RPC endpoint `eth_call` accepts a block number as an input argument. This block number specifies that the execution of `eth_call` has to be based on the state that is produced after the execution of all transactions into the specified block. In this way, the state would reliably reflect the changes included in the given block.

The block number can be specified in a hexadecimal format or with string values - `“latest”` or `“earliest”`.  The other strings defined in Ethereum won’t be supported, since they don’t have an alternative in Hedera. These are - `“pending”`, `“safe”` and `“finalized”`. In order to be possible to query historical blocks, we should meet some requirements:

With the current package, we would enhance this support also for system precompiles.

### User stories

1. As a user, I want to perform `eth_call` Ethereum JSON-RPC queries using historical blocks, calling a view function of a smart contract that  in turn make calls to Hedera read only system contracts. This will allow me to see what a particular smart contract state was in the past which I can use to develop block explorers, analytical tools, etc.

### **Specification**

The Mirror Node Rest endpoint [/api/v1/contracts/call](https://testnet.mirrornode.hedera.com/api/v1/docs/#/contracts/contractsCall) currently only supports the “latest” value for the block number.

This work package supports call with a historical block .
Instead of “block”: “latest” a user can pass a hexadacimal value which will represent a call
with historical block. Example → “block”: “0x1” we want to make a call with block number 1.

Once a block number is passed - web3 need to check which evm version was supported during that block.

To do this we will have a config which will work in hierarchical manner.

First: A yaml config in web3 package with the following structure:

<img width="366" alt="image" src="https://github.com/hashgraph/hedera-mirror-node/assets/138600514/5d513066-a669-4d94-98fc-337048774c4c">

This config shows at which block which evm version was active.
block number → evm version.

Based on it we can read the block number passed from contracts/call request and map it to the 
proper evm version and use that evm version during the call.

In case no yaml config is defined. There will be present a HederaNetwork config in java context for every network. This config will have the same mapping structure as the yaml config. So in case yaml config is not defined calls will fallback to the java config.

<img width="558" alt="image" src="https://github.com/hashgraph/hedera-mirror-node/assets/138600514/62bd63dd-f479-41ac-9b90-5eddfd706944">

In case no java config is defined for that network. Then calls will fallback to default evm version
which is used during “block”: “latest” call.

1. Accept incoming block numbers populated in the `eth_call` requests.
    1. The Mirror Node Rest endpoint **[/api/v1/contracts/call](https://testnet.mirrornode.hedera.com/api/v1/docs/#/contracts/contractsCall)** currently only supports the “latest” value for the block number
    2. Add support for block number in hex format and also for the “earliest” block
    4. Using the block number apply the search mechanism above to load the proper evm config based on block number
    5. Return `NOT_SUPPORTED` for `“pending”`, `“safe”` and `“finalized”` and block numbers from before the first supported block
2. Create a test plan and tests

### **Backwards compatibility**

We extend the functionality of the existing code base in `hedera-mirror-web3`, so no implications here. 

### **Security Implications**

This work package shares the same security consideration like `HIP-584` itself. We may receive a bunch of requests that put high load on the network, but we have a global rate limit mechanism over the `web3` module, so we don’t have security implications specific for this work package.

### **References/Dependencies**

1. https://hips.hedera.com/hip/hip-584
2. https://hips.hedera.com/hip/hip-415
3. [Mirror-Node historical information support](https://www.notion.so/Mirror-Node-historical-information-support-70f9e448999f4f25b19b667fd72de6f1?pvs=21)
7. [EVM Archive Node with Historical block support for `eth_call` -design doc- [shared]](https://www.notion.so/EVM-Archive-Node-with-Historical-block-support-for-eth_call-design-doc-shared-7ffd952a53ff4677ac71fad1b46c9678?pvs=21)

**Comment by bibitibooo1** [comment]
To change the description.

**Comment by steven-sheehy** [comment]
This design work is completed and the feature released.
