### ISSUE TITLE
Data size limits to posting to contract calls need to be increased.  

### ISSUE THREAD

**Issue by ebadiere** [hashgraph/hedera-mirror-node#6731]
### Description

Some of the smart contracts tests are now failing when running ```eth_call``` ( ```api/v1/contracts/call``` ) with data sizes that could be handled by the consensus node.

The specific tests are ```should be able to aggregate 1000 calls to processLongInput```, and ```should be able to aggregate 80 calls to processLongOutput and handle 820 kb of output data``` in the smart contracts repository.  Scripts that run the post requests that those tests run via the relay will be attached below.

### Steps to reproduce

1. The test ```should be able to aggregate 1000 calls to processLongInput``` posts a data field of 266, 000 bytes in size.  This triggers a 500 server error. The following setting on the ContractCallRequest class seems suspect for this error: 
```
@Hex(maxLength = 24576 * 2) // HAPI caps contract creates at 24KiB
private String data;
```
The attached script curl-500-response-consensus-node-data-size-processLongInput.sh will post the request the relay runs to your web3 server running out of your local node.  

2. When the data field was reduced to 12,298 bytes in size the mirror node returns a 400 response with ```"data field must not exceed call size limit``` message.  A quick search through the mirror node project found the following snippet in the ContractCallRequest, that maybe related: 
```
   @AssertTrue(message = "must not exceed call size limit")
    private boolean hasData() {
        if (data == null) {
            return true;
        } else {
            final var dataSize = data.length();

            // In case of contract calls we should limit requests to 6KiB
            return to == null || dataSize <= 6144 * 2;
        }
    }
```
The attached script ```curl-ContracCall-data-field-must-not-exceed-call-size-limit-processLongInputData.sh will post the request to the mirror node running out of the local node, that the relay posts.

3. The script ```curl-ContractCall-data-field-must-not-exceed-call-size-limit-processLongOutputData.sh``` also reproduces the 400 size limit response posted by the relay in a similar test for LongOutputData.
4. The script ```curl-200-success-mirror-node-processLongInputData.sh``` returns a 200 response and illustrates how small the data field needs to be in comparison to what was running successfully on the consensus node.

[curl-500-response-consensus-node-data-size-processLongInput.sh.zip](https://github.com/hashgraph/hedera-mirror-node/files/12425082/curl-500-response-consensus-node-data-size-processLongInput.sh.zip)
[curl-ContractCall-data-field-must-not-exceed-call-size-limit-processLongInputData.sh.zip](https://github.com/hashgraph/hedera-mirror-node/files/12425123/curl-ContractCall-data-field-must-not-exceed-call-size-limit-processLongInputData.sh.zip)
[curl-ContractCall-data-field-must-not-exceed-call-size-limit-processLongOutputData.sh.zip](https://github.com/hashgraph/hedera-mirror-node/files/12425150/curl-ContractCall-data-field-must-not-exceed-call-size-limit-processLongOutputData.sh.zip)
[curl-200-success-mirror-node-processLongInputData.sh.zip](https://github.com/hashgraph/hedera-mirror-node/files/12425159/curl-200-success-mirror-node-processLongInputData.sh.zip)

### Hedera network

other

### Version

v0.86.1

### Operating system

macOS

**Comment by steven-sheehy** [comment]
The max data size has been increased to 24KiB (i.e. 48KiB of hex) in #7756 for both create and call. It has also been made configurable in case operators want to increase it for their needs. There are no plans to increase it beyond 24KiB since consensus nodes cannot support that.
