### ISSUE TITLE
Decouple REST Service Route Code from HTTP entities

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-mirror-node#677]
**Problem**
Right now REST service routes all receive the req and res objects and set the res object.
This makes it tightly coupled and we'd prefer it to be void of HTTP logic for easier organization and testing

**Solution**
Refactor service routes to be able to stand on their take in necessary params and return the retrieved data to be formatted into json else where - likely in server.js or a middleware

**Alternatives**

**Additional Context**

**Comment by steven-sheehy** [comment]
We've done some splitting of controller and services. We should continue that refactoring but eventually move to Java.
