### ISSUE TITLE
`from` field is not populated correctly for reverted transaction (e.g. contract call)

### ISSUE THREAD

**Issue by natanasow** [hashgraph/hedera-mirror-node#6831]
### Description

When a user sends a transaction via the JSON RPC relay, the payer of tx is the relayer but the sender should be the signer. That case works as expected for valid transactions. But if the transaction is reverted, as we can see on [these lines in hedera-mirror-node-importer](https://github.com/hashgraph/hedera-mirror-node/blob/main/hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java#L137), the `senderId` equals the `payerId`, which in the user-relayer context is wrong. The proper `senderId` is set only for successful transactions, [here](https://github.com/hashgraph/hedera-mirror-node/blob/main/hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java#L273).

### Steps to reproduce

1. Make a contract call to a non-existing contract
2. Get the tx hash
3. Observe the `from` value in the exposed rest endpoint `/api/v1/contracts/results/<txHash>`

### Hedera network

other

### Version

latest

### Operating system

Linux

**Comment by steven-sheehy** [comment]
Do you have an example from testnet? How would we extract the real sender if there's not a contract result? Mirror node doesn't have a mechanism to convert transaction signatures into account IDs like consensus nodes do. This is why we previously asked consensus nodes to always send a contract result for reverts instead of us attempting to construct a synthetic one.

**Comment by stoqnkpL** [comment]
> Do you have an example from testnet? How would we extract the real sender if there's not a contract result? Mirror node doesn't have a mechanism to convert transaction signatures into account IDs like consensus nodes do. This is why we previously asked consensus nodes to always send a contract result for reverts instead of us attempting to construct a synthetic one.

I logged https://github.com/hashgraph/hedera-services/issues/9149 to address this.

**Comment by steven-sheehy** [comment]
@stoqnkpL If we're going to address this in services can we close this ticket or is there still some work to do on mirror node?

**Comment by stoqnkpL** [comment]
> @stoqnkpL If we're going to address this in services can we close this ticket or is there still some work to do on mirror node?

@steven-sheehy In services, we may populate the contractfnresult for failing transactions. I thought we'd need to update the [`addDefaultEthereumTransactionContractResult()`](https://github.com/hashgraph/hedera-mirror-node/blob/9507636eea2934f0ef199c3fbbd48cfbcb78c23a/hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java#L110) method in the importer as well after that.

**Comment by steven-sheehy** [comment]
There's already a [check](https://github.com/hashgraph/hedera-mirror-node/blob/9507636eea2934f0ef199c3fbbd48cfbcb78c23a/hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java#L82C39-L82C68) that verifies this method is not called if it has a contract result. Unless services will send us a partial `ContractFunctionResult` to avoid sending us duplicated data and we need to add data to it.

**Comment by stoqnkpL** [comment]
My thinking is it makes sense to have this ticket and revisit the Mirror node logic after the services fix. 
In theory services should not produce transaction records with no `ContractFunctionResult` anymore, right? Maybe it would make sense to remove the check on the Mirror node side or handle missing `ContractFunctionResult`s in a different way?

**Comment by konstantinabl** [comment]
Issue is fixed after this fix in services https://github.com/hashgraph/hedera-services/issues/9149 . Currently the isValidContractResult check always returns true, therefore we always set the senderId as the sender not the payer. 
it would be a nice thing to refactor the current logic and not use the isValidContractResult in the same way
