### ISSUE TITLE
Design Filter topic messages REST API by text

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-mirror-node#684]
**Problem**
A customer requested a way to filter topic messages by its content. We store the string internally as a byte array but it may be useful for customers that treat the field as a string to 

**Solution**
Enhance the `/api/v1/topic/<id>/messages?<filters>` REST API to:
- ~~Add a `type` param with values of `text` or `binary`, defaulting to `binary`~~
- Add a `message` param with valid ops `eq` and `like`
- `message` only considered if `type=text`
- ~~Response message is base64 encoded if `type=binary` and converted to UTF-8 strings for `type=text`~~
- If string conversion fails, return an error to the client
- Ensure SQL is escaped properly, especially like keywords `%` and `_`

**Alternatives**
- Add string filtering to the REST API

**Additional Context**
We expect this to be an important feature in the future. As such we should explore solution at varied timelines and not require the current utilization of the DB - external solution can be considered.
We do want to support schema specification at topic creation and key value storage

**Comment by Nana-EC** [comment]
I don't think we should return an error to the client if string conversion fails. Per my understanding we have no control on the actual text going into messages. They could be encrypted or not and encoded in other formats prior to provision.
In which case we can't rely on decoding all messages in a topic. Some may work and others won't.
The searching logic should apply to those that are applicable and the rest ignored. 
This should be conveyed in the support details of the API.

Other than that we probably don't need to require the type field if the message filed is provided but we'll see what implementation looks like.

**Comment by Nana-EC** [comment]
Here's a draft of a design approach for this

### Problem
Customers are currently able to subscribe to messages through GRPC API  and get all messages but have to manually filter through messages to find those containing a certain string in their message field.
Customers instead would like to use REST API to retrieve messages from a topic that contain a certain string instead.

### Solution
Currently the GET  `/topic/:id/` REST endpoint returns messages for a given topic and supports filtering by timestamp and sequence range.
E.g. `/api/v1/topic/7?sequencenumber=lt:4&sequencenumber=gte:1&timestamp=lte:1234567890.000000004&timestamp=gt:1234567890.000000001`

This will be extended with 2 additional filter queries to support message searching.
`type=<text|binary>` & `message=<search_term>`

### Details
As is messages are returned with the message field (which is a byte array) being base64 encoded
```
{
        "messages":[
                {
                        "consensus_timestamp":"1586996234.456739001",
                        "topic_id":"0.0.1234567891",
                        "message":"/woUHg==",
                        "running_hash":"/woUHg==",
                        "sequence_number":1
                }
        ],
        "links":{
                "next":null
        }
}
```

This conforms to the type=binary format.

To return legible messages type=text should be set resulting in
```
{
        "messages":[
                {
                        "consensus_timestamp":"1586996234.456739001",
                        "topic_id":"0.0.1234567891",
                        "message":"abc",
                        "running_hash":"/woUHg==",
                        "sequence_number":1
                }
        ],
        "links":{
                "next":null
        }
}
```

To search amongst the message in the filter range the query filter message=<search_term>must be added
This will search for messages that contain the given search term

An example query to obtain all messages in a topic with 'hedera' would look like this
`/api/v1/topic/7?type=text&message=hedera`

### Limitations
	• Unlike GRPC API a max page size limit of 1000 messages will be received at a time. Users will have to call API endpoint as needed to obtain all messages desired
	• The search logic will only be applicable for non encrypted texts that supports UTF-8 encoding. The items returned will represent only those messages. All others will be ignored as we can't rely on the message contents format across topics.

**Comment by Nana-EC** [comment]
Updated above comment to reflect the fact it should be /topic/:id/messages and not /topic/:id/ as we are dealing with message entities and not topic entities

**Comment by Nana-EC** [comment]
We do already have a type query filter which refers to the crypto debit or credit.
Maybe 'message type' or 'format' or 'messageformat' would be more suitable.

**Comment by Nana-EC** [comment]
I compared using "...like '%<Search_term>'%'.." and "...position(<search_term>::bytea in message) > 0 ..." and they performed within a few seconds of each other.
Prescribed approach works for basic scenarios, however at scale it becomes impractical.
Tries with a topic of millions of messages and the search for a non existent term took over 100 seconds.
The right thing here would be to employ [full test search](https://www.postgresql.org/docs/9.6/textsearch-tables.html) and utilize the tsvector and tsquery after creating an index on a textual format of the message column.

Next step here would be to explore this briefly and some kind of schema or key value pair search support based off of specification at topic creation time

**Comment by steven-sheehy** [comment]
Doing text based searching of 39+ billion HCS messages isn't feasible, at least not without a payment model to support the extra indexes or databases it would take to support it.
