### ISSUE TITLE
/api/v1/balances does not give a "next" link to get more tokens after 50

### ISSUE THREAD

**Issue by iron4548** [hashgraph/hedera-mirror-node#6864]
### Description

I queried the latest balances for an account containing more than 50 tokens.

/api/v1/balances?account.id=0.0.xxxx returned top 50 tokens (using the public mirror node), but the "next" link is missing. 

Therefore I am unable to get the other tokens.

After dissociating some of the tokens, I ran that query again and some new ones appeared in the top 50 tokens returned.

It may need something like this first: /api/v1/balances?account.id=0.0.xxxx&token.id=lt:0.0.xxxxx

### Steps to reproduce

Query an account containing more than 50 tokens using /api/v1/balances?account.id=0.0.xxxx, and note that the "next" link in the JSON body isn't provided.

### Hedera network

mainnet

### Version

NA - public mirror node

### Operating system

None

**Comment by xin-hedera** [comment]
you can query `/api/v1/accounts/{id}/tokens` instead.

our rest apis generally support a single level pagination, the `/api/v1/balances` api pages over account id.

**Comment by iron4548** [comment]
Thanks, I guess I missed that one because the useful data is cut off from the side panel as shown below. Maybe something for the team to figure how to to improve the side panel navigation?

![image](https://github.com/hashgraph/hedera-mirror-node/assets/22169356/d0137480-e8d0-4752-91c4-ea9a63515249)

**Comment by steven-sheehy** [comment]
Recommend to use our interactive Swagger endpoint for the nost up to date info about our APIs: https://mainnet-public.mirrornode.hedera.com/api/v1/docs/.

Going to close this since the initial issue has been addressed.
