### ISSUE TITLE
Auto Clean up old master images in GCR

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-mirror-node#689]
**Problem**
As part of CI we will push images to GCR on master merges.
This will create a build up of images that we'll want to remove.

**Solution**
Update circle ci config to remove images older than 7 days

**Additional Context**
Current logic exists to do this but we saw discrepancies in the time filter at the precision of a few hours. .
In some tests when filtering on images older than a few hours ago the console would return an expected subset, upon running the delete command all images with that tag were removed.
Seems to not occur when accuracy of timing is in days and not hours.
For now logic is left as an echo to see intentions but not actually remove images.

**Comment by apeksharma** [comment]
@Nana-EC  This seems to have been addressed in #683. Can we close this?
