### ISSUE TITLE
Citus Read Replicas Not working

### ISSUE THREAD

**Issue by jnels124** [hashgraph/hedera-mirror-node#6890]
### Problem

In the new citus cluster, read replicas are not being used for reads. 

### Solution

Investigate configuration/changes needed to load balance read operations between replicas

**Comment by xin-hedera** [comment]
citus supports load balancing read-only queries to secondary worker nodes from secondary coordinators with the following configuration:

- call `citus_add_secondary_node(nodename, nodeport, primaryname , primaryport)` to add all secondary worker nodes
- set `citus.use_secondary_nodes` to `always` on secondary coordinators (in postgresql.conf), and restart the secondary coordinators to take effect afaict

Then the read-only queries when sent to the secondary coordinators, will get pushed down to the registered secondary worker nodes. However, read-only queries sent to the primary coordinator will still only utilize primary worker nodes.

This definitely requires patroni support including

- maintain `pg_dist_node` with secondary node and update them properly during switchover / failover
- maintain `citus.use_secondary_nodes` when transitioning coordinators between primary <-> secondary

**Comment by xin-hedera** [comment]
patroni ticket https://github.com/zalando/patroni/issues/2880

**Comment by teoincontatto** [comment]
SGCluster are generated from an SGShardedCluster so that the latter will also use Patroni 4
