### ISSUE TITLE
Support consistent reads in multi-cluster environments

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-mirror-node#6911]
### Problem

Some environments like testnet and mainnet are multi-cluster where each cluster could be processing at slightly different rates. This can cause clients to query successfully for a specific transaction then later query for its related data and it not be present due to it being routed to a cluster that's slightly behind.

### Solution

Investigate use of Google's Client IP based session [affinity](https://cloud.google.com/load-balancing/docs/backend-service#session_affinity).

**Comment by xin-hedera** [comment]
we decided to increase the google cloud load balancer backed max RPS to improve read consistency as the solution.
