### ISSUE TITLE
Update the Besu EVM library to version 23.7.2

### ISSUE THREAD

**Issue by kselveliev** [hashgraph/hedera-mirror-node#6958]
### Problem

Description:
Use version 23.7.2 of the Besu EVM library

### Solution

Update the besu version in gradle

**Comment by kselveliev** [comment]
Related to [this](https://github.com/hashgraph/hedera-services/pull/8472)

**Comment by Nana-EC** [comment]
@bilyana-gospodinova closing this in favour of https://github.com/hashgraph/hedera-mirror-node/issues/7092
i.e. please upgrade to 23.10.0 instead
