### ISSUE TITLE
Topic Message Endpoints Show Regression in V2

### ISSUE THREAD

**Issue by jnels124** [hashgraph/hedera-mirror-node#6976]
### Problem

`/topics/{id}/messages`,  `/topics/{id}/messages/{sequenceNumber}`, and `/topics/{id}/messages?sequencenumber={sequenceNumber}` show large performance decrease in V2 when compared to V1

### Solution

When `topic_message` table is partitioned by timestamp range, we need to utilize `topic_message_lookup` table to narrow down the number of partitions to query for better performance.

- Set `hedera.mirror.importer.parser.record.entity.persist.topicMessageLookups=true` to enable `topic_message_lookup` and run the migration to backfill the table from existing data in `topic_message` table
- In Rest API
  -  Add a utility function `isV2Schema` to lazily detect if it's running v2 by checking if migration version `2.0.0` is in `flyway_schema_history` table. The function should cache the result
  - For `/topics/{id}/messages`, parse the `sequencenumber` query filters to build a sequence number range, query `topic_message_lookups` table to find the covering timestamp ranges, e.g.
     ```sql
     select timestamp_range
     from topic_message_lookup
     where topic_id = $1 and sequence_number_range && $2
     order by sequence_number_range
     ```
     `&&` is the PostgreSQL range overlap operator, `$2` is the sequence number range built from query filters. 
     A couple of things to note for building the sequence number range
     -  Consider the limit and order to modify either the lower or the upper bound
     - When there is no `sequencenumber` query filters, depending on the order, use different queries to get the first or the last X topic messages' timestamp range from `topic_message_lookup` table
     - Consider shortcut and return empty response if the range built is empty, e.g., `sequencenumber=gt:10&&sequencenumber=lt:10`
     - Reject the query if there is any `ne` operator, e.g., `sequencenumber=ne:10`
     - Reject the query if there are multiple `eq` operators, eg., `sequencenumber=10&&sequencenumber=eq:11`
  - For `/topics/{id}/messages/{sequenceNumber}`, the query to find the timestamp range is similar, just need to use the range include operation, e.g., `sequence_number_range @> $2`
  - Limit the number of timestamp partitions by adding the timestamp ranges to the where conditions

**Comment by steven-sheehy** [comment]
Probably we need to enable topic_message_lookup in citus env and re-run the migration

**Comment by mgoelswirlds** [comment]
Upon calling the above endpoints and inspecting the queries they seem to be partitioned and sharded on the partition key and distribution key respectively.

**Comment by xin-hedera** [comment]
The rest API changes to utilize topic_message_lookup table to narrow down the number of topic_message partitions aren't there yet.

**Comment by mgoelswirlds** [comment]
For reference. The topic_message_lookup was populated on the citus cluster.

**Comment by mgoelswirlds** [comment]
Refer to https://github.com/hashgraph/hedera-mirror-node/issues/7157 for the /topics/{id}/messages/{sequenceNumber} endpoint

**Comment by xin-hedera** [comment]
> @xin-hedera to use v2 schema check why can't we simply use the config `process.env.MIRROR_NODE_SCHEMA` instead of checking the flyway_schema table?

because that's an env variable we only set when running rest api integration tests
