### ISSUE TITLE
eth_call fails on some read-only methods

### ISSUE THREAD

**Issue by iron4548** [hashgraph/hedera-mirror-node#7034]
### Description

The factory contract (UniswapV2Factory) used by SaucerSwap has these methods that does not change the state.

```solidity
\\IUniswapV2Factory.sol
function pairCreateFee() external view returns (uint256);
function getPair(address tokenA, address tokenB) external view returns (address pair);
function allPairs(uint) external view returns (address pair);
function allPairsLength() external view returns (uint);

\\UniswapFactory.sol
uint256 public override pairCreateFee;

mapping(address => mapping(address => address)) public override getPair;
address[] public override allPairs;

function allPairsLength() external override view returns (uint) {
  return allPairs.length;
}
```

I tested getting the data via mirror node **testnet** (rest-api and json-api) and only pairCreateFee() returned a valid value.

"pairCreateFee()" (0x881a075a) returned '20000000000' - correct
```json
{
    "jsonrpc": "2.0",
    "method": "eth_call",
    "params": [
        {
            "to": "0x000000000000000000000000000000000000de01",
            "data": "0x881a075a"
        },
        "latest"
    ],
    "id": 0
}
```
"allPairsLength()" (0x574f2ba3) returned 0 (incorrect). The correct value should be at least 23.
```json
{
    "jsonrpc": "2.0",
    "method": "eth_call",
    "params": [
        {
            "to": "0x000000000000000000000000000000000000de01",
            "data": "0x574f2ba3"
        },
        "latest"
    ],
    "id": 0
}
```

"getPair(tokenA, tokenB)" also returned 0 (zero) when expecting a non-zero pair address.

for tokenA: 0x000000000000000000000000000000000000ef52 (SAUCE)
for tokenB: 0x000000000000000000000000000000000000e6a2 (WHBAR)

```json
{
    "jsonrpc": "2.0",
    "method": "eth_call",
    "params": [
        {
            "to": "0x000000000000000000000000000000000000de01",
            "data": "0xe6a43905000000000000000000000000000000000000000000000000000000000000ef52000000000000000000000000000000000000000000000000000000000000e6a2"
        },
        "latest"
    ],
    "id": 0
}
```

### Steps to reproduce

1. Go to https://playground.open-rpc.org/?schemaUrl=https://raw.githubusercontent.com/hashgraph/hedera-json-rpc-relay/main/docs/openrpc.json&uiSchema%5BappBar%5D%5Bui:splitView%5D=false&uiSchema%5BappBar%5D%5Bui:input%5D=false&uiSchema%5BappBar%5D%5Bui:examplesDropdown%5D=false

2. Use https://testnet.hashio.io/api

3. Test with above JSON objects

Same results are also seen for REST-API's `/api/v1/contracts/call` as well. 

### Hedera network

testnet

### Version

public testnet (live)

### Operating system

None

**Comment by 0xivanov** [comment]
There are 3 transactions on this contract before 10th of October (this was me).
The first transaction if for contract create - no state changes. The second transaction input is `0x16af9344000000000000000000000000000000000000000000000000000000000000d661`
calling `setRentPayer`
The third transaction input is `0xf46901ed000000000000000000000000000000000000000000000000000000000000de0c`
calling `setFeeTo`
The function `createPair` is not called at all.
It's obvious why the mapping and arrays are not changed. Their lengths too.

You can see the transactions here:
https://hashscan.io/testnet/transaction/1690510038.547070304
https://hashscan.io/testnet/transaction/1690510044.841198003
https://hashscan.io/testnet/transaction/1690510047.187500809

**Comment by iron4548** [comment]
@0xivanov Factory's createPair() usually gets called from UniswapV2Router

```solidity
function addLiquidityETHNewPool(
        address token,
        uint amountTokenDesired,
        uint amountTokenMin,
        uint amountETHMin,
        address to,
        uint deadline
    ) external virtual payable override ensure(deadline) returns (uint amountToken, uint amountETH, uint liquidity) {
        require (IUniswapV2Factory(factory).getPair(token, whbar) == address(0), "UniswapV2Router: POOL ALREADY EXISTS");
        uint256 feeInTinybars = tinycentsToTinybars(IUniswapV2Factory(factory).pairCreateFee());

        address addr = IUniswapV2Factory(factory).createPair{value: feeInTinybars}(token, whbar);
        safeAssociateToken(to, IUniswapV2Pair(addr).lpToken());

        (amountToken, amountETH) = _addLiquidity(token, whbar, amountTokenDesired, msg.value - feeInTinybars, amountTokenMin, amountETHMin);
        address pair = UniswapV2Library.pairFor(factory, token, whbar);
        
        safeTransferTokenRouter(
            token, msg.sender, pair, amountToken
        );
        IWHBAR(WHBAR).deposit{value: amountETH}(msg.sender, pair);
        liquidity = IUniswapV2Pair(pair).mint(to);
        if (msg.value - feeInTinybars > amountETH) TransferHelper.safeTransferETH(msg.sender, msg.value - feeInTinybars - amountETH);
    }
```

**Comment by iron4548** [comment]
The existing Factory contract 0x000000000000000000000000000000000000de01 should have at least 23 pairs.

**Comment by 0xivanov** [comment]
Yes you are right. The router is calling the factory and it is only the top level calls that are displayed by chain analysis tools like hashscan. But i did some digging and found out that the factory contract that you are using `0x000000000000000000000000000000000000de01` is not the actual factory used by the router.

1. I went into the saucerswap docs to find the contract addresses: https://docs.saucerswap.finance/resources/saucer-contracts
As you can see `0x000000000000000000000000000000000000de01` is displayed is factory. I grabbed the router address `0x000000000000000000000000000000000000e8df` and called it's factory field like this:
``` json
```

**Comment by 0xivanov** [comment]
If my assumption is right, then the documentation of saucerswap is invalid and should be updated

**Comment by iron4548** [comment]
@0xivanov good catch!! You're right, the documentation was wrong and the address you provided is correct. I've relayed this info to the SaucerSwap team. Sorry about the false positive. Thank you for your time on this and helping me to get to the bottom of this.
