### ISSUE TITLE
evm address value returned from eth_call is 64 characters long (66 with 0x) when 40 characters is expected

### ISSUE THREAD

**Issue by iron4548** [hashgraph/hedera-mirror-node#7037]
### Description

I queried the token0 address data from a pair contract and it returned me with a 64 character long EVM address:

`0x000000000000000000000000000000000000000000000000000000000000e6a2`

I was expecting an EVM address that is 40 characters long excluding 0x

When I paste that address in hashscan.io it returned with no result.

If I modify the address to:

`0x000000000000000000000000000000000000e6a2`

Then hashscan.io will give me the correct result (token) for my search.

Here's the solidity contract definition for token0
```solidity
contract UniswapV2Pair is SafeHederaTokenService {
    using SafeMath for uint256;
    using UQ112x112 for uint224;
    using Bits for uint;

    uint256 public constant MINIMUM_LIQUIDITY = 10**3;

    address public factory;
    address public token0; <<
    address public token1;
    address public lpToken;
...


interface IUniswapV2Pair {
    ...
    function MINIMUM_LIQUIDITY() external pure returns (uint);
    function factory() external view returns (address);
    function token0() external view returns (address); <<
    function token1() external view returns (address);
    function lpToken() external view returns (address);
```

### Steps to reproduce

1. https://testnet.mirrornode.hedera.com/api/v1/docs/#/contracts/contractsCall
2. Send this data

```json
{
  "block": "latest",
  "data": "0x0dfe1681",
  "to": "65d0acb9f5fd237344c6ac36c1b7eaf8a6138396"
}
```

And you'll get
```json
{
  "result": "0x000000000000000000000000000000000000000000000000000000000000e6a2"
}
```

Same result when JSON-RPC is used.

### Hedera network

testnet

### Version

public mirror node - live

### Operating system

None

**Comment by Nana-EC** [comment]
Thanks for opening the ticket @iron4548 .
We'll take a look at this.

**Comment by iron4548** [comment]
Turns out that this was due to my lack of knowledge about how the data is stored.

I was told that the storage slot in solidity are all 32 bytes long, so that would explain the 64 characters long data.

To get the correct 40 character long address I use ethers.AbiCoder.defaultAbiCoder.decode(['address'], data) and that worked.

Closing this issue.
