### ISSUE TITLE
HIP-679: Rollup support

### ISSUE THREAD

**Issue by mgoelswirlds** [hashgraph/hedera-mirror-node#7050]
### Problem

The phase 3 from [this HIP](https://hips.hedera.com/hip/hip-679) will be implemented and we need to be able to read the compressed tar into the mirror node.

### Solution

- Create a technical design for the above.
- Implement downloading the compressed file and parsing it in the Mirror node. Until the lambda function which creates the tar is implemented we will maintain both forms of parsing i.e. the current mirror node approach as well as reading from the tar.

**Comment by steven-sheehy** [comment]
Closing since HIP-679 won't be implemented in favor of block nodes.
