### ISSUE TITLE
Improve REST API Query Filter Handling 

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-mirror-node#712]
**Problem**
The current design of query filters could be improved.

Currently REST API query filters are transformed into an array of filter objects of the following format
{
    key: '',
    operator: '',
    value: '',
  }

It was suggested to turn this into a map instead of an array of filters to make it easier to extract values later on as the sql query is built.

We also currently support repeated query filter keys. In some cases this doesn't make sense e.g. limit, order, type, result.
We may want to consider how to limit this or error on this.

**Solution**
- Create map of filter queries instead of array
- Limit specific filters to one occurrence 

The above could eb achieved using a 3rd part library such as [Express Validator](https://express-validator.github.io/)

**Alternatives**
Use a more OO approach and avoid current cases in util file. See suggested pseudo code form Steven
```
// filters.js
var filters = {};

class Filter {
  constructor(name, validator, comparator) {
    this.name = name;
    this.validator = validator;
    this.comparator = comparator;
  }
}

func addFilter(tokenId) {
  filters[tokenId.name.toLowerCase()] = tokenId;
}

func validate(key, value) {
  const filter = filters[param.toLowerCase()];
  if (filter) {
    filter.validator(value);
  }
}

addFilter(new Filter('tokenId', (value) => ...));
...
```

**Additional Context**

**Comment by Nana-EC** [comment]
Also see suggestion from https://github.com/hashgraph/hedera-mirror-node/pull/704#discussion_r414168254

**Comment by steven-sheehy** [comment]
We should move to either automatic OpenAPI validation or to Java REST APIs instead of the above.
