### ISSUE TITLE
Add in-equivalence tests 

### ISSUE THREAD

**Issue by yiliev0** [hashgraph/hedera-mirror-node#7193]
### Problem

Currently we don't have tests that verify system accounts called via different opcodes like

- [ ] - direct calls
- [ ] - callcode
- [ ] - call
- [ ] - delegatecall
- [ ] - staticcall
- [x] - selfdestruct
- [x] - balance
- [x] - extcodecopy
- [x] - extcodehash
- [x] - extcodesize
- [ ] - HTS transfers

### Solution

Add tests that would cover all opcodes with system accounts

**Comment by bilyana-gospodinova** [comment]
Closing this task as we decided to close all existing PRs.
