### ISSUE TITLE
Performance Tests: set up and tooling

### ISSUE THREAD

**Issue by calvinchengx** [hashgraph/hedera-mirror-node#72]
Begin evaluating tooling and implementing performance tests, to be run from CI (nightly test?).

- spin up environment to test the performance of the mirror-node (parser and rest-api), likely nightly build.
- get results for:
  - rest-api performance numbers per transaction
  - insert/processing performance numbers from the parser
 ...

cc @atul-hedera

**Comment by calvinchengx** [comment]
@mike-burrage-hedera @steven-sheehy 

I need to switch circleci to use machine executor (as opposed to the default docker executor) in order to invoke commands on the Performance Test Machine (a digital ocean box) via ssh.

Let me know if you think of any better alternatives.

**Comment by mike-burrage-hedera** [comment]
Good test of an A/B comparison would be running a perf test with accountBalancesUseTransaction to true vs false - see #117
