### ISSUE TITLE
Add transactionHash to Transaction API

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-mirror-node#720]
Add transactionHash to /transactions api.

**Comment by Nana-EC** [comment]
Changed from Pw to P1. Pretty high pri so  do as soon is practical. At the the least should be slated for next spring v0.12 given importance of larger use case scenario

**Comment by Nana-EC** [comment]
Customer seems to for sure need transaction hash as Kabuto and Dragon Glass are exposing a  transaction hash and we aren't.

This is doable in addition to entity id (topicid). Sequence number however exists in a different table.
Also if topicid is added together with the consensustimestamp users can get the exact topic message if desired.

Split this item up into 
1. Adding transaction hash & entity id
2. Explore Sequence number addition

**Comment by apeksharma** [comment]
EntityId is in table `t_entities`, so adding it to the response will require another join.
We already have plans to denormalize it and put it directly into `t_transactions` soon.
Rather than adding join now and then refactoring it later, let's do it with/right after denormalization.

**Comment by apeksharma** [comment]
Created #756 for adding topicId and sequenceNumber
