### ISSUE TITLE
Performance test entity_transaction ingestion in V2

### ISSUE THREAD

**Issue by xin-hedera** [hashgraph/hedera-mirror-node#7232]
### Problem

Due to the amount of data to write for `entity_transaction` table, there is noticeable increase in record file parse duration at 10K tps in V1.

We need to test the same with V2 to see the ingestion performance impact.

### Solution

- Set up a citus cluster with production env configuration
- Run `RecordFileParserPerformanceTest` with 10K TPS crypto transfer transactions including both crypto transfer and token transfers from a minimum of 1000 distinct entity IDs
- Observe the record file parse duration especially the time spent on `entity_transaction` table over the time. Ideally, the test should run long enough to fill up a one-month time partition

**Comment by steven-sheehy** [comment]
Closing as we don't think this is the correct approach.
