### ISSUE TITLE
Inaccurate Gas Estimation for Contract Deployment on Hedera Network

### ISSUE THREAD

**Issue by mshakeg** [hashgraph/hedera-mirror-node#7249]
### Description

I am experiencing an issue with gas estimation when deploying a contract to the Hedera network using Hardhat and ethers.js. The `eth_estimateGas` method returns a gas value of 61060, but deploying the contract with this gas limit results in a failure due to insufficient gas. Presumably the hedera relay returns the gas estimation value as is from the mirror node, hence why I am reporting the issue here.

### Steps to reproduce

1. Set up a Hardhat environment configured for the Hedera network.
2. Use ethers.js with the following contract deployment code:
    ```javascript
    import {
      abi as UV3MATH_ABI,
      bytecode as UV3MATH_BYTECODE,
    } from "UV3Math.json";
    
    import { ethers } from "hardhat";
    
    const deployer = (await ethers.getSigners())[0];

    const uV3MathLibraryFactory = new ethers.ContractFactory(UV3MATH_ABI, UV3MATH_BYTECODE, deployer);
    const deployTx = uV3MathLibraryFactory.getDeployTransaction();
    const estimatedGas = await deployer.estimateGas(deployTx); // returns 61_060
    console.log("Estimated Gas:", estimatedGas.toString());

    const uV3MathLibrary = await uV3MathLibraryFactory.deploy({ gasLimit: estimatedGas });
    await uV3MathLibrary.deployTransaction.wait(blockConfirmations);
    ```
3. Observe the estimated gas and attempt the contract deployment.
4. Observe the deployment transaction fails with the following error:
```
ProviderError: [Request ID: 327cb8b3-a1d8-4779-a247-9ac7fa0555e8] Transaction gas limit provided '61060' is insufficient of intrinsic gas required '76232'
```

### Additional context

I have attach the ABI and bytecode file for the contract (`UV3Math.json`) to this issue.

If you want to replicate the issue in hardhat using the same deps versions:
"@nomiclabs/hardhat-ethers": "^2.2.1",
"ethers": "^5.7.2",
"hardhat": "^2.19.1",

[UV3Math.json](https://github.com/hashgraph/hedera-mirror-node/files/13452911/UV3Math.json)

### Hedera network

testnet

### Version

mirror-node@0.92.0

### Operating system

None

**Comment by bilyana-gospodinova** [comment]
We are currently investigating the issue. The value from the error message (76232) comes from the calculation in the relay. As a workaround you can pass about 25% more gas than the estimated from the mirror node and the contract deploy should succeed.

**Comment by mshakeg** [comment]
Hu @IvanKavaldzhiev I'm not sure this has been fixed as gas estimation now fails, however the contract deploys if I manually specify a sufficient gas limit.

**Comment by bilyana-gospodinova** [comment]
Can you please clarify which environment you use for testing? I retested the code that you provided locally and with the latest versions of mirror-node-web3 and json-rpc-relay I was able to run the code successfully:
Estimated gas: 116265
Actual gas used: 108995

**Comment by mshakeg** [comment]
@bilyana-gospodinova it failed to estimate gas for another contract specifically the attached `ICHIVaultDepositGuard`
 
[ICHIVaultDepositGuard.json](https://github.com/hashgraph/hedera-mirror-node/files/13844041/ICHIVaultDepositGuard.json)

**Comment by bilyana-gospodinova** [comment]
@mshakeg, Can you please provide the full js file and all of its dependencies with which you deploy the `ICHIVaultDepositGuard` contract?

**Comment by mshakeg** [comment]
@bilyana-gospodinova you can use the same js script in step 2 of `Steps to Reproduce` to deploy the `ICHIVaultDepositGuard` contract, obviously modify it to import from `ICHIVaultDepositGuard.json` instead of `UV3Math.json`

**Comment by bilyana-gospodinova** [comment]
@mshakeg `ICHIVaultDepositGuard` contract's constructor requires two arguments so if I reuse the code directly I get this error on deploy:
Error: missing argument:  in Contract constructor (count=0, expectedCount=2, code=MISSING_ARGUMENT, version=contracts/5.7.0)
This is why I requested the code - so I can pass the correct arguments and debug the mirror node code and investigate further.

**Comment by mshakeg** [comment]
@bilyana-gospodinova ah yes, you can pass the following 2 addresses `0x3319A941c8cfe43a75632340C0b97BBd7900c83C` and `0x000000000000000000000000000000000000e6a1` in that order.

**Comment by mshakeg** [comment]
@bilyana-gospodinova were you able to deploy using those args?

**Comment by bilyana-gospodinova** [comment]
@mshakeg Thank you for the provided arguments. I debugged the scenario and the cause for the error is: CONTRACT_REVERT_EXECUTED so it seems like an issue with the contract itself and this cases the estimation to fail.

**Comment by mshakeg** [comment]
@bilyana-gospodinova hmm, it shouldn't, can you please share that tx?

**Comment by mshakeg** [comment]
@bilyana-gospodinova does gas estimation result in the `CONTRACT_REVERT_EXECUTED` error? If so, then you've replicated the issue, as if you manually specify the gasLimit(try 6m) to avoid gas estimation then you should observe that the contract is actually deployed.

**Comment by bilyana-gospodinova** [comment]
@mshakeg yes, I think I replicated the issue. Can you please send me the abi for the contracts at address `0x3319A941c8cfe43a75632340C0b97BBd7900c83C` and `0x000000000000000000000000000000000000e6a1`?

**Comment by mshakeg** [comment]
@bilyana-gospodinova not sure why you need it, but you can access the abi for all verified contracts in the `metadata.json` file.

Example for [0x3319A941c8cfe43a75632340C0b97BBd7900c83C](https://[repository-verify.hashscan.io/contracts/full_match/296/0x3319A941c8cfe43a75632340C0b97BBd7900c83C/metadata.json](https://repository-verify.hashscan.io/contracts/full_match/296/0x3319A941c8cfe43a75632340C0b97BBd7900c83C/metadata.json))

`0x000000000000000000000000000000000000e6a1`  isn't verified but is identical to this [mainnet verified contract](https://hashscan.io/mainnet/contract/0.0.1456985?p=1&k=1704805034.668051003) so you can use the abi.

**Comment by bilyana-gospodinova** [comment]
@mshakeg Thank you for the provided details. I made a fix and retested the gas estimation with the provided contracts locally and I see no errors now. Please retest when version 0.97 is available on testnet and let me know if you still have issues.

**Comment by mshakeg** [comment]
@bilyana-gospodinova thanks, will let you know if the issue persists for this or any other deployments.

**Comment by mshakeg** [comment]
Hi @bilyana-gospodinova I'm having gas estimation issues when attempting to deploy the [Safe contract](https://github.com/safe-global/safe-smart-account/blob/main/contracts/Safe.sol) to testnet. Manually specifying a gasLimit of 6_000_000 works.

**Comment by bilyana-gospodinova** [comment]
Hi @mshakeg, I am not familiar with this repo but I followed your steps and on step 3 I get this error:
```
CompilerError: Stack too deep, try removing local variables.
   --> @matterlabs/zksync-contracts/l2/system-contracts/BootloaderUtilities.sol:104:34:
    |
104 |             uint256 listLength = encodedNonce.length +
    |    
``` 
I suppose this is not the one that you meant. Did you get it too and if yes - what steps did you take to fix it? What are the solidity settings, the hardhat version and the @matterlabs/zksync-contracts version that you have?

What is the exact error that you get? Does it happen again on step 3?

How do you pass the Safe contract to the deployed SafeSingeltonFactory in order to be deployed? Can you please provide example data?

**Comment by bilyana-gospodinova** [comment]
Hi @mshakeg, thank you for the clarifications. I was able to reproduce the issue. The cause for that is when a contract is used to deploy another contract this is a contract call case and not a contract deploy case so there are more strict limitations about the size of the data. For GnosisSafe and GnosisSafeL2 the data gets too large and this is why the estimation fails. We made PR https://github.com/hashgraph/hedera-mirror-node/pull/7756 and it is about to be merged soon. In there we extend a little but the data size limit. I retested with your contracts and I see that the estimation is successful now. However, please note that if GnosisSafe or GnosisSafeL2 get bigger the same issue would occur. We are working on a more permanent solution.
