### ISSUE TITLE
Inconsistent Success Response in `eth_call` for Gas-Heavy `performUpkeep` Transactions Involving HTS Precompile on Hedera

### ISSUE THREAD

**Issue by mshakeg** [hashgraph/hedera-mirror-node#7272]
### Description

I have identified a specific issue with the Hedera mirror node's handling of `/api/v1/contracts/call` requests(at least if there's not bug in the Hedera relay as I'm making `eth_call` requests), particularly when interacting with the [UniswapInterfaceMulticall](https://github.com/Uniswap/v3-periphery/blob/main/contracts/lens/UniswapInterfaceMulticall.sol) contract for Chainlink Automation `performUpkeep` functions. This issue is distinctly observed in cases where the call interacts with the Hedera Token Service (HTS) precompile contract. Such transactions tend to be gas-heavy. In these scenarios, the `eth_call` returns `success` as `false`, despite the actual transaction being successfully executed on the network. This behavior contrasts with `performUpkeep` transactions that involve only typical EVM operations(not extending to any precompiles) and are less gas-intensive, which do not exhibit this issue.

Notably, this problem is unique to the Hedera network. Similar setups and transactions on other networks like Ethereum, Arbitrum, and BSC accurately reflect the `success` status in `eth_call` requests.

Expected Behavior:
The `eth_call` method should consistently reflect the actual `success` status of calls within a transaction, regardless of their complexity or gas usage, aligning with the transaction execution results on the network.

Actual Behavior:
For gas-heavy `performUpkeep` transactions, especially those involving HTS precompile interactions, `eth_call` requests return `success` as `false`, contradicting the actual successful execution of these transactions on the network.

### Steps to reproduce

1. Encode the calldata for a gas-heavy call involving HTS precompile contract interactions(get HTS balance, transfer, etc) that should ordinarily succeed.
2. Perform an `eth_call` request on the constructed transaction via the `UniswapInterfaceMulticall` contract.
3. Observe the returned `success` field from the `eth_call` is false
4. Now instead of an `eth_call` actually execute the transaction and note that it succeeded.
5. Compare this with a typical, less gas-intensive transaction, which does not show this discrepancy.

If it helps with debugging I can put one of my testnet contracts into a state where `eth_call` `success` is false, but the actual transaction is successful.

### Additional context

- The issue has been consistently reproducible on the Hedera network for the specified type of `performUpkeep` transaction.
- The transaction that succeeded can be inspected at [hashscan.io/testnet/transaction/1701089946.967156003](https://hashscan.io/testnet/transaction/1701089946.967156003).

### Hedera network

testnet

### Version

mirror-node@0.92.0

### Operating system

None

**Comment by mshakeg** [comment]
So I think I may have come across a similar issue with the below call which also happens to be more consistently replicable. Note that all 3 use the same `calldata`, `from` and `to`

#### 1. failure on eth_call

```shell
curl https://testnet.hashio.io/api \
  -X POST \
  -H "Content-Type: application/json" \
  --data '{"method":"eth_call","params":[{"from":"0x11111D16485aa71D2f2BfFBD294DCACbaE79c1d4","to":"0x0B0C5E6c39195301D8922C89b873836b206A0d1e","data":"0x5d123e3f0000000000000000000000001abee930ed0fed631c7b5166b7686baa2ee9d69a000000000000000000000000ec7428cb95cd92e7556172ffbe735c6d48f6deb7000000000000000000000000000000000000000000000000000000000000ef5200000000000000000000000000000000000000000000000000000000000f4240000000000000000000000000000000000000000000000000000000000000000100000000000000000000000011111d16485aa71d2f2bffbd294dcacbae79c1d4"}, "latest"],"id":1,"jsonrpc":"2.0"}'
```

#### 2. success on eth_estimateGas

```shell
curl https://testnet.hashio.io/api \
  -X POST \
  -H "Content-Type: application/json" \
  --data '{"method":"eth_estimateGas","params":[{"from":"0x11111D16485aa71D2f2BfFBD294DCACbaE79c1d4","to":"0x0B0C5E6c39195301D8922C89b873836b206A0d1e","data":"0x5d123e3f0000000000000000000000001abee930ed0fed631c7b5166b7686baa2ee9d69a000000000000000000000000ec7428cb95cd92e7556172ffbe735c6d48f6deb7000000000000000000000000000000000000000000000000000000000000ef5200000000000000000000000000000000000000000000000000000000000f4240000000000000000000000000000000000000000000000000000000000000000100000000000000000000000011111d16485aa71d2f2bffbd294dcacbae79c1d4"}, "latest"],"id":1,"jsonrpc":"2.0"}'
```

#### 3. success on the actual transaction

https://hashscan.io/testnet/transaction/1701200806.005115507

**Comment by mshakeg** [comment]
Interestingly if I specify a high gas limit override for the `eth_call` in [this comment](https://github.com/hashgraph/hedera-mirror-node/issues/7272#issuecomment-1830838927) it works:

```shell
curl https://testnet.hashio.io/api \
  -X POST \
  -H "Content-Type: application/json" \
  --data '{"method":"eth_call","params":[{"from":"0x11111D16485aa71D2f2BfFBD294DCACbaE79c1d4","to":"0x0B0C5E6c39195301D8922C89b873836b206A0d1e",
  "gas":"0x4c4b40",
  "data":"0x5d123e3f0000000000000000000000001abee930ed0fed631c7b5166b7686baa2ee9d69a000000000000000000000000ec7428cb95cd92e7556172ffbe735c6d48f6deb7000000000000000000000000000000000000000000000000000000000000ef5200000000000000000000000000000000000000000000000000000000000f4240000000000000000000000000000000000000000000000000000000000000000100000000000000000000000011111d16485aa71d2f2bffbd294dcacbae79c1d4"}, "latest"],"id":1,"jsonrpc":"2.0"}'
```

**Comment by mshakeg** [comment]
I can also now confirm that specifying a high gas limit for the original `eth_call` of this issue also fixes this issue. So I suppose this could be fixed at the Hedera relay by specifying the max 8m gas if an `eth_call` does not specify the `gas`, though ideally I think it should be fixed at the mirror node.

**Comment by 0xivanov** [comment]
@mshakeg can you provide the source code for `0x0B0C5E6c39195301D8922C89b873836b206A0d1e` . It seems like it does not have the multiCall signature.

**Comment by mshakeg** [comment]
Hey @0xivanov the `UniswapInterfaceMulticall#multicall` is for the transaction outlined in the initial issue description so the `UniswapInterfaceMulticall` is `0x7a3bf3ee39af554555f3c15d69cf253e6910d04c`.

`0x0B0C5E6c39195301D8922C89b873836b206A0d1e` is for another contract and the call in [this comment](https://github.com/hashgraph/hedera-mirror-node/issues/7272#issuecomment-1830838927) is to a different function with the signature:

```solidity
function forwardDepositToICHIVault(address, address, address, uint256, uint256, address) external returns (uint256 vaultTokens);
```

**Comment by mshakeg** [comment]
@0xivanov I just approved an allowance to make the issue replicable on testnet:

#### failure on eth_call

```shell
curl https://testnet.hashio.io/api \
  -X POST \
  -H "Content-Type: application/json" \
  --data '{"method":"eth_call","params":[{"from":"0x11111D16485aa71D2f2BfFBD294DCACbaE79c1d4","to":"0x0B0C5E6c39195301D8922C89b873836b206A0d1e","data":"0x5d123e3f0000000000000000000000001abee930ed0fed631c7b5166b7686baa2ee9d69a000000000000000000000000ec7428cb95cd92e7556172ffbe735c6d48f6deb7000000000000000000000000000000000000000000000000000000000000ef5200000000000000000000000000000000000000000000000000000000000f4240000000000000000000000000000000000000000000000000000000000000000100000000000000000000000011111d16485aa71d2f2bffbd294dcacbae79c1d4"}, "latest"],"id":1,"jsonrpc":"2.0"}'
```

#### success on eth_call provided gas is specified

```shell
curl https://testnet.hashio.io/api \
  -X POST \
  -H "Content-Type: application/json" \
  --data '{"method":"eth_call","params":[{"from":"0x11111D16485aa71D2f2BfFBD294DCACbaE79c1d4","to":"0x0B0C5E6c39195301D8922C89b873836b206A0d1e",
  "gas":"0x4c4b40", "data":"0x5d123e3f0000000000000000000000001abee930ed0fed631c7b5166b7686baa2ee9d69a000000000000000000000000ec7428cb95cd92e7556172ffbe735c6d48f6deb7000000000000000000000000000000000000000000000000000000000000ef5200000000000000000000000000000000000000000000000000000000000f4240000000000000000000000000000000000000000000000000000000000000000100000000000000000000000011111d16485aa71d2f2bffbd294dcacbae79c1d4"}, "latest"],"id":1,"jsonrpc":"2.0"}'
```

This contract call does a multiplicity of nested calls to other contracts some of which aren't deployed by me which you can verify by observing the call trace of [this transaction](https://hashscan.io/testnet/transaction/1701200806.005115507). I could try to replicate the issue on a local node, but I don't have the time.

**Comment by mshakeg** [comment]
Hey @0xivanov I just wanted to follow up on the progress of this issue. As shown [here](https://github.com/hashgraph/hedera-mirror-node/issues/7272#issuecomment-1833512905) the issue can be replicated on testnet.

**Comment by 0xivanov** [comment]
Thank you for checking in on the issue's progress. Replicating the problem on a local node for debugging has proven challenging, as it appears to be intricately tied to the testnet state of the tokens used.

To better understand and resolve the issue, we are exploring the option of creating a shadow fork of the testnet state to mimic the token states and setup. However, this task is complex and time-consuming.

**Comment by mshakeg** [comment]
@0xivanov I see, I guess a short term fix would be to just use the max gas limit that the mirror node supports if a gas limit isn't provided in the request?

**Comment by mshakeg** [comment]
@0xivanov `0x0B0C5E6c39195301D8922C89b873836b206A0d1e` is very similar to [0.0.6804129](https://hashscan.io/testnet/contract/0.0.6804129)

**Comment by 0xivanov** [comment]
Only [0.0.6804129](https://hashscan.io/testnet/contract/0.0.6804129) is verified, but is guess it will do the job. Verification for 0x0B0C5E6c39195301D8922C89b873836b206A0d1e could be helpful too.

**Comment by mshakeg** [comment]
@0xivanov yes, but it's basically the same source code with a few minor changes. I don't recall the exact commit that was used to deploy `0x0B0C5E6c39195301D8922C89b873836b206A0d1e` so it won't be as easy to get verified.

**Comment by 0xivanov** [comment]
Hey @mshakeg , is the does the sender have approved allowance right now, because `eth_call` is failing with `SafeERC20: low-level call failed` when i don't specify gas.
Weirdly it passes if I specify gas bigger than the estimated which is around 1m. The default gas is 15m if this parameter is not set in the req body, so this behaviour is very confusing to me.

**Comment by mshakeg** [comment]
Hey @0xivanov are you referring to the 2 calls [here](https://github.com/hashgraph/hedera-mirror-node/issues/7272#issuecomment-1833512905)? If so the behaviour is still the same i.e. the eth_call that doesn't specify `gas` fails, but the `eth_call` that does specify it does not fail.

**Comment by 0xivanov** [comment]
Can you try these call here : https://testnet.mirrornode.hedera.com/api/v1/docs/#/contracts/contractsCall

**Comment by 0xivanov** [comment]
With this request body
```json
{
  "block": "latest",
  "data": "0x5d123e3f0000000000000000000000001abee930ed0fed631c7b5166b7686baa2ee9d69a000000000000000000000000ec7428cb95cd92e7556172ffbe735c6d48f6deb7000000000000000000000000000000000000000000000000000000000000ef5200000000000000000000000000000000000000000000000000000000000f4240000000000000000000000000000000000000000000000000000000000000000100000000000000000000000011111d16485aa71d2f2bffbd294dcacbae79c1d4",
  "estimate": false,
  "from": "0x11111D16485aa71D2f2BfFBD294DCACbaE79c1d4",
  "to": "0x0B0C5E6c39195301D8922C89b873836b206A0d1e"
}
```
it seems to return proper response..

**Comment by mshakeg** [comment]
@0xivanov strangely both work for me if making the request directly to the mirror node as opposed to via the relay.

succeeds if gas is provided:
```shell
curl -X 'POST' \
  'https://testnet.mirrornode.hedera.com/api/v1/contracts/call' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "block": "latest",
  "data": "0x5d123e3f0000000000000000000000001abee930ed0fed631c7b5166b7686baa2ee9d69a000000000000000000000000ec7428cb95cd92e7556172ffbe735c6d48f6deb7000000000000000000000000000000000000000000000000000000000000ef5200000000000000000000000000000000000000000000000000000000000f4240000000000000000000000000000000000000000000000000000000000000000100000000000000000000000011111d16485aa71d2f2bffbd294dcacbae79c1d4",
  "estimate": false,
  "from": "0x11111D16485aa71D2f2BfFBD294DCACbaE79c1d4",
  "gas": 5000000,
  "gasPrice": 100000000,
  "to": "0x0B0C5E6c39195301D8922C89b873836b206A0d1e",
  "value": 0
}'
```

also succeeds if gas is not provided:

```shell
curl -X 'POST' \
  'https://testnet.mirrornode.hedera.com/api/v1/contracts/call' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "block": "latest",
  "data": "0x5d123e3f0000000000000000000000001abee930ed0fed631c7b5166b7686baa2ee9d69a000000000000000000000000ec7428cb95cd92e7556172ffbe735c6d48f6deb7000000000000000000000000000000000000000000000000000000000000ef5200000000000000000000000000000000000000000000000000000000000f4240000000000000000000000000000000000000000000000000000000000000000100000000000000000000000011111d16485aa71d2f2bffbd294dcacbae79c1d4",
  "estimate": false,
  "from": "0x11111D16485aa71D2f2BfFBD294DCACbaE79c1d4",
  "gasPrice": 100000000,
  "to": "0x0B0C5E6c39195301D8922C89b873836b206A0d1e",
  "value": 0
}'
```

**Comment by 0xivanov** [comment]
Maybe the relay does some logic that breaks the `gasLimit` field. I cannot debug this unfortunately to check it, because it is on testnet. Have to sync with the relay colleagues for this.

**Comment by mshakeg** [comment]
@0xivanov seems likely, the relay probably defaults to an insufficient gas limit if gas is specified for an `eth_call`

**Comment by 0xivanov** [comment]
Hey @mshakeg
We found the issue in the relay codebase. Here is the corresponding ticket https://github.com/hashgraph/hedera-json-rpc-relay/issues/2050
I will close this issue, we can continue over there if needed.
