### ISSUE TITLE
Possible Regression on `0.93.0-rc` deployed on `previewnet`

### ISSUE THREAD

**Issue by AlfredoG87** [hashgraph/hedera-mirror-node#7284]
### Description

When doing certain `eth_call` requests the mirror node is returning `INVALID_TRANSACTION` error, this is only happening on `previewnet` and not `testnet` or `mainnet`

### Steps to reproduce

Run the following snippet:

```
curl --location 'https://previewnet.mirrornode.hedera.com/api/v1/contracts/call' \
--header 'Content-Type: application/json' \
--data '{
    "from": "0x123f379429c8876036a200a39ef3b1ae0e339780",
    "value": 0,
    "gasPrice": 0,
    "to": "0xc0e9a3b52a049097cf9e76c85a0419c4378583c1"
}'
```

**Response:**
```
{
    "_status": {
        "messages": [
            {
                "message": "INVALID_TRANSACTION",
                "detail": "",
                "data": ""
            }
        ]
    }
}
```

### Additional context

Run the following snippet on testnet and it will work:

```
curl --location 'https://testnet.mirrornode.hedera.com/api/v1/contracts/call' \
--header 'Content-Type: application/json' \
--data '{
    "from": "0x123f379429c8876036a200a39ef3b1ae0e339780",
    "value": 0,
    "gasPrice": 0,
    "to": "0xc0e9a3b52a049097cf9e76c85a0419c4378583c1"
}'
```

**Result**
```
{
    "result": "0x"
}
```

### Hedera network

previewnet

### Version

v0.93.0-rc1

### Operating system

None

**Comment by steven-sheehy** [comment]
Believe this was an intentional change to return INVALID_TRANSACTION like consensus nodes when there is no runtime bytecode. See https://github.com/hashgraph/hedera-mirror-node/pull/7203
