### ISSUE TITLE
Bump Node.js from 18 to 21

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-mirror-node#7334]
### Problem

We attempted to upgrade Node.js from 18 to 20 but it had some performance regressions. Supposedly 21 has some performance improvements to stream processing that may help.

### Solution

* Bump Node.js to 21
* Build an image and run k6 performance tests against it
* If still slow, investigate why and make necessary adjustments

### Alternatives

Bump to 20 and investigate why it's slow

**Comment by mgoelswirlds** [comment]
v0.96.0 mirror node was tested with node 21.5 , but the k6 test results were really bad. Attaching the spreadsheet link [here](https://docs.google.com/spreadsheets/d/1aL57QhjdPy-D97P0-9384ggeHdy_C8GoK-KRTAiPZtM/edit?usp=sharing)
Closing this ticket for now.
