### ISSUE TITLE
Implement integration and acceptance tests covering opcode tracer

### ISSUE THREAD

**Issue by IvanKavaldzhiev** [hashgraph/hedera-mirror-node#7341]
### Problem

We need to validate that the new REST API `/api/v1/contracts/results/{transactionIdOrHash}/opcodes` works correctly with all type of parameters and values.

### Solution

Implement integration and acceptance tests that are configurable and could be disabled. This would be needed since they would be time consuming and put load on different environments.

They need to cover all type of optional parameters that can be send to the request. This include having `stack`, `memory` and `storage` flags turned on and the output should be expected for containing the different sections.

After validating everything works as expected, we can enable the REST endpoint.

**Comment by bibitibooo1** [comment]
For Q2
