### ISSUE TITLE
Marketplace: Helm Deployer image

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-mirror-node#736]
**Problem**
Google Cloud Marketplace requires a [Helm deployer image](https://github.com/GoogleCloudPlatform/marketplace-k8s-app-tools/blob/master/docs/building-deployer-helm.md) to be created to manage deployments.

**Solution**
Create the helm deployer image
- [x] Folder structure
- [x] schema.yaml
- [x] Dockerfile
- [x] Automate image building

**Alternatives**

**Additional Context**

**Comment by Nana-EC** [comment]
Initially I thought this issue would have been partially addressed by #740 but looking back I made progress enough to address the main asks of the ticket. Other tickets can be opened to address bugs related to the cluster operations
