### ISSUE TITLE
Inaccurate Display of Pending Rewards on Mirror Node

### ISSUE THREAD

**Issue by mgarbs** [hashgraph/hedera-mirror-node#7369]
### Description

The Blade team encountered an issue where the pending rewards on the mirror node consistently display as zero if the account has claimed or restaked since the 9th of December (if this hasn't happened, the pending reward will just be inaccurate). The discrepancy arises because the pending rewards, although present, are not reflected accurately in the user interface.

**Expected Behavior:**
The mirror node should accurately display the pending rewards at all times, providing users with correct and up-to-date information about their earnings.

**Actual Behavior:**
The pending rewards are shown as zero or are inaccurate, despite the fact that users are earning rewards. This issue leads to confusion and potential mistrust in the system.

### Steps to reproduce

1. Observe the rewards displayed on the mirror node for an account that has claimed or restaked since the 9th (if they haven't done this then the pending reward wont show 0 but wont be accurate either.)
2. Notice that the account shows zero rewards available for claiming. (supporting pic shows inaccurate reward)
3. Re-stake or transfer hbar to the account.
4. Observe that rewards are then distributed, contradicting the initial display of zero rewards.

### Additional context
Pic related (again pending reward is not accurate):
![image](https://github.com/hashgraph/hedera-mirror-node/assets/101222532/882718a3-b67e-4288-8148-c3711f7b5f73)

### Hedera network

mainnet

### Version

v0.93.1

### Operating system

None

**Comment by Liebenfiels** [comment]
I logged that bug there https://github.com/hashgraph/hedera-mirror-node-explorer/issues/794

I think the % reward dropped so low 1.03% per year and code is not expected to do calculation correct on such low % value per day

Maybe you need higher longer decimal space precision as you have very low 1.03 % reward per year /365 and per day it is 0.0028%, maybe is rounded to two deciman spaces in calculations and round as 0.00.
Rounding error, double precision needed maybe in total calculations

**Comment by Liebenfiels** [comment]
The explanation is as:
- if you claimed reward and restarted Pending to 0, it stays 0 now as most likely error in calculation cannot compute on such low % values now since drop to 1.03% per year or 0.00282% per day.
- if you have not claimed in past days it shows old Pending balance and simply does not add more Hbar to old balance, hence it is discrepancy.

**Comment by steven-sheehy** [comment]
This has now been fixed and deployed to mainnet.
