### ISSUE TITLE
DAPPS NOT WORKING FOR IOS USERS

### ISSUE THREAD

**Issue by Cazaubo** [hashgraph/hedera-mirror-node#7389]
### Description

Dapps are not connecting on hashpack wallet for iOS users

### Steps to reproduce

Connect to dapps on iOS

### Additional context

None

### Hedera network

mainnet

### Version

9.3.1

### Operating system

Other

**Comment by steven-sheehy** [comment]
There's not enough info in this ticket to act upon. Have you checked with hashpack about any wallet problems you may be having?

**Comment by steven-sheehy** [comment]
Closing as not enough detail and not mirror node related.
