### ISSUE TITLE
Investigate and optimize auto vacuum settings

### ISSUE THREAD

**Issue by xin-hedera** [hashgraph/hedera-mirror-node#7422]
### Description

Importer record file parsing duration spikes when ingesting extremely large record files with > 50k HCS topic messages in perfnet, temporarily disabling autovacuum on `topic_message` table can reduce the time to less than 2 seconds, however with certain cloudsql instances it doesn't help at all.

On the other side, the current autovacuum settings for most insert only tables are tuned for balanced writes and reads, we need to investigate the impact to database reads if we need to change the settings to favor writes over reads. 

### Steps to reproduce

1. Restore the database from a recent backup before the TPS spike
2. Run importer and observe parsing duration when it starts to ingest large record files

### Hedera network

other

### Version

v0.95.0-SNAPSHOT

### Operating system

None

**Comment by steven-sheehy** [comment]
We now believe this is due to a CPU config change that did not grant the importer enough CPU to handle the transaction spike in testnet. This has since been re-configured correctly.
