### ISSUE TITLE
Test EntityStake Repository In V2

### ISSUE THREAD

**Issue by jnels124** [hashgraph/hedera-mirror-node#7432]
### Problem

We have updated temp table logic to include temp tables as real tables in a different schema. During this process entity_stake_temp was not created here as there is special handling of that temp table due to it being created by the repository query. 

We need to performance test in v2 to determine if this logic should be updated.

### Solution

If v2 performance regression is determined, we should convert this logic to create the temporary table in the new schema and distribute accordingly.

**Comment by xin-hedera** [comment]
close the ticket since we have implemented the improvements in the linked PR
