### ISSUE TITLE
Default topicRunningHashV2AddedTimestamp

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-mirror-node#745]
**Problem**
You can't run 0.11.x or master without specifying `topicRunningHashV2AddedTimestamp`. We've had a user in discord, ops team and our own team experience this issue. 

**Solution**
Testnet has been deployed and mainnet deployment has a date. We should incorporate the logic to hardcode the field to the known/expected dates. Logic should be:

- If network is Mainnet, use estimated mainnet date (we can tweak later if it changes)
- Else use actual testnet date

It's fine to use testnet for pre-prod as we don't know the actual date and don't care about exact data accuracy

**Alternatives**
- Keep empty

**Additional Context**

**Comment by apeksharma** [comment]
Value for testnet is `1588706343553042000`
From query: `SELECT consensus_timestamp FROM topic_message WHERE running_hash_version = 2 ORDER BY consensus_timestamp ASC LIMIT 1;`

**Comment by apeksharma** [comment]
After #763 is merged in, we'll put this one back in backlog since mainnet value needs to be updated too.

**Comment by steven-sheehy** [comment]
Fixed by #763
