### ISSUE TITLE
Solidity revert string decodes not working as expected on verified contract

### ISSUE THREAD

**Issue by littletarzan** [hashgraph/hedera-mirror-node#7484]
### Description

For verified contracts, it appears that require statements that revert with a string are not decoded properly in the hashscan interface. We expect that a smart contract reverting on a solidity require statement: `require(1 ==0, 'abcd')` should render 'abcd' in hashscan as the error reason

### Steps to reproduce

Call a verified smart contract that reverts using a require statement.

### Additional context

An example of a transaction we suspect should revert with a string:
https://hashscan.io/mainnet/transaction/1704390315.881373003

Line where suspected revert occurs in the smart contract:
https://github.com/saucerswaplabs/saucerswap-periphery/blob/1f0e50ef94dee14dc616bfe4bf5315029f21c18e/contracts/UniswapV2Router02.sol#L48

Another example on testnet where a smart contract calls another smart contract, resulting in a revert (note that the string is decoded in the call trace on page 3):
https://hashscan.io/testnet/transaction/1704318176.839930003

### Hedera network

mainnet, testnet

### Version

latest

### Operating system

macOS

**Comment by svienot** [comment]
This issue was actually intended for the explorer project and is now tracked there as [#829](https://github.com/hashgraph/hedera-mirror-node-explorer/issues/829)

**Comment by steven-sheehy** [comment]
Will close since it's tracked by hashscan. Can re-open if we find mirror node is at fault.
