### ISSUE TITLE
Design: Change the structure of the hedera-mirror-web3 module - entirely perf improvement

### ISSUE THREAD

**Issue by bibitibooo1** [hashgraph/hedera-mirror-node#7557]

**Comment by steven-sheehy** [comment]
We should have some details in this ticket. Is it related to https://github.com/hashgraph/hedera-mirror-node/issues/7566?

**Comment by bibitibooo1** [comment]
Yes, it's related, that's the work package. I'll move this architecture task to done. Thanks for bringing it up!

**Comment by steven-sheehy** [comment]
This design work is completed as noted above.
