### ISSUE TITLE
Add Topic ID and SeqNum to Transaction API

### ISSUE THREAD

**Issue by apeksharma** [hashgraph/hedera-mirror-node#756]
Kabuto returns both topicId and sequenceNumber in its `/transactions` api. Ask came from customer if we can do the same.

It'll require following:
- For topicId: Joining with `t_entities` table.
  Since there's another task (which is to be done soon) to denormalize entities' information into transactions table, it's better if we do this change after denormalization.
- For sequenceNumber: Joining with `topic_message` table

Outstanding questions:
- How do we encapsulate this information in response?
  For TopicId
  Option 1: `topicId`.  Extending this to other types would lead to adding 'contractId', 'fileId', 'accountId' fields too.
  Option 2: `entityId` : Agnostic to type of entity.
  For sequenceNumber:
  Option 1: Add it to top level. Extending this to other fields (and for other txn types) will lead to a lot of fields (and ugly?)
  Option 2: Encapsulate fields by entity or transaction type.

**Comment by apeksharma** [comment]
See comments in #720 for some more details.

**Comment by Nana-EC** [comment]
The current mirror node addresses this in part with 

1. the existence of the `/api/v1/topics/messages/{consensusTimestamp}` endpoint. Using this customers can get the topic and sequence numbers using the consensustimestamp of the transaction.
2. the presence of the `entity_id` value in transaction response which represents the topic_number for transactions of type `CONSENSUSSUBMITMESSAGE`

Additionally, we don't want to continue to bloat the `/api/v1/transactions` endpoint, but rather have entity specific transaction information be provided in less general API endpoints e.g. `/api/v1/(accounts|balances|tokens|topics|schedules).
