### ISSUE TITLE
Add EVM v046 version in `hedera-mirror-web3`

### ISSUE THREAD

**Issue by IvanKavaldzhiev** [hashgraph/hedera-mirror-node#7560]
## Definition

As part of the effort to achieve full Ethereum equivalence, a new EVM version v046 is created in this [PR](https://github.com/hashgraph/hedera-services/pull/9628) with relaxed validations for the address used as:

- receiver in top-level and internal EVM calls
- address of contract to load code for
- and balance operations

Following this change, we should adapt the new v046 EVM version also in `hedera-mirror-web3`, so that the mirror archive node is compliant with the consensus node behaviour. This would require copying of the necessary `hedera-services` code components.

## Code Changes Overview

1. Create a new 046 EVM version by creating a new bean in EvmConfiguration
2. Override the AbstractLedgerEvmWorldUpdater [getOrCreate](https://github.com/hashgraph/hedera-services/blob/c93989a07e85e8f30467120f581b2e277f60f266/hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/store/contracts/AbstractLedgerEvmWorldUpdater.java#L98) method that Besu [calls](https://github.com/hyperledger/besu/blob/be5cc68b6069ca2f718d08c95994e1a764576391/evm/src/main/java/org/hyperledger/besu/evm/processor/MessageCallProcessor.java#L109) internally for each receiver when it starts executing a new message frame
    a. In [AbstractLedgerWorldUpdater](https://github.com/hashgraph/hedera-services/blob/c93989a07e85e8f30467120f581b2e277f60f266/hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/AbstractLedgerWorldUpdater.java#L135), add logic to create a ghost account in case we know we won't be persisting the account
3. Copy the needed op codes outside of the ones defined in `hedera-evm` from `hedera-mono-service` to `hedera-mirror-web3` (inside `com.hedera.services` package)
4. Update `hedera-evm` version to 0.46.0
5. Make sure we cover the updated journaled EVM configuration that was done in services in this [PR](https://github.com/hashgraph/hedera-services/pull/11171).

## Abstract

Hedera’s EVM implementation will diverge from the Ethereum specification in order to handle operations on system accounts differently. EVM operations that work in any way with addresses include all `Call` operations, the `SelfDestruct` operation, `Balance` operation, and all `ExtCode` operations.

## Motivation

Ethereum addresses 0x0 → 0x3E8 map to Hedera IDs 0.0.0 → 0.0.1000. 

When a call is made to an address, the EVM loads the corresponding code belonging to the contract with Hedera ID mapping to the EVM address that was called.

Ethereum addresses 0x1 → 0x9 are special addresses on which precompiled contracts exist. For example, the Solidity language keyword `ecrecover` is “sugar syntax” which compiles to a `call` to address `0x1`. More information [here](https://www.evm.codes/precompiled).
Hedera IDs in the range 0.0.1 → 0.0.1000 are reserved for “system” accounts. Some of them exist today - for example the genesis account, the fee collecting account, etc - and more can be created in the future.

## Rationale

We need to align mirror node and consensus node behaviour related to operations, which use system accounts. This would guarantee that users have seamless experience and observe the same behaviour from both nodes.

## Backwards Compatibility

We introduce a new EVM version and would continue support of the existing ones, so no backward compatibility issues should be expected.

## Security Implications

None

## References & Dependencies

[PR9628](https://github.com/hashgraph/hedera-services/pull/9628) removal of address validity checks for top-level EVM calls 
```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/7697
```

**Comment by steven-sheehy** [comment]
Fixed via https://github.com/hashgraph/hedera-mirror-node/pull/7749
