### ISSUE TITLE
Web3 service Intermittently return mixed up values with `/contracts/call` when making requests in quick succession

### ISSUE THREAD

**Issue by thusaras-vc** [hashgraph/hedera-mirror-node#7572]
### Description

When making two separate calls to `/api/v1/contracts/call` rapidly, sometimes the results from one call is returned as the result of the second call. In the below examples, we're invoking the `decimals()` method on the ERC-20 token contract, so we expect a static unchanging value to be returned each time, but occasionally this would not be true.

### Steps to reproduce

Option-1: Directly
The following python script runs two threads: 
- each repeatedly making a post request to `/api/v1/contracts/call`
- Thread-1 expects an '8' returned, and Thread-2 expects an '6'. 
- At random times Thread-1 could receive a '6', and vice versa.

Python script: https://gist.github.com/thusaras-vc/879e4fe7fd022e3aa299710714b07d17

Option-2: Through JSON RPC Relay
- Same as above, but this one targets the JSON RPC Relay (and is written in typescript)
- From the [JSON RPC list](https://docs.hedera.com/hedera/tutorials/more-tutorials/json-rpc-connections), this has not been reproducible against the Hashio endpoint, but it happens for Arkhia and ValidationCloud endpoints

TypeScript script: https://gist.github.com/thusaras-vc/710cf6416d9dc2ab83c2fd401de6809d

### Additional context

```bash
...
...
SAUCE matched 6 vs 6
WHBAR matched 8 vs 8
WHBAR matched 8 vs 8
SAUCE matched 6 vs 6
SAUCE matched 6 vs 6
WHBAR matched 8 vs 8
SAUCE mismatch decimal 8 vs 6!
```

### Hedera network

mainnet

### Version

0.96.0

### Operating system

Linux

**Comment by steven-sheehy** [comment]
The script references localhost so I'm not sure what you have running locally. Do you have a reproduction against previewnet or testnet we can use?

**Comment by thusaras-vc** [comment]
> The script references localhost so I'm not sure what you have running locally. Do you have a reproduction against previewnet or testnet we can use?

only a mainnet example for now, this setup uses the [docker compose file](https://github.com/hashgraph/hedera-mirror-node/blob/main/docker-compose.yml), and `localhost:8545` is pointing to the `hedera-mirror-web3:0.96.0` image, which is linked to a postgres DB

**Comment by kasey-alusi-vcc** [comment]
Hey @kselveliev is there additional detail you need from us to triage this?

**Comment by kselveliev** [comment]
Hi @kasey-alusi-vcc, no need for additional info, ty. I was able to reproduce the problem but it’s a bit tricky to find the root cause of it, I will have to spend some more time on it.
