### ISSUE TITLE
Create and implement a test plan for direct calls towards Ethereum precompiles

### ISSUE THREAD

**Issue by georgi-l95** [hashgraph/hedera-mirror-node#7609]
Create and implement a test plan for direct calls towards Ethereum precompiles: 

- Calling each of the precompile addresses with correct input should result in correct output.
- Calling each of the precompile addresses with incorrect input should result in revert.
- Estimate gas each of the precompile addresses with the correct input should result in gas estimation.
- Estimate gas each of the precompile addresses with the incorrect input should result in revert reason.

**Comment by steven-sheehy** [comment]
I think we should do this in the web3 module and not as acceptance tests. Acceptance is not meant for exhaustive testing.

**Comment by georgi-l95** [comment]
Yeah, your right. I've placed the wrong label. E2E can be done as well in other repos like hedera-smart-contracts.
