### ISSUE TITLE
Mirror Importer SSL support

### ISSUE THREAD

**Issue by exodus-justinz** [hashgraph/hedera-mirror-node#7620]
### Problem

Do we have any plans on supporting SSL on importer, the same way we do with the rest API?

For context, we want to improve our security in general and one way to do this is to require SSL on db connections.

### Solution

-

**Comment by steven-sheehy** [comment]
It should already be supported via the underlying libraries, though we haven't tested it. Spring boot has nice ssl support via its [ssl bundles](https://spring.io/blog/2023/06/07/securing-spring-boot-applications-with-ssl/) for everything except jdbc unfortunately. For jdbc, you have to set the ssl connection [properties](https://jdbc.postgresql.org/documentation/use/#connection-parameters/) in the `spring.datasource.url`.

**Comment by exodus-justinz** [comment]
is there a way to set the SSL config now on importer?

**Comment by steven-sheehy** [comment]
See above where i mention to set it in the url

**Comment by exodus-justinz** [comment]
ok... we set the config via environment variables. so does that mean using `SPRING_DATASOURCE_USESSL=true` will work since we can use spring config?

**Comment by steven-sheehy** [comment]
No, you set the aforementioned property to something with the appropriate jdbc ssl config [parameters](https://jdbc.postgresql.org/documentation/use/#connection-parameters/) e.g. `SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/mirror_node?ssl=true&sslmode=require&.....`

**Comment by exodus-justinz** [comment]
We have a script to set the jdbc url and unset the db host, port, and db name to test this
```sh
export SPRING_DATASOURCE_URL=jdbc:postgresql://mirror-node-db:5432/mirror_node

unset HEDERA_MIRROR_IMPORTER_DB_HOST
unset HEDERA_MIRROR_IMPORTER_DB_PORT
unset HEDERA_MIRROR_IMPORTER_DB_NAME

## Start application
java org.springframework.boot.loader.launch.JarLauncher
```

But upon running it, we encounter this error message
```
2024-01-29T04:31:46.804Z ERROR main c.z.h.p.HikariPool HikariPool-1 - Exception during pool initialization. org.postgresql.util.PSQLException: Connection to 127.0.0.1:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
```
