### ISSUE TITLE
Token Account Upserter V2 Performance

### ISSUE THREAD

**Issue by jnels124** [hashgraph/hedera-mirror-node#7669]
### Problem

While ingesting mainnet data in v2, token account upserter is to slow. It averages about 100ms to insert a single or very few rows.

### Solution

The problem is caused by the join on token. Without the join on token, the time to insert drops to 20-30ms  We need a way to optimize to get rid of the join or construct in an efficient manner.

**Comment by xin-hedera** [comment]
We can get rid of the join in token account upsert, and set token account relationship kyc_status / freeze_status to a token's default when needed on read for rest api `/api/v1/account/:idOrAliasOrEvmAddress/tokens`

- Change token_account schema to make `freeze_status` and `kyc_status` nullable without default
- Remove the join in the token account upsert SQL, potentially get rid of the custom `TokenAccountUpsertQueryGenerator` bean and directly use the upsert template. However pay attention to not copy `freeze_status` / `kyc_status` from a previous dissociated token account relationship to a new one
-  In rest api `TokenController.getTokenRelationships`, query and cache token's default freeze / kyc status for token account with `null` freeze / kyc status
