### ISSUE TITLE
Update timestamp description on Open API to be more clear on expected format

### ISSUE THREAD

**Issue by a-ridley** [hashgraph/hedera-mirror-node#7754]
### Problem

When working with the swagger API documentation to get the state of a smart contract, I came across needing a timestamp in seconds.nanoseconds format. When going to hash scan, the timestamp was given in local time (which is valid), but nowhere could I find an easy way to convert it to what the mirror node was expecting. It took me a bit of asking around to figure out i could give a UNIX timestamp. 
![image (3)](https://github.com/hashgraph/hedera-mirror-node/assets/18725916/800bf838-e26f-4d9f-aba1-b8eee114f489)

### Solution

Other devs may experience a similar thing as me and was hoping we could update the swagger api docs where there is a timestamp section to be a bit more clear on what the mirror node expects the timestamp in. Reading seconds.nanoseconds format is not very clear. In addition, adding a tip on how to get a timestamp in that format would be great.

**Comment by xin-hedera** [comment]
We should ask hashscan to add a tooltip to show the consensus timestamp returned by mirrornode rest api. It's not just that converting the local time to consensus timestamp is not straightforward, but also the local time shown on hashscan only has 4 digits after the decimal point.

**Comment by a-ridley** [comment]
@xin-hedera I can go ahead and ask. Thanks!
