### ISSUE TITLE
Refactor isValidContractResult in ContractResultServiceImpl

### ISSUE THREAD

**Issue by konstantinabl** [hashgraph/hedera-mirror-node#7759]
### Problem

After this [fix](https://github.com/hashgraph/hedera-services/issues/9149 ) and this [fix](https://github.com/hashgraph/hedera-services/pull/11045) in services the isValidContractFunctionResult always returns true. It is a good idea to check the class and this function in particular and possibly remove the check or adjust it.

### Solution

- Enhance the isValidContractFunctionResult check

**Comment by steven-sheehy** [comment]
Don't think we need this ticket. It doesn't matter if consensus nodes have improved their logic and will always send a function result. Mirror nodes have to support the full history of transactions so since in the past it was not present it should stay. Unless I'm missing something?
