### ISSUE TITLE
transactions flag does not work in rest module's accounts endpoint 

### ISSUE THREAD

**Issue by isavov** [hashgraph/hedera-mirror-node#7779]
### Description

`/api/v1/accounts/{idOrAliasOrEvmAddress}`'s `transactions` flag does not work so a call using it instead throws:
 `"message": "Invalid parameter: transactions"`

Issue appears to have been caused by the refactoring in: https://github.com/hashgraph/hedera-mirror-node/pull/7503

### Steps to reproduce

1. Run the mirror-node rest component.
2. Try calling that endpoint (or opening the Swagger UI which shows the parameter is missing)

### Hedera network

other

### Version

main

### Operating system

None

**Comment by xin-hedera** [comment]
Can't reproduce, can you make sure you use either `/accounts/{id}/transactions=true` or `/accounts/{id}/transactions=false`?

**Comment by isavov** [comment]
> Can't reproduce, can you make sure you use either `/accounts/{id}/transactions=true` or `/accounts/{id}/transactions=false`?

I was getting this error running a locally built image in local node, but rebuilding can no longer reproduce, so it seems to have been some local/caching issue. Closing.
