### ISSUE TITLE
Invalid input data for `redirectForToken()` method in the HTS system contract

### ISSUE THREAD

**Issue by quiet-node** [hashgraph/hedera-mirror-node#7830]
## Problem
When calling the [/api/v1/contracts/{contractIdOrAddress}/results/{timestamp}](https://testnet.mirrornode.hedera.com/api/v1/docs/#/contracts/getContractResultByIdAndTimestamp) endpoint with `{contractIdOrAddress}` set to the HTS system contract address (0x167), the `function_parameters` field in the returned object appears to be an invalid EVM hex string. This `function_parameters` cannot be decoded using `ethers.Interface.decodeFunctionData()`.

## Example

Execute the following curl request:

```bash
curl --location 'https://testnet.mirrornode.hedera.com/api/v1/contracts/0x0000000000000000000000000000000000000167/results/1709231062.359357004'
```

In the returned object, examine the `function_parameters` field, which should resemble the hex string below:

```bash
"function_parameters":"0x618dc65e000000000000000000000000000000000035c72306fdde03"
```

However, attempting to decode this hex string using the `redirectForToken()` ABI and ethers.js Interface class will result in a `RangeError` exception.

```typescript
// Initialize interface for redirectForToken() method
const redirectForTokenInterface = new ethers.Interface([
  {
    inputs: [
      {
        internalType: 'address',
        name: 'token',
        type: 'address',
      },
      {
        internalType: 'bytes',
        name: 'encodedFunctionSelector',
        type: 'bytes',
      },
    ],
    name: 'redirectForToken',
    outputs: [
      {
        internalType: 'int64',
        name: 'responseCode',
        type: 'int64',
      },
      {
        internalType: 'bytes',
        name: 'response',
        type: 'bytes',
      },
    ],
    stateMutability: 'nonpayable',
    type: 'function',
  },
]);

try {
  redirectForTokenInterface.decodeFunctionData(
    'redirectForToken',
    "0x618dc65e000000000000000000000000000000000035c72306fdde03" // function_parameters
  );
} catch (err) { // A RangeError will be thrown
  console.log(err) // RangeError: data out-of-bounds (buffer=0x000000000000000000000000000000000035c72306fdde03, length=24, offset=32, code=BUFFER_OVERRUN, version=6.11.0)
}
```

## Relatable Issue
This problem is related to [issue #237 - Inconsistency between ABI and transaction](https://github.com/hashgraph/hedera-smart-contracts/issues/237) on the `hedera-smart-contracts` repository. 

Essentially, when a request is made to the `redirectForToken()` method, it first passes through a wrapper contract, which then relays the request to the HTS system contract. This results in two transactions: a "parent transaction" executed at the wrapper contract level, and a "child transaction" executed at the HTS system contract level. 

When calling the `/api/v1/contracts/{contractIdOrAddress}/results/{timestamp}` endpoint with the wrapper contract's contract ID, the `function_parameters` returned is a valid EVM hex string decodable by the `ethers.Interface` class. However, making the same call with the HTS system contract's contract ID yields the invalid hex string in question. 

To illustrate this inconsistency, I have put together a detailed unit test which can be found here [RedirectForToken Inconsistent Input Data Between System Contract And Regular Contract](https://github.com/hashgraph/hedera-smart-contracts/blob/redirectForToken()-returns-different-input-data/test/hts-precompile/redirect-inconsistent-data.js). This unit test highlights the inconsistency in input data between the system contract and regular wrapper contract.

### Steps to reproduce

Read `Example` section above

### Hedera network

mainnet, testnet, previewnet

### Version

latest

### Operating system

None

**Comment by xin-hedera** [comment]
This shouldn't be a mirrorrnode issue unless there is a feasible way for mirrornode to fix old function parameters in such contract call result. mirrornode persists function parameters from the corresponding transaction record contract call result (as defined in hedera protobufs) as is and show it in rest API.

**Comment by quiet-node** [comment]
Gotcha thanks @xin-hedera!
