### ISSUE TITLE
503 (Service Unavailable) error for some historical blocks contract calls

### ISSUE THREAD

**Issue by AlfredoG87** [hashgraph/hedera-mirror-node#7840]
### Description

During TheGraph Indexing process, the indexer node performs some `eth_call` requests, the Relay in turn translates the request to use the mirror node, however for certain historical blocks (the older the worse) the mirror-node takes around 10 to 12 seconds to reply with `503 Service Unavailable` Status Error Code.

Most of the times the timeout goes away with a couple of retries.

however some times it does not matter the amount of retries it seems like it always fails.

The older the block the more likely to take a long time and timeout.

### Steps to reproduce

Basically run any `contracts/call` for a contract using historical blocks (an old block), notice how the first time it takes quite a lot of time (sometimes timeouts and replies 503) and other.

But here is an example of one request that always fails, no matter how many retries.
```
{
    "to": "0x0000000000000000000000000000000000212711",
    "data": "0x70a08231000000000000000000000000000000000000000000000000000000000008aa2b",
    "estimate": false,
    "block": "0x2ce8b47"
}
```

Example 2:

```
{
    "to": "0x00000000000000000000000000000000002ebfe6",
    "data": "0x70a08231000000000000000000000000000000000000000000000000000000000011add5",
    "estimate": false,
    "block": "0x2fbe944"
}

```

### Hedera network

mainnet

### Version

v0.98.0

### Operating system

None

**Comment by AlfredoG87** [comment]
This call is trying to fetch the `name` of an HTS token using its ERC20 Interface. (This never changes) but using what I believe is a troublesome Block number:

I would say that any request using the specific `historical block number` = `0x3199357' will fail with `503`

Example 3:
```
{
    "data": "0x06fdde03",
    "to": "0x00000000000000000000000000000000000b2ad5",
    "estimate": false,
    "block": "0x3199357"
}
```

**Comment by steven-sheehy** [comment]
Here's the underlying error:
```
2024-03-04T17:38:21.240Z  WARN reactor-http-epoll-1 o.h.e.j.s.SqlExceptionHelper SQL Error: 0, SQLState: 57014 
2024-03-04T17:38:21.243Z ERROR reactor-http-epoll-1 o.h.e.j.s.SqlExceptionHelper ERROR: canceling statement due to statement timeout 
2024-03-04T17:38:21.294Z ERROR reactor-http-epoll-1 c.h.m.w.c.ContractController Query timed out: JDBC exception executing SQL [select count(*)
from (
    (
        select token_id
        from nft
        where account_id = ?
            and timestamp_range @> ?
            and deleted is not true
    )
    union all
    (
        select token_id
        from nft_history
        where account_id = ?
            and timestamp_range @> ?
            and deleted is not true
    )
) as n
join entity e on e.id = n.token_id
where (e.deleted is not true or lower(e.timestamp_range) > ?)
] [ERROR: canceling statement due to statement timeout] [n/a]; SQL [n/a] 
2024-03-04T17:38:21.301Z  INFO reactor-http-epoll-1 c.h.m.w.c.LoggingFilter POST /api/v1/contracts/call in 11249 ms: 503 SERVICE_UNAVAILABLE 
```
