### ISSUE TITLE
High number of database selected rows during 10K tps performance test

### ISSUE THREAD

**Issue by xin-hedera** [hashgraph/hedera-mirror-node#7861]
### Description

During canonical 10K tps performance test, the database metrics show a pattern of high number of selected rows at beginning of each contiguous period and high volume traffic, some last a couple of minutes and some last about an hour.

Note: the number of selected rows corresponds to `pg_stat_database.tup_fetched`

### Steps to reproduce

Check grafana importer dashboard for performance environment for time from 03/02/2024 02:00:00 to 03/02/2024 06:30:00. Set up importer and database to ingest data from the same period to reproduce.

### Hedera network

other

### Version

v0.100.0-SNAPSHOT

### Operating system

None

**Comment by steven-sheehy** [comment]
We don't see this behavior anymore.
