### ISSUE TITLE
Change rest-java DomainRecordMapper to reuse setters in EntityMetadataRegistry

### ISSUE THREAD

**Issue by xin-hedera** [hashgraph/hedera-mirror-node#7906]
### Problem

rest-java `DomainRecordMapper` use MethodHandle setters to map jooq `Record` objects to domain objects. `EntityMetadataRegistry` in `hedera-mirror-importer` already has the logic to lookup the setters. We should move `EntityMetadataRegistry` to the common module and let importer and rest-java use it.

### Solution

- Move `EntityMetadataRegistry` to `hedera-mirror-common`
- Change rest-java `DomainRecordMapper` to use setters from `EntityMetadataRegsitry` instead, make changes to the interface / implementation if needed

**Comment by steven-sheehy** [comment]
Closing for now. Requires more effort than it's worth. Effort that would be better spent converting it from reflection to a compile time mapping framework like mapstruct.
