### ISSUE TITLE
To package: Mirror Node Web3 Module Outstanding Items on perf ands observability

### ISSUE THREAD

**Issue by bibitibooo1** [hashgraph/hedera-mirror-node#7941]
- Ensure log and metrics exist around all call data size provided to inform future increases on this
- Ensure log and metrics exist around all gasLimits provided to inform future increases on this
- Perf testing on call data size at
- Perf testing on gasLimit at 30M and 50M
- Rate limiter by gas for aggregate per pod

**Comment by IvanKavaldzhiev** [comment]
#8017 - defined package
