### ISSUE TITLE
Add /file/{fileID}/ REST API endpoint to expose HFS metadata

### ISSUE THREAD

**Issue by Reccetech** [hashgraph/hedera-mirror-node#8029]
### Problem

**Problem**
Currently there is no API to get HFS file metadata. 
Getting HFS metadata might be useful for some customers for example to learn the size of a file before using the SDK to retrieve its contents.

### Solution

Add /file/{fileID}/ REST API endpoint to expose HFS file metadata
Information returned from this API call should match the results from the SDK File Info [Response](https://docs.hedera.com/hedera/sdks-and-apis/sdks/file-service/get-file-info)

- FileID
- Key(s)
- Size
- Expiration time
- Deleted
- Ledger ID
- Memo

### Alternatives

Don't add this API endpoint

**Comment by steven-sheehy** [comment]
Duplicates #6426
