### ISSUE TITLE
Update Docs operations.md to incorporate docker-compose scenario

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-mirror-node#803]
**Problem**
We are duplicating operational information in the top level README for the docker-compose flow when there's already a docs/operations.md with similar information for Linux server deployment. 

**Solution**
This information should be moved and merged into that doc.

**Alternatives**

**Additional Context**
Documentation is being created on docs.hedera.com that users of many different technical capabilities will be looking at. They will reference the this repo and where possible utilize its instructions or add. As such we need to make sure we have clear concise steps to make ramp up quickly

**Comment by steven-sheehy** [comment]
This was completed as part of https://github.com/hashgraph/hedera-mirror-node/pull/3104
