### ISSUE TITLE
Recover from account balance files with different timestamps

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-mirror-node#804]
**Detailed Description**
Twice on mainnet we have seen a scenario where a particular account balance signature is failing to verify. The logs will repeatedly print every polling period (30s):

```
c.h.m.i.d.b.AccountBalancesDownloader Signature verification failed for 2020-06-03T17_00_01.985229Z_Balances.csv_sig: {MISSING=[0.0.10, 0.0.12, 0.0.13, 0.0.14, 0.0.15, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.9], VERIFIED=[0.0.11]}
```

Investigation revealed one node had a balance file with a close, but slightly different timestamp for its filename than other nodes. In the above case, node 0.0.11 had `2020-06-03T17_00_01.985229Z_Balances.csv_sig` while every other node had `2020-06-03T17_00_00.672290001Z_Balances.csv_sig`.

**Actual Behavior**
Signature fails to verify

**Expected Behavior**
Importer should detect and recover from the scenario until main nodes can implement a permanent fix.

**Environment:**
- Java: OpenJDK 11.0.2
- OS: Ubuntu 18.04
- Version: v0.10.1

**Additional Context**

**Comment by steven-sheehy** [comment]
As intended by its current design, main nodes can occasionally generate balance files with slightly different timestamps and contents for the same time period. Each file is valid for that time, it is just differing from the others and should be ignored since it can never reach 1/3 consensus. See https://github.com/hashgraph/hedera-services/issues/248 for further discussion.

While record and event streams are guaranteed to be generated at the exact same timestamp for all nodes, it's still possible a malicious node could upload a corrupt or badly named file and halt mirror node processing. As a result, we can no longer group just based upon filename and we need to address the problem for all stream types.

To fix, we should wrap the existing logic that groups based upon filename and wrap it in an additional layer of grouping based upon an immutable object that represents an expected time range where those files would fall. To calculate the expected time range for files, first assume they're written at every interval `P` and the last valid file was at time `T`. We can calculate the expected time range for the next file should be within the range: `[T + P/2, T + P + P/2)`. We should verify all filenames within that time range and if any one of them reaches 1/3 consensus, it should be accepted. 

For example, given the following account balance files:

```
2020-06-03T16_45_00.000000000Z_Balances.csv_sig - all nodes
2020-06-03T17_00_00.000000000Z_Balances.csv_sig - all nodes but one
2020-06-03T17_00_01.000000000Z_Balances.csv_sig - one node
2020-06-03T17_15_00.000000000Z_Balances.csv_sig - all nodes
```

Given we know `P=15m` and `T=2020-06-03T16_45_00.000000000Z` we can calculate the time range as `[2020-06-03T16_52_30.000000000Z, 2020-06-03T17_07_30.000000000Z)`. Thus we would group `2020-06-03T17_00_00.000000000Z_Balances.csv_sig` and `2020-06-03T17_00_01.000000000Z_Balances.csv_sig` into the same group. Since `2020-06-03T17_00_00.000000000Z_Balances.csv_sig` is present for all nodes but one he would be accepted. Since `2020-06-03T17_00_01.000000000Z_Balances.csv_sig` is present for only one node he would be skipped.

**Comment by ksemaev** [comment]
I have the same behaviour I suppose:  just started the sync from 0 and got that loop:
`2020-07-23 10:00:56,188 INFO  [pool-6-thread-5] c.h.m.i.d.r.RecordFileDownloader Downloaded 40 signatures for node 0.0.6 in 213.9 ms
2020-07-23 10:00:56,200 INFO  [pool-6-thread-6] c.h.m.i.d.r.RecordFileDownloader Downloaded 40 signatures for node 0.0.4 in 226.2 ms
2020-07-23 10:00:56,202 INFO  [pool-6-thread-8] c.h.m.i.d.r.RecordFileDownloader Downloaded 40 signatures for node 0.0.3 in 226.5 ms
2020-07-23 10:00:56,241 INFO  [pool-6-thread-7] c.h.m.i.d.r.RecordFileDownloader Downloaded 40 signatures for node 0.0.5 in 266.0 ms
2020-07-23 10:00:56,241 INFO  [scheduling-2] c.h.m.i.d.r.RecordFileDownloader Downloaded 160 signatures in 267.7 ms (597/s)
2020-07-23 10:00:56,244 WARN  [scheduling-2] c.h.m.i.d.r.RecordFileDownloader Signature verification failed for 2019-10-11T16_39_35.154691Z.rcd_sig: {MISSING=[], PARSED=[0.0.3, 0.0.4, 0.0.5, 0.0.6]}`

**Comment by steven-sheehy** [comment]
This issue can only occur for account balances since their filename can vary. Record files by design cannot unless there's a rogue node in the system, which there is currently not since we're permissioned. So your issue is something else. It's failing when using the address book to verify the downloaded signature file. Your address book is probably bad. Try moving addressbook.bin elsewhere and restarting.

**Comment by ksemaev** [comment]
@steven-sheehy TY for advice! resync with empty storage did the trick, although I had to cleanup postgres as well. Please ignore this case then, let's hope it won't appear again. Just to be clear: can I cleanup local storage of the node at any time without touching PG? Or the content of PG database should be removed when I clenup storage on the node?

**Comment by steven-sheehy** [comment]
No, the two are related and should be cleaned up together. We store the state of what files on local storage have been downloaded and processed and we also maintain an address book on the local storage that is updated by transactions (though latter is [moving](https://github.com/hashgraph/hedera-mirror-node/pull/894) to db very soon).
