### ISSUE TITLE
Search accounts by public key does not return accounts with threshold key

### ISSUE THREAD

**Issue by SvetBorislavov** [hashgraph/hedera-mirror-node#8060]
### Description

A public key may be part of a threshold key with many levels. When trying to search accounts by a public key the accounts with nested key in which the searched public key is part of are not being returned

### Steps to reproduce

The following public key: `b9f147e105795132dc8a915605c01e3032e2caf2723579298d4ad2e75d68132b`
is associated with account: `0.0.3993519`

1. Execute this request to get all the accounts with the above public key:
`https://testnet.mirrornode.hedera.com/api/v1/accounts?account.publickey=b9f147e105795132dc8a915605c01e3032e2caf2723579298d4ad2e75d68132b`

2. You may see that the result is 0 accounts associated with the public key but there should be one: `0.0.3993519`

### Hedera network

testnet

### Version

v1

### Operating system

None

**Comment by steven-sheehy** [comment]
Correct, this isn't supported and would be challenging to support with arbitrary key depths at our scale.

**Comment by SvetBorislavov** [comment]
Sure, thank you for the information!

**Comment by SimiHunjan** [comment]
What if we could define the max key depth? Say 39? We were intending to using this API to return a list of accounts the public key is associated with for a user and as a way to determine who the signers would be for a given transaction for the Transaction Tool app. All council member managed Hedera accounts are threshold keys: https://hashscan.io/mainnet/adminKey/0.0.50.

**Comment by SimiHunjan** [comment]
Closing this issue for now as we have identified an alternative work around for the time being.

**Comment by SimiHunjan** [comment]
oops forgot to hit the close with comment button :sweat_smile:. Thanks!
