### ISSUE TITLE
Add a test script that checks each local mirror node container is functional

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-mirror-node#808]
**Problem**
In following the README.md setup steps we go into detail about how to check each container and whether it's running appropriately.

It was suggested that a single and simple to run script that checks each containers endpoints etc might be good to have

**Solution**
Create a script that can be run that checks the following suggestions
- Importer is up and running - maybe that given volume is not empty, or given log was made
- db is up and running
- REST api endpoints return 200's

Additional scenarios could be
- gRPC endpoint return messages or that expected logs for run are present

**Alternatives**
- docker exec commands 
- docker logs reads
...

**Additional Context**

**Comment by steven-sheehy** [comment]
I think the monitor sufficiently handles this now. Additionally, kubernetes probes, docker health checks or metrics should be used to validate the health of the system.
