### ISSUE TITLE
HIP-968: Query tokens by name

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-mirror-node#8115]
### Problem

To enhance the experience for our users, we would like to request querying tokens by token name and token symbol. 

When a user comes to the explorer they often want to search for a token by name or symbol. For example, search LINK or Chainlink on https://etherscan.io/. 

For us to support this experience, we need to add additional query options to `/api/v1/tokens` such that if I search for token KARATE by name it returns the corresponding token ID and information.

Related Issue: https://github.com/hashgraph/hedera-mirror-node-explorer/issues/33

### Solution

```[tasklist]
### Tasks
- [ ] #8702
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/8703
```

**Comment by SimiHunjan** [comment]
Partial match or exact match to query by name

**Comment by AliNik4n** [comment]
We are looking for the ability to search by tokenID or token name, when searching for token name it should return results for partial match or exact match to query by name. 
We are also looking to get token symbol when searching for a token name. 

This is a very common use case in all explorers, and it's really important for users in hashscan (it's been brough up by many members in the community)
