### ISSUE TITLE
Running an `eth_estimateGas` call through the web3 service, on an existing contract, returns a `403 Forbidden`

### ISSUE THREAD

**Issue by ebadiere** [hashgraph/hedera-mirror-node#8180]
### Description

The following contract on mainnet appears to be an EIP-1967Proxy contract: https://hashscan.io/mainnet/contract/0.0.4323024
Calling an `eth_estimateGas` on it returns a `403 Forbidden` response.  Anyone should be able to run `eth_estimateGas` on a contract.

### Steps to reproduce

Attached is a curl script that will reproduce the problem.
[curl.sh.txt](https://github.com/hashgraph/hedera-mirror-node/files/15122091/curl.sh.txt)

### Hedera network

mainnet

### Version

v0.102.0

### Operating system

macOS

**Comment by steven-sheehy** [comment]
```
> POST /api/v1/contracts/call HTTP/2
> Host: mainnet-public.mirrornode.hedera.com
> User-Agent: curl/8.4.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 76846
```

We reject content-length greater than 55K at the load balancer, hence the 403

**Comment by steven-sheehy** [comment]
Closing as we've increased the request body limit since this was opened.
