### ISSUE TITLE
Deploy Citus to testnet-eu

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-mirror-node#8188]
### Problem

We need to get Citus onto testnet to get real world experience with it.

### Solution

* Create a `testnet-citus` namespace in testnet-eu cluster
* Run migration scripts to populate citus from Cloud SQL

**Comment by xin-hedera** [comment]
Status:

- [ ] Create a testnet-citus namespace in testnet-eu cluster
- [ ] Run migration scripts to populate citus from Cloud SQL
- [ ] Spin down Cloud SQL namespace

**Comment by steven-sheehy** [comment]
Completed
