### ISSUE TITLE
Increase call data size limit to 128 KB for testnet and mainnet

### ISSUE THREAD

**Issue by anshuman-supraoracles** [hashgraph/hedera-mirror-node#8210]
### Problem

While pushing the data pairs we are facing issue with the call data size.For many days the txns are failing and we are bleeding hedera mainet tokens without updating the pair prices on chain. The call data size will increase if we add more and more pairs. For now it will be safe for us if you increase call data size limit to 128 KB and i hope it will last for a long time

Infact https://github.com/ethereum/go-ethereum/blob/830f3c764c21f0d314ae0f7e60d6dd581dc540ce/core/txpool/legacypool/legacypool.go#L49-L53

i was going through the geth implementation and found the max txn limit is 128KB (default) but it can be changed

### Solution

Increase call data size limit to 128 KB  for testnet and mainnet

**Comment by anshuman-supraoracles** [comment]
We need this increase in size for pushing the data price pairs into the hedera network

**Comment by anshuman-supraoracles** [comment]
[curl (2).log](https://github.com/hashgraph/hedera-mirror-node/files/15290926/curl.2.log)

**Comment by anshuman-supraoracles** [comment]
[Uploading curl (2).log…]()

**Comment by astrid-net** [comment]
If Hedera team doesn't increase the limit, we won't be able to adopt Iracles in our DeFi applications.

**Comment by steven-sheehy** [comment]
Thanks for your report. We've increased the max call data size to 128 KiB on both testnet and mainnet. Please test and let us know if you have any further issues.
