### ISSUE TITLE
Web3 historical fungible token total supply query times out frequently

### ISSUE THREAD

**Issue by xin-hedera** [hashgraph/hedera-mirror-node#8217]
### Description

The web3 TokenRepository historical fungible token total supply query times out and causes `CONTRACT_REVERT_EXECUTED ` error.

### Steps to reproduce

Check mainnet web3 logs 

### Hedera network

mainnet

### Version

v0.103.0

### Operating system

None

**Comment by jnels124** [comment]
We have additional logs present that can help identify the issue. See https://mirrornode.grafana.net/goto/oQg-fRwSR?orgId=1
