### ISSUE TITLE
Simplify log based alerting

### ISSUE THREAD

**Issue by apeksharma** [hashgraph/hedera-mirror-node#825]
Current process:
If a log line changes which has also been added to alerting policies, then we need to notify devops, they need to update policies, etc. Process is too manual.

Simplify the process by configuring alert policies to alert on either of the following:
- a custom log level dedicated for alerting
- `ERROR`: Use warn for all non-alerting logs that signify not normal functioning

Update the documentation here https://github.com/hashgraph/hedera-mirror-node/blob/master/docs/troubleshooting.md#log-based-alerts

**Comment by steven-sheehy** [comment]
Closing in favor of https://github.com/hashgraph/hedera-mirror-node/issues/1218 and alerting off of other metrics besides logs.
