### ISSUE TITLE
Create a new metric for data size in web3

### ISSUE THREAD

**Issue by kselveliev** [hashgraph/hedera-mirror-node#8258]
### Problem

We need to create a new metric for calldata size to be able to monitor in grafana the data size per second that the system is handling. With this metric we will be able to also determine if we would be able to increase the maxDataSize config in evm properties.

### Solution

Similar to the current gas metric `private final MeterProvider<Counter> gasCounter` we should create a new call data metric that accumulates call data size into the counter. We need to expose this metric to grafana for monitoring. Execute k6 to monitor the metrics.

**Comment by steven-sheehy** [comment]
I don't think we need this ticket. We have a `hedera.mirror.web3.request.bytes` metric I added via the `MetricsFilter` that stores the entire request size. The call data is the only variable piece of data in the request so we can calculate the approximate data size by subtracting the fixed size overhead for the other fields.

**Comment by kselveliev** [comment]
Closing this one.
