### ISSUE TITLE
Documentation about mainnet and testnet helm chart installation

### ISSUE THREAD

**Issue by insider89** [hashgraph/hedera-mirror-node#8260]
### Problem

I am installing hedera mirror node with helm chart https://github.com/hashgraph/hedera-mirror-node/tree/main/charts/hedera-mirror. I don't understand how to make difference between mainnet and testnet running. Does it only depends what you set in importer.network value for bucket?

### Solution

Improve documentation with clear explanation how to install mainnet and testnet with helm chart.

**Comment by insider89** [comment]
Yes, I saw this documentation. So the only difference between running mirror node for `mainnet` and `testnet` is `hedera.mirror.importer.network` helm value?

**Comment by steven-sheehy** [comment]
Each mirror node component might have a separate network property you also need to adjust. Also, the credentials might vary per network depending upon how you set it up. Please use discussions or discord for further questions.
