### ISSUE TITLE
HIP-904 Add support to Web3 for unlimited Max Automatic Token Associations 

### ISSUE THREAD

**Issue by edwin-greene** [hashgraph/hedera-mirror-node#8274]
### Problem

Add support to Web3 for unlimited Max Automatic Token Associations. 

### Solution

Update Web3 `CryptoOpsUsage` and `SyntheticTxnFactory` to handle `-1` values for `maxAutomaticTokenAssociations` for protobuf versions greater than or equal to 0.51. If the HAPI protobuf version is less than that version then the methods should use the existing behavior.

**Comment by xin-hedera** [comment]
the feature has been delayed to 0.52, we need to change the target HAPI version to 0.52 accordingly
