### ISSUE TITLE
RestJava improve request limit handling

### ISSUE THREAD

**Issue by xin-hedera** [hashgraph/hedera-mirror-node#8310]
### Description

The request limit parameter in js rest module is

- with configurable default and max
- a soft constraint, i.e., the max value is used to cap the limit, instead of used as a validation constraint

We need to do the same in rest-java

### Steps to reproduce

see the description

### Hedera network

other

### Version

v0.106.0-SNAPSHOT

### Operating system

None

**Comment by steven-sheehy** [comment]
I considered this, but not sure I'm convinced it needs to be a soft limit. Especially for new APIs. The reason why we made it soft before was that we lowered it from 1000 to 25 and we didn't want to break customers. But could argue it's better customers are aware what the bounds are so they don't receive unexpected amounts than desired.

**Comment by xin-hedera** [comment]
Sure. Overall I think we are going to change the course to fail the client early, close the ticket now.
