### ISSUE TITLE
Getting `403 Forbidden` Response for very large requessts on `previewnet`

### ISSUE THREAD

**Issue by AlfredoG87** [hashgraph/hedera-mirror-node#8353]
### Description

When we try to run `contract/calls` that have a very large payload against `previewnet` mirror node, we are getting the following error:

```
<!doctype html>
<meta charset="utf-8">
<meta name=viewport content="width=device-width, initial-scale=1">
<title>403</title>403 Forbidden
```

This is not happening on testnet or mainnet.

### Steps to reproduce

[Curl.request.txt](https://github.com/hashgraph/hedera-mirror-node/files/15424583/Curl.request.txt)

### Hedera network

previewnet

### Version

0.105.0-rc2

### Operating system

None

**Comment by steven-sheehy** [comment]
I've adjusted the cloud armor rule. Please check and close if it's good

**Comment by AlfredoG87** [comment]
I've verified that is working now, thank you! 👍
