### ISSUE TITLE
HCS Topic Fragmentation

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-mirror-node#838]
**Problem**
HAPI will be adding chunk support to ConsensusSubmitMessage as part of the next release. Mirror Node should be updated to understand and store this chunk information.

**Solution**
- Add new fields
- Populate them when inserting
- Expose new fields on the gRPC API. Can probably reuse ConsensusMessageChunkInfo object.

**Alternatives**

**Additional Context**
https://github.com/hashgraph/hedera-services/issues/53

**Comment by Nana-EC** [comment]
Looking into this. Waiting on updated proto of service that will allow on updated logic to importer
