### ISSUE TITLE
Hedera mirror node syncing slowly after migrating to bare metal server from GCP

### ISSUE THREAD

**Issue by shivraj001** [hashgraph/hedera-mirror-node#8409]
### Description

We migrated hedera mainnet mirror node from GCP to bare metal server. After, migration for first few days it was syncing and trying to catch up with actual hedera mirror node height. Hosted mirror node is syncing comparatively slowly then GCP. 
We checked the hardware specification with GCP and bare metal server sizing as well.

Find the bare metal server specification below:

Processor: AMD Ryzen 7 Pro 3700 - 8c/16t - 3.6GHz/4.4GHz
Memory: 64GB DDR4 ECC 2933MHz
System Storage: 2x SSD SATA 480GB Enterprise Class Soft RAID
Data Storage: 8× 14TB HDD SAS Hard RAID ( Usable storage on RAID 5 98TB)
Public Bandwidth: 1Gbit/s - Limited traffic 25TB
Private Bandwidth: 2Gbit/s unmetered and guaranteed

Observation:
After switching from GCP to S3, we saw improvement in sync speed. Even though it is slow.

Is there a way to pin point where is the bottleneck?  
 

### Steps to reproduce

1. Run the hedera mirror node by following https://github.com/hashgraph/hedera-mirror-node
2. Migrate the data to new server in other cloud
3. Run the hedera mirror node again in new cloud
4. Wait for mirror node to catch up

### Hedera network

mainnet

### Version

0.94.1

### Operating system

None

**Comment by steven-sheehy** [comment]
The mirror node is not optimized for fast historical sync. We have an [epic](https://github.com/hashgraph/hedera-mirror-node/issues/5016) that we started down that road but haven't completed it out. If your company has an important use case, feel free to reach to our developer advocates in Discord and we might be able to provide recent database dumps.

**Comment by steven-sheehy** [comment]
Closing in favor of epic
