### ISSUE TITLE
Transaction Stateproof API slow In V2

### ISSUE THREAD

**Issue by jnels124** [hashgraph/hedera-mirror-node#8420]
### Problem

When observing grafana metrics for testnet, it appears `/api/v1/transactions/{transactionId}/stateproof` is much slower in v2 vs v1. (880ms vs 220ms)

### Solution

Investigate slowdown in v2 and optimize

**Comment by steven-sheehy** [comment]
Missing optimization from `/api/v1/transactions/{id}` to limit timestamp range
