### ISSUE TITLE
Mirrornode returns a total supply of 0 even when some accounts hold the token.

### ISSUE THREAD

**Issue by se7enarianelabs** [hashgraph/hedera-mirror-node#8433]
### Description

The mirrornode returns a total_supply of 0 for the testnet USDC token: [link](https://hashscan.io/testnet/token/0.0.429274?p=1), but this is not accurate as some accounts hold the token: [link](https://testnet.mirrornode.hedera.com/api/v1/tokens/0.0.429274/balances).

Maybe important(because of the mirrornode instance), I'm from Europe

### Steps to reproduce

1. Search for this token (0.0.429274) on the Testnet HashScan: https://hashscan.io/testnet/token/0.0.429274?p=1 and check the total supply.
2. Verify that some accounts hold the token: https://testnet.mirrornode.hedera.com/api/v1/tokens/0.0.429274/balances

### Additional context

![image](https://github.com/hashgraph/hedera-mirror-node/assets/101180841/354b040b-361d-47ce-9ad7-5e20e177219c)

### Hedera network

testnet

### Version

v0.1.0

### Operating system

None

**Comment by Neurone** [comment]
Hi guys, I have the same issue. But if I switch to an US based IP via VPN, the API (https://testnet.mirrornode.hedera.com/api/v1/tokens/0.0.429274) returns `"total_supply":"10000000000000000"`. If I switch back to an Italian-based IP, I get `0` again.

**Comment by xin-hedera** [comment]
Thanks for reporting the issue. This indeed only happened for testnet-eu cluster which serves traffic from EU region by our load balancer rules.

The result should be correct now and we'll also fix the bug in the code in an upcoming PR.
