### ISSUE TITLE
Hardcode bucket names

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-mirror-node#844]
**Problem**
If someone wants to run a Mirror Node, they previously had to request access and Hedera would pay for their data retrieval from cloud storage. Now that all buckets are requester pays, anyone can run a Mirror Node but they still have to ask Hedera what the bucket names are.

**Solution**
We should remove this limitation and hardcode the bucket names in the code. Users should just pick which network they want to connect to and provide their requester pays credentials and it should just work.

**Alternatives**

**Additional Context**

**Comment by Nana-EC** [comment]
Started draft on this. Will wait for next sprint to push up since there's too many large item changes in this sprint.
