### ISSUE TITLE
Research `web3j-solidity-gradle-plugin`

### ISSUE THREAD

**Issue by petreze** [hashgraph/hedera-mirror-node#8466]
Explore [web3j-solidity-gradle-plugin](https://github.com/hyperledger/web3j-solidity-gradle-plugin) plugin. Essentially, the goal here is to compile the solidity contracts at build time with the help of this plugin. This will allow us to remove `.bin` and `.json` files related to the contracts and generate them as part of the build process

**Comment by fchitakova** [comment]
Created issue to Web3j Gradle Plugin -> https://github.com/hyperledger/web3j-solidity-gradle-plugin/issues/73

**Comment by kselveliev** [comment]
Closing in favor of https://github.com/hashgraph/hedera-mirror-node/issues/8467

**Comment by kselveliev** [comment]
Reopening this. With the historical tests we probably can investigate and use this plugin to be able to compile and generate older binary files with older version of solidity since it currently is not possible with the web3j-gradle for classes using the openzeppelin contracts

**Comment by steven-sheehy** [comment]
Closing in favor of generating historical wrappers
