### ISSUE TITLE
Bump web3j version in mirror-node

### ISSUE THREAD

**Issue by IvanKavaldzhiev** [hashgraph/hedera-mirror-node#8505]
### Problem

We need to bump `org.web3j:core` from `4.12.0` to `5.0.0` version, which is a major version change and requires code changes.

### Solution

Analyze `5.00` version needs and adapt code base, so that this dependency can be updated.

**Comment by steven-sheehy** [comment]
web3j 5.0.0 is 3 years old and not the latest version
