### ISSUE TITLE
Some transactions with signature v values set to 1 cause the go ethereum client to fail when trying to unmarshal them. 

### ISSUE THREAD

**Issue by ebadiere** [hashgraph/hedera-mirror-node#8597]
### Description

The following transactions on mainnet cannot be unmarshalled using the go ethereum client:
`0x65486c84522a4f581aeaf5d2b17dc7993c76c916e78158f375d0c89d625e4979`
`0x814b3b545d381b61564733c76cd281f9a1903874319c6594bc6828adba42a08b`
`0x1c9a630ae53193c4f982e48a28247cb561f7e7ff2bd99cbbbaa270aab23c0bf4`

The following transaction on testnet cannot be unmarshalled using the go ethereum client:
`0xaacb25c6bd26870204b566b138a37b33a17d4e44d7dcd9c05678a3f46352f7a0`

Setting the signature v values to 37 or 38 allows them to be unmarshalled in the go-client.  These are type 0 (Legacy) transactions.

### Steps to reproduce

Relay issue [2500](https://github.com/hashgraph/hedera-json-rpc-relay/issues/2500) has a reproducer.

### Hedera network

mainnet

### Version

v0.106.1

### Operating system

Linux

**Comment by steven-sheehy** [comment]
There's not enough info here to investigate. v, r, s signatures are set by the client and are just a pass through for mirror node. v is only set for legacy ethereum transactions. If they're in an incompatible format for relay that would've came directly from the client that way. Please provide more info on how you think mirror node did something wrong.
