### ISSUE TITLE
Deploy Citus to mainnet-eu

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-mirror-node#8604]
### Problem

After stabilizing and improving the performance of Citus on testnet, we should roll it out to one of the two mainnet clusters to get additional feedback.

### Solution

* Add a mainnet-citus namespace to mainnet-eu cluster
* Disable importer, ingress, etc as in https://github.com/hashgraph/hedera-mirror-node/pull/8257/files
* Migrate data

**Comment by jnels124** [comment]
closing ticket as we have successfully deployed citus to mainnet-eu
