### ISSUE TITLE
JavaScript state proof sample code

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-mirror-node#866]
**Problem**
We need standalone code for validating the state proof in Javascript

**Solution**

**Alternatives**

**Additional Context**

**Comment by publu** [comment]
Will it be possible validate a proof belongs to a specific transaction record?

**Comment by steven-sheehy** [comment]
@publu We believe so. We are providing a REST API that will return the address books, signatures and rcd file (that contains many transaction + records) for a specific transaction ID. Then this task will provide sample code how to use that info to validate and prove the state.

**Comment by publu** [comment]
that answers so many questions, thanks steven

**Comment by publu** [comment]
+1 for the javascript version

**Comment by ShivaSunny9** [comment]
Will it be possible to validate a proof belongs to a specific transaction record through javascript code?

**Comment by steven-sheehy** [comment]
@ShivaSunny9 Yes, we will provide both Java and JavaScript sample code to validate the proof against a transaction record file.

**Comment by ShivaSunny9** [comment]
@steven-sheehy can you please let me know, how to get access to that sample code.

**Comment by steven-sheehy** [comment]
It's not written yet. Once it is there will be an associated PR linked to this ticket and it will be available in this open source repo for viewing.
