### ISSUE TITLE
Research feasibility of query contract logs by transaction hash

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-mirror-node#8701]
### Problem

Synthetic contract results were never enabled as they were a performance concern during ingest. To unblock oracles, they need a way to access synthetic contract logs by hash.

### Solution

* See https://github.com/hashgraph/hedera-mirror-node/pull/8649 for API side changes
* Research feasibility of adding a search by transaction hash to `/api/v1/contracts/results/logs` for both v1 and v2 schema.
* If it's easy enough, add the necessary schema and importer changes.

**Comment by xin-hedera** [comment]
more performant approach

- drop the current hash index on`transaction_hash`, create a new index on `substring(transaction_hash.hash from 1 for 32)`
- backfill ethereum transaction hash to `transaction_hash` table and persist ethereum transaction hash in parser
- change the query to `select * from transaction_hash where substring(hash from 1 for 32) = $1` where applicable
