### ISSUE TITLE
HIP-869 Add admin_key to the /network/nodes REST API

### ISSUE THREAD

**Issue by mgoelswirlds** [hashgraph/hedera-mirror-node#8757]
### Problem

`admin_key` is not returned in REST API.

### Solution

- Update the `/network/nodes` API to return the `admin_key`

**Comment by SvetBorislavov** [comment]
The `domain_name` is also missing in the response

**Comment by steven-sheehy** [comment]
`domain_name` is already present in the REST API response

**Comment by Svetoslavb04** [comment]
Correct!
