### ISSUE TITLE
AWS AssumeRole support

### ISSUE THREAD

**Issue by ksemaev** [hashgraph/hedera-mirror-node#900]
I know that currently it is a grey area, as it is still WIP, but I can access s3 bucket from my account with `aws s3 ls s3://hedera-mainnet-streams --request-pa`

But when I try to pass to the importer those vars:
```
- name: HEDERA_MIRROR_IMPORTER_NETWORK
  value: "MAINNET"
- name: HEDERA_MIRROR_IMPORTER_DOWNLOADER_BUCKETNAME
  value: "hedera-mainnet-streams"
- name: HEDERA_MIRROR_IMPORTER_DOWNLOADER_CLOUDPROVIDER
  value: "S3"
- name: HEDERA_MIRROR_IMPORTER_DOWNLOADER_ACCESSKEY
  value: "AWS121212121212212"
- name: HEDERA_MIRROR_IMPORTER_DOWNLOADER_SECRETKEY
  value: "121212121212121212112"
```
I get:
> 2020-07-22 15:09:12,585 ERROR [pool-6-thread-6] c.h.m.i.d.r.RecordFileDownloader Error downloading signature files for node 0.0.4 after 14.69 ms
> java.util.concurrent.ExecutionException: software.amazon.awssdk.services.s3.model.S3Exception: Access Denied (Service: S3, Status Code: 403, Request ID: 0EF468C115A1C0A8)

Please advice! Maybe I can drop the keys and pass some equivalent of `--request-pa` to the app? Maybe I need some equivalent of `gcpProjectId` for AWS? Maybe I'm spelling the var names wrong?

**Comment by steven-sheehy** [comment]
We've tested with requester pays against S3 and a customer is successfully using it. It should work as long as your config is correct. Your environment variables seem to be correct. Are you sure the access key and secret key are the same you passed to `aws configure`?  When you use `aws s3 ls s3://hedera-mainnet-streams --request-pa` it still uses credentials it just gets them from the global config. Maybe try using the application.yaml approach to ensure the mapping is 100% correct?

**Comment by ksemaev** [comment]
TY, I made it work with IAM role with permissions like
```
{
      "Sid": "hederaMainnetS3Bucket",
      "Effect": "Allow",
      "Action": [
        "s3:Get*",
        "s3:List*"
      ],
      "Resource": [
        "arn:aws:s3:::hedera-mainnet-streams",
        "arn:aws:s3:::hedera-mainnet-streams/*"
      ]
}
```

@steven-sheehy can I ask for an improvement: right now when I run the command `aws s3 ls s3://hedera-mainnet-streams --request-pa` in the console I get results (since I now have IAM role attached). But when I run the code on the same machine I still get the error if I don't mention accesskey and secretkey. Maybe you can grab the auth data from the OS, same way as aws cli does? Cause now I have to create a separate AWS user creds just for the app

Using `sts:assume` role to get the IAM role and policy (similar to how aws s3 cli does it) would be a better approach than having to create a programmatic user account which is less secure than an assume role token. Possibly adding the `x-amz-request-payer` header to any GET or HEAD requests would remove the need for dedicated user account.

**Comment by steven-sheehy** [comment]
Hi @ksemaev I'm glad you got it working. We do set `x-amz-request-payer` for all GET or HEAD requests in the code. You can see a below with trace logging turned on:
```
GET /recordstreams/record0.0.6/2020-07-10T05_47_50.959720Z.rcd_sig HTTP/1.1
Host: hedera-mainnet-streams.s3.amazonaws.com
amz-sdk-invocation-id: 2792e4d7-42a2-5884-5f2f-9d271f01e67f
amz-sdk-retry: 0/0/
Authorization: AWS4-HMAC-SHA256 Credential=...
User-Agent: aws-sdk-java/2.13.11 
x-amz-content-sha256: UNSIGNED-PAYLOAD
X-Amz-Date: 20200723T142447Z
x-amz-request-payer: requester
```

About reading credentials from the OS, I think depending upon a user having AWS CLI tools installed and having ran `aws configure` and populated his personal credentials first is more involved and error prone than populating the credentials in a yaml file. Most people run the mirror node in containers (where aws cli cannot be installed) or on a provisioned server in the cloud, making this external setup less feasible. Also, the solution would not be compatible with GCS which is what the majority of people use including Hedera's deployments.

**Comment by ksemaev** [comment]
@steven-sheehy TY for understanding, actually I do run it in container in kubernetes, I don't have any tools installed, and I'm not doing any aws configure also, I just attach an IAM role to pod (any pod, any OS, minimal container with nothing installed) and it works. So I'm wondering why we need those access and secret keys, since my container already authorized with IAM..

**Comment by Merlz** [comment]
@steven-sheehy Thanks for the details above. If an AWS customer is using IAM Roles for an EC2 instance and sts:assume-role to get a session token, are you passing that request in addition to access-key/secret-key (generated from the iam role) so that IAM User Accounts are not required?

We don't use single AWS account, instead we have multiple within our Org and a central account just for IAM users/roles/groups for access management and use assume-roles for access in different accounts, so creating an IAM User in 3 of our accounts (dev/stage/prod) would be a last resort.

**Comment by steven-sheehy** [comment]
Hedera uses GCS with service accounts. Most customers use GCS with regular accounts and populate the project billing ID. So to my knowledge everyone is using user accounts and populating them in the configuration.

Sorry I don't have familiarity with AWS assume role to figure out how to make that work with the mirror node. I assume (no pun intended) there's some setting in the AWS SDK you can tweak in `MirrorImporterConfiguration`. We'd happily support any code contributions if you figure it out.

**Comment by james-callahan** [comment]
We also use IAM roles so that we don't need to issue credentials to applications. Would love to see this implemented.

**Comment by Merlz** [comment]
@steven-sheehy I'm not a java programmer so can't help with a PR, but I suspect what is required in [this](https://github.com/hashgraph/hedera-mirror-node/blob/fd4f69dadfded5ce3e390514ced863528ba7b5fe/hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/MirrorImporterConfiguration.java) file would be something similar to using STS as shown in this [sample](https://github.com/symphonyoss/fugue/blob/7b3fae276319e8a2abf3bd56e1db5dc87bf81a4d/aws-fugue/src/main/java/org/symphonyoss/s2/fugue/aws/sts/StsManager.java) and in this [sample](https://github.com/anurag1192/AWS/blob/26430a77eaa23b4cde6b9e16b92f9b4e21be7408/JavaCredentials/AssumeRoleTest.java).

Documentation for [AssumeRole](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/securitytoken/AWSSecurityTokenService.html#assumeRole-com.amazonaws.services.securitytoken.model.AssumeRoleRequest-) indicates you'd get the temporary credentials which consist of an access key ID, a secret access key, and a security token which can be used in the call to your S3 bucket to ensure Requester Pays.

**Comment by james-callahan** [comment]
I don't believe #971 sufficiently solves this issue. Using e.g. https://github.com/aws/amazon-eks-pod-identity-webhook/ we expect that the env vars `AWS_ROLE_ARN` and `AWS_WEB_IDENTITY_TOKEN_FILE` will automatically be picked up with no configuration required.

**Comment by james-callahan** [comment]
@ijungmann why did you close #988?

I don't think it was fixed, can this be reopened?

**Comment by ijungmann** [comment]
@james-callahan #988 was a rough draft of what was needed to fully support the default credentials provider, but I ran into some issues along the way that needed more time to fully address that we did not have capacity for at the time.  We've now completed #1281 which should support AssumeRole (and others) without requiring keys and ARN in the config, while still supporting the old static credentials and anonymous access approaches.
