### ISSUE TITLE
Hedera-importer requirements/RAM usage

### ISSUE THREAD

**Issue by ksemaev** [hashgraph/hedera-mirror-node#902]
I wasn't able to find the CPU/RAM requirements for importer (please share the doc/link if it's there), but when sycning from 0 I see RAM usage constantly growing. When I restart the container, RAM usage is back to 700M

For the last 24h it went up to 5Gb. Is it expected, or maybe it's indicating some kind of a leak?
<img width="443" alt="Снимок экрана 2020-07-24 в 13 23 06" src="https://user-images.githubusercontent.com/20893598/88382342-efd6ee80-cdb0-11ea-94d7-73a0adcd70f1.png">

**Comment by steven-sheehy** [comment]
We don't have it documented per se, but we do have the resource requirements in our helm [chart](https://github.com/hashgraph/hedera-mirror-node/blob/e0e2f0dcea52cdf1e88ba6b15bc38b52155ea6ec/charts/hedera-mirror-importer/values.yaml#L85). What version are you using? It shouldn't grow unbounded like that. Perhaps there is a memory leak regression that only appears for catch up mode. We haven't had to spin up a new instance in a while hence why we may not have seen it.

**Comment by ksemaev** [comment]
TY for response! I'm having my own charts with:
```
  resources:
    requests:
      cpu: 400m
      memory: 2Gi
```
And regarding the version it's:
```
  image:
    repository: gcr.io/mirrornode/hedera-mirror-importer
    tag: 0.15.0
```

It indeed happens during initial syncup from 0

**Comment by ksemaev** [comment]
It's normal after initial sync finished
