### ISSUE TITLE
HIP-904 Support Deleted Airdrops

### ISSUE THREAD

**Issue by edwin-greene** [hashgraph/hedera-mirror-node#9033]
### Problem

Airdrops can be deleted from the consensus nodes state when the sender no longer owns the nft or has an insufficient balance of the fungible token. These deletions from state are not sent in record files. Rather they are only communicated in a record file when a receiver attempts to claim an airdrop and receives an `INVALID_TOKEN_IN_PENDING_AIRDROP` response code.

### Solution

-Add a new state to the `token_airdrop` table -> `DELETED`. This state represents an insufficient balance or non-ownership of the token on the part of the sender of the airdrop.
 -When the mirror node parses a transaction and sees the `INVALID_TOKEN_IN_PENDING_AIRDROP` response code, it will also receive in that transaction the `pendingAirdropId`, so it shouldn't need to lookup anything in the database, but instead can handle the transaction similarly to a token cancel airdrop transaction and set the state of the airdrop to `DELETED`.

**Comment by steven-sheehy** [comment]
Services will only mark the transaction as successful if all transfers are successful, so we no longer need this ticket.
