### ISSUE TITLE
Empty KeyList Reports Differently between Mirror vs Node

### ISSUE THREAD

**Issue by coltsfanatic07** [hashgraph/hedera-mirror-node#9048]
### Description

When updating a tokens keys to an empty KeyList per HIP-540, the mirror node represents the key as below instead of null as the query token info from mainnet does.

MIRROR TOKEN QUERY

  "supply_key": {
    "_type": "ProtobufEncoded",
    "key": "3200"
  }
  
 MAINNET QUERY
 
 "supply_key": null
 
 This makes numerous dapps "interpret" the token as having keys when the dapps utilize the mirror nodes for token information.

### Steps to reproduce

Create a token with various keys, update said token to empty KeyList per HIP-540.

### Hedera network

mainnet

### Version

v0.111.0

### Operating system

Windows

**Comment by steven-sheehy** [comment]
Thanks for the report. This has already been fixed and will be in the next release. https://github.com/hashgraph/hedera-mirror-node/issues/8845
