### ISSUE TITLE
Provide a API to return the mirror node version

### ISSUE THREAD

**Issue by iron4548** [hashgraph/hedera-mirror-node#9066]
### Problem

I would like to know what the current version of the mirror node is running on 3rd party mirror node providers such as Validation Cloud, Arkhia and hashio.io.

It is useful to know what version they're running for the following reasons:

1. Including the actual mirror node version when reporting a bug related to the mirror node codebase
2. If the bug happens on one provider but not the other provider ('is it due to different version?')
3. To determine if a certain bug fix is available or not
4. To determine how up-to-date the mirror node provider is
5. To check what version is running on testnet, mainnet and previewnet
6. For logging purposes

Validation Cloud and Arkhia both have REST API, but hashio.io only offer JSON-RPC so it would be good to have a new endpoint for both.

### Solution

1) A new official REST API to return the mirror node version
2) A new JSON-RPC endpoint to return the mirror node version because some providers don't run a REST API

**Comment by steven-sheehy** [comment]
Believe I've already answered your question on discord, but to repeat it here:

You can use the version in https://mainnet.mirrornode.hedera.com/api/v1/docs/ or in https://mainnet.mirrornode.hedera.com/api/v1/docs/openapi.yml. The latter can be used for programmatic parsing of the version and satisfy all 6 of your stated reasons. I don't think it provides value to provide a dedicated REST API with just the version as it will still have a payload wrapper that requires some parsing just like the yaml endpoint.

For JSON-RPC relay, this is not the place for such requests and you'll need to ask in the [hedera-json-rpc-relay](https://github.com/hashgraph/hedera-json-rpc-relay/) repo.

**Comment by iron4548** [comment]
> Believe I've already answered your question on discord, but to repeat it here:
> 
> You can use the version in https://mainnet.mirrornode.hedera.com/api/v1/docs/ or in https://mainnet.mirrornode.hedera.com/api/v1/docs/openapi.yml. The latter can be used for programmatic parsing of the version and satisfy all 6 of your stated reasons. I don't think it provides value to provide a dedicated REST API with just the version as it will still have a payload wrapper that requires some parsing just like the yaml endpoint.
> 
> For JSON-RPC relay, this is not the place for such requests and you'll need to ask in the [hedera-json-rpc-relay](https://github.com/hashgraph/hedera-json-rpc-relay/) repo.

Yes, I did receive your response. The problem is - those API don't exist on other mirror node providers, hence the suggestion.

**Comment by steven-sheehy** [comment]
Should ask them to expose them. They'd have to explicitly exclude them since it's under the `/api/v1` prefix that all APIs are.

**Comment by iron4548** [comment]
I see. I had thought it was only specific to Hedera's public REST API. I didn't realize they were excluding it.

**Comment by iron4548** [comment]
> @iron4548 Aaron here, Product Manager at Validation Cloud. Thanks for raising this.
> 
> I wanted to follow-up and say we have now exposed `/api/v1/docs/` to be accessed if you have an API Key with us. So you will be able to hit `https://mainnet.hedera.validationcloud.io/v1/<API_KEY>/api/v1/docs/openapi.yml` to check the mirror node version.
> 
> I just checked and we're currently running Mirror Node version `0.107.2`, see screenshot below. We try to stay close to the latest releases across all chains we support so we've got some upgrading to do here.
> 
> If you don't already have an API key with us, you can get one at https://app.validationcloud.io/
> 
> Thanks!
> 
> ![Screenshot 2024-08-21 at 09 34 09](https://private-user-images.githubusercontent.com/166038182/359823620-b518985b-5fce-48c4-8650-ad853ae1a370.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyMzgzNzYsIm5iZiI6MTcyNDIzODA3NiwicGF0aCI6Ii8xNjYwMzgxODIvMzU5ODIzNjIwLWI1MTg5ODViLTVmY2UtNDhjNC04NjUwLWFkODUzYWUxYTM3MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMVQxMTAxMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNDc3MzdmYWVkY2U3Y2QwOWU5YzlmYjMzYjYxYjQ4YzlmOWU4ZGFhZWJjM2NkNWVjNTg4MDI4M2MxZDJmOWU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Z8o4qfYH3Esv3qWUAizYvGj0vm9evglZfMwTvE90N2Y)

Thanks Aaron,

I can confirm that Validation Cloud now exposes the /api/v1/docs/ path for both testnet and mainnet. Thanks for that! It will help devs like myself know what version you're running without having to ask you guys each time.
