### ISSUE TITLE
Contract id is empty for a SUCCESS Post-Eip1559 Eth transaction

### ISSUE THREAD

**Issue by iron4548** [hashgraph/hedera-mirror-node#9161]
### Description

My tool gave a warning for a SUCCESS transaction but the contract id is empty (0). Not sure if it's an issue or not, but thought I'd just report it here anyway just in case.

The transaction in question is 1724663616.458933003 (https://hashscan.io/mainnet/transaction/1724663616.458933003). It was sent to '0x1e3bafcfb32c40b6b74073d483087c2b3ecc904d' but this contract doesn't exist when I searched for it via hashscan.io and the contract id is empty.

### Steps to reproduce

Not sure - as the transaction was sent by someone else.

### Hedera network

mainnet

### Version

0.52

### Operating system

None

**Comment by 0xivanov** [comment]
Hey @iron4548 
Consensus nodes and mirror nodes did not know about such account id. This was verified via calling the sdk (returnint `INVALID_CONTRACT_ID`) and then I actually auto-created this account in this [txn](https://hashscan.io/mainnet/transaction/1724748146.691357003)
I guess the sender somehow made a successful ethereum transaction to a non-existent contract and it resulted in a no-op. I'm not really sure how to reproduce this, as my transactions trying to do it fail with `INVALID_ACCOUNT_ID`.

**Comment by iron4548** [comment]
My tool detected more instances of this.

https://hashscan.io/mainnet/transaction/1724912729.629899003
https://hashscan.io/mainnet/transaction/1724913011.541448003

**Comment by kselveliev** [comment]
Hey @iron4548,
It's normal for ethereum transactions to a non existing contract address to execute with success with no op and take around 21k gas.

**Comment by iron4548** [comment]
Thanks @kselveliev. I'll update my tools to treat this behavior as normal.
