### ISSUE TITLE
Improve AddressBook Update Process Accuracy

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-mirror-node#920]
**Problem**
We currently adopt a flow that will always take the new addressBook that is sent by the network and apply it to signature verification immediately.

As is this is okay since address book updates have been very few and of the append nature when it comes to nodes with no public key changes.

When the "Hedera Managed AddressBook" is implemented it will support more complex scenarios
* Node removals
* Node replacements
* Increased address book update frequency.

To support this we should adopt more robust logic to figure out the 
* correct time to switch to a new address back
* conclude on the correct start and end times for improved accuracy

**Solution**
Obtain a clear understanding and requirements of the "Hedera Managed Addressbook" and what is the reliable flag to note an addressbook update is.

Potentially utilize the FREEZE transaction if it remains a good signal. Currently this should immediately follow an address book update.

**Alternatives**
* Monitor the bucket node count/details. Should it change consider this the flag to reload the most recent address book

**Additional Context**

**Comment by steven-sheehy** [comment]
There's no clear actionable items in this ticket. With the dynamic address book project this process will be redesigned so we don't need this ticket.
