### ISSUE TITLE
5xx errors from your mainnet endpoint mainnet.mirrornode.hedera.com

### ISSUE THREAD

**Issue by osharykov-ledger** [hashgraph/hedera-mirror-node#9281]
### Description

Facing 5xx errors from your mainnet endpoint `mainnet.mirrornode.hedera.com`
Request can be successful and not for two consecutive times: 
200 example: 
` curl https://mainnet.mirrornode.hedera.com/api/v1/transactions\?account.id\=0.0.xxxxxx\&timestamp\=gt:1723625042
`
`> `{"transactions":[{"bytes":null,"charged_tx_fee":189044,"consensus_timestamp":"1723625042.518559962","entity_id":null,"max_fee":"100000000","memo_base64":"WW91ciBhaXJkcm9wIHJld2FyZCBpcyB3YWl0aW5nIGZvciB5b3UgLSBoZWRlcmFkcm9wLGNvbQ==","name":"CRYPTOTRANSFER","nft_transfers":[],"node":"0.0.9","nonce":0,"parent_consensus_timestamp":null,"result":"SUCCESS","scheduled":false,"staking_reward_transfers":[{"account":"0.0.4152671","amount":633836820}],"token_transfers":[],"transaction_hash":"YpFSzG12X1NI4o/k+Ui22Upf+J+QC4+i/BLMRbQ0Y+85rhHSh6i8g00br+d95bZ2","transaction_id":"0.0.6734581-1723624912-609788381","transfers":[{"account":"0.0.9","amount":7676,"is_approval":false},{"account":"0.0.98","amount":163232,"is_approval":false},{"account":"0.0.800","amount":-633818684,"is_approval":false},{"account":"0.0.4152671","amount":633837830,"is_approval":false},{"account":"0.0.6734581","amount":-190054,"is_approval":false}],"valid_duration_seconds":"180","valid_start_timestamp":"1723624912.609788381"}],"links":{"next":null}}#```

Same request after previous with 5xx error: 
```
> curl https://mainnet.mirrornode.hedera.com/api/v1/transactions\?account.id\=0.0.xxxxxxx\&timestamp\=gt:1723625042

> {"_status":{"messages":[{"message":"Service unavailable"}]}}#
```

### Steps to reproduce

curl from external source to different accounts 
`curl https://mainnet.mirrornode.hedera.com/api/v1/transactions\?account.id`

### Hedera network

mainnet

### Version

non

### Operating system

Other

**Comment by steven-sheehy** [comment]
It's hard to tell without the full URL, but we were testing a new database deployment with some canary traffic in the EU region. You might have experienced some slowdown during that time if your requests hit the new database. 

We've rolled out a newer version that optimizes those endpoints so you should see better results now. Can you please check again and let us know if you still experience any issue?

**Comment by osharykov-ledger** [comment]
Hello @steven-sheehy 
After your fix 5xx rate dropped at zero level. Thank you a lot! 
![image](https://github.com/user-attachments/assets/bee5a97f-4725-420b-b5b2-3ada98ae213f)
