### ISSUE TITLE
Fully synced historical node has not enough data

### ISSUE THREAD

**Issue by ksemaev** [hashgraph/hedera-mirror-node#931]
When requesting data from our fully synced archival node with `api/v1/accounts?account.id=0.0.46053` call through hedera-rest api I get ``` {"accounts":[],"links":{"next":null}} ``` although the data should be there: https://explorer.kabuto.sh/mainnet/id/0.0.46053

I see no errors in rest api logs

Maybe we're using wrong calls? 
Maybe we lack some data during initail syncup? 
Maybe this is related to https://github.com/hashgraph/hedera-mirror-node/issues/929 and https://github.com/hashgraph/hedera-mirror-node/issues/930

Please advice

**Comment by steven-sheehy** [comment]
That API is correct. Here's the output on our mirror node:

`curl -s "http://mainnet.mirrornode.hedera.com/api/v1/accounts?account.id=0.0.46053" | jq`
```json
{
  "accounts": [
    {
      "balance": {
        "timestamp": "1596468600.651999000",
        "balance": 100053261
      },
      "account": "0.0.46053",
      "expiry_timestamp": null,
      "auto_renew_period": 7890000,
      "key": {
        "_type": "ED25519",
        "key": "6e955ae687296910554f232b56dcd5f9210ab10d2335de9091691be5c511768d"
      },
      "deleted": false
    }
  ],
  "links": {
    "next": null
  }
}
```

You said it's fully synced, but there are 3 different streams: account balances, events and record files. I'm guessing just your record stream is fully synced, but that particular API comes from the account balance stream data. What does the latest log entry look for this log?

```
AccountBalancesFileLoader Successfully processed account balances file 2020-08-03T15_30_00.264901Z_Balances.csv
```

**Comment by ksemaev** [comment]
Was fixed on main-node level by hedera team
