### ISSUE TITLE
Fix Staging Citus PG Version

### ISSUE THREAD

**Issue by jnels124** [hashgraph/hedera-mirror-node#9349]
### Problem

When staging was replaced with na snapshots, the pg version for the cluster doesn't match the data version.

### Solution

Recreate the staging cluster with the correct pg version. Check performance-citus and perform work there if necessary

**Comment by xin-hedera** [comment]
performance-citus is fine. I rebuilt the citus database after 0.113.1 was deployed

**Comment by jnels124** [comment]
Cluster was replaced
