### ISSUE TITLE
Replay production REST API traffic

### ISSUE THREAD

**Issue by mgoelswirlds** [hashgraph/hedera-mirror-node#9401]
### Problem

We need to be able to replay production traffic from mainnet on a test environment , to reproduce production rest request scenario.

### Solution

- Work on a possible bash script to read rest logs and replay it on a cluster.

**Comment by xin-hedera** [comment]
will try out this tool https://github.com/buger/goreplay

It requires traffic mirroring in google cloud though. The tool does provide more than what we need, it can save traffic to a file and replay later with the original time differences between requests preserved.
