### ISSUE TITLE
Add a type query parameter to Token Airdrops REST API

### ISSUE THREAD

**Issue by edwin-greene** [hashgraph/hedera-mirror-node#9530]
### Problem

Add a type query parameter to the outstanding and pending token airdrops REST API.

### Solution

Type values suggested: [ "ALL", "FUNGIBLE_COMMON", "NON_FUNGIBLE_UNIQUE" ]

**Comment by HarshSawarkar** [comment]
Hi, I would like to work on this issue. Is it open?

**Comment by HarshSawarkar** [comment]
Also this enum types are to be included in the model class AbstractTokenAirdrop or only the DTO TokenAirdropRequest?

**Comment by steven-sheehy** [comment]
Thanks for your interest in this @HarshSawarkar. I haven't seen any feedback on users needing this and it would require a HIP to proceed. I think we will close this as not planned.

**Comment by HarshSawarkar** [comment]
> Thanks for your interest in this @HarshSawarkar. I haven't seen any feedback on users needing this and it would require a HIP to proceed. I think we will close this as not planned.

If the need arises in the future, I would love to work on it.
