### ISSUE TITLE
Transactions API Should Return All Relevant Transactions

### ISSUE THREAD

**Issue by jnels124** [hashgraph/hedera-mirror-node#9606]
### Problem

`parent_consensus_timestamp` is only set on following children. #4672 made changes to exclude synthetic transactions and inadvertently excludes transactions that precede another transaction. For instance, a `CRYPTOTRANSFER` that creates a  `CRYPTOCREATEACCOUNT` transaction. These `CRYPTOCREATEACCOUNT` transactions will have a non-zero `nonce` and will not have a `parent_consensus_timestamp` so the query adjustment in the mentioned pr will exclude these transactions in the response.

### Solution

- [ ] Determine other transaction types that may be effected
- [ ] Adjust query so that all relevant transactions are returned

**Comment by HarshSawarkar** [comment]
Hi, I have linked a PR for this issue. Could you review it?

**Comment by HarshSawarkar** [comment]
Hi @jnels124 , I had to close the previous PR because of some conflicts. Could you review this new PR https://github.com/hashgraph/hedera-mirror-node/pull/9808 please?
