### ISSUE TITLE
Update Application Cache To Use Normalized URL

### ISSUE THREAD

**Issue by jnels124** [hashgraph/hedera-mirror-node#9679]
### Problem

We recently added a redis caching layer to the rest module. This functionality should use the normalized url added by [PR](https://github.com/hashgraph/hedera-mirror-node/pull/9591)

### Solution

Update the cache key to use normalized url

**Comment by steven-sheehy** [comment]
Seems to be a duplicate of https://github.com/hashgraph/hedera-mirror-node/issues/9676
