### ISSUE TITLE
Add an Endpoint for Token Balance Count

### ISSUE THREAD

**Issue by psychoter** [hashgraph/hedera-mirror-node#9702]
### Problem

Currently, the Hedera Mirror Node API provides an endpoint, `/api/v1/tokens/{tokenId}/balances`, which returns an array of objects detailing each account's ID, balance, and decimals. While this is very useful for fetching detailed balance information, there is no straightforward way to retrieve just the `count` of balances for a specific token at a certain point in time.

### Solution

Proposed Enhancement Introduce a new endpoint following the current API structure:

`/api/v1/tokens/{tokenId}/balances/count`

Details:

- **Method**: `GET`
- **Query Parameter**:
> **timestamp (optional)**: Specifies the point in time for which to return the count of balances.

- **Response**:
`{
  "timestamp": "1586567700.453054000",
  "count": 150
}`

**Benefits**:

- **Performance**: Optimizes data retrieval when only the count of balances is needed.
- **Simplicity**: Reduces response size and overhead for applications that only require basic count information.
- **Consistency**: Aligns with current API URL patterns and naming conventions.

**Potential Use Cases**
- Analyzing token distribution trends over time.
- Quick data checks for reporting and dashboard statistics.
- Enhancing client-side applications that display token statistics in summary form.

**Impact** This addition is expected to be backward-compatible and would add utility without disrupting existing endpoints or functionality. It provides added flexibility for developers interacting with the Hedera Mirror Node API.

### Alternatives

An alternative approach could be adding an optional query parameter to the existing `/api/v1/tokens/{tokenId}/balances` endpoint, such as `?summary=count`, which would modify the response to only include the count. However, this may complicate the current endpoint's logic and response structure, so creating a dedicated endpoint, `/balances/count`, is cleaner and more intuitive.

**Comment by steven-sheehy** [comment]
The mirror node database is not setup to be an analytics platform. For one, count queries in PostgreSQL are extremely slow. If a specific token had tens of millions of rows then it could take seconds to respond. So we'd have to change the importer to pre-aggregate the count for each token ID to be efficient. This would decrease the write performance. I don't see the value in doing all this for an endpoint that seems a very specific use case.

It's preferable the users or other mirror node providers take the data and insert it into a data lake or data warehouse that is more suitable for these type of queries. You might also try hgraph.io to see if their GraphQL API has such capability.

**Comment by psychoter** [comment]
You're correct, and I see your point. This type of feature is best left to other mirror node providers or external analytics platforms to implement. Keeping the core mirror node focused on efficient data ingestion and retrieval without added complexity makes sense. Thanks for your input and for clarifying the potential impact!
