### ISSUE TITLE
Nonce Filter Is Ignored on /api/v1/transactions/{hash}

### ISSUE THREAD

**Issue by jnels124** [hashgraph/hedera-mirror-node#9715]
### Description

The nonce query param is only respected when making request with the transaction id and not when request is made with transaction hash.

### Steps to reproduce

Given the following request:
```bash
 curl -X 'GET' \                                                                                                                                                                                        
'https://testnet.mirrornode.hedera.com/api/v1/transactions/r6rpaXaYCvy9pPnCfO0f64IoDf0TrnNU0dHfFFbeOeBvhivdO+rcP134dCb44LkA?nonce=0' \
 -H 'accept: application/json'
```
The following result will be returned(correct):
```json
{"transactions":[{"bytes":null,"charged_tx_fee":207448,"consensus_timestamp":"1730913223.447111312","entity_id":null,"max_fee":"2655000000","memo_base64":"","name":"ETHEREUMTRANSACTION","nft_transfers":[],"node":"0.0.3","nonce":0,"parent_consensus_timestamp":null,"result":"WRONG_NONCE","scheduled":false,"staking_reward_transfers":[],"token_transfers":[],"transaction_hash":"r6rpaXaYCvy9pPnCfO0f64IoDf0TrnNU0dHfFFbeOeBvhivdO+rcP134dCb44LkA","transaction_id":"0.0.902-1730913210-989942481","transfers":[{"account":"0.0.3","amount":7413,"is_approval":false},{"account":"0.0.98","amount":180032,"is_approval":false},{"account":"0.0.800","amount":20003,"is_approval":false},{"account":"0.0.902","amount":-207448,"is_approval":false}],"valid_duration_seconds":"120","valid_start_timestamp":"1730913210.989942481"}]}
```
However with the following request with the wrong nonce filter still returns the result
```bash
curl -X 'GET' \                                                                                                              
'https://testnet.mirrornode.hedera.com/api/v1/transactions/r6rpaXaYCvy9pPnCfO0f64IoDf0TrnNU0dHfFFbeOeBvhivdO+rcP134dCb44LkA?nonce=1000' \
 -H 'accept: application/json'
```

### Hedera network

testnet

### Version

v0.117.0

### Operating system

None

**Comment by AsfarHorani** [comment]
Hi @jnels124 can u assign it to me? I am willing to solve it

**Comment by HarshSawarkar** [comment]
I would like to work on this issue if no one else is working on it currently.

**Comment by HarshSawarkar** [comment]
Hi @jnels124, I have raised a PR. Could you please review it?

**Comment by HarshSawarkar** [comment]
I also tried to run the transactions.test.js class extractSqlFromTransactionsByIdOrHashRequest test, but I kept getting the following error. Could you guide me on how to resolve it? Here’s the error I’m encountering:
`
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    D:\Hedera-Mirror-Node\hedera-mirror-rest\__tests__\jestSetup.js:17
    import { jest } from '@jest/globals';
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1505:14)
`

**Comment by xin-hedera** [comment]
> I also tried to run the transactions.test.js class extractSqlFromTransactionsByIdOrHashRequest test, but I kept getting the following error. Could you guide me on how to resolve it? Here’s the error I’m encountering: ` ● Test suite failed to run
> 
> ```
> Jest encountered an unexpected token
> 
> Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.
> 
> Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.
> 
> By default "node_modules" folder is ignored by transformers.
> 
> Here's what you can do:
>  • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
>  • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
>  • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
>  • If you need a custom transformation specify a "transform" option in your config.
>  • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.
> 
> You'll find more details and examples of these config options in the docs:
> https://jestjs.io/docs/configuration
> For information about custom transformations, see:
> https://jestjs.io/docs/code-transformation
> 
> Details:
> 
> D:\Hedera-Mirror-Node\hedera-mirror-rest\__tests__\jestSetup.js:17
> import { jest } from '@jest/globals';
> ^^^^^^
> 
> SyntaxError: Cannot use import statement outside a module
> 
>   at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1505:14)
> ```
> 
> `

What is the command you used to run the test? can you try this instead?

```bash
 npm test -- __tests__/transactions.test.js
```

**Comment by HarshSawarkar** [comment]
@xin-hedera 
>  npm test -- __tests__/transactions.test.js


I tried running this command but encountered this issue mentioned below

`(Use `node --trace-warnings ...` to show where the warning was created)
node:internal/errors:490
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:399:5)
    at validateString (node:internal/validators:163:11)
    at Object.join (node:path:429:7)
    at file:///D:/Hedera-Mirror-Node/hedera-mirror-rest/__tests__/integration/generator.js:31:34
    at Array.forEach (<anonymous>)
    at file:///D:/Hedera-Mirror-Node/hedera-mirror-rest/__tests__/integration/generator.js:31:4
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25) {
  code: 'ERR_INVALID_ARG_TYPE'
}

Node.js v18.16.1
`
