### ISSUE TITLE
`/network/nodes` API returning null for admin_key

### ISSUE THREAD

**Issue by yiliev0** [hashgraph/hedera-mirror-node#9864]
### Description

The `/network/nodes` API was recently fixed to include the admin_key, which was previously not returned. However, after testing against:

1. SOLO Environment: Version 0.120.0-SNAPSHOT
2. Previewnet Endpoint -> https://previewnet.mirrornode.hedera.com/api/v1/network/nodes

The API now returns the admin_key field but with a value of null for all nodes. 

### Steps to reproduce

1. Query the /network/nodes API in the SOLO environment with version 0.120.0-SNAPSHOT or on Previewnet (https://previewnet.mirrornode.hedera.com/api/v1/network/nodes).
2. Observe the admin_key field in the response.

### Version

0.120.0-SNAPSHOT

### Operating system

None

**Comment by steven-sheehy** [comment]
The `admin_key` is only present on NodeCreate and NodeUpdate transactions. The information in `/api/v1/network/nodes` comes entirely from `0.0.102` except for the `admin_key`. If it's null, then that means there were either no node transactions or there were but adminKey was not populated on them. The DB shows there were zero node transactions in previewnet.

```
mirror_node=> select count(*) from transaction where type in (54, 55, 56);
 count 
-------
     0
(1 row)
```

Please send a node create or update with an admin key if you want to test admin key.

**Comment by yiliev0** [comment]
Thank you for the clarification. I'll review this further and proceed to test with a NodeCreate or NodeUpdate transaction that includes an admin key, as suggested. Appreciated!

**Comment by steven-sheehy** [comment]
We've removed admin key until 0.57. closing this
