### ISSUE TITLE
Mirror Node displays incorrect lagre values

### ISSUE THREAD

**Issue by ivaylogarnev-limechain** [hashgraph/hedera-mirror-node#9874]
### Description

When creating a token on Testnet with a large amount value of `9223372036854775807` (maximum value for a signed 64-bit integer), the Mirror Node displays the amount as `9223372036854776000`, whereas the Consensus Node correctly records the value.

The Mirror Node displays the token amount as `9223372036854776000`, likely due to an overflow or incorrect handling of large integers.

### Steps to reproduce

1. Create a token on Testnet with amount set to `9223372036854775807`.
2. Verify the value recorded by the Consensus Node (correct: `9223372036854775807`).
3. Check the value displayed in the Mirror Node (incorrect: `9223372036854776000`).

### Additional context

The value is passed as a `Long` type in the transaction. It's not related to a specific tx property.

### Hedera network

testnet, other

### Version

latest

### Operating system

macOS

**Comment by xin-hedera** [comment]
Which endpoint do you hit the issue with?

Also if you were using jq to process the json response, it’s because jq which can’t handle numbers greater than JavaScript max safe integer.

**Comment by ivaylogarnev-limechain** [comment]
The issue was due to how the JSON response from the Mirror Node was being handled. If you intercept the raw data before it gets parsed by the default JSON parser, you can retrieve the correct value. Implementing the following approach resolved the issue for me:

```
import axios from "axios";
import JSONBigInt from "json-bigint";

const fetchData = async (url: string): Promise<any> => {
  const response = await axios.get(url, {
    transformResponse: (data) => data, // Prevent axios from automatically parsing JSON
  });
  if (response.data) {
    return JSONBigInt.parse(response.data); // Use JSON-bigint to parse the response
  }
  throw new Error("No data received");
};
```

This method ensures accurate parsing of large integer values, preventing overflowing issues with the default JSON parser's limitations.
