### ISSUE TITLE
Add integrated reverse proxy or multiple port support for easier Mirror Node setup

### ISSUE THREAD

**Issue by mgarbs** [hashgraph/hedera-mirror-node#9938]
### Problem
Currently, running the Mirror Node requires configuring an external reverse proxy (e.g., Nginx or Apache) to route requests for different services. This makes setup harder for new or smaller operators.

### Solution
Provide a default reverse proxy container in the Mirror Node Docker Compose setup, or
Enable the Relay to serve multiple services on different ports directly.
This would simplify deployments, reduce external configuration overhead, and make the Mirror Node more accessible to a wider range of users.

**Comment by steven-sheehy** [comment]
Our docker compose is not guaranteed to be production ready deployment. It [states](https://github.com/hashgraph/hedera-mirror-node/#running) as much in our README. Our Helm chart is supported for production use and does have Traefik available in the common chart for use. We also support both the Ingress and Gateway APIs in Kubernetes so operators can install their own reverse proxy including cloud provider native ones with almost no config necessary.

**Comment by Neurone** [comment]
Hi @steven-sheehy the change would be very simple (see [this PR](https://github.com/hashgraph/hedera-mirror-node/pull/9939)) and it would make life much easier for developers using docker for testing purposes.

**Comment by mgarbs** [comment]
> Our docker compose is not guaranteed to be production ready deployment. It [states](https://github.com/hashgraph/hedera-mirror-node/#running) as much in our README. 

I understand this and I marked this issue as an enhancement because it would simply enhance the user experience of the product. Hopefully, it comes across that way.
