### ISSUE TITLE
PREVIEWNET Mirror Node Fails to raise RPC Exception for addresses known not to be Topics

### ISSUE THREAD

**Issue by bugbytesinc** [hashgraph/hedera-mirror-node#997]
This appears to be a regression in 0.7.x on the hedera previewnet mirror node:

 hcs.previewnet.mirrornode.hedera.com

Expected behavior (previous behavior) was that when an attempt to subscribe to a topic of an address that is known to the system but is not a topic address (such as a crypto account) the gRPC call would fail, returning an RpcException with a status Code of "invalid argument" 

Current failing unit test example (.net sdk):
```
        [Fact(DisplayName = "Subscribe Topic: Invalid Topic Raises Error")]
        public async Task InvalidTopicIdRaisesError()
        {
            await using var mirror = _network.NewMirror();
            var capture = new TopicMessageCapture(1);
            var mex = await Assert.ThrowsAsync<MirrorException>(async () =>
            {
                await mirror.SubscribeTopicAsync(new SubscribeTopicParams
                {
                    Topic = _network.Payer,
                    MessageWriter = capture,
                    CancellationToken = new CancellationTokenSource(2500).Token
                });
            });
            Assert.Equal(MirrorExceptionCode.InvalidTopicAddress, mex.Code);
            Assert.StartsWith("The address exists, but is not a topic.", mex.Message);
            Assert.Empty(capture.CapturedList);
        }
```
.net sdk previewnet branch commit 239d5f19e2a365cb5c3c93e8992165686fdfb52b

**Comment by steven-sheehy** [comment]
I'm not able to reproduce. Here's what I tried using [grpcurl](https://github.com/fullstorydev/grpcurl):
```bash
$> grpcurl -plaintext -d '{"topicID":{"shardNum":0,"realmNum":0,"topicNum":99999},"limit":0}' hcs.previewnet.mirrornode.hedera.com:5600 com.hedera.mirror.api.proto.ConsensusService/subscribeTopic
ERROR:
  Code: NotFound
  Message: Topic does not exist

$> grpcurl -plaintext -d '{"topicID":{"shardNum":0,"realmNum":0,"topicNum":98},"limit":0}' hcs.previewnet.mirrornode.hedera.com:5600 com.hedera.mirror.api.proto.ConsensusService/subscribeTopic
ERROR:
  Code: InvalidArgument
  Message: Not a valid topic
```

Do you have a particular topic that you tried?

**Comment by bugbytesinc** [comment]
0.0.99999 is not a valid topic because it likely does not exist as an address yet (different edge case).  The example test uses the payer account as the topic address, which is *known* by the system as a crypto address.  The edge case in question is an address value that we know exists in the system, and we also know is not a topic, but a file, account or contract instead.

**Comment by bugbytesinc** [comment]
0.0.98 is also a reserved address, so it may be given special consideration as well.

**Comment by bugbytesinc** [comment]
Maybe try 0.0.1189?

**Comment by steven-sheehy** [comment]
> 0.0.99999 is not a valid topic because it likely does not exist as an address yet (different edge case).

Yes, just showing you an example of the two different scenarios.

> 0.0.98 is also a reserved address, so it may be given special consideration as well.

It is not given special consideration. It is a well known account that exists in the mirror node, hence why I picked it as an example.

> Maybe try 0.0.1189?

You're right, this one is an account but I can subscribe to it. After restarting the grpc process it now properly returns "Not a valid topic". I know what the issue is. We cache the entity lookups and our operations team frequently resets this environment. They must not be restarting the gRPC process after a reset to clear that cache. I'll have them be sure to add that to their automation in the future.

**Comment by steven-sheehy** [comment]
Our operations team has resolved this via their automation scripts. Let us know if you still experience it after the next previewnet deploy.
